VERSION = "1.1.11"

# fmt: off
MAPPING = {
    "adafruit_pureio": "https://adafruit-pureio.readthedocs.io/en/stable/",
    "adafruit_pureio.smbus": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#module-Adafruit_PureIO.smbus",
    "adafruit_pureio.smbus.i2c_msg": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.i2c_msg",
    "adafruit_pureio.smbus.i2c_rdwr_ioctl_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.i2c_rdwr_ioctl_data",
    "adafruit_pureio.smbus.make_i2c_rdwr_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.make_i2c_rdwr_data",
    "adafruit_pureio.smbus.smbus": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus",
    "adafruit_pureio.smbus.smbus.close": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.close",
    "adafruit_pureio.smbus.smbus.open": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.open",
    "adafruit_pureio.smbus.smbus.process_call": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.process_call",
    "adafruit_pureio.smbus.smbus.read_block_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.read_block_data",
    "adafruit_pureio.smbus.smbus.read_byte": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.read_byte",
    "adafruit_pureio.smbus.smbus.read_byte_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.read_byte_data",
    "adafruit_pureio.smbus.smbus.read_bytes": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.read_bytes",
    "adafruit_pureio.smbus.smbus.read_i2c_block_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.read_i2c_block_data",
    "adafruit_pureio.smbus.smbus.read_word_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.read_word_data",
    "adafruit_pureio.smbus.smbus.write_block_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.write_block_data",
    "adafruit_pureio.smbus.smbus.write_byte": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.write_byte",
    "adafruit_pureio.smbus.smbus.write_byte_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.write_byte_data",
    "adafruit_pureio.smbus.smbus.write_bytes": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.write_bytes",
    "adafruit_pureio.smbus.smbus.write_i2c_block_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.write_i2c_block_data",
    "adafruit_pureio.smbus.smbus.write_quick": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.write_quick",
    "adafruit_pureio.smbus.smbus.write_word_data": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.smbus.SMBus.write_word_data",
    "adafruit_pureio.spi": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#module-Adafruit_PureIO.spi",
    "adafruit_pureio.spi.spi": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI",
    "adafruit_pureio.spi.spi.bits_per_word": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.bits_per_word",
    "adafruit_pureio.spi.spi.cs_high": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.cs_high",
    "adafruit_pureio.spi.spi.loop": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.loop",
    "adafruit_pureio.spi.spi.lsb_first": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.lsb_first",
    "adafruit_pureio.spi.spi.max_speed_hz": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.max_speed_hz",
    "adafruit_pureio.spi.spi.mode": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.mode",
    "adafruit_pureio.spi.spi.no_cs": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.no_cs",
    "adafruit_pureio.spi.spi.phase": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.phase",
    "adafruit_pureio.spi.spi.polarity": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.polarity",
    "adafruit_pureio.spi.spi.readbytes": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.readbytes",
    "adafruit_pureio.spi.spi.ready": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.ready",
    "adafruit_pureio.spi.spi.three_wire": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.three_wire",
    "adafruit_pureio.spi.spi.transfer": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.transfer",
    "adafruit_pureio.spi.spi.writebytes": "https://adafruit-pureio.readthedocs.io/en/stable/api.html#Adafruit_PureIO.spi.SPI.writebytes",
}
