VERSION = "2.12.1"

# fmt: off
MAPPING = {
    "aiohttp_session": "https://aiohttp-session.readthedocs.io/en/stable/",
    "aiohttp_session.abstractstorage": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage",
    "aiohttp_session.abstractstorage.cookie_name": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.cookie_name",
    "aiohttp_session.abstractstorage.cookie_params": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.cookie_params",
    "aiohttp_session.abstractstorage.decoder": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.decoder",
    "aiohttp_session.abstractstorage.encoder": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.encoder",
    "aiohttp_session.abstractstorage.load_cookie": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.load_cookie",
    "aiohttp_session.abstractstorage.load_session": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.load_session",
    "aiohttp_session.abstractstorage.max_age": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.max_age",
    "aiohttp_session.abstractstorage.new_session": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.new_session",
    "aiohttp_session.abstractstorage.save_cookie": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.save_cookie",
    "aiohttp_session.abstractstorage.save_session": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.AbstractStorage.save_session",
    "aiohttp_session.cookie_storage": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#module-aiohttp_session.cookie_storage",
    "aiohttp_session.cookie_storage.encryptedcookiestorage": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.cookie_storage.EncryptedCookieStorage",
    "aiohttp_session.cookie_storage.naclcookiestorage": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.cookie_storage.NaClCookieStorage",
    "aiohttp_session.get_session": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.get_session",
    "aiohttp_session.new_session": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.new_session",
    "aiohttp_session.redis_storage": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#module-aiohttp_session.redis_storage",
    "aiohttp_session.redis_storage.memcachedstorage": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.redis_storage.MemcachedStorage",
    "aiohttp_session.redis_storage.redisstorage": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.redis_storage.RedisStorage",
    "aiohttp_session.session": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.Session",
    "aiohttp_session.session.changed": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.Session.changed",
    "aiohttp_session.session.created": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.Session.created",
    "aiohttp_session.session.identity": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.Session.identity",
    "aiohttp_session.session.invalidate": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.Session.invalidate",
    "aiohttp_session.session.new": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.Session.new",
    "aiohttp_session.session.set_new_identity": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.Session.set_new_identity",
    "aiohttp_session.session_middleware": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.session_middleware",
    "aiohttp_session.setup": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.setup",
    "aiohttp_session.simplecookiestorage": "https://aiohttp-session.readthedocs.io/en/stable/reference.html#aiohttp_session.SimpleCookieStorage",
}
