VERSION = "3.7.1"

# fmt: off
MAPPING = {
    "argcomplete": "https://kislyuk.github.io/argcomplete/",
    "argcomplete.argcompleteexception": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.ArgcompleteException",
    "argcomplete.autocomplete": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.autocomplete",
    "argcomplete.choicescompleter": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.ChoicesCompleter",
    "argcomplete.choicescompleter.__call__": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.ChoicesCompleter.__call__",
    "argcomplete.choicescompleter.__init__": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.ChoicesCompleter.__init__",
    "argcomplete.completers": "https://kislyuk.github.io/argcomplete/index.html",
    "argcomplete.completers.choicescompleter": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.ChoicesCompleter",
    "argcomplete.completers.directoriescompleter": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.DirectoriesCompleter",
    "argcomplete.completers.filescompleter": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.FilesCompleter",
    "argcomplete.completers.suppresscompleter": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.SuppressCompleter",
    "argcomplete.completionfinder": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.CompletionFinder",
    "argcomplete.completionfinder.__call__": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.CompletionFinder.__call__",
    "argcomplete.completionfinder.__init__": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.CompletionFinder.__init__",
    "argcomplete.completionfinder.collect_completions": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.CompletionFinder.collect_completions",
    "argcomplete.completionfinder.filter_completions": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.CompletionFinder.filter_completions",
    "argcomplete.completionfinder.get_display_completions": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.CompletionFinder.get_display_completions",
    "argcomplete.completionfinder.quote_completions": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.CompletionFinder.quote_completions",
    "argcomplete.completionfinder.rl_complete": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.CompletionFinder.rl_complete",
    "argcomplete.directoriescompleter": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.DirectoriesCompleter",
    "argcomplete.directoriescompleter.__init__": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.DirectoriesCompleter.__init__",
    "argcomplete.exceptions": "https://kislyuk.github.io/argcomplete/index.html",
    "argcomplete.exceptions.argcompleteexception": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.ArgcompleteException",
    "argcomplete.exclusivecompletionfinder": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.ExclusiveCompletionFinder",
    "argcomplete.filescompleter": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.FilesCompleter",
    "argcomplete.filescompleter.__call__": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.FilesCompleter.__call__",
    "argcomplete.filescompleter.__init__": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.FilesCompleter.__init__",
    "argcomplete.finders": "https://kislyuk.github.io/argcomplete/index.html",
    "argcomplete.finders.completionfinder": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.CompletionFinder",
    "argcomplete.finders.exclusivecompletionfinder": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.ExclusiveCompletionFinder",
    "argcomplete.shellcode": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.shellcode",
    "argcomplete.suppresscompleter": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.SuppressCompleter",
    "argcomplete.suppresscompleter.__init__": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.SuppressCompleter.__init__",
    "argcomplete.suppresscompleter.suppress": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.SuppressCompleter.suppress",
    "argcomplete.warn": "https://kislyuk.github.io/argcomplete/index.html#argcomplete.warn",
}
