VERSION = "10.4.2"

# fmt: off
MAPPING = {
    "arrow_odbc": "https://arrow-odbc.readthedocs.io/en/stable/",
    "arrow_odbc.batch_reader_protocol": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html",
    "arrow_odbc.batch_reader_protocol.batchreaderprotocol": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchReaderProtocol",
    "arrow_odbc.batchreader": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchReader",
    "arrow_odbc.batchreader.into_pyarrow_record_batch_reader": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchReader.into_pyarrow_record_batch_reader",
    "arrow_odbc.batchreader.more_results": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchReader.more_results",
    "arrow_odbc.batchreaderprotocol": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchReaderProtocol",
    "arrow_odbc.batchreaderprotocol.schema": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchReaderProtocol.schema",
    "arrow_odbc.batchwriter": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchWriter",
    "arrow_odbc.batchwriter.flush": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchWriter.flush",
    "arrow_odbc.batchwriter.from_connection": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchWriter.from_connection",
    "arrow_odbc.batchwriter.write_batch": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchWriter.write_batch",
    "arrow_odbc.connect": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.connect",
    "arrow_odbc.connect.connection": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Connection",
    "arrow_odbc.connection": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Connection",
    "arrow_odbc.connection.commit": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Connection.commit",
    "arrow_odbc.connection.enable_connection_pooling": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Connection.enable_connection_pooling",
    "arrow_odbc.connection.execute": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Connection.execute",
    "arrow_odbc.connection.from_table_to_db": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Connection.from_table_to_db",
    "arrow_odbc.connection.insert_into_table": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Connection.insert_into_table",
    "arrow_odbc.connection.read_arrow_batches": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Connection.read_arrow_batches",
    "arrow_odbc.connection.rollback": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Connection.rollback",
    "arrow_odbc.enable_odbc_connection_pooling": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.enable_odbc_connection_pooling",
    "arrow_odbc.error": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html",
    "arrow_odbc.Error": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Error",
    "arrow_odbc.error.error": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Error",
    "arrow_odbc.error.message": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.Error.message",
    "arrow_odbc.from_table_to_db": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.from_table_to_db",
    "arrow_odbc.insert_into_table": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.insert_into_table",
    "arrow_odbc.log_to_stderr": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.log_to_stderr",
    "arrow_odbc.read_arrow_batches_from_odbc": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.read_arrow_batches_from_odbc",
    "arrow_odbc.reader": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html",
    "arrow_odbc.reader.batchreader": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchReader",
    "arrow_odbc.text_encoding": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html",
    "arrow_odbc.text_encoding.textencoding": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.TextEncoding",
    "arrow_odbc.textencoding": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.TextEncoding",
    "arrow_odbc.textencoding.auto": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.TextEncoding.AUTO",
    "arrow_odbc.textencoding.utf16": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.TextEncoding.UTF16",
    "arrow_odbc.textencoding.utf8": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.TextEncoding.UTF8",
    "arrow_odbc.writer": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html",
    "arrow_odbc.writer.batchwriter": "https://arrow-odbc.readthedocs.io/en/stable/arrow_odbc.html#arrow_odbc.BatchWriter",
}
