VERSION = "2.0.0"

# fmt: off
MAPPING = {
    "aspectlib": "https://python-aspectlib.readthedocs.io/en/stable/",
    "aspectlib.all_methods": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.ALL_METHODS",
    "aspectlib.aspect": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.Aspect",
    "aspectlib.contrib": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.contrib.html#module-aspectlib.contrib",
    "aspectlib.contrib.exponential_backoff": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.contrib.html#aspectlib.contrib.exponential_backoff",
    "aspectlib.contrib.flat_backoff": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.contrib.html#aspectlib.contrib.flat_backoff",
    "aspectlib.contrib.retry": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.contrib.html#aspectlib.contrib.retry",
    "aspectlib.contrib.straight_backoff": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.contrib.html#aspectlib.contrib.straight_backoff",
    "aspectlib.debug": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.debug.html#module-aspectlib.debug",
    "aspectlib.debug.format_stack": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.debug.html#aspectlib.debug.format_stack",
    "aspectlib.debug.frame_iterator": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.debug.html#aspectlib.debug.frame_iterator",
    "aspectlib.debug.log": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.debug.html#aspectlib.debug.log",
    "aspectlib.debug.strip_non_ascii": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.debug.html#aspectlib.debug.strip_non_ascii",
    "aspectlib.normal_methods": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.NORMAL_METHODS",
    "aspectlib.proceed": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.Proceed",
    "aspectlib.return": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.Return",
    "aspectlib.rollback": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.Rollback",
    "aspectlib.rollback.__call__": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.Rollback.__call__",
    "aspectlib.rollback.__enter__": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.Rollback.__enter__",
    "aspectlib.rollback.__exit__": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.Rollback.__exit__",
    "aspectlib.rollback.rollback": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.Rollback.rollback",
    "aspectlib.test": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.test.html#module-aspectlib.test",
    "aspectlib.test.mock": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.test.html#aspectlib.test.mock",
    "aspectlib.test.record": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.test.html#aspectlib.test.record",
    "aspectlib.test.replay": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.test.html#aspectlib.test.Replay",
    "aspectlib.test.replay.diff": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.test.html#aspectlib.test.Replay.diff",
    "aspectlib.test.replay.missing": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.test.html#aspectlib.test.Replay.missing",
    "aspectlib.test.replay.unexpected": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.test.html#aspectlib.test.Replay.unexpected",
    "aspectlib.test.story": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.test.html#aspectlib.test.Story",
    "aspectlib.test.story.replay": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.test.html#aspectlib.test.Story.replay",
    "aspectlib.weave": "https://python-aspectlib.readthedocs.io/en/stable/reference/aspectlib.html#aspectlib.weave",
}
