VERSION = "0.4.1"

# fmt: off
MAPPING = {
    "augmax": "https://augmax.readthedocs.io/en/stable/",
    "augmax.blur": "https://augmax.readthedocs.io/en/stable/augmentations/imagelevel.html#augmax.Blur",
    "augmax.bytetofloat": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.ByteToFloat",
    "augmax.centercrop": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.CenterCrop",
    "augmax.channeldrop": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.ChannelDrop",
    "augmax.channelshuffle": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.ChannelShuffle",
    "augmax.colorjitter": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.ColorJitter",
    "augmax.colorspace": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html",
    "augmax.colorspace.bytetofloat": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.ByteToFloat",
    "augmax.colorspace.channeldrop": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.ChannelDrop",
    "augmax.colorspace.channelshuffle": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.ChannelShuffle",
    "augmax.colorspace.colorjitter": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.ColorJitter",
    "augmax.colorspace.normalize": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.Normalize",
    "augmax.colorspace.randombrightness": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomBrightness",
    "augmax.colorspace.randomchannelgamma": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomChannelGamma",
    "augmax.colorspace.randomcontrast": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomContrast",
    "augmax.colorspace.randomgamma": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomGamma",
    "augmax.colorspace.randomgrayscale": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomGrayscale",
    "augmax.colorspace.solarization": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.Solarization",
    "augmax.crop": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Crop",
    "augmax.gaussianblur": "https://augmax.readthedocs.io/en/stable/augmentations/imagelevel.html#augmax.GaussianBlur",
    "augmax.geometric": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html",
    "augmax.geometric.centercrop": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.CenterCrop",
    "augmax.geometric.crop": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Crop",
    "augmax.geometric.horizontalflip": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.HorizontalFlip",
    "augmax.geometric.randomcrop": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.RandomCrop",
    "augmax.geometric.randomsizedcrop": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.RandomSizedCrop",
    "augmax.geometric.resize": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Resize",
    "augmax.geometric.rotate": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Rotate",
    "augmax.geometric.rotate90": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Rotate90",
    "augmax.geometric.verticalflip": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.VerticalFlip",
    "augmax.geometric.warp": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Warp",
    "augmax.gridshuffle": "https://augmax.readthedocs.io/en/stable/augmentations/imagelevel.html#augmax.GridShuffle",
    "augmax.horizontalflip": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.HorizontalFlip",
    "augmax.imagelevel": "https://augmax.readthedocs.io/en/stable/augmentations/imagelevel.html",
    "augmax.imagelevel.blur": "https://augmax.readthedocs.io/en/stable/augmentations/imagelevel.html#augmax.Blur",
    "augmax.imagelevel.gaussianblur": "https://augmax.readthedocs.io/en/stable/augmentations/imagelevel.html#augmax.GaussianBlur",
    "augmax.imagelevel.gridshuffle": "https://augmax.readthedocs.io/en/stable/augmentations/imagelevel.html#augmax.GridShuffle",
    "augmax.normalize": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.Normalize",
    "augmax.randombrightness": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomBrightness",
    "augmax.randomchannelgamma": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomChannelGamma",
    "augmax.randomcontrast": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomContrast",
    "augmax.randomcrop": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.RandomCrop",
    "augmax.randomgamma": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomGamma",
    "augmax.randomgrayscale": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.RandomGrayscale",
    "augmax.randomsizedcrop": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.RandomSizedCrop",
    "augmax.resize": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Resize",
    "augmax.rotate": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Rotate",
    "augmax.rotate90": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Rotate90",
    "augmax.solarization": "https://augmax.readthedocs.io/en/stable/augmentations/colorspace.html#augmax.Solarization",
    "augmax.verticalflip": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.VerticalFlip",
    "augmax.warp": "https://augmax.readthedocs.io/en/stable/augmentations/geometric.html#augmax.Warp",
}
