VERSION = "1.3.7"

# fmt: off
MAPPING = {
    "authcaptureproxy": "https://auth-capture-proxy.readthedocs.io/en/stable/",
    "authcaptureproxy.auth_capture_proxy": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#module-authcaptureproxy.auth_capture_proxy",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.access_url": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.access_url",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.active": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.active",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.all_handler": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.all_handler",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.all_handler_active": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.all_handler_active",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.change_host_url": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.change_host_url",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.check_redirects": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.check_redirects",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.modifiers": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.modifiers",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.modify_headers": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.modify_headers",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.port": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.port",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.refresh_modifiers": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.refresh_modifiers",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.refresh_tests": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.refresh_tests",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.reset_data": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.reset_data",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.start_proxy": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.start_proxy",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.stop_proxy": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.stop_proxy",
    "authcaptureproxy.auth_capture_proxy.authcaptureproxy.tests": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/auth_capture_proxy/index.html#authcaptureproxy.auth_capture_proxy.AuthCaptureProxy.tests",
    "authcaptureproxy.cli": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/cli/index.html#module-authcaptureproxy.cli",
    "authcaptureproxy.cli.coro": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/cli/index.html#authcaptureproxy.cli.coro",
    "authcaptureproxy.cli.info": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/cli/index.html#authcaptureproxy.cli.info",
    "authcaptureproxy.cli.proxy_example": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/cli/index.html#authcaptureproxy.cli.proxy_example",
    "authcaptureproxy.const": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/const/index.html#module-authcaptureproxy.const",
    "authcaptureproxy.examples": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/index.html#module-authcaptureproxy.examples",
    "authcaptureproxy.examples.modifiers": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/modifiers/index.html#module-authcaptureproxy.examples.modifiers",
    "authcaptureproxy.examples.modifiers.autofill": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/modifiers/index.html#authcaptureproxy.examples.modifiers.autofill",
    "authcaptureproxy.examples.modifiers.find_regex_urls": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/modifiers/index.html#authcaptureproxy.examples.modifiers.find_regex_urls",
    "authcaptureproxy.examples.modifiers.find_urls_bs4": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/modifiers/index.html#authcaptureproxy.examples.modifiers.find_urls_bs4",
    "authcaptureproxy.examples.modifiers.prepend_relative_urls": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/modifiers/index.html#authcaptureproxy.examples.modifiers.prepend_relative_urls",
    "authcaptureproxy.examples.modifiers.replace_empty_action_urls": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/modifiers/index.html#authcaptureproxy.examples.modifiers.replace_empty_action_urls",
    "authcaptureproxy.examples.modifiers.replace_matching_urls": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/modifiers/index.html#authcaptureproxy.examples.modifiers.replace_matching_urls",
    "authcaptureproxy.examples.testers": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/testers/index.html#module-authcaptureproxy.examples.testers",
    "authcaptureproxy.examples.testers.test_amazon": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/examples/testers/index.html#authcaptureproxy.examples.testers.test_amazon",
    "authcaptureproxy.helper": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#module-authcaptureproxy.helper",
    "authcaptureproxy.helper.convert_multidict_to_dict": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#authcaptureproxy.helper.convert_multidict_to_dict",
    "authcaptureproxy.helper.get_content_type": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#authcaptureproxy.helper.get_content_type",
    "authcaptureproxy.helper.get_nested_dict_keys": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#authcaptureproxy.helper.get_nested_dict_keys",
    "authcaptureproxy.helper.prepend_url": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#authcaptureproxy.helper.prepend_url",
    "authcaptureproxy.helper.print_resp": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#authcaptureproxy.helper.print_resp",
    "authcaptureproxy.helper.print_resp_aiohttp": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#authcaptureproxy.helper.print_resp_aiohttp",
    "authcaptureproxy.helper.replace_empty_url": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#authcaptureproxy.helper.replace_empty_url",
    "authcaptureproxy.helper.run_func": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#authcaptureproxy.helper.run_func",
    "authcaptureproxy.helper.swap_url": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/helper/index.html#authcaptureproxy.helper.swap_url",
    "authcaptureproxy.stackoverflow": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/stackoverflow/index.html#module-authcaptureproxy.stackoverflow",
    "authcaptureproxy.stackoverflow.get_open_port": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/stackoverflow/index.html#authcaptureproxy.stackoverflow.get_open_port",
    "authcaptureproxy.stackoverflow.return_timer_countdown_refresh_html": "https://auth-capture-proxy.readthedocs.io/en/stable/autoapi/authcaptureproxy/stackoverflow/index.html#authcaptureproxy.stackoverflow.return_timer_countdown_refresh_html",
}
