VERSION = "0.2.14"

# fmt: off
MAPPING = {
    "azfs": "https://azfs.readthedocs.io/en/stable/",
    "azfs.azfileclient": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient",
    "azfs.azfileclient.cp": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.cp",
    "azfs.azfileclient.exists": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.exists",
    "azfs.azfileclient.get": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.get",
    "azfs.azfileclient.glob": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.glob",
    "azfs.azfileclient.info": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.info",
    "azfs.azfileclient.ls": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.ls",
    "azfs.azfileclient.put": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.put",
    "azfs.azfileclient.read": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.read",
    "azfs.azfileclient.read_csv": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.read_csv",
    "azfs.azfileclient.read_json": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.read_json",
    "azfs.azfileclient.read_line_iter": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.read_line_iter",
    "azfs.azfileclient.read_pickle": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.read_pickle",
    "azfs.azfileclient.read_table": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.read_table",
    "azfs.azfileclient.rm": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.rm",
    "azfs.azfileclient.write_csv": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.write_csv",
    "azfs.azfileclient.write_json": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.write_json",
    "azfs.azfileclient.write_pickle": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.write_pickle",
    "azfs.azfileclient.write_table": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.AzFileClient.write_table",
    "azfs.blobpathdecoder": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.BlobPathDecoder",
    "azfs.clients": "https://azfs.readthedocs.io/en/stable/sources/development_api.html",
    "azfs.clients.azfsclient": "https://azfs.readthedocs.io/en/stable/sources/development_api.html#azfs.clients.AzfsClient",
    "azfs.clients.client_interface": "https://azfs.readthedocs.io/en/stable/sources/development_api.html",
    "azfs.clients.client_interface.clientinterface": "https://azfs.readthedocs.io/en/stable/sources/development_api.html#azfs.clients.client_interface.ClientInterface",
    "azfs.clients.client_interface.clientinterface.get_container_client_from_path": "https://azfs.readthedocs.io/en/stable/sources/development_api.html#azfs.clients.client_interface.ClientInterface.get_container_client_from_path",
    "azfs.clients.client_interface.clientinterface.get_file_client_from_path": "https://azfs.readthedocs.io/en/stable/sources/development_api.html#azfs.clients.client_interface.ClientInterface.get_file_client_from_path",
    "azfs.tablestorage": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.TableStorage",
    "azfs.tablestoragewrapper": "https://azfs.readthedocs.io/en/stable/sources/api.html#azfs.TableStorageWrapper",
}
