VERSION = "0.4.0"

# fmt: off
MAPPING = {
    "bcp": "https://bcp.readthedocs.io/en/latest/",
    "bcp.config": "https://bcp.readthedocs.io/en/latest/index.html#module-bcp.config",
    "bcp.connections": "https://bcp.readthedocs.io/en/latest/index.html#module-bcp.connections",
    "bcp.connections.auth": "https://bcp.readthedocs.io/en/latest/index.html#bcp.connections.Auth",
    "bcp.connections.auth.type": "https://bcp.readthedocs.io/en/latest/index.html#bcp.connections.Auth.type",
    "bcp.connections.connection": "https://bcp.readthedocs.io/en/latest/index.html#bcp.connections.Connection",
    "bcp.core": "https://bcp.readthedocs.io/en/latest/index.html#module-bcp.core",
    "bcp.core.bcp": "https://bcp.readthedocs.io/en/latest/index.html#bcp.core.BCP",
    "bcp.core.bcp.dump": "https://bcp.readthedocs.io/en/latest/index.html#bcp.core.BCP.dump",
    "bcp.core.bcp.load": "https://bcp.readthedocs.io/en/latest/index.html#bcp.core.BCP.load",
    "bcp.dialects": "https://bcp.readthedocs.io/en/latest/index.html",
    "bcp.dialects.base": "https://bcp.readthedocs.io/en/latest/index.html#module-bcp.dialects.base",
    "bcp.dialects.base.bcpdump": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.base.BCPDump",
    "bcp.dialects.base.bcpdump.execute": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.base.BCPDump.execute",
    "bcp.dialects.base.bcpload": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.base.BCPLoad",
    "bcp.dialects.base.bcpload.execute": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.base.BCPLoad.execute",
    "bcp.dialects.mssql": "https://bcp.readthedocs.io/en/latest/index.html#module-bcp.dialects.mssql",
    "bcp.dialects.mssql.mssqlbcp": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLBCP",
    "bcp.dialects.mssql.mssqlbcp.command": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLBCP.command",
    "bcp.dialects.mssql.mssqlbcp.config": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLBCP.config",
    "bcp.dialects.mssql.mssqlbcp.logging": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLBCP.logging",
    "bcp.dialects.mssql.mssqldump": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLDump",
    "bcp.dialects.mssql.mssqldump.command": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLDump.command",
    "bcp.dialects.mssql.mssqldump.execute": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLDump.execute",
    "bcp.dialects.mssql.mssqlload": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLLoad",
    "bcp.dialects.mssql.mssqlload.command": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLLoad.command",
    "bcp.dialects.mssql.mssqlload.config": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLLoad.config",
    "bcp.dialects.mssql.mssqlload.error": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLLoad.error",
    "bcp.dialects.mssql.mssqlload.execute": "https://bcp.readthedocs.io/en/latest/index.html#bcp.dialects.mssql.MSSQLLoad.execute",
    "bcp.exceptions": "https://bcp.readthedocs.io/en/latest/index.html#module-bcp.exceptions",
    "bcp.exceptions.drivernotsupportedexception": "https://bcp.readthedocs.io/en/latest/index.html#bcp.exceptions.DriverNotSupportedException",
    "bcp.exceptions.invalidcredentialexception": "https://bcp.readthedocs.io/en/latest/index.html#bcp.exceptions.InvalidCredentialException",
    "bcp.files": "https://bcp.readthedocs.io/en/latest/index.html#module-bcp.files",
    "bcp.files.datafile": "https://bcp.readthedocs.io/en/latest/index.html#bcp.files.DataFile",
    "bcp.files.errorfile": "https://bcp.readthedocs.io/en/latest/index.html#bcp.files.ErrorFile",
    "bcp.files.file": "https://bcp.readthedocs.io/en/latest/index.html#bcp.files.File",
    "bcp.files.logfile": "https://bcp.readthedocs.io/en/latest/index.html#bcp.files.LogFile",
}
