VERSION = "3.2.3"

# fmt: off
MAPPING = {
    "beancount": "https://beancount.github.io/docs/",
    "beancount.api": "https://beancount.github.io/docs/api_reference/beancount.loader/",
    "beancount.api.load_doc": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_doc",
    "beancount.api.load_encrypted_file": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_encrypted_file",
    "beancount.api.load_file": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_file",
    "beancount.core": "https://beancount.github.io/docs/api_reference/beancount.core/#beancount.core",
    "beancount.load_doc": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_doc",
    "beancount.load_encrypted_file": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_encrypted_file",
    "beancount.load_file": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_file",
    "beancount.loader": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader",
    "beancount.loader.aggregate_options_map": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.aggregate_options_map",
    "beancount.loader.combine_plugins": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.combine_plugins",
    "beancount.loader.compute_input_hash": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.compute_input_hash",
    "beancount.loader.delete_cache_function": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.delete_cache_function",
    "beancount.loader.get_cache_filename": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.get_cache_filename",
    "beancount.loader.initialize": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.initialize",
    "beancount.loader.load_doc": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_doc",
    "beancount.loader.load_encrypted_file": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_encrypted_file",
    "beancount.loader.load_file": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_file",
    "beancount.loader.load_string": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.load_string",
    "beancount.loader.loaderror": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.LoadError",
    "beancount.loader.needs_refresh": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.needs_refresh",
    "beancount.loader.pickle_cache_function": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.pickle_cache_function",
    "beancount.loader.run_transformations": "https://beancount.github.io/docs/api_reference/beancount.loader/#beancount.loader.run_transformations",
    "beancount.ops": "https://beancount.github.io/docs/api_reference/beancount.ops/#beancount.ops",
    "beancount.parser": "https://beancount.github.io/docs/api_reference/beancount.parser/#beancount.parser",
    "beancount.plugins": "https://beancount.github.io/docs/api_reference/beancount.plugins/#beancount.plugins",
    "beancount.scripts": "https://beancount.github.io/docs/api_reference/beancount.scripts/#beancount.scripts",
    "beancount.tools": "https://beancount.github.io/docs/api_reference/beancount.tools/#beancount.tools",
    "beancount.utils": "https://beancount.github.io/docs/api_reference/beancount.utils/#beancount.utils",
}
