VERSION = "0.22.9"

# fmt: off
MAPPING = {
    "beartype": "https://beartype.readthedocs.io/en/stable/",
    "beartype.beartype": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.beartype",
    "beartype.beartypeconf": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeConf",
    "beartype.beartypeconf.is_color": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeConf.is_color",
    "beartype.beartypeconf.is_debug": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeConf.is_debug",
    "beartype.beartypeconf.is_pep484_tower": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeConf.is_pep484_tower",
    "beartype.beartypeconf.strategy": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeConf.strategy",
    "beartype.beartypestrategy": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeStrategy",
    "beartype.beartypestrategy.o0": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeStrategy.O0",
    "beartype.beartypestrategy.o1": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeStrategy.O1",
    "beartype.beartypestrategy.ologn": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeStrategy.Ologn",
    "beartype.beartypestrategy.on": "https://beartype.readthedocs.io/en/stable/api_decor/#beartype.BeartypeStrategy.On",
    "beartype.claw": "https://beartype.readthedocs.io/en/stable/api_claw/#module-beartype.claw",
    "beartype.claw.beartype_all": "https://beartype.readthedocs.io/en/stable/api_claw/#beartype.claw.beartype_all",
    "beartype.claw.beartype_package": "https://beartype.readthedocs.io/en/stable/api_claw/#beartype.claw.beartype_package",
    "beartype.claw.beartype_packages": "https://beartype.readthedocs.io/en/stable/api_claw/#beartype.claw.beartype_packages",
    "beartype.claw.beartype_this_package": "https://beartype.readthedocs.io/en/stable/api_claw/#beartype.claw.beartype_this_package",
    "beartype.door": "https://beartype.readthedocs.io/en/stable/api_door/#module-beartype.door",
    "beartype.door.die_if_unbearable": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.die_if_unbearable",
    "beartype.door.is_bearable": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.is_bearable",
    "beartype.door.is_subhint": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.is_subhint",
    "beartype.door.typehint": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.TypeHint",
    "beartype.door.typehint.args": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.TypeHint.args",
    "beartype.door.typehint.die_if_unbearable": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.TypeHint.die_if_unbearable",
    "beartype.door.typehint.hint": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.TypeHint.hint",
    "beartype.door.typehint.is_bearable": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.TypeHint.is_bearable",
    "beartype.door.typehint.is_ignorable": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.TypeHint.is_ignorable",
    "beartype.door.typehint.is_subhint": "https://beartype.readthedocs.io/en/stable/api_door/#beartype.door.TypeHint.is_subhint",
    "beartype.roar": "https://beartype.readthedocs.io/en/stable/api_roar/#module-beartype.roar",
    "beartype.roar.beartypecallexception": "https://beartype.readthedocs.io/en/stable/api_roar/#beartype.roar.BeartypeCallException",
    "beartype.roar.beartypecallhintexception": "https://beartype.readthedocs.io/en/stable/api_roar/#beartype.roar.BeartypeCallHintException",
    "beartype.roar.beartypecallhintforwardrefexception": "https://beartype.readthedocs.io/en/stable/api_roar/#beartype.roar.BeartypeCallHintForwardRefException",
    "beartype.roar.beartypecallhintviolation": "https://beartype.readthedocs.io/en/stable/api_roar/#beartype.roar.BeartypeCallHintViolation",
    "beartype.roar.beartypecallhintviolation.culprits": "https://beartype.readthedocs.io/en/stable/api_roar/#beartype.roar.BeartypeCallHintViolation.culprits",
    "beartype.roar.beartypedecorexception": "https://beartype.readthedocs.io/en/stable/api_roar/#beartype.roar.BeartypeDecorException",
    "beartype.roar.beartypeexception": "https://beartype.readthedocs.io/en/stable/api_roar/#beartype.roar.BeartypeException",
    "beartype.vale": "https://beartype.readthedocs.io/en/stable/api_vale/#module-beartype.vale",
    "beartype.vale.is": "https://beartype.readthedocs.io/en/stable/api_vale/#beartype.vale.Is",
    "beartype.vale.isattr": "https://beartype.readthedocs.io/en/stable/api_vale/#beartype.vale.IsAttr",
    "beartype.vale.isequal": "https://beartype.readthedocs.io/en/stable/api_vale/#beartype.vale.IsEqual",
    "beartype.vale.isinstance": "https://beartype.readthedocs.io/en/stable/api_vale/#beartype.vale.IsInstance",
    "beartype.vale.issubclass": "https://beartype.readthedocs.io/en/stable/api_vale/#beartype.vale.IsSubclass",
}
