VERSION = "2.6.0"

# fmt: off
MAPPING = {
    "flask_bootstrap": "https://bootstrap-flask.readthedocs.io/en/stable/",
    "flask_bootstrap._bootstrap": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap",
    "flask_bootstrap._bootstrap.bootstrap_css_filename": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.bootstrap_css_filename",
    "flask_bootstrap._bootstrap.bootstrap_css_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.bootstrap_css_integrity",
    "flask_bootstrap._bootstrap.bootstrap_js_filename": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.bootstrap_js_filename",
    "flask_bootstrap._bootstrap.bootstrap_js_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.bootstrap_js_integrity",
    "flask_bootstrap._bootstrap.bootstrap_version": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.bootstrap_version",
    "flask_bootstrap._bootstrap.init_app": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.init_app",
    "flask_bootstrap._bootstrap.jquery_filename": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.jquery_filename",
    "flask_bootstrap._bootstrap.jquery_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.jquery_integrity",
    "flask_bootstrap._bootstrap.jquery_version": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.jquery_version",
    "flask_bootstrap._bootstrap.load_css": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.load_css",
    "flask_bootstrap._bootstrap.load_js": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.load_js",
    "flask_bootstrap._bootstrap.popper_filename": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.popper_filename",
    "flask_bootstrap._bootstrap.popper_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.popper_integrity",
    "flask_bootstrap._bootstrap.popper_version": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.popper_version",
    "flask_bootstrap._bootstrap.static_folder": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap._Bootstrap.static_folder",
    "flask_bootstrap.bootstrap4": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4",
    "flask_bootstrap.bootstrap4.bootstrap_css_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4.bootstrap_css_integrity",
    "flask_bootstrap.bootstrap4.bootstrap_js_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4.bootstrap_js_integrity",
    "flask_bootstrap.bootstrap4.bootstrap_version": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4.bootstrap_version",
    "flask_bootstrap.bootstrap4.jquery_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4.jquery_integrity",
    "flask_bootstrap.bootstrap4.jquery_version": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4.jquery_version",
    "flask_bootstrap.bootstrap4.popper_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4.popper_integrity",
    "flask_bootstrap.bootstrap4.popper_name": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4.popper_name",
    "flask_bootstrap.bootstrap4.popper_version": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4.popper_version",
    "flask_bootstrap.bootstrap4.static_folder": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap4.static_folder",
    "flask_bootstrap.bootstrap5": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap5",
    "flask_bootstrap.bootstrap5.bootstrap_css_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap5.bootstrap_css_integrity",
    "flask_bootstrap.bootstrap5.bootstrap_js_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap5.bootstrap_js_integrity",
    "flask_bootstrap.bootstrap5.bootstrap_version": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap5.bootstrap_version",
    "flask_bootstrap.bootstrap5.popper_integrity": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap5.popper_integrity",
    "flask_bootstrap.bootstrap5.popper_name": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap5.popper_name",
    "flask_bootstrap.bootstrap5.popper_version": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap5.popper_version",
    "flask_bootstrap.bootstrap5.static_folder": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.Bootstrap5.static_folder",
    "flask_bootstrap.switchfield": "https://bootstrap-flask.readthedocs.io/en/stable/api/#flask_bootstrap.SwitchField",
}
