VERSION = "7.1.8"

# fmt: off
MAPPING = {
    "cachetools": "https://cachetools.readthedocs.io/en/latest/",
    "cachetools.cache": "https://cachetools.readthedocs.io/en/latest/#cachetools.Cache",
    "cachetools.cache.currsize": "https://cachetools.readthedocs.io/en/latest/#cachetools.Cache.currsize",
    "cachetools.cache.getsizeof": "https://cachetools.readthedocs.io/en/latest/#cachetools.Cache.getsizeof",
    "cachetools.cache.maxsize": "https://cachetools.readthedocs.io/en/latest/#cachetools.Cache.maxsize",
    "cachetools.cached": "https://cachetools.readthedocs.io/en/latest/#cachetools.cached",
    "cachetools.cachedmethod": "https://cachetools.readthedocs.io/en/latest/#cachetools.cachedmethod",
    "cachetools.fifocache": "https://cachetools.readthedocs.io/en/latest/#cachetools.FIFOCache",
    "cachetools.fifocache.popitem": "https://cachetools.readthedocs.io/en/latest/#cachetools.FIFOCache.popitem",
    "cachetools.func": "https://cachetools.readthedocs.io/en/latest/#module-cachetools.func",
    "cachetools.func.fifo_cache": "https://cachetools.readthedocs.io/en/latest/#cachetools.func.fifo_cache",
    "cachetools.func.lfu_cache": "https://cachetools.readthedocs.io/en/latest/#cachetools.func.lfu_cache",
    "cachetools.func.lru_cache": "https://cachetools.readthedocs.io/en/latest/#cachetools.func.lru_cache",
    "cachetools.func.rr_cache": "https://cachetools.readthedocs.io/en/latest/#cachetools.func.rr_cache",
    "cachetools.func.ttl_cache": "https://cachetools.readthedocs.io/en/latest/#cachetools.func.ttl_cache",
    "cachetools.keys": "https://cachetools.readthedocs.io/en/latest/#module-cachetools.keys",
    "cachetools.keys.hashkey": "https://cachetools.readthedocs.io/en/latest/#cachetools.keys.hashkey",
    "cachetools.keys.methodkey": "https://cachetools.readthedocs.io/en/latest/#cachetools.keys.methodkey",
    "cachetools.keys.typedkey": "https://cachetools.readthedocs.io/en/latest/#cachetools.keys.typedkey",
    "cachetools.keys.typedmethodkey": "https://cachetools.readthedocs.io/en/latest/#cachetools.keys.typedmethodkey",
    "cachetools.lfucache": "https://cachetools.readthedocs.io/en/latest/#cachetools.LFUCache",
    "cachetools.lfucache.popitem": "https://cachetools.readthedocs.io/en/latest/#cachetools.LFUCache.popitem",
    "cachetools.lrucache": "https://cachetools.readthedocs.io/en/latest/#cachetools.LRUCache",
    "cachetools.lrucache.popitem": "https://cachetools.readthedocs.io/en/latest/#cachetools.LRUCache.popitem",
    "cachetools.rrcache": "https://cachetools.readthedocs.io/en/latest/#cachetools.RRCache",
    "cachetools.rrcache.choice": "https://cachetools.readthedocs.io/en/latest/#cachetools.RRCache.choice",
    "cachetools.rrcache.popitem": "https://cachetools.readthedocs.io/en/latest/#cachetools.RRCache.popitem",
    "cachetools.tlrucache": "https://cachetools.readthedocs.io/en/latest/#cachetools.TLRUCache",
    "cachetools.tlrucache.expire": "https://cachetools.readthedocs.io/en/latest/#cachetools.TLRUCache.expire",
    "cachetools.tlrucache.popitem": "https://cachetools.readthedocs.io/en/latest/#cachetools.TLRUCache.popitem",
    "cachetools.tlrucache.timer": "https://cachetools.readthedocs.io/en/latest/#cachetools.TLRUCache.timer",
    "cachetools.tlrucache.ttu": "https://cachetools.readthedocs.io/en/latest/#cachetools.TLRUCache.ttu",
    "cachetools.ttlcache": "https://cachetools.readthedocs.io/en/latest/#cachetools.TTLCache",
    "cachetools.ttlcache.expire": "https://cachetools.readthedocs.io/en/latest/#cachetools.TTLCache.expire",
    "cachetools.ttlcache.popitem": "https://cachetools.readthedocs.io/en/latest/#cachetools.TTLCache.popitem",
    "cachetools.ttlcache.timer": "https://cachetools.readthedocs.io/en/latest/#cachetools.TTLCache.timer",
    "cachetools.ttlcache.ttl": "https://cachetools.readthedocs.io/en/latest/#cachetools.TTLCache.ttl",
}
