VERSION = "6.1.4"

# fmt: off
MAPPING = {
    "cbor2": "https://cbor2.readthedocs.io/en/latest/",
    "cbor2.cbordecodeeof": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBORDecodeEOF",
    "cbor2.cbordecodeerror": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBORDecodeError",
    "cbor2.cbordecoder": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBORDecoder",
    "cbor2.cbordecoder.decode": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBORDecoder.decode",
    "cbor2.cbordecoder.read": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBORDecoder.read",
    "cbor2.cborencodeerror": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncodeError",
    "cbor2.cborencoder": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncoder",
    "cbor2.cborencoder.encode": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncoder.encode",
    "cbor2.cborencoder.encode_semantic": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncoder.encode_semantic",
    "cbor2.cborencoder.encode_sortable_item": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncoder.encode_sortable_item",
    "cbor2.cborencoder.encode_sortable_key": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncoder.encode_sortable_key",
    "cbor2.cborencoder.encode_to_bytes": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncoder.encode_to_bytes",
    "cbor2.cborencoder.write": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncoder.write",
    "cbor2.cborencodetypeerror": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncodeTypeError",
    "cbor2.cborencodevalueerror": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBOREncodeValueError",
    "cbor2.cborerror": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBORError",
    "cbor2.cborsimplevalue": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBORSimpleValue",
    "cbor2.cbortag": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.CBORTag",
    "cbor2.dump": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.dump",
    "cbor2.dumps": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.dumps",
    "cbor2.frozendict": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.frozendict",
    "cbor2.load": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.load",
    "cbor2.loads": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.loads",
    "cbor2.shareable_decoder": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.shareable_decoder",
    "cbor2.shareable_encoder": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.shareable_encoder",
    "cbor2.undefined": "https://cbor2.readthedocs.io/en/latest/api.html#cbor2.undefined",
}
