VERSION = "0.8.1"

# fmt: off
MAPPING = {
    "cdshealpix": "https://cds-astro.github.io/cds-healpix-python/",
    "cdshealpix.from_ring": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.from_ring.html#cdshealpix.from_ring",
    "cdshealpix.nested": "https://cds-astro.github.io/cds-healpix-python/api.html#module-cdshealpix.nested",
    "cdshealpix.nested.bilinear_interpolation": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.bilinear_interpolation.html#cdshealpix.nested.bilinear_interpolation",
    "cdshealpix.nested.cone_search": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.cone_search.html#cdshealpix.nested.cone_search",
    "cdshealpix.nested.elliptical_cone_search": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.elliptical_cone_search.html#cdshealpix.nested.elliptical_cone_search",
    "cdshealpix.nested.external_neighbours": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.external_neighbours.html#cdshealpix.nested.external_neighbours",
    "cdshealpix.nested.healpix_to_lonlat": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.healpix_to_lonlat.html#cdshealpix.nested.healpix_to_lonlat",
    "cdshealpix.nested.healpix_to_skycoord": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.healpix_to_skycoord.html#cdshealpix.nested.healpix_to_skycoord",
    "cdshealpix.nested.healpix_to_xy": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.healpix_to_xy.html#cdshealpix.nested.healpix_to_xy",
    "cdshealpix.nested.lonlat_to_healpix": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.lonlat_to_healpix.html#cdshealpix.nested.lonlat_to_healpix",
    "cdshealpix.nested.lonlat_to_xy": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.lonlat_to_xy.html#cdshealpix.nested.lonlat_to_xy",
    "cdshealpix.nested.neighbours": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.neighbours.html#cdshealpix.nested.neighbours",
    "cdshealpix.nested.polygon_search": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.polygon_search.html#cdshealpix.nested.polygon_search",
    "cdshealpix.nested.skycoord_to_healpix": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.skycoord_to_healpix.html#cdshealpix.nested.skycoord_to_healpix",
    "cdshealpix.nested.vertices": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.vertices.html#cdshealpix.nested.vertices",
    "cdshealpix.nested.vertices_skycoord": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.vertices_skycoord.html#cdshealpix.nested.vertices_skycoord",
    "cdshealpix.nested.xy_to_lonlat": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.nested.xy_to_lonlat.html#cdshealpix.nested.xy_to_lonlat",
    "cdshealpix.ring": "https://cds-astro.github.io/cds-healpix-python/api.html#module-cdshealpix.ring",
    "cdshealpix.ring.healpix_to_lonlat": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.ring.healpix_to_lonlat.html#cdshealpix.ring.healpix_to_lonlat",
    "cdshealpix.ring.healpix_to_skycoord": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.ring.healpix_to_skycoord.html#cdshealpix.ring.healpix_to_skycoord",
    "cdshealpix.ring.healpix_to_xy": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.ring.healpix_to_xy.html#cdshealpix.ring.healpix_to_xy",
    "cdshealpix.ring.lonlat_to_healpix": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.ring.lonlat_to_healpix.html#cdshealpix.ring.lonlat_to_healpix",
    "cdshealpix.ring.skycoord_to_healpix": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.ring.skycoord_to_healpix.html#cdshealpix.ring.skycoord_to_healpix",
    "cdshealpix.ring.vertices": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.ring.vertices.html#cdshealpix.ring.vertices",
    "cdshealpix.ring.vertices_skycoord": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.ring.vertices_skycoord.html#cdshealpix.ring.vertices_skycoord",
    "cdshealpix.skymap": "https://cds-astro.github.io/cds-healpix-python/api.html",
    "cdshealpix.skymap.skymap": "https://cds-astro.github.io/cds-healpix-python/api.html",
    "cdshealpix.skymap.skymap.skymapexplicit": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapExplicit",
    "cdshealpix.skymap.skymap.skymapimplicit": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapImplicit",
    "cdshealpix.skymap.skymapexplicit": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapExplicit",
    "cdshealpix.skymap.skymapexplicit.__init__": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapExplicit.__init__",
    "cdshealpix.skymap.skymapexplicit.from_fits": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapExplicit.from_fits",
    "cdshealpix.skymap.skymapexplicit.to_fits": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapExplicit.to_fits",
    "cdshealpix.skymap.skymapexplicit.to_implicit": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapExplicit.to_implicit",
    "cdshealpix.skymap.skymapimplicit": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapImplicit",
    "cdshealpix.skymap.skymapimplicit.__init__": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapImplicit.__init__",
    "cdshealpix.skymap.skymapimplicit.from_fits": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapImplicit.from_fits",
    "cdshealpix.skymap.skymapimplicit.quick_plot": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapImplicit.quick_plot",
    "cdshealpix.skymap.skymapimplicit.to_explicit": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapImplicit.to_explicit",
    "cdshealpix.skymap.skymapimplicit.to_fits": "https://cds-astro.github.io/cds-healpix-python/api.html#cdshealpix.skymap.SkymapImplicit.to_fits",
    "cdshealpix.to_ring": "https://cds-astro.github.io/cds-healpix-python/stubs/cdshealpix.to_ring.html#cdshealpix.to_ring",
}
