VERSION = "0.11"

# fmt: off
MAPPING = {
    "celery_batches": "https://celery-batches.readthedocs.io/en/stable/",
    "celery_batches.batches": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches",
    "celery_batches.batches.abstract": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.abstract",
    "celery_batches.batches.apply": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.apply",
    "celery_batches.batches.flush": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.flush",
    "celery_batches.batches.flush_every": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.flush_every",
    "celery_batches.batches.flush_interval": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.flush_interval",
    "celery_batches.batches.ignore_result": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.ignore_result",
    "celery_batches.batches.priority": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.priority",
    "celery_batches.batches.rate_limit": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.rate_limit",
    "celery_batches.batches.reject_on_worker_lost": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.reject_on_worker_lost",
    "celery_batches.batches.request_stack": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.request_stack",
    "celery_batches.batches.run": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.run",
    "celery_batches.batches.serializer": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.serializer",
    "celery_batches.batches.store_errors_even_if_ignored": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.store_errors_even_if_ignored",
    "celery_batches.batches.strategy": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.Strategy",
    "celery_batches.batches.track_started": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.track_started",
    "celery_batches.batches.typing": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.Batches.typing",
    "celery_batches.simplerequest": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest",
    "celery_batches.simplerequest.args": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.args",
    "celery_batches.simplerequest.chord": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.chord",
    "celery_batches.simplerequest.correlation_id": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.correlation_id",
    "celery_batches.simplerequest.delivery_info": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.delivery_info",
    "celery_batches.simplerequest.from_request": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.from_request",
    "celery_batches.simplerequest.hostname": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.hostname",
    "celery_batches.simplerequest.id": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.id",
    "celery_batches.simplerequest.ignore_result": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.ignore_result",
    "celery_batches.simplerequest.kwargs": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.kwargs",
    "celery_batches.simplerequest.name": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.name",
    "celery_batches.simplerequest.reply_to": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.reply_to",
    "celery_batches.simplerequest.request_dict": "https://celery-batches.readthedocs.io/en/stable/api.html#celery_batches.SimpleRequest.request_dict",
}
