VERSION = "3.3.1"

# fmt: off
MAPPING = {
    "cf_units": "https://cf-units.readthedocs.io/en/stable/",
    "cf_units.calendar_aliases": "https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.CALENDAR_ALIASES",
    "cf_units.calendars": "https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.CALENDARS",
    "cf_units.date2num": "https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.date2num",
    "cf_units.decode_time": "https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.decode_time",
    "cf_units.encode_clock": "https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.encode_clock",
    "cf_units.encode_date": "https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.encode_date",
    "cf_units.encode_time": "https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.encode_time",
    "cf_units.num2date": "https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.num2date",
    "cf_units.num2pydate": "https://cf-units.readthedocs.io/en/stable/utilities.html#cf_units.num2pydate",
    "cf_units.unit": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit",
    "cf_units.unit.calendar": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.calendar",
    "cf_units.unit.category": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.category",
    "cf_units.unit.cftime_unit": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.cftime_unit",
    "cf_units.unit.change_calendar": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.change_calendar",
    "cf_units.unit.convert": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.convert",
    "cf_units.unit.date2num": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.date2num",
    "cf_units.unit.definition": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.definition",
    "cf_units.unit.format": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.format",
    "cf_units.unit.invert": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.invert",
    "cf_units.unit.is_convertible": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.is_convertible",
    "cf_units.unit.is_dimensionless": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.is_dimensionless",
    "cf_units.unit.is_long_time_interval": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.is_long_time_interval",
    "cf_units.unit.is_no_unit": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.is_no_unit",
    "cf_units.unit.is_time": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.is_time",
    "cf_units.unit.is_time_reference": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.is_time_reference",
    "cf_units.unit.is_udunits": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.is_udunits",
    "cf_units.unit.is_unknown": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.is_unknown",
    "cf_units.unit.is_vertical": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.is_vertical",
    "cf_units.unit.log": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.log",
    "cf_units.unit.modulus": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.modulus",
    "cf_units.unit.name": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.name",
    "cf_units.unit.num2date": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.num2date",
    "cf_units.unit.num2pydate": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.num2pydate",
    "cf_units.unit.offset_by_time": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.offset_by_time",
    "cf_units.unit.origin": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.origin",
    "cf_units.unit.root": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.root",
    "cf_units.unit.symbol": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.symbol",
    "cf_units.unit.title": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.title",
    "cf_units.unit.ut_unit": "https://cf-units.readthedocs.io/en/stable/unit.html#cf_units.Unit.ut_unit",
}
