VERSION = "7.6.0"

# fmt: off
MAPPING = {
    "chardet": "https://chardet.readthedocs.io/en/latest/",
    "chardet.default_max_bytes": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DEFAULT_MAX_BYTES",
    "chardet.detect": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.detect",
    "chardet.detect_all": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.detect_all",
    "chardet.detectiondict": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionDict",
    "chardet.detectiondict.confidence": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionDict.confidence",
    "chardet.detectiondict.encoding": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionDict.encoding",
    "chardet.detectiondict.language": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionDict.language",
    "chardet.detectiondict.mime_type": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionDict.mime_type",
    "chardet.detectionresult": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionResult",
    "chardet.detectionresult.confidence": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionResult.confidence",
    "chardet.detectionresult.encoding": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionResult.encoding",
    "chardet.detectionresult.language": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionResult.language",
    "chardet.detectionresult.mime_type": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionResult.mime_type",
    "chardet.detectionresult.to_dict": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.DetectionResult.to_dict",
    "chardet.encodingera": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.EncodingEra",
    "chardet.encodingera.all": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.EncodingEra.ALL",
    "chardet.encodingera.dos": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.EncodingEra.DOS",
    "chardet.encodingera.legacy_iso": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.EncodingEra.LEGACY_ISO",
    "chardet.encodingera.legacy_mac": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.EncodingEra.LEGACY_MAC",
    "chardet.encodingera.legacy_regional": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.EncodingEra.LEGACY_REGIONAL",
    "chardet.encodingera.mainframe": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.EncodingEra.MAINFRAME",
    "chardet.encodingera.modern_web": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.EncodingEra.MODERN_WEB",
    "chardet.languagefilter": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.LanguageFilter",
    "chardet.languagefilter.all": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.LanguageFilter.ALL",
    "chardet.languagefilter.chinese": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.LanguageFilter.CHINESE",
    "chardet.languagefilter.chinese_simplified": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.LanguageFilter.CHINESE_SIMPLIFIED",
    "chardet.languagefilter.chinese_traditional": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.LanguageFilter.CHINESE_TRADITIONAL",
    "chardet.languagefilter.cjk": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.LanguageFilter.CJK",
    "chardet.languagefilter.japanese": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.LanguageFilter.JAPANESE",
    "chardet.languagefilter.korean": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.LanguageFilter.KOREAN",
    "chardet.languagefilter.non_cjk": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.LanguageFilter.NON_CJK",
    "chardet.minimum_threshold": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.MINIMUM_THRESHOLD",
    "chardet.universaldetector": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.UniversalDetector",
    "chardet.universaldetector.close": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.UniversalDetector.close",
    "chardet.universaldetector.done": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.UniversalDetector.done",
    "chardet.universaldetector.feed": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.UniversalDetector.feed",
    "chardet.universaldetector.legacy_map": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.UniversalDetector.LEGACY_MAP",
    "chardet.universaldetector.minimum_threshold": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.UniversalDetector.MINIMUM_THRESHOLD",
    "chardet.universaldetector.reset": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.UniversalDetector.reset",
    "chardet.universaldetector.result": "https://chardet.readthedocs.io/en/latest/api/index.html#chardet.UniversalDetector.result",
}
