VERSION = "3.1.2"

# fmt: off
MAPPING = {
    "cidr_trie": "https://cidr-trie.readthedocs.io/en/stable/",
    "cidr_trie.bits_util": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#module-cidr_trie.bits_util",
    "cidr_trie.bits_util.bit_not": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.bits_util.bit_not",
    "cidr_trie.bits_util.ffs": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.bits_util.ffs",
    "cidr_trie.bits_util.fls": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.bits_util.fls",
    "cidr_trie.bits_util.is_set": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.bits_util.is_set",
    "cidr_trie.cidr_util": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#module-cidr_trie.cidr_util",
    "cidr_trie.cidr_util.cidr_atoi": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.cidr_util.cidr_atoi",
    "cidr_trie.cidr_util.get_subnet_mask": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.cidr_util.get_subnet_mask",
    "cidr_trie.cidr_util.ip_atoi": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.cidr_util.ip_atoi",
    "cidr_trie.cidr_util.ip_itoa": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.cidr_util.ip_itoa",
    "cidr_trie.cidr_util.is_v6": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.cidr_util.is_v6",
    "cidr_trie.cidr_util.longest_common_prefix_length": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.cidr_util.longest_common_prefix_length",
    "cidr_trie.patricianode": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaNode",
    "cidr_trie.patricianode.bit": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaNode.bit",
    "cidr_trie.patricianode.get_child_values": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaNode.get_child_values",
    "cidr_trie.patricianode.get_values": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaNode.get_values",
    "cidr_trie.patricianode.ip": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaNode.ip",
    "cidr_trie.patricianode.left": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaNode.left",
    "cidr_trie.patricianode.masks": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaNode.masks",
    "cidr_trie.patricianode.parent": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaNode.parent",
    "cidr_trie.patricianode.right": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaNode.right",
    "cidr_trie.patriciatrie": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie",
    "cidr_trie.patriciatrie.check_value_exists": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.check_value_exists",
    "cidr_trie.patriciatrie.find": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.find",
    "cidr_trie.patriciatrie.find_all": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.find_all",
    "cidr_trie.patriciatrie.insert": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.insert",
    "cidr_trie.patriciatrie.root": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.root",
    "cidr_trie.patriciatrie.size": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.size",
    "cidr_trie.patriciatrie.traverse": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.traverse",
    "cidr_trie.patriciatrie.traverse_from_node": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.traverse_from_node",
    "cidr_trie.patriciatrie.traverse_inorder": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.traverse_inorder",
    "cidr_trie.patriciatrie.traverse_inorder_from_node": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.traverse_inorder_from_node",
    "cidr_trie.patriciatrie.traverse_preorder": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.traverse_preorder",
    "cidr_trie.patriciatrie.traverse_preorder_from_node": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.traverse_preorder_from_node",
    "cidr_trie.patriciatrie.v6": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.v6",
    "cidr_trie.patriciatrie.validate_ip_type_for_trie": "https://cidr-trie.readthedocs.io/en/stable/cidr_trie.html#cidr_trie.PatriciaTrie.validate_ip_type_for_trie",
}
