VERSION = "0.9.2"

# fmt: off
MAPPING = {
    "cmake_parser": "https://roehling.github.io/cmake_parser/",
    "cmake_parser.ast": "https://roehling.github.io/cmake_parser/api/ast.html#module-cmake_parser.ast",
    "cmake_parser.ast.astfilenode": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.AstFileNode",
    "cmake_parser.ast.astnode": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.AstNode",
    "cmake_parser.ast.block": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Block",
    "cmake_parser.ast.break": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Break",
    "cmake_parser.ast.builtin": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Builtin",
    "cmake_parser.ast.builtinblock": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.BuiltinBlock",
    "cmake_parser.ast.builtinnoargs": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.BuiltinNoArgs",
    "cmake_parser.ast.command": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Command",
    "cmake_parser.ast.comment": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Comment",
    "cmake_parser.ast.continue": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Continue",
    "cmake_parser.ast.foreach": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.ForEach",
    "cmake_parser.ast.function": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Function",
    "cmake_parser.ast.if": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.If",
    "cmake_parser.ast.include": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Include",
    "cmake_parser.ast.macro": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Macro",
    "cmake_parser.ast.math": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Math",
    "cmake_parser.ast.option": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Option",
    "cmake_parser.ast.return": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Return",
    "cmake_parser.ast.set": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Set",
    "cmake_parser.ast.unset": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.Unset",
    "cmake_parser.ast.while": "https://roehling.github.io/cmake_parser/api/ast.html#cmake_parser.ast.While",
    "cmake_parser.error": "https://roehling.github.io/cmake_parser/api/error.html#module-cmake_parser.error",
    "cmake_parser.error.cmakeerror": "https://roehling.github.io/cmake_parser/api/error.html#cmake_parser.error.CMakeError",
    "cmake_parser.error.cmakeexprerror": "https://roehling.github.io/cmake_parser/api/error.html#cmake_parser.error.CMakeExprError",
    "cmake_parser.error.cmakeparseerror": "https://roehling.github.io/cmake_parser/api/error.html#cmake_parser.error.CMakeParseError",
    "cmake_parser.interpreter": "https://roehling.github.io/cmake_parser/api/interpreter.html#module-cmake_parser.interpreter",
    "cmake_parser.interpreter.context": "https://roehling.github.io/cmake_parser/api/interpreter.html#cmake_parser.interpreter.Context",
    "cmake_parser.interpreter.context.exists": "https://roehling.github.io/cmake_parser/api/interpreter.html#cmake_parser.interpreter.Context.exists",
    "cmake_parser.interpreter.eval_bool_expr": "https://roehling.github.io/cmake_parser/api/interpreter.html#cmake_parser.interpreter.eval_bool_expr",
    "cmake_parser.interpreter.eval_expr": "https://roehling.github.io/cmake_parser/api/interpreter.html#cmake_parser.interpreter.eval_expr",
    "cmake_parser.interpreter.lookaheaditerator": "https://roehling.github.io/cmake_parser/api/interpreter.html#cmake_parser.interpreter.LookAheadIterator",
    "cmake_parser.interpreter.resolve_args": "https://roehling.github.io/cmake_parser/api/interpreter.html#cmake_parser.interpreter.resolve_args",
    "cmake_parser.lexer": "https://roehling.github.io/cmake_parser/api/lexer.html#module-cmake_parser.lexer",
    "cmake_parser.lexer.token": "https://roehling.github.io/cmake_parser/api/lexer.html#cmake_parser.lexer.Token",
    "cmake_parser.lexer.tokenize": "https://roehling.github.io/cmake_parser/api/lexer.html#cmake_parser.lexer.tokenize",
    "cmake_parser.parser": "https://roehling.github.io/cmake_parser/api/parser.html#module-cmake_parser.parser",
    "cmake_parser.parser.parse_raw": "https://roehling.github.io/cmake_parser/api/parser.html#cmake_parser.parser.parse_raw",
    "cmake_parser.parser.parse_tree": "https://roehling.github.io/cmake_parser/api/parser.html#cmake_parser.parser.parse_tree",
}
