VERSION = "2.0"

# fmt: off
MAPPING = {
    "cocotb_coverage": "https://cocotb-coverage.readthedocs.io/en/stable/",
    "cocotb_coverage.coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#module-cocotb_coverage.coverage",
    "cocotb_coverage.coverage.coverage_db": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.coverage_db",
    "cocotb_coverage.coverage.coverage_section": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.coverage_section",
    "cocotb_coverage.coverage.coveragedb": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverageDB",
    "cocotb_coverage.coverage.coveragedb.export_to_xml": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverageDB.export_to_xml",
    "cocotb_coverage.coverage.coveragedb.export_to_yaml": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverageDB.export_to_yaml",
    "cocotb_coverage.coverage.coveragedb.report_coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverageDB.report_coverage",
    "cocotb_coverage.coverage.coveragesection": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.coverageSection",
    "cocotb_coverage.coverage.covercheck": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverCheck",
    "cocotb_coverage.coverage.covercheck.coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverCheck.coverage",
    "cocotb_coverage.coverage.covercheck.detailed_coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverCheck.detailed_coverage",
    "cocotb_coverage.coverage.covercross": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverCross",
    "cocotb_coverage.coverage.covercross.coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverCross.coverage",
    "cocotb_coverage.coverage.covercross.detailed_coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverCross.detailed_coverage",
    "cocotb_coverage.coverage.coveritem": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem",
    "cocotb_coverage.coverage.coveritem.add_bins_callback": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem.add_bins_callback",
    "cocotb_coverage.coverage.coveritem.add_threshold_callback": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem.add_threshold_callback",
    "cocotb_coverage.coverage.coveritem.at_least": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem.at_least",
    "cocotb_coverage.coverage.coveritem.cover_percentage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem.cover_percentage",
    "cocotb_coverage.coverage.coveritem.coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem.coverage",
    "cocotb_coverage.coverage.coveritem.detailed_coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem.detailed_coverage",
    "cocotb_coverage.coverage.coveritem.new_hits": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem.new_hits",
    "cocotb_coverage.coverage.coveritem.size": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem.size",
    "cocotb_coverage.coverage.coveritem.weight": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverItem.weight",
    "cocotb_coverage.coverage.coverpoint": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverPoint",
    "cocotb_coverage.coverage.coverpoint.coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverPoint.coverage",
    "cocotb_coverage.coverage.coverpoint.detailed_coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.CoverPoint.detailed_coverage",
    "cocotb_coverage.coverage.merge_coverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.merge_coverage",
    "cocotb_coverage.coverage.reportcoverage": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.coverage.reportCoverage",
    "cocotb_coverage.crv": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#module-cocotb_coverage.crv",
    "cocotb_coverage.crv.randomized": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized",
    "cocotb_coverage.crv.randomized.add_constraint": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.add_constraint",
    "cocotb_coverage.crv.randomized.add_rand": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.add_rand",
    "cocotb_coverage.crv.randomized.addconstraint": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.addConstraint",
    "cocotb_coverage.crv.randomized.addrand": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.addRand",
    "cocotb_coverage.crv.randomized.del_constraint": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.del_constraint",
    "cocotb_coverage.crv.randomized.delconstraint": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.delConstraint",
    "cocotb_coverage.crv.randomized.post_randomize": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.post_randomize",
    "cocotb_coverage.crv.randomized.pre_randomize": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.pre_randomize",
    "cocotb_coverage.crv.randomized.randomize": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.randomize",
    "cocotb_coverage.crv.randomized.randomize_with": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.randomize_with",
    "cocotb_coverage.crv.randomized.solve_order": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.solve_order",
    "cocotb_coverage.crv.randomized.solveorder": "https://cocotb-coverage.readthedocs.io/en/stable/reference.html#cocotb_coverage.crv.Randomized.solveOrder",
}
