VERSION = "1.3.0"

# fmt: off
MAPPING = {
    "colormap": "https://colormap.readthedocs.io/en/stable/",
    "colormap.colors": "https://colormap.readthedocs.io/en/stable/references.html#module-colormap.colors",
    "colormap.colors.color": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color",
    "colormap.colors.color.blue": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.blue",
    "colormap.colors.color.get_standard_hex_color": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.get_standard_hex_color",
    "colormap.colors.color.green": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.green",
    "colormap.colors.color.hex": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.hex",
    "colormap.colors.color.hls": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.hls",
    "colormap.colors.color.hsv": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.hsv",
    "colormap.colors.color.hue": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.hue",
    "colormap.colors.color.is_valid_hex_color": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.is_valid_hex_color",
    "colormap.colors.color.lightness": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.lightness",
    "colormap.colors.color.red": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.red",
    "colormap.colors.color.rgb": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.rgb",
    "colormap.colors.color.saturation_hls": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.saturation_hls",
    "colormap.colors.color.value": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.value",
    "colormap.colors.color.yiq": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Color.yiq",
    "colormap.colors.colormap": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap",
    "colormap.colors.colormap.cmap": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap.cmap",
    "colormap.colors.colormap.cmap_bicolor": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap.cmap_bicolor",
    "colormap.colors.colormap.cmap_linear": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap.cmap_linear",
    "colormap.colors.colormap.get_cmap_heat": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap.get_cmap_heat",
    "colormap.colors.colormap.get_cmap_heat_r": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap.get_cmap_heat_r",
    "colormap.colors.colormap.get_cmap_rainbow": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap.get_cmap_rainbow",
    "colormap.colors.colormap.plot_colormap": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap.plot_colormap",
    "colormap.colors.colormap.plot_rgb_from_hex_list": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap.plot_rgb_from_hex_list",
    "colormap.colors.colormap.test_colormap": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.Colormap.test_colormap",
    "colormap.colors.hex": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.HEX",
    "colormap.colors.hex.get_standard_hex_color": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.HEX.get_standard_hex_color",
    "colormap.colors.hex.is_valid_hex_color": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.HEX.is_valid_hex_color",
    "colormap.colors.hex2dec": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.hex2dec",
    "colormap.colors.hex2rgb": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.hex2rgb",
    "colormap.colors.hex2web": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.hex2web",
    "colormap.colors.hls2rgb": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.hls2rgb",
    "colormap.colors.hsv2rgb": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.hsv2rgb",
    "colormap.colors.rgb2hex": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.rgb2hex",
    "colormap.colors.rgb2hls": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.rgb2hls",
    "colormap.colors.rgb2hsv": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.rgb2hsv",
    "colormap.colors.rgb2yuv": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.rgb2yuv",
    "colormap.colors.rgb2yuv_int": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.rgb2yuv_int",
    "colormap.colors.to_intensity": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.to_intensity",
    "colormap.colors.web2hex": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.web2hex",
    "colormap.colors.yuv2rgb": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.yuv2rgb",
    "colormap.colors.yuv2rgb_int": "https://colormap.readthedocs.io/en/stable/references.html#colormap.colors.yuv2rgb_int",
    "colormap.get_cmap": "https://colormap.readthedocs.io/en/stable/references.html#module-colormap.get_cmap",
    "colormap.xfree86": "https://colormap.readthedocs.io/en/stable/references.html#module-colormap.xfree86",
}
