VERSION = "0.13.0"

# fmt: off
MAPPING = {
    "conda_package_streaming": "https://conda.github.io/conda-package-streaming/",
    "conda_package_streaming.create": "https://conda.github.io/conda-package-streaming/create.html#module-conda_package_streaming.create",
    "conda_package_streaming.create.anonymize": "https://conda.github.io/conda-package-streaming/create.html#conda_package_streaming.create.anonymize",
    "conda_package_streaming.create.conda_builder": "https://conda.github.io/conda-package-streaming/create.html#conda_package_streaming.create.conda_builder",
    "conda_package_streaming.create.condatarfile": "https://conda.github.io/conda-package-streaming/create.html#conda_package_streaming.create.CondaTarFile",
    "conda_package_streaming.create.condatarfile.addfile": "https://conda.github.io/conda-package-streaming/create.html#conda_package_streaming.create.CondaTarFile.addfile",
    "conda_package_streaming.create.condatarfile.info_tar": "https://conda.github.io/conda-package-streaming/create.html#conda_package_streaming.create.CondaTarFile.info_tar",
    "conda_package_streaming.create.condatarfile.is_info": "https://conda.github.io/conda-package-streaming/create.html#conda_package_streaming.create.CondaTarFile.is_info",
    "conda_package_streaming.extract": "https://conda.github.io/conda-package-streaming/extract.html#module-conda_package_streaming.extract",
    "conda_package_streaming.extract.extract": "https://conda.github.io/conda-package-streaming/extract.html#conda_package_streaming.extract.extract",
    "conda_package_streaming.extract.extract_stream": "https://conda.github.io/conda-package-streaming/extract.html#conda_package_streaming.extract.extract_stream",
    "conda_package_streaming.lazy_wheel": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#module-conda_package_streaming.lazy_wheel",
    "conda_package_streaming.lazy_wheel.httprangerequestunsupported": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.HTTPRangeRequestUnsupported",
    "conda_package_streaming.lazy_wheel.lazyconda": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyConda",
    "conda_package_streaming.lazy_wheel.lazyconda.prefetch": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyConda.prefetch",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.close": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.close",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.closed": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.closed",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.mode": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.mode",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.name": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.name",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.read": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.read",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.readable": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.readable",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.seek": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.seek",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.seekable": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.seekable",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.tell": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.tell",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.truncate": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.truncate",
    "conda_package_streaming.lazy_wheel.lazyzipoverhttp.writable": "https://conda.github.io/conda-package-streaming/lazy_wheel.html#conda_package_streaming.lazy_wheel.LazyZipOverHTTP.writable",
    "conda_package_streaming.package_streaming": "https://conda.github.io/conda-package-streaming/package_streaming.html#module-conda_package_streaming.package_streaming",
    "conda_package_streaming.package_streaming.condacomponent": "https://conda.github.io/conda-package-streaming/package_streaming.html#conda_package_streaming.package_streaming.CondaComponent",
    "conda_package_streaming.package_streaming.condacomponent.info": "https://conda.github.io/conda-package-streaming/package_streaming.html#conda_package_streaming.package_streaming.CondaComponent.info",
    "conda_package_streaming.package_streaming.condacomponent.pkg": "https://conda.github.io/conda-package-streaming/package_streaming.html#conda_package_streaming.package_streaming.CondaComponent.pkg",
    "conda_package_streaming.package_streaming.stream_conda_component": "https://conda.github.io/conda-package-streaming/package_streaming.html#conda_package_streaming.package_streaming.stream_conda_component",
    "conda_package_streaming.package_streaming.stream_conda_info": "https://conda.github.io/conda-package-streaming/package_streaming.html#conda_package_streaming.package_streaming.stream_conda_info",
    "conda_package_streaming.package_streaming.tar_generator": "https://conda.github.io/conda-package-streaming/package_streaming.html#conda_package_streaming.package_streaming.tar_generator",
    "conda_package_streaming.package_streaming.tarfilenosameowner": "https://conda.github.io/conda-package-streaming/package_streaming.html#conda_package_streaming.package_streaming.TarfileNoSameOwner",
    "conda_package_streaming.package_streaming.tarfilenosameowner.chmod": "https://conda.github.io/conda-package-streaming/package_streaming.html#conda_package_streaming.package_streaming.TarfileNoSameOwner.chmod",
    "conda_package_streaming.package_streaming.tarfilenosameowner.chown": "https://conda.github.io/conda-package-streaming/package_streaming.html#conda_package_streaming.package_streaming.TarfileNoSameOwner.chown",
    "conda_package_streaming.s3": "https://conda.github.io/conda-package-streaming/s3.html#module-conda_package_streaming.s3",
    "conda_package_streaming.s3.conda_reader_for_s3": "https://conda.github.io/conda-package-streaming/s3.html#conda_package_streaming.s3.conda_reader_for_s3",
    "conda_package_streaming.s3.stream_conda_info": "https://conda.github.io/conda-package-streaming/s3.html#conda_package_streaming.s3.stream_conda_info",
    "conda_package_streaming.transmute": "https://conda.github.io/conda-package-streaming/transmute.html#module-conda_package_streaming.transmute",
    "conda_package_streaming.transmute.transmute": "https://conda.github.io/conda-package-streaming/transmute.html#conda_package_streaming.transmute.transmute",
    "conda_package_streaming.transmute.transmute_stream": "https://conda.github.io/conda-package-streaming/transmute.html#conda_package_streaming.transmute.transmute_stream",
    "conda_package_streaming.transmute.transmute_tar_bz2": "https://conda.github.io/conda-package-streaming/transmute.html#conda_package_streaming.transmute.transmute_tar_bz2",
    "conda_package_streaming.url": "https://conda.github.io/conda-package-streaming/url.html#module-conda_package_streaming.url",
    "conda_package_streaming.url.conda_reader_for_url": "https://conda.github.io/conda-package-streaming/url.html#conda_package_streaming.url.conda_reader_for_url",
    "conda_package_streaming.url.extract_conda_info": "https://conda.github.io/conda-package-streaming/url.html#conda_package_streaming.url.extract_conda_info",
    "conda_package_streaming.url.stream_conda_info": "https://conda.github.io/conda-package-streaming/url.html#conda_package_streaming.url.stream_conda_info",
}
