VERSION = "9.17.2"

# fmt: off
MAPPING = {
    "copier": "https://copier.readthedocs.io/en/stable/",
    "copier.errors": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors",
    "copier.errors.configfileerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.ConfigFileError",
    "copier.errors.copieranswersinterrupt": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.CopierAnswersInterrupt",
    "copier.errors.copiererror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.CopierError",
    "copier.errors.copierwarning": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.CopierWarning",
    "copier.errors.dirtylocalwarning": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.DirtyLocalWarning",
    "copier.errors.extensionnotfounderror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.ExtensionNotFoundError",
    "copier.errors.forbiddenpatherror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.ForbiddenPathError",
    "copier.errors.interactivesessionerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.InteractiveSessionError",
    "copier.errors.invalidconfigfileerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.InvalidConfigFileError",
    "copier.errors.invalidtypeerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.InvalidTypeError",
    "copier.errors.missingfilewarning": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.MissingFileWarning",
    "copier.errors.missingsettingswarning": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.MissingSettingsWarning",
    "copier.errors.multipleconfigfileserror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.MultipleConfigFilesError",
    "copier.errors.multipleyieldtagserror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.MultipleYieldTagsError",
    "copier.errors.oldtemplatewarning": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.OldTemplateWarning",
    "copier.errors.patherror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.PathError",
    "copier.errors.pathnotabsoluteerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.PathNotAbsoluteError",
    "copier.errors.pathnotrelativeerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.PathNotRelativeError",
    "copier.errors.shallowclonewarning": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.ShallowCloneWarning",
    "copier.errors.taskerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.TaskError",
    "copier.errors.taskerror.from_process": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.TaskError.from_process",
    "copier.errors.unknowncopierversionwarning": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.UnknownCopierVersionWarning",
    "copier.errors.unsafetemplateerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.UnsafeTemplateError",
    "copier.errors.unsupportedversionerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.UnsupportedVersionError",
    "copier.errors.usermessageerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.UserMessageError",
    "copier.errors.yieldtaginfileerror": "https://copier.readthedocs.io/en/stable/reference/api/#copier.errors.YieldTagInFileError",
    "copier.load_settings": "https://copier.readthedocs.io/en/stable/reference/api/#copier.load_settings",
    "copier.phase": "https://copier.readthedocs.io/en/stable/reference/api/#copier.Phase",
    "copier.phase.current": "https://copier.readthedocs.io/en/stable/reference/api/#copier.Phase.current",
    "copier.phase.use": "https://copier.readthedocs.io/en/stable/reference/api/#copier.Phase.use",
    "copier.run_copy": "https://copier.readthedocs.io/en/stable/reference/api/#copier.run_copy",
    "copier.run_recopy": "https://copier.readthedocs.io/en/stable/reference/api/#copier.run_recopy",
    "copier.run_update": "https://copier.readthedocs.io/en/stable/reference/api/#copier.run_update",
    "copier.settings": "https://copier.readthedocs.io/en/stable/reference/api/#copier.Settings",
    "copier.settings.defaults": "https://copier.readthedocs.io/en/stable/reference/api/#copier.Settings.defaults",
    "copier.settings.trust": "https://copier.readthedocs.io/en/stable/reference/api/#copier.Settings.trust",
    "copier.vcsref": "https://copier.readthedocs.io/en/stable/reference/api/#copier.VcsRef",
    "copier.vcsref.current": "https://copier.readthedocs.io/en/stable/reference/api/#copier.VcsRef.CURRENT",
}
