VERSION = "1.3.3"

# fmt: off
MAPPING = {
    "csaps": "https://csaps.readthedocs.io/en/stable/",
    "csaps._shortcut": "https://csaps.readthedocs.io/en/stable/api.html",
    "csaps._shortcut.autosmoothingresult": "https://csaps.readthedocs.io/en/stable/api.html#csaps.AutoSmoothingResult",
    "csaps.autosmoothingresult": "https://csaps.readthedocs.io/en/stable/api.html#csaps.AutoSmoothingResult",
    "csaps.autosmoothingresult.smooth": "https://csaps.readthedocs.io/en/stable/api.html#csaps.AutoSmoothingResult.smooth",
    "csaps.autosmoothingresult.values": "https://csaps.readthedocs.io/en/stable/api.html#csaps.AutoSmoothingResult.values",
    "csaps.csaps": "https://csaps.readthedocs.io/en/stable/api.html#csaps.csaps",
    "csaps.cubicsmoothingspline": "https://csaps.readthedocs.io/en/stable/api.html#csaps.CubicSmoothingSpline",
    "csaps.cubicsmoothingspline.__call__": "https://csaps.readthedocs.io/en/stable/api.html#csaps.CubicSmoothingSpline.__call__",
    "csaps.cubicsmoothingspline.smooth": "https://csaps.readthedocs.io/en/stable/api.html#csaps.CubicSmoothingSpline.smooth",
    "csaps.cubicsmoothingspline.spline": "https://csaps.readthedocs.io/en/stable/api.html#csaps.CubicSmoothingSpline.spline",
    "csaps.ismoothingspline": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISmoothingSpline",
    "csaps.ismoothingspline.__call__": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISmoothingSpline.__call__",
    "csaps.ismoothingspline.smooth": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISmoothingSpline.smooth",
    "csaps.ismoothingspline.spline": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISmoothingSpline.spline",
    "csaps.isplineppform": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISplinePPForm",
    "csaps.isplineppform.breaks": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISplinePPForm.breaks",
    "csaps.isplineppform.coeffs": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISplinePPForm.coeffs",
    "csaps.isplineppform.ndim": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISplinePPForm.ndim",
    "csaps.isplineppform.order": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISplinePPForm.order",
    "csaps.isplineppform.pieces": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISplinePPForm.pieces",
    "csaps.isplineppform.shape": "https://csaps.readthedocs.io/en/stable/api.html#csaps.ISplinePPForm.shape",
    "csaps.ndgridcubicsmoothingspline": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridCubicSmoothingSpline",
    "csaps.ndgridcubicsmoothingspline.__call__": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridCubicSmoothingSpline.__call__",
    "csaps.ndgridcubicsmoothingspline.smooth": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridCubicSmoothingSpline.smooth",
    "csaps.ndgridcubicsmoothingspline.spline": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridCubicSmoothingSpline.spline",
    "csaps.ndgridsplineppform": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridSplinePPForm",
    "csaps.ndgridsplineppform.breaks": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridSplinePPForm.breaks",
    "csaps.ndgridsplineppform.coeffs": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridSplinePPForm.coeffs",
    "csaps.ndgridsplineppform.ndim": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridSplinePPForm.ndim",
    "csaps.ndgridsplineppform.order": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridSplinePPForm.order",
    "csaps.ndgridsplineppform.pieces": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridSplinePPForm.pieces",
    "csaps.ndgridsplineppform.shape": "https://csaps.readthedocs.io/en/stable/api.html#csaps.NdGridSplinePPForm.shape",
    "csaps.splineppform": "https://csaps.readthedocs.io/en/stable/api.html#csaps.SplinePPForm",
    "csaps.splineppform.breaks": "https://csaps.readthedocs.io/en/stable/api.html#csaps.SplinePPForm.breaks",
    "csaps.splineppform.coeffs": "https://csaps.readthedocs.io/en/stable/api.html#csaps.SplinePPForm.coeffs",
    "csaps.splineppform.ndim": "https://csaps.readthedocs.io/en/stable/api.html#csaps.SplinePPForm.ndim",
    "csaps.splineppform.order": "https://csaps.readthedocs.io/en/stable/api.html#csaps.SplinePPForm.order",
    "csaps.splineppform.pieces": "https://csaps.readthedocs.io/en/stable/api.html#csaps.SplinePPForm.pieces",
    "csaps.splineppform.shape": "https://csaps.readthedocs.io/en/stable/api.html#csaps.SplinePPForm.shape",
}
