VERSION = "3.4.0"

# fmt: off
MAPPING = {
    "daiquiri": "https://daiquiri.readthedocs.io/en/stable/",
    "daiquiri.formatter": "https://daiquiri.readthedocs.io/en/stable/index.html#module-daiquiri.formatter",
    "daiquiri.formatter.colorextrasformatter": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.formatter.ColorExtrasFormatter",
    "daiquiri.formatter.colorextrasformatter.format": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.formatter.ColorExtrasFormatter.format",
    "daiquiri.formatter.colorformatter": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.formatter.ColorFormatter",
    "daiquiri.formatter.colorformatter.format": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.formatter.ColorFormatter.format",
    "daiquiri.formatter.datadogformatter": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.formatter.DatadogFormatter",
    "daiquiri.formatter.datadogformatter.add_fields": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.formatter.DatadogFormatter.add_fields",
    "daiquiri.formatter.extrasformatter": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.formatter.ExtrasFormatter",
    "daiquiri.formatter.extrasformatter.format": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.formatter.ExtrasFormatter.format",
    "daiquiri.getlogger": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.getLogger",
    "daiquiri.handlers": "https://daiquiri.readthedocs.io/en/stable/index.html#module-daiquiri.handlers",
    "daiquiri.handlers.journalhandler": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.handlers.JournalHandler",
    "daiquiri.handlers.journalhandler.emit": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.handlers.JournalHandler.emit",
    "daiquiri.handlers.plaintextsockethandler": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.handlers.PlainTextSocketHandler",
    "daiquiri.handlers.plaintextsockethandler.makepickle": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.handlers.PlainTextSocketHandler.makePickle",
    "daiquiri.handlers.sysloghandler": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.handlers.SyslogHandler",
    "daiquiri.handlers.sysloghandler.emit": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.handlers.SyslogHandler.emit",
    "daiquiri.handlers.ttydetectorstreamhandler": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.handlers.TTYDetectorStreamHandler",
    "daiquiri.handlers.ttydetectorstreamhandler.format": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.handlers.TTYDetectorStreamHandler.format",
    "daiquiri.keywordargumentadapter": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.KeywordArgumentAdapter",
    "daiquiri.keywordargumentadapter.process": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.KeywordArgumentAdapter.process",
    "daiquiri.keywordargumentadapter.setlevel": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.KeywordArgumentAdapter.setLevel",
    "daiquiri.output": "https://daiquiri.readthedocs.io/en/stable/index.html#module-daiquiri.output",
    "daiquiri.output.datadog": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.Datadog",
    "daiquiri.output.file": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.File",
    "daiquiri.output.journal": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.Journal",
    "daiquiri.output.output": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.Output",
    "daiquiri.output.output.add_to_logger": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.Output.add_to_logger",
    "daiquiri.output.rotatingfile": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.RotatingFile",
    "daiquiri.output.rotatingfile.do_rollover": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.RotatingFile.do_rollover",
    "daiquiri.output.stream": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.Stream",
    "daiquiri.output.syslog": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.Syslog",
    "daiquiri.output.timedrotatingfile": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.TimedRotatingFile",
    "daiquiri.output.timedrotatingfile.do_rollover": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.output.TimedRotatingFile.do_rollover",
    "daiquiri.parse_and_set_default_log_levels": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.parse_and_set_default_log_levels",
    "daiquiri.set_default_log_levels": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.set_default_log_levels",
    "daiquiri.setup": "https://daiquiri.readthedocs.io/en/stable/index.html#daiquiri.setup",
}
