VERSION = "2026.3.0"

# fmt: off
MAPPING = {
    "dask_gateway": "https://gateway.dask.org/",
    "dask_gateway.auth": "https://gateway.dask.org/api-client.html",
    "dask_gateway.auth.basicauth": "https://gateway.dask.org/api-client.html#dask_gateway.auth.BasicAuth",
    "dask_gateway.auth.gatewayauth": "https://gateway.dask.org/api-client.html#dask_gateway.auth.GatewayAuth",
    "dask_gateway.auth.jupyterhubauth": "https://gateway.dask.org/api-client.html#dask_gateway.auth.JupyterHubAuth",
    "dask_gateway.auth.kerberosauth": "https://gateway.dask.org/api-client.html#dask_gateway.auth.KerberosAuth",
    "dask_gateway.client": "https://gateway.dask.org/api-client.html",
    "dask_gateway.client.gateway": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway",
    "dask_gateway.client.gatewaycluster": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayCluster",
    "dask_gateway.client.gatewayclustererror": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayClusterError",
    "dask_gateway.client.gatewayservererror": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayServerError",
    "dask_gateway.gateway": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway",
    "dask_gateway.gateway.adapt_cluster": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.adapt_cluster",
    "dask_gateway.gateway.close": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.close",
    "dask_gateway.gateway.cluster_options": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.cluster_options",
    "dask_gateway.gateway.connect": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.connect",
    "dask_gateway.gateway.get_cluster": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.get_cluster",
    "dask_gateway.gateway.get_versions": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.get_versions",
    "dask_gateway.gateway.list_clusters": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.list_clusters",
    "dask_gateway.gateway.new_cluster": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.new_cluster",
    "dask_gateway.gateway.scale_cluster": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.scale_cluster",
    "dask_gateway.gateway.stop_cluster": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.stop_cluster",
    "dask_gateway.gateway.submit": "https://gateway.dask.org/api-client.html#dask_gateway.Gateway.submit",
    "dask_gateway.gatewaycluster": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayCluster",
    "dask_gateway.gatewaycluster.adapt": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayCluster.adapt",
    "dask_gateway.gatewaycluster.close": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayCluster.close",
    "dask_gateway.gatewaycluster.from_name": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayCluster.from_name",
    "dask_gateway.gatewaycluster.get_client": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayCluster.get_client",
    "dask_gateway.gatewaycluster.scale": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayCluster.scale",
    "dask_gateway.gatewaycluster.shutdown": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayCluster.shutdown",
    "dask_gateway.gatewayclustererror": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayClusterError",
    "dask_gateway.gatewayservererror": "https://gateway.dask.org/api-client.html#dask_gateway.GatewayServerError",
    "dask_gateway.options": "https://gateway.dask.org/api-client.html",
    "dask_gateway.options.options": "https://gateway.dask.org/api-client.html#dask_gateway.options.Options",
}
