VERSION = "2024.5.0"

# fmt: off
MAPPING = {
    "dask_sql": "https://dask-sql.readthedocs.io/en/stable/",
    "dask_sql.cmd_loop": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.cmd_loop",
    "dask_sql.context": "https://dask-sql.readthedocs.io/en/stable/api.html",
    "dask_sql.Context": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context",
    "dask_sql.context.alter_schema": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.alter_schema",
    "dask_sql.context.alter_table": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.alter_table",
    "dask_sql.context.context": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context",
    "dask_sql.context.create_schema": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.create_schema",
    "dask_sql.context.create_table": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.create_table",
    "dask_sql.context.default_catalog_name": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.DEFAULT_CATALOG_NAME",
    "dask_sql.context.default_schema_name": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.DEFAULT_SCHEMA_NAME",
    "dask_sql.context.drop_schema": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.drop_schema",
    "dask_sql.context.drop_table": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.drop_table",
    "dask_sql.context.explain": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.explain",
    "dask_sql.context.fqn": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.fqn",
    "dask_sql.context.ipython_magic": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.ipython_magic",
    "dask_sql.context.register_aggregation": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.register_aggregation",
    "dask_sql.context.register_experiment": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.register_experiment",
    "dask_sql.context.register_function": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.register_function",
    "dask_sql.context.register_model": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.register_model",
    "dask_sql.context.run_server": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.run_server",
    "dask_sql.context.sql": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.sql",
    "dask_sql.context.stop_server": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.stop_server",
    "dask_sql.context.visualize": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.Context.visualize",
    "dask_sql.integrations": "https://dask-sql.readthedocs.io/en/stable/api.html",
    "dask_sql.integrations.fugue": "https://dask-sql.readthedocs.io/en/stable/api.html",
    "dask_sql.integrations.fugue.dasksqlexecutionengine": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.integrations.fugue.DaskSQLExecutionEngine",
    "dask_sql.integrations.fugue.fsql_dask": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.integrations.fugue.fsql_dask",
    "dask_sql.run_server": "https://dask-sql.readthedocs.io/en/stable/api.html#dask_sql.run_server",
}
