VERSION = "2026.2.1"

# fmt: off
MAPPING = {
    "dask_awkward": "https://dask-awkward.readthedocs.io/en/stable/",
    "dask_awkward.array": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.Array.html#dask_awkward.Array",
    "dask_awkward.array.__init__": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.Array.html#dask_awkward.Array.__init__",
    "dask_awkward.dask_method": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.dask_method.html#dask_awkward.dask_method",
    "dask_awkward.dask_property": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.dask_property.html#dask_awkward.dask_property",
    "dask_awkward.from_awkward": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.from_awkward.html#dask_awkward.from_awkward",
    "dask_awkward.from_dask_array": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.from_dask_array.html#dask_awkward.from_dask_array",
    "dask_awkward.from_delayed": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.from_delayed.html#dask_awkward.from_delayed",
    "dask_awkward.from_json": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.from_json.html#dask_awkward.from_json",
    "dask_awkward.from_lists": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.from_lists.html#dask_awkward.from_lists",
    "dask_awkward.from_map": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.from_map.html#dask_awkward.from_map",
    "dask_awkward.from_parquet": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.from_parquet.html#dask_awkward.from_parquet",
    "dask_awkward.from_text": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.from_text.html#dask_awkward.from_text",
    "dask_awkward.lib.core.array": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.Array.html#dask_awkward.Array",
    "dask_awkward.lib.core.partitioncompatibility": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.PartitionCompatibility.html#dask_awkward.PartitionCompatibility",
    "dask_awkward.lib.core.record": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.Record.html#dask_awkward.Record",
    "dask_awkward.lib.core.scalar": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.Scalar.html#dask_awkward.Scalar",
    "dask_awkward.partition_compatibility": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.partition_compatibility.html#dask_awkward.partition_compatibility",
    "dask_awkward.partitioncompatibility": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.PartitionCompatibility.html#dask_awkward.PartitionCompatibility",
    "dask_awkward.partitioncompatibility.__init__": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.PartitionCompatibility.html#dask_awkward.PartitionCompatibility.__init__",
    "dask_awkward.partitioncompatibility.maybe": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.PartitionCompatibility.html#dask_awkward.PartitionCompatibility.MAYBE",
    "dask_awkward.partitioncompatibility.no": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.PartitionCompatibility.html#dask_awkward.PartitionCompatibility.NO",
    "dask_awkward.partitioncompatibility.yes": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.PartitionCompatibility.html#dask_awkward.PartitionCompatibility.YES",
    "dask_awkward.record": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.Record.html#dask_awkward.Record",
    "dask_awkward.record.__init__": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.Record.html#dask_awkward.Record.__init__",
    "dask_awkward.report_necessary_buffers": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.report_necessary_buffers.html#dask_awkward.report_necessary_buffers",
    "dask_awkward.report_necessary_columns": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.report_necessary_columns.html#dask_awkward.report_necessary_columns",
    "dask_awkward.sample": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.sample.html#dask_awkward.sample",
    "dask_awkward.scalar": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.Scalar.html#dask_awkward.Scalar",
    "dask_awkward.scalar.__init__": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.Scalar.html#dask_awkward.Scalar.__init__",
    "dask_awkward.to_dask_array": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.to_dask_array.html#dask_awkward.to_dask_array",
    "dask_awkward.to_dask_bag": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.to_dask_bag.html#dask_awkward.to_dask_bag",
    "dask_awkward.to_dataframe": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.to_dataframe.html#dask_awkward.to_dataframe",
    "dask_awkward.to_delayed": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.to_delayed.html#dask_awkward.to_delayed",
    "dask_awkward.to_json": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.to_json.html#dask_awkward.to_json",
    "dask_awkward.to_parquet": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.to_parquet.html#dask_awkward.to_parquet",
    "dask_awkward.utils.concretizationtypeerror": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.utils.ConcretizationTypeError.html#dask_awkward.utils.ConcretizationTypeError",
    "dask_awkward.utils.incompatiblepartitions": "https://dask-awkward.readthedocs.io/en/stable/api/generated/dask_awkward.utils.IncompatiblePartitions.html#dask_awkward.utils.IncompatiblePartitions",
}
