VERSION = "0.4.0"

# fmt: off
MAPPING = {
    "dask_glm": "https://dask-glm.readthedocs.io/en/latest/",
    "dask_glm.algorithms": "https://dask-glm.readthedocs.io/en/latest/api.html#module-dask_glm.algorithms",
    "dask_glm.algorithms.admm": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.algorithms.admm",
    "dask_glm.algorithms.compute_stepsize_dask": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.algorithms.compute_stepsize_dask",
    "dask_glm.algorithms.gradient_descent": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.algorithms.gradient_descent",
    "dask_glm.algorithms.lbfgs": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.algorithms.lbfgs",
    "dask_glm.algorithms.newton": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.algorithms.newton",
    "dask_glm.algorithms.proximal_grad": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.algorithms.proximal_grad",
    "dask_glm.estimators": "https://dask-glm.readthedocs.io/en/latest/api.html#module-dask_glm.estimators",
    "dask_glm.estimators.linearregression": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.estimators.LinearRegression",
    "dask_glm.estimators.logisticregression": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.estimators.LogisticRegression",
    "dask_glm.estimators.poissonregression": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.estimators.PoissonRegression",
    "dask_glm.families": "https://dask-glm.readthedocs.io/en/latest/api.html#module-dask_glm.families",
    "dask_glm.families.logistic": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.families.Logistic",
    "dask_glm.families.logistic.gradient": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.families.Logistic.gradient",
    "dask_glm.families.logistic.hessian": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.families.Logistic.hessian",
    "dask_glm.families.logistic.loglike": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.families.Logistic.loglike",
    "dask_glm.families.logistic.pointwise_gradient": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.families.Logistic.pointwise_gradient",
    "dask_glm.families.logistic.pointwise_loss": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.families.Logistic.pointwise_loss",
    "dask_glm.families.normal": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.families.Normal",
    "dask_glm.families.poisson": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.families.Poisson",
    "dask_glm.regularizers": "https://dask-glm.readthedocs.io/en/latest/api.html#module-dask_glm.regularizers",
    "dask_glm.regularizers.elasticnet": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.ElasticNet",
    "dask_glm.regularizers.elasticnet.proximal_operator": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.ElasticNet.proximal_operator",
    "dask_glm.regularizers.l1": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.L1",
    "dask_glm.regularizers.l2": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.L2",
    "dask_glm.regularizers.regularizer": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.Regularizer",
    "dask_glm.regularizers.regularizer.add_reg_f": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.Regularizer.add_reg_f",
    "dask_glm.regularizers.regularizer.add_reg_grad": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.Regularizer.add_reg_grad",
    "dask_glm.regularizers.regularizer.add_reg_hessian": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.Regularizer.add_reg_hessian",
    "dask_glm.regularizers.regularizer.f": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.Regularizer.f",
    "dask_glm.regularizers.regularizer.get": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.Regularizer.get",
    "dask_glm.regularizers.regularizer.gradient": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.Regularizer.gradient",
    "dask_glm.regularizers.regularizer.hessian": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.Regularizer.hessian",
    "dask_glm.regularizers.regularizer.proximal_operator": "https://dask-glm.readthedocs.io/en/latest/api.html#dask_glm.regularizers.Regularizer.proximal_operator",
}
