VERSION = "0.7"

# fmt: off
MAPPING = {
    "dcor": "https://dcor.readthedocs.io/en/stable/",
    "dcor._dcor.distancecovariancemethod": "https://dcor.readthedocs.io/en/stable/functions/dcor.DistanceCovarianceMethod.html#dcor.DistanceCovarianceMethod",
    "dcor._dcor.stats": "https://dcor.readthedocs.io/en/stable/functions/dcor.Stats.html#dcor.Stats",
    "dcor._energy": "https://dcor.readthedocs.io/en/stable/functions/dcor.EstimationStatistic.html",
    "dcor._energy.estimationstatistic": "https://dcor.readthedocs.io/en/stable/functions/dcor.EstimationStatistic.html#dcor.EstimationStatistic",
    "dcor._hypothesis": "https://dcor.readthedocs.io/en/stable/functions/dcor.HypothesisTest.html",
    "dcor._hypothesis.hypothesistest": "https://dcor.readthedocs.io/en/stable/functions/dcor.HypothesisTest.html#dcor.HypothesisTest",
    "dcor._utils.compilemode": "https://dcor.readthedocs.io/en/stable/functions/dcor.CompileMode.html#dcor.CompileMode",
    "dcor._utils.rowwisemode": "https://dcor.readthedocs.io/en/stable/functions/dcor.RowwiseMode.html#dcor.RowwiseMode",
    "dcor.compilemode": "https://dcor.readthedocs.io/en/stable/functions/dcor.CompileMode.html#dcor.CompileMode",
    "dcor.distance_correlation": "https://dcor.readthedocs.io/en/stable/functions/dcor.distance_correlation.html#dcor.distance_correlation",
    "dcor.distance_correlation_af_inv": "https://dcor.readthedocs.io/en/stable/functions/dcor.distance_correlation_af_inv.html#dcor.distance_correlation_af_inv",
    "dcor.distance_correlation_af_inv_sqr": "https://dcor.readthedocs.io/en/stable/functions/dcor.distance_correlation_af_inv_sqr.html#dcor.distance_correlation_af_inv_sqr",
    "dcor.distance_correlation_sqr": "https://dcor.readthedocs.io/en/stable/functions/dcor.distance_correlation_sqr.html#dcor.distance_correlation_sqr",
    "dcor.distance_covariance": "https://dcor.readthedocs.io/en/stable/functions/dcor.distance_covariance.html#dcor.distance_covariance",
    "dcor.distance_covariance_sqr": "https://dcor.readthedocs.io/en/stable/functions/dcor.distance_covariance_sqr.html#dcor.distance_covariance_sqr",
    "dcor.distance_stats": "https://dcor.readthedocs.io/en/stable/functions/dcor.distance_stats.html#dcor.distance_stats",
    "dcor.distance_stats_sqr": "https://dcor.readthedocs.io/en/stable/functions/dcor.distance_stats_sqr.html#dcor.distance_stats_sqr",
    "dcor.distancecovariancemethod": "https://dcor.readthedocs.io/en/stable/functions/dcor.DistanceCovarianceMethod.html#dcor.DistanceCovarianceMethod",
    "dcor.distances": "https://dcor.readthedocs.io/en/stable/functions/dcor.distances.pairwise_distances.html",
    "dcor.distances.pairwise_distances": "https://dcor.readthedocs.io/en/stable/functions/dcor.distances.pairwise_distances.html#dcor.distances.pairwise_distances",
    "dcor.double_centered": "https://dcor.readthedocs.io/en/stable/functions/dcor.double_centered.html#dcor.double_centered",
    "dcor.energy_distance": "https://dcor.readthedocs.io/en/stable/functions/dcor.energy_distance.html#dcor.energy_distance",
    "dcor.estimationstatistic": "https://dcor.readthedocs.io/en/stable/functions/dcor.EstimationStatistic.html#dcor.EstimationStatistic",
    "dcor.estimationstatistic.from_string": "https://dcor.readthedocs.io/en/stable/functions/dcor.EstimationStatistic.html#dcor.EstimationStatistic.from_string",
    "dcor.homogeneity.energy_test": "https://dcor.readthedocs.io/en/stable/functions/dcor.homogeneity.energy_test.html#dcor.homogeneity.energy_test",
    "dcor.homogeneity.energy_test_statistic": "https://dcor.readthedocs.io/en/stable/functions/dcor.homogeneity.energy_test_statistic.html#dcor.homogeneity.energy_test_statistic",
    "dcor.hypothesistest": "https://dcor.readthedocs.io/en/stable/functions/dcor.HypothesisTest.html#dcor.HypothesisTest",
    "dcor.hypothesistest.__init__": "https://dcor.readthedocs.io/en/stable/functions/dcor.HypothesisTest.html#dcor.HypothesisTest.__init__",
    "dcor.independence.distance_correlation_t_statistic": "https://dcor.readthedocs.io/en/stable/functions/dcor.independence.distance_correlation_t_statistic.html#dcor.independence.distance_correlation_t_statistic",
    "dcor.independence.distance_correlation_t_test": "https://dcor.readthedocs.io/en/stable/functions/dcor.independence.distance_correlation_t_test.html#dcor.independence.distance_correlation_t_test",
    "dcor.independence.distance_covariance_test": "https://dcor.readthedocs.io/en/stable/functions/dcor.independence.distance_covariance_test.html#dcor.independence.distance_covariance_test",
    "dcor.mean_product": "https://dcor.readthedocs.io/en/stable/functions/dcor.mean_product.html#dcor.mean_product",
    "dcor.partial_distance_correlation": "https://dcor.readthedocs.io/en/stable/functions/dcor.partial_distance_correlation.html#dcor.partial_distance_correlation",
    "dcor.partial_distance_covariance": "https://dcor.readthedocs.io/en/stable/functions/dcor.partial_distance_covariance.html#dcor.partial_distance_covariance",
    "dcor.rowwise": "https://dcor.readthedocs.io/en/stable/functions/dcor.rowwise.html#dcor.rowwise",
    "dcor.rowwisemode": "https://dcor.readthedocs.io/en/stable/functions/dcor.RowwiseMode.html#dcor.RowwiseMode",
    "dcor.stats": "https://dcor.readthedocs.io/en/stable/functions/dcor.Stats.html#dcor.Stats",
    "dcor.stats.__init__": "https://dcor.readthedocs.io/en/stable/functions/dcor.Stats.html#dcor.Stats.__init__",
    "dcor.u_centered": "https://dcor.readthedocs.io/en/stable/functions/dcor.u_centered.html#dcor.u_centered",
    "dcor.u_complementary_projection": "https://dcor.readthedocs.io/en/stable/functions/dcor.u_complementary_projection.html#dcor.u_complementary_projection",
    "dcor.u_distance_correlation_sqr": "https://dcor.readthedocs.io/en/stable/functions/dcor.u_distance_correlation_sqr.html#dcor.u_distance_correlation_sqr",
    "dcor.u_distance_covariance_sqr": "https://dcor.readthedocs.io/en/stable/functions/dcor.u_distance_covariance_sqr.html#dcor.u_distance_covariance_sqr",
    "dcor.u_distance_stats_sqr": "https://dcor.readthedocs.io/en/stable/functions/dcor.u_distance_stats_sqr.html#dcor.u_distance_stats_sqr",
    "dcor.u_product": "https://dcor.readthedocs.io/en/stable/functions/dcor.u_product.html#dcor.u_product",
    "dcor.u_projection": "https://dcor.readthedocs.io/en/stable/functions/dcor.u_projection.html#dcor.u_projection",
}
