VERSION = "1.0.0"

# fmt: off
MAPPING = {
    "cookie_consent": "https://django-cookie-consent.readthedocs.io/en/stable/",
    "cookie_consent.middleware": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_middleware.html",
    "cookie_consent.middleware.cleancookiesmiddleware": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_middleware.html#cookie_consent.middleware.CleanCookiesMiddleware",
    "cookie_consent.models": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#module-cookie_consent.models",
    "cookie_consent.models.basequeryset": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.BaseQueryset",
    "cookie_consent.models.basequeryset.delete": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.BaseQueryset.delete",
    "cookie_consent.models.basequeryset.update": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.BaseQueryset.update",
    "cookie_consent.models.cookie": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.Cookie",
    "cookie_consent.models.cookie.doesnotexist": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.Cookie.DoesNotExist",
    "cookie_consent.models.cookie.multipleobjectsreturned": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.Cookie.MultipleObjectsReturned",
    "cookie_consent.models.cookie.save": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.Cookie.save",
    "cookie_consent.models.cookiegroup": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.CookieGroup",
    "cookie_consent.models.cookiegroup.doesnotexist": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.CookieGroup.DoesNotExist",
    "cookie_consent.models.cookiegroup.multipleobjectsreturned": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.CookieGroup.MultipleObjectsReturned",
    "cookie_consent.models.cookiegroup.save": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.CookieGroup.save",
    "cookie_consent.models.cookiegroupdict": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.CookieGroupDict",
    "cookie_consent.models.logitem": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.LogItem",
    "cookie_consent.models.logitem.doesnotexist": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.LogItem.DoesNotExist",
    "cookie_consent.models.logitem.multipleobjectsreturned": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_models.html#cookie_consent.models.LogItem.MultipleObjectsReturned",
    "cookie_consent.templatetags": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_templatetags.html",
    "cookie_consent.templatetags.cookie_consent_tags": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_templatetags.html#module-cookie_consent.templatetags.cookie_consent_tags",
    "cookie_consent.templatetags.cookie_consent_tags.all_cookie_groups": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_templatetags.html#cookie_consent.templatetags.cookie_consent_tags.all_cookie_groups",
    "cookie_consent.templatetags.cookie_consent_tags.all_cookies_accepted": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_templatetags.html#cookie_consent.templatetags.cookie_consent_tags.all_cookies_accepted",
    "cookie_consent.templatetags.cookie_consent_tags.cookie_consent_enabled": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_templatetags.html#cookie_consent.templatetags.cookie_consent_tags.cookie_consent_enabled",
    "cookie_consent.templatetags.cookie_consent_tags.cookie_group_accepted": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_templatetags.html#cookie_consent.templatetags.cookie_consent_tags.cookie_group_accepted",
    "cookie_consent.templatetags.cookie_consent_tags.cookie_group_declined": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_templatetags.html#cookie_consent.templatetags.cookie_consent_tags.cookie_group_declined",
    "cookie_consent.templatetags.cookie_consent_tags.not_accepted_or_declined_cookie_groups": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_templatetags.html#cookie_consent.templatetags.cookie_consent_tags.not_accepted_or_declined_cookie_groups",
    "cookie_consent.util": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_util.html#module-cookie_consent.util",
    "cookie_consent.util.are_all_cookies_accepted": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_util.html#cookie_consent.util.are_all_cookies_accepted",
    "cookie_consent.util.dict_to_cookie_str": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_util.html#cookie_consent.util.dict_to_cookie_str",
    "cookie_consent.util.get_accepted_cookie_groups": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_util.html#cookie_consent.util.get_accepted_cookie_groups",
    "cookie_consent.util.get_cookie_value_from_request": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_util.html#cookie_consent.util.get_cookie_value_from_request",
    "cookie_consent.util.get_declined_cookie_groups": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_util.html#cookie_consent.util.get_declined_cookie_groups",
    "cookie_consent.util.get_not_accepted_or_declined_cookie_groups": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_util.html#cookie_consent.util.get_not_accepted_or_declined_cookie_groups",
    "cookie_consent.util.is_cookie_consent_enabled": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_util.html#cookie_consent.util.is_cookie_consent_enabled",
    "cookie_consent.views": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#module-cookie_consent.views",
    "cookie_consent.views.cookiegroupacceptview": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieGroupAcceptView",
    "cookie_consent.views.cookiegroupacceptview.cookie_process_action": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieGroupAcceptView.cookie_process_action",
    "cookie_consent.views.cookiegroupbaseprocessview": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieGroupBaseProcessView",
    "cookie_consent.views.cookiegroupbaseprocessview.cookie_process_action": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieGroupBaseProcessView.cookie_process_action",
    "cookie_consent.views.cookiegroupbaseprocessview.get_default_redirect_url": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieGroupBaseProcessView.get_default_redirect_url",
    "cookie_consent.views.cookiegroupdeclineview": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieGroupDeclineView",
    "cookie_consent.views.cookiegroupdeclineview.cookie_process_action": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieGroupDeclineView.cookie_process_action",
    "cookie_consent.views.cookiegrouplistview": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieGroupListView",
    "cookie_consent.views.cookiegrouplistview.model": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieGroupListView.model",
    "cookie_consent.views.cookiestatusview": "https://django-cookie-consent.readthedocs.io/en/stable/reference/api_views.html#cookie_consent.views.CookieStatusView",
}
