VERSION = "7.1.1"

# fmt: off
MAPPING = {
    "debug_toolbar": "https://django-debug-toolbar.readthedocs.io/en/stable/",
    "debug_toolbar.panels": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.alerts": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.alerts.alertspanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.alerts.AlertsPanel",
    "debug_toolbar.panels.cache": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.cache.cachepanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.community": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.community.communitypanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.community.CommunityPanel",
    "debug_toolbar.panels.headers": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.headers.headerspanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.history": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.history.historypanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.history.HistoryPanel",
    "debug_toolbar.panels.profiling": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.profiling.profilingpanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.profiling.ProfilingPanel",
    "debug_toolbar.panels.redirects": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.redirects.redirectspanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.redirects.RedirectsPanel",
    "debug_toolbar.panels.request": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.request.requestpanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.settings": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.settings.settingspanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.signals": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.signals.signalspanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.sql": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.sql.sqlpanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.staticfiles.staticfilespanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.tasks": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.tasks.taskspanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.tasks.TasksPanel",
    "debug_toolbar.panels.templates": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.templates.templatespanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.templates.TemplatesPanel",
    "debug_toolbar.panels.timer": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.timer.timerpanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.versions": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html",
    "debug_toolbar.panels.versions.versionspanel": "https://django-debug-toolbar.readthedocs.io/en/stable/panels.html#debug_toolbar.panels.versions.VersionsPanel",
}
