VERSION = "2.5.1"

# fmt: off
MAPPING = {
    "configurations": "https://django-configurations.readthedocs.io/en/stable/",
    "configurations.values": "https://django-configurations.readthedocs.io/en/stable/values.html#module-configurations.values",
    "configurations.values.backendsvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.BackendsValue",
    "configurations.values.booleanvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.BooleanValue",
    "configurations.values.cacheurlvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.CacheURLValue",
    "configurations.values.castingmixin": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.CastingMixin",
    "configurations.values.databaseurlvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.DatabaseURLValue",
    "configurations.values.decimalvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.DecimalValue",
    "configurations.values.dictvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.DictValue",
    "configurations.values.emailurlvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.EmailURLValue",
    "configurations.values.emailvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.EmailValue",
    "configurations.values.floatvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.FloatValue",
    "configurations.values.integervalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.IntegerValue",
    "configurations.values.ipvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.IPValue",
    "configurations.values.listvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.ListValue",
    "configurations.values.multiplemixin": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.MultipleMixin",
    "configurations.values.pathvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.PathValue",
    "configurations.values.positiveintegervalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.PositiveIntegerValue",
    "configurations.values.regexvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.RegexValue",
    "configurations.values.searchurlvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.SearchURLValue",
    "configurations.values.secretvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.SecretValue",
    "configurations.values.sequencevalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.SequenceValue",
    "configurations.values.setvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.SetValue",
    "configurations.values.singlenestedlistvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.SingleNestedListValue",
    "configurations.values.singlenestedsequencevalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.SingleNestedSequenceValue",
    "configurations.values.singlenestedtuplevalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.SingleNestedTupleValue",
    "configurations.values.tuplevalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.TupleValue",
    "configurations.values.urlvalue": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.URLValue",
    "configurations.values.validationmixin": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.ValidationMixin",
    "configurations.values.value": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.Value",
    "configurations.values.value.setup": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.Value.setup",
    "configurations.values.value.to_python": "https://django-configurations.readthedocs.io/en/stable/values.html#configurations.values.Value.to_python",
}
