VERSION = "0.13.0"

# fmt: off
MAPPING = {
    "revproxy": "https://django-revproxy.readthedocs.io/en/stable/",
    "revproxy.utils": "https://django-revproxy.readthedocs.io/en/stable/modules.html#module-revproxy.utils",
    "revproxy.utils.cookie_from_string": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.cookie_from_string",
    "revproxy.utils.default_charset": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.DEFAULT_CHARSET",
    "revproxy.utils.encode_items": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.encode_items",
    "revproxy.utils.get_charset": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.get_charset",
    "revproxy.utils.html_content_types": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.HTML_CONTENT_TYPES",
    "revproxy.utils.ignore_headers": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.IGNORE_HEADERS",
    "revproxy.utils.is_html_content_type": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.is_html_content_type",
    "revproxy.utils.min_streaming_length": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.MIN_STREAMING_LENGTH",
    "revproxy.utils.normalize_request_headers": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.normalize_request_headers",
    "revproxy.utils.required_header": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.required_header",
    "revproxy.utils.set_response_headers": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.set_response_headers",
    "revproxy.utils.should_stream": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.should_stream",
    "revproxy.utils.unquote": "https://django-revproxy.readthedocs.io/en/stable/modules.html#revproxy.utils.unquote",
    "revproxy.views": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html",
    "revproxy.views.diazoproxyview": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.DiazoProxyView",
    "revproxy.views.diazoproxyview.diazo_rules": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.DiazoProxyView.diazo_rules",
    "revproxy.views.diazoproxyview.diazo_theme_template": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.DiazoProxyView.diazo_theme_template",
    "revproxy.views.diazoproxyview.html5": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.DiazoProxyView.html5",
    "revproxy.views.proxyview": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.ProxyView",
    "revproxy.views.proxyview.add_remote_user": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.ProxyView.add_remote_user",
    "revproxy.views.proxyview.add_x_forwarded": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.ProxyView.add_x_forwarded",
    "revproxy.views.proxyview.default_content_type": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.ProxyView.default_content_type",
    "revproxy.views.proxyview.retries": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.ProxyView.retries",
    "revproxy.views.proxyview.rewrite": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.ProxyView.rewrite",
    "revproxy.views.proxyview.streaming_amount": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.ProxyView.streaming_amount",
    "revproxy.views.proxyview.strict_cookies": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.ProxyView.strict_cookies",
    "revproxy.views.proxyview.upstream": "https://django-revproxy.readthedocs.io/en/stable/proxyview.html#revproxy.views.ProxyView.upstream",
}
