VERSION = "2.8.1"

# fmt: off
MAPPING = {
    "concurrency": "https://django-concurrency.readthedocs.io/en/stable/",
    "concurrency.admin": "https://django-concurrency.readthedocs.io/en/stable/api.html",
    "concurrency.admin.concurrencyactionmixin": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.admin.ConcurrencyActionMixin",
    "concurrency.admin.concurrencylisteditablemixin": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.admin.ConcurrencyListEditableMixin",
    "concurrency.admin.concurrentmodeladmin": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.admin.ConcurrentModelAdmin",
    "concurrency.exceptions": "https://django-concurrency.readthedocs.io/en/stable/api.html",
    "concurrency.exceptions.inconsistencyerror": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.exceptions.InconsistencyError",
    "concurrency.exceptions.recordmodifiederror": "https://django-concurrency.readthedocs.io/en/stable/api.html#id0",
    "concurrency.exceptions.versionchangederror": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.exceptions.VersionChangedError",
    "concurrency.exceptions.versionerror": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.exceptions.VersionError",
    "concurrency.fields": "https://django-concurrency.readthedocs.io/en/stable/fields.html",
    "concurrency.fields.autoincversionfield": "https://django-concurrency.readthedocs.io/en/stable/fields.html#concurrency.fields.AutoIncVersionField",
    "concurrency.fields.integerversionfield": "https://django-concurrency.readthedocs.io/en/stable/fields.html#concurrency.fields.IntegerVersionField",
    "concurrency.fields.triggerversionfield": "https://django-concurrency.readthedocs.io/en/stable/fields.html#concurrency.fields.TriggerVersionField",
    "concurrency.fields.versionfield": "https://django-concurrency.readthedocs.io/en/stable/fields.html#concurrency.fields.VersionField",
    "concurrency.forms": "https://django-concurrency.readthedocs.io/en/stable/api.html",
    "concurrency.forms.concurrentform": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.forms.ConcurrentForm",
    "concurrency.forms.versionwidget": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.forms.VersionWidget",
    "concurrency.middleware": "https://django-concurrency.readthedocs.io/en/stable/api.html",
    "concurrency.middleware.concurrencymiddleware": "https://django-concurrency.readthedocs.io/en/stable/api.html#id11",
    "concurrency.templatetags": "https://django-concurrency.readthedocs.io/en/stable/api.html",
    "concurrency.templatetags.concurrency": "https://django-concurrency.readthedocs.io/en/stable/api.html",
    "concurrency.templatetags.concurrency.identity": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.templatetags.concurrency.identity",
    "concurrency.templatetags.concurrency.is_version": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.templatetags.concurrency.is_version",
    "concurrency.templatetags.concurrency.version": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.templatetags.concurrency.version",
    "concurrency.triggers": "https://django-concurrency.readthedocs.io/en/stable/api.html",
    "concurrency.triggers.triggerfactory": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.triggers.TriggerFactory",
    "concurrency.views": "https://django-concurrency.readthedocs.io/en/stable/api.html",
    "concurrency.views.conflict": "https://django-concurrency.readthedocs.io/en/stable/api.html#concurrency.views.conflict",
}
