VERSION = "2.2.0"

# fmt: off
MAPPING = {
    "django_comments": "https://django-contrib-comments.readthedocs.io/en/stable/",
    "django_comments.forms": "https://django-contrib-comments.readthedocs.io/en/stable/forms.html#module-django_comments.forms",
    "django_comments.forms.commentdetailsform": "https://django-contrib-comments.readthedocs.io/en/stable/forms.html#django_comments.forms.CommentDetailsForm",
    "django_comments.forms.commentform": "https://django-contrib-comments.readthedocs.io/en/stable/forms.html#django_comments.forms.CommentForm",
    "django_comments.forms.commentsecurityform": "https://django-contrib-comments.readthedocs.io/en/stable/forms.html#django_comments.forms.CommentSecurityForm",
    "django_comments.get_approve_url": "https://django-contrib-comments.readthedocs.io/en/stable/custom.html#django_comments.get_approve_url",
    "django_comments.get_delete_url": "https://django-contrib-comments.readthedocs.io/en/stable/custom.html#django_comments.get_delete_url",
    "django_comments.get_flag_url": "https://django-contrib-comments.readthedocs.io/en/stable/custom.html#django_comments.get_flag_url",
    "django_comments.get_form": "https://django-contrib-comments.readthedocs.io/en/stable/custom.html#django_comments.get_form",
    "django_comments.get_form_target": "https://django-contrib-comments.readthedocs.io/en/stable/custom.html#django_comments.get_form_target",
    "django_comments.get_model": "https://django-contrib-comments.readthedocs.io/en/stable/custom.html#django_comments.get_model",
    "django_comments.models": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#module-django_comments.models",
    "django_comments.models.comment": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment",
    "django_comments.models.comment.comment": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.comment",
    "django_comments.models.comment.content_object": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.content_object",
    "django_comments.models.comment.content_type": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.content_type",
    "django_comments.models.comment.ip_address": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.ip_address",
    "django_comments.models.comment.is_public": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.is_public",
    "django_comments.models.comment.is_removed": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.is_removed",
    "django_comments.models.comment.object_pk": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.object_pk",
    "django_comments.models.comment.site": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.site",
    "django_comments.models.comment.submit_date": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.submit_date",
    "django_comments.models.comment.user": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.user",
    "django_comments.models.comment.user_email": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.user_email",
    "django_comments.models.comment.user_name": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.user_name",
    "django_comments.models.comment.user_url": "https://django-contrib-comments.readthedocs.io/en/stable/models.html#django_comments.models.Comment.user_url",
    "django_comments.moderation": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#module-django_comments.moderation",
    "django_comments.moderation.commentmoderator": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator",
    "django_comments.moderation.commentmoderator.allow": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator.allow",
    "django_comments.moderation.commentmoderator.auto_close_field": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator.auto_close_field",
    "django_comments.moderation.commentmoderator.auto_moderate_field": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator.auto_moderate_field",
    "django_comments.moderation.commentmoderator.close_after": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator.close_after",
    "django_comments.moderation.commentmoderator.email": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator.email",
    "django_comments.moderation.commentmoderator.email_notification": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator.email_notification",
    "django_comments.moderation.commentmoderator.enable_field": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator.enable_field",
    "django_comments.moderation.commentmoderator.moderate": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator.moderate",
    "django_comments.moderation.commentmoderator.moderate_after": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.CommentModerator.moderate_after",
    "django_comments.moderation.moderator": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html",
    "django_comments.moderation.Moderator": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.Moderator",
    "django_comments.moderation.moderator.connect": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.Moderator.connect",
    "django_comments.moderation.moderator.post_save_moderation": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.Moderator.post_save_moderation",
    "django_comments.moderation.moderator.pre_save_moderation": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.Moderator.pre_save_moderation",
    "django_comments.moderation.moderator.register": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.moderator.register",
    "django_comments.moderation.moderator.unregister": "https://django-contrib-comments.readthedocs.io/en/stable/moderation.html#django_comments.moderation.moderator.unregister",
    "django_comments.signals": "https://django-contrib-comments.readthedocs.io/en/stable/signals.html#module-django_comments.signals",
    "django_comments.signals.comment_was_flagged": "https://django-contrib-comments.readthedocs.io/en/stable/signals.html#django_comments.signals.comment_was_flagged",
    "django_comments.signals.comment_was_posted": "https://django-contrib-comments.readthedocs.io/en/stable/signals.html#django_comments.signals.comment_was_posted",
    "django_comments.signals.comment_will_be_posted": "https://django-contrib-comments.readthedocs.io/en/stable/signals.html#django_comments.signals.comment_will_be_posted",
}
