VERSION = "0.9.3"

# fmt: off
MAPPING = {
    "admin_tools": "https://django-admin-tools.readthedocs.io/en/stable/",
    "admin_tools.dashboard": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#module-admin_tools.dashboard",
    "admin_tools.dashboard.appindexdashboard": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.AppIndexDashboard",
    "admin_tools.dashboard.appindexdashboard.get_app_content_types": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.AppIndexDashboard.get_app_content_types",
    "admin_tools.dashboard.appindexdashboard.get_app_model_classes": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.AppIndexDashboard.get_app_model_classes",
    "admin_tools.dashboard.appindexdashboard.get_id": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.AppIndexDashboard.get_id",
    "admin_tools.dashboard.dashboard": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.Dashboard",
    "admin_tools.dashboard.dashboard.get_id": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.Dashboard.get_id",
    "admin_tools.dashboard.dashboard.init_with_context": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.Dashboard.init_with_context",
    "admin_tools.dashboard.modules": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#module-admin_tools.dashboard.modules",
    "admin_tools.dashboard.modules.applist": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.AppList",
    "admin_tools.dashboard.modules.dashboardmodule": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.DashboardModule",
    "admin_tools.dashboard.modules.dashboardmodule.init_with_context": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.DashboardModule.init_with_context",
    "admin_tools.dashboard.modules.dashboardmodule.is_empty": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.DashboardModule.is_empty",
    "admin_tools.dashboard.modules.dashboardmodule.render_css_classes": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.DashboardModule.render_css_classes",
    "admin_tools.dashboard.modules.feed": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.Feed",
    "admin_tools.dashboard.modules.group": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.Group",
    "admin_tools.dashboard.modules.group.is_empty": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.Group.is_empty",
    "admin_tools.dashboard.modules.linklist": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.LinkList",
    "admin_tools.dashboard.modules.modellist": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.ModelList",
    "admin_tools.dashboard.modules.recentactions": "https://django-admin-tools.readthedocs.io/en/stable/dashboard.html#admin_tools.dashboard.modules.RecentActions",
    "admin_tools.menu": "https://django-admin-tools.readthedocs.io/en/stable/menu.html",
    "admin_tools.menu.items": "https://django-admin-tools.readthedocs.io/en/stable/menu.html",
    "admin_tools.menu.items.applist": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.AppList",
    "admin_tools.menu.items.applist.init_with_context": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.AppList.init_with_context",
    "admin_tools.menu.items.applist.is_empty": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.AppList.is_empty",
    "admin_tools.menu.items.bookmarks": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.Bookmarks",
    "admin_tools.menu.items.bookmarks.init_with_context": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.Bookmarks.init_with_context",
    "admin_tools.menu.items.bookmarks.is_selected": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.Bookmarks.is_selected",
    "admin_tools.menu.items.menuitem": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.MenuItem",
    "admin_tools.menu.items.menuitem.init_with_context": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.MenuItem.init_with_context",
    "admin_tools.menu.items.menuitem.is_empty": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.MenuItem.is_empty",
    "admin_tools.menu.items.menuitem.is_selected": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.MenuItem.is_selected",
    "admin_tools.menu.items.modellist": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.ModelList",
    "admin_tools.menu.items.modellist.init_with_context": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.ModelList.init_with_context",
    "admin_tools.menu.items.modellist.is_empty": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.items.ModelList.is_empty",
    "admin_tools.menu.menu": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.Menu",
    "admin_tools.menu.menu.init_with_context": "https://django-admin-tools.readthedocs.io/en/stable/menu.html#admin_tools.menu.Menu.init_with_context",
}
