VERSION = "9.9.0"

# fmt: off
MAPPING = {
    "esi": "https://django-esi.readthedocs.io/en/stable/",
    "esi.app_settings": "https://django-esi.readthedocs.io/en/stable/operations.html#module-esi.app_settings",
    "esi.app_settings.esi_always_create_token": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_ALWAYS_CREATE_TOKEN",
    "esi.app_settings.esi_cache_response": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_CACHE_RESPONSE",
    "esi.app_settings.esi_connection_pool_keepalive_expiry": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_CONNECTION_POOL_KEEPALIVE_EXPIRY",
    "esi.app_settings.esi_connection_pool_max_connections": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_CONNECTION_POOL_MAX_CONNECTIONS",
    "esi.app_settings.esi_connection_pool_max_keepalive": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_CONNECTION_POOL_MAX_KEEPALIVE",
    "esi.app_settings.esi_requests_connect_timeout": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_REQUESTS_CONNECT_TIMEOUT",
    "esi.app_settings.esi_requests_pool_timeout": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_REQUESTS_POOL_TIMEOUT",
    "esi.app_settings.esi_requests_read_timeout": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_REQUESTS_READ_TIMEOUT",
    "esi.app_settings.esi_requests_write_timeout": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_REQUESTS_WRITE_TIMEOUT",
    "esi.app_settings.esi_server_error_max_retries": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_SERVER_ERROR_MAX_RETRIES",
    "esi.app_settings.esi_server_error_wait_exponent": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_SERVER_ERROR_WAIT_EXPONENT",
    "esi.app_settings.esi_user_contact_email": "https://django-esi.readthedocs.io/en/stable/operations.html#esi.app_settings.ESI_USER_CONTACT_EMAIL",
    "esi.decorators": "https://django-esi.readthedocs.io/en/stable/api.html#module-esi.decorators",
    "esi.decorators.esi_rate_limiter_bucketed": "https://django-esi.readthedocs.io/en/stable/api.html#esi.decorators.esi_rate_limiter_bucketed",
    "esi.decorators.rate_limit_retry_task": "https://django-esi.readthedocs.io/en/stable/api.html#esi.decorators.rate_limit_retry_task",
    "esi.decorators.rate_limited_task": "https://django-esi.readthedocs.io/en/stable/api.html#esi.decorators.rate_limited_task",
    "esi.decorators.single_use_token": "https://django-esi.readthedocs.io/en/stable/api.html#esi.decorators.single_use_token",
    "esi.decorators.token_required": "https://django-esi.readthedocs.io/en/stable/api.html#esi.decorators.token_required",
    "esi.decorators.tokens_required": "https://django-esi.readthedocs.io/en/stable/api.html#esi.decorators.tokens_required",
    "esi.decorators.wait_for_esi_errorlimit_reset": "https://django-esi.readthedocs.io/en/stable/api.html#esi.decorators.wait_for_esi_errorlimit_reset",
    "esi.errors": "https://django-esi.readthedocs.io/en/stable/api.html#module-esi.errors",
    "esi.errors.djangoesiexception": "https://django-esi.readthedocs.io/en/stable/api.html#esi.errors.DjangoEsiException",
    "esi.errors.incompleteresponseerror": "https://django-esi.readthedocs.io/en/stable/api.html#esi.errors.IncompleteResponseError",
    "esi.errors.notrefreshabletokenerror": "https://django-esi.readthedocs.io/en/stable/api.html#esi.errors.NotRefreshableTokenError",
    "esi.errors.tokenerror": "https://django-esi.readthedocs.io/en/stable/api.html#esi.errors.TokenError",
    "esi.errors.tokenexpirederror": "https://django-esi.readthedocs.io/en/stable/api.html#esi.errors.TokenExpiredError",
    "esi.errors.tokeninvaliderror": "https://django-esi.readthedocs.io/en/stable/api.html#esi.errors.TokenInvalidError",
    "esi.managers": "https://django-esi.readthedocs.io/en/stable/api.html",
    "esi.managers.tokenqueryset": "https://django-esi.readthedocs.io/en/stable/api.html#esi.managers.TokenQueryset",
    "esi.managers.tokenqueryset.bulk_refresh": "https://django-esi.readthedocs.io/en/stable/api.html#esi.managers.TokenQueryset.bulk_refresh",
    "esi.managers.tokenqueryset.equivalent_to": "https://django-esi.readthedocs.io/en/stable/api.html#esi.managers.TokenQueryset.equivalent_to",
    "esi.managers.tokenqueryset.get_expired": "https://django-esi.readthedocs.io/en/stable/api.html#esi.managers.TokenQueryset.get_expired",
    "esi.managers.tokenqueryset.require_scopes": "https://django-esi.readthedocs.io/en/stable/api.html#esi.managers.TokenQueryset.require_scopes",
    "esi.managers.tokenqueryset.require_scopes_exact": "https://django-esi.readthedocs.io/en/stable/api.html#esi.managers.TokenQueryset.require_scopes_exact",
    "esi.managers.tokenqueryset.require_valid": "https://django-esi.readthedocs.io/en/stable/api.html#esi.managers.TokenQueryset.require_valid",
    "esi.models": "https://django-esi.readthedocs.io/en/stable/api.html",
    "esi.models.token": "https://django-esi.readthedocs.io/en/stable/api.html#esi.models.Token",
    "esi.models.token.can_refresh": "https://django-esi.readthedocs.io/en/stable/api.html#esi.models.Token.can_refresh",
    "esi.models.token.expired": "https://django-esi.readthedocs.io/en/stable/api.html#esi.models.Token.expired",
    "esi.models.token.expires": "https://django-esi.readthedocs.io/en/stable/api.html#esi.models.Token.expires",
    "esi.models.token.get_token": "https://django-esi.readthedocs.io/en/stable/api.html#esi.models.Token.get_token",
    "esi.models.token.notupdated": "https://django-esi.readthedocs.io/en/stable/api.html#esi.models.Token.NotUpdated",
    "esi.models.token.refresh": "https://django-esi.readthedocs.io/en/stable/api.html#esi.models.Token.refresh",
    "esi.models.token.refresh_or_delete": "https://django-esi.readthedocs.io/en/stable/api.html#esi.models.Token.refresh_or_delete",
    "esi.models.token.valid_access_token": "https://django-esi.readthedocs.io/en/stable/api.html#esi.models.Token.valid_access_token",
    "esi.openapi_clients": "https://django-esi.readthedocs.io/en/stable/api.html",
    "esi.openapi_clients.esiclientprovider": "https://django-esi.readthedocs.io/en/stable/api.html#esi.openapi_clients.ESIClientProvider",
}
