VERSION = "10.1.0"

# fmt: off
MAPPING = {
    "django_structlog": "https://django-structlog.readthedocs.io/en/stable/",
    "django_structlog.celery": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#module-django_structlog.celery",
    "django_structlog.celery.signals": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#module-django_structlog.celery.signals",
    "django_structlog.celery.signals.bind_extra_task_metadata": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.celery.signals.bind_extra_task_metadata",
    "django_structlog.celery.signals.modify_context_before_task_publish": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.celery.signals.modify_context_before_task_publish",
    "django_structlog.celery.signals.pre_task_succeeded": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.celery.signals.pre_task_succeeded",
    "django_structlog.celery.steps": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#module-django_structlog.celery.steps",
    "django_structlog.celery.steps.django_structlog": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html",
    "django_structlog.celery.steps.django_structlog.celery": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html",
    "django_structlog.celery.steps.django_structlog.celery.steps": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html",
    "django_structlog.celery.steps.django_structlog.celery.steps.djangostructloginitstep": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.celery.steps.DjangoStructLogInitStep",
    "django_structlog.celery.steps.djangostructloginitstep": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.celery.steps.DjangoStructLogInitStep",
    "django_structlog.celery.steps.djangostructloginitstep.name": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.celery.steps.DjangoStructLogInitStep.name",
    "django_structlog.middlewares": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#module-django_structlog.middlewares",
    "django_structlog.middlewares.request": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html",
    "django_structlog.middlewares.request.requestmiddleware": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware",
    "django_structlog.middlewares.requestmiddleware": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware",
    "django_structlog.middlewares.requestmiddleware.async_capable": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware.async_capable",
    "django_structlog.middlewares.requestmiddleware.bind_ip": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware.bind_ip",
    "django_structlog.middlewares.requestmiddleware.bind_user_id": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware.bind_user_id",
    "django_structlog.middlewares.requestmiddleware.format_request": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware.format_request",
    "django_structlog.middlewares.requestmiddleware.handle_response": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware.handle_response",
    "django_structlog.middlewares.requestmiddleware.prepare": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware.prepare",
    "django_structlog.middlewares.requestmiddleware.process_got_request_exception": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware.process_got_request_exception",
    "django_structlog.middlewares.requestmiddleware.sync_capable": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.middlewares.RequestMiddleware.sync_capable",
    "django_structlog.signals": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#module-django_structlog.signals",
    "django_structlog.signals.bind_extra_request_failed_metadata": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.signals.bind_extra_request_failed_metadata",
    "django_structlog.signals.bind_extra_request_finished_metadata": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.signals.bind_extra_request_finished_metadata",
    "django_structlog.signals.bind_extra_request_metadata": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.signals.bind_extra_request_metadata",
    "django_structlog.signals.update_failure_response": "https://django-structlog.readthedocs.io/en/stable/api_documentation.html#django_structlog.signals.update_failure_response",
}
