VERSION = "3.3.5"

# fmt: off
MAPPING = {
    "app_helper": "https://django-app-helper.readthedocs.io/en/stable/",
    "app_helper.base_test": "https://django-app-helper.readthedocs.io/en/stable/basetest.html",
    "app_helper.base_test.basenodatatestcasemixin": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.BaseNoDataTestCaseMixin",
    "app_helper.base_test.basetestcase": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.BaseTestCase",
    "app_helper.base_test.basetestcasemixin": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.BaseTestCaseMixin",
    "app_helper.base_test.basetransactiontestcase": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.BaseTransactionTestCase",
    "app_helper.base_test.cmspagerenderingmixin": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin",
    "app_helper.base_test.cmspagerenderingmixin._pages_data": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin._pages_data",
    "app_helper.base_test.cmspagerenderingmixin._setup_cms": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin._setup_cms",
    "app_helper.base_test.cmspagerenderingmixin.create_pages": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.create_pages",
    "app_helper.base_test.cmspagerenderingmixin.get_content_renderer": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.get_content_renderer",
    "app_helper.base_test.cmspagerenderingmixin.get_page_request": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.get_page_request",
    "app_helper.base_test.cmspagerenderingmixin.get_pages": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.get_pages",
    "app_helper.base_test.cmspagerenderingmixin.get_pages_data": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.get_pages_data",
    "app_helper.base_test.cmspagerenderingmixin.get_plugin_context": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.get_plugin_context",
    "app_helper.base_test.cmspagerenderingmixin.get_request": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.get_request",
    "app_helper.base_test.cmspagerenderingmixin.get_toolbar_request": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.get_toolbar_request",
    "app_helper.base_test.cmspagerenderingmixin.post_request": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.post_request",
    "app_helper.base_test.cmspagerenderingmixin.render_plugin": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CMSPageRenderingMixin.render_plugin",
    "app_helper.base_test.createtestdatamixin": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin",
    "app_helper.base_test.createtestdatamixin._admin_user_email": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._admin_user_email",
    "app_helper.base_test.createtestdatamixin._admin_user_password": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._admin_user_password",
    "app_helper.base_test.createtestdatamixin._admin_user_username": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._admin_user_username",
    "app_helper.base_test.createtestdatamixin._setup_users": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._setup_users",
    "app_helper.base_test.createtestdatamixin._staff_user_email": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._staff_user_email",
    "app_helper.base_test.createtestdatamixin._staff_user_password": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._staff_user_password",
    "app_helper.base_test.createtestdatamixin._staff_user_username": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._staff_user_username",
    "app_helper.base_test.createtestdatamixin._teardown_users": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._teardown_users",
    "app_helper.base_test.createtestdatamixin._user_user_email": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._user_user_email",
    "app_helper.base_test.createtestdatamixin._user_user_password": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._user_user_password",
    "app_helper.base_test.createtestdatamixin._user_user_username": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin._user_user_username",
    "app_helper.base_test.createtestdatamixin.create_django_image": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin.create_django_image",
    "app_helper.base_test.createtestdatamixin.create_django_image_object": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin.create_django_image_object",
    "app_helper.base_test.createtestdatamixin.create_filer_image": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin.create_filer_image",
    "app_helper.base_test.createtestdatamixin.create_filer_image_object": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin.create_filer_image_object",
    "app_helper.base_test.createtestdatamixin.create_image": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin.create_image",
    "app_helper.base_test.createtestdatamixin.create_user": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.CreateTestDataMixin.create_user",
    "app_helper.base_test.generichelpersmixin": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.GenericHelpersMixin",
    "app_helper.base_test.generichelpersmixin.captured_output": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.GenericHelpersMixin.captured_output",
    "app_helper.base_test.generichelpersmixin.reload_model": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.GenericHelpersMixin.reload_model",
    "app_helper.base_test.generichelpersmixin.reload_urlconf": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.GenericHelpersMixin.reload_urlconf",
    "app_helper.base_test.generichelpersmixin.temp_dir": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.GenericHelpersMixin.temp_dir",
    "app_helper.base_test.requesttestcasemixin": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.RequestTestCaseMixin",
    "app_helper.base_test.requesttestcasemixin.login_user_context": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.RequestTestCaseMixin.login_user_context",
    "app_helper.base_test.requesttestcasemixin.request": "https://django-app-helper.readthedocs.io/en/stable/basetest.html#app_helper.base_test.RequestTestCaseMixin.request",
}
