VERSION = "26.1"

# fmt: off
MAPPING = {
    "django_filters": "https://django-filter.readthedocs.io/en/stable/",
    "django_filters.fields": "https://django-filter.readthedocs.io/en/stable/ref/fields.html#module-django_filters.fields",
    "django_filters.fields.isodatetimefield": "https://django-filter.readthedocs.io/en/stable/ref/fields.html#django_filters.fields.IsoDateTimeField",
    "django_filters.filters": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#module-django_filters.filters",
    "django_filters.filters.allvaluesfilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.AllValuesFilter",
    "django_filters.filters.allvaluesmultiplefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.AllValuesMultipleFilter",
    "django_filters.filters.baseinfilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.BaseInFilter",
    "django_filters.filters.baserangefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.BaseRangeFilter",
    "django_filters.filters.booleanfilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.BooleanFilter",
    "django_filters.filters.charfilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.CharFilter",
    "django_filters.filters.choicefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.ChoiceFilter",
    "django_filters.filters.datefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.DateFilter",
    "django_filters.filters.datefromtorangefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.DateFromToRangeFilter",
    "django_filters.filters.daterangefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.DateRangeFilter",
    "django_filters.filters.datetimefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.DateTimeFilter",
    "django_filters.filters.datetimefromtorangefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.DateTimeFromToRangeFilter",
    "django_filters.filters.durationfilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.DurationFilter",
    "django_filters.filters.isodatetimefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.IsoDateTimeFilter",
    "django_filters.filters.isodatetimefromtorangefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.IsoDateTimeFromToRangeFilter",
    "django_filters.filters.lookupchoicefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.LookupChoiceFilter",
    "django_filters.filters.modelchoicefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.ModelChoiceFilter",
    "django_filters.filters.modelmultiplechoicefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.ModelMultipleChoiceFilter",
    "django_filters.filters.multiplechoicefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.MultipleChoiceFilter",
    "django_filters.filters.numberfilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.NumberFilter",
    "django_filters.filters.numberfilter.get_max_validator": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.NumberFilter.get_max_validator",
    "django_filters.filters.numericrangefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.NumericRangeFilter",
    "django_filters.filters.orderingfilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.OrderingFilter",
    "django_filters.filters.rangefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.RangeFilter",
    "django_filters.filters.timefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.TimeFilter",
    "django_filters.filters.timerangefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.TimeRangeFilter",
    "django_filters.filters.typedchoicefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.TypedChoiceFilter",
    "django_filters.filters.typedmultiplechoicefilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.TypedMultipleChoiceFilter",
    "django_filters.filters.uuidfilter": "https://django-filter.readthedocs.io/en/stable/ref/filters.html#django_filters.filters.UUIDFilter",
    "django_filters.filterset": "https://django-filter.readthedocs.io/en/stable/ref/filterset.html#module-django_filters.filterset",
    "django_filters.filterset.filterset": "https://django-filter.readthedocs.io/en/stable/ref/filterset.html#django_filters.filterset.FilterSet",
    "django_filters.filterset.filterset.filter_for_lookup": "https://django-filter.readthedocs.io/en/stable/ref/filterset.html#django_filters.filterset.FilterSet.filter_for_lookup",
    "django_filters.filterset.filterset_factory": "https://django-filter.readthedocs.io/en/stable/ref/filterset.html#django_filters.filterset.filterset_factory",
    "django_filters.widgets": "https://django-filter.readthedocs.io/en/stable/ref/widgets.html#module-django_filters.widgets",
    "django_filters.widgets.booleanwidget": "https://django-filter.readthedocs.io/en/stable/ref/widgets.html#django_filters.widgets.BooleanWidget",
    "django_filters.widgets.csvwidget": "https://django-filter.readthedocs.io/en/stable/ref/widgets.html#django_filters.widgets.CSVWidget",
    "django_filters.widgets.linkwidget": "https://django-filter.readthedocs.io/en/stable/ref/widgets.html#django_filters.widgets.LinkWidget",
    "django_filters.widgets.rangewidget": "https://django-filter.readthedocs.io/en/stable/ref/widgets.html#django_filters.widgets.RangeWidget",
    "django_filters.widgets.suffixedmultiwidget": "https://django-filter.readthedocs.io/en/stable/ref/widgets.html#django_filters.widgets.SuffixedMultiWidget",
}
