VERSION = "2.7"

# fmt: off
MAPPING = {
    "formtools": "https://django-formtools.readthedocs.io/en/stable/",
    "formtools.preview": "https://django-formtools.readthedocs.io/en/stable/preview.html#module-formtools.preview",
    "formtools.preview.formpreview": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview",
    "formtools.preview.formpreview.done": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.done",
    "formtools.preview.formpreview.failed_hash": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.failed_hash",
    "formtools.preview.formpreview.form_template": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.form_template",
    "formtools.preview.formpreview.get_auto_id": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.get_auto_id",
    "formtools.preview.formpreview.get_context": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.get_context",
    "formtools.preview.formpreview.get_initial": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.get_initial",
    "formtools.preview.formpreview.parse_params": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.parse_params",
    "formtools.preview.formpreview.preview_template": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.preview_template",
    "formtools.preview.formpreview.process_preview": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.process_preview",
    "formtools.preview.formpreview.security_hash": "https://django-formtools.readthedocs.io/en/stable/preview.html#formtools.preview.FormPreview.security_hash",
    "formtools.wizard": "https://django-formtools.readthedocs.io/en/stable/wizard.html",
    "formtools.wizard.views": "https://django-formtools.readthedocs.io/en/stable/wizard.html#module-formtools.wizard.views",
    "formtools.wizard.views.cookiewizardview": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.CookieWizardView",
    "formtools.wizard.views.namedurlcookiewizardview": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.NamedUrlCookieWizardView",
    "formtools.wizard.views.namedurlsessionwizardview": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.NamedUrlSessionWizardView",
    "formtools.wizard.views.namedurlwizardview": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.NamedUrlWizardView",
    "formtools.wizard.views.namedurlwizardview.get_step_url": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.NamedUrlWizardView.get_step_url",
    "formtools.wizard.views.sessionwizardview": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.SessionWizardView",
    "formtools.wizard.views.wizardview": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView",
    "formtools.wizard.views.wizardview.as_view": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.as_view",
    "formtools.wizard.views.wizardview.condition_dict": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.condition_dict",
    "formtools.wizard.views.wizardview.done": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.done",
    "formtools.wizard.views.wizardview.file_storage": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.file_storage",
    "formtools.wizard.views.wizardview.get_all_cleaned_data": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_all_cleaned_data",
    "formtools.wizard.views.wizardview.get_cleaned_data_for_step": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_cleaned_data_for_step",
    "formtools.wizard.views.wizardview.get_context_data": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_context_data",
    "formtools.wizard.views.wizardview.get_form": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_form",
    "formtools.wizard.views.wizardview.get_form_initial": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_form_initial",
    "formtools.wizard.views.wizardview.get_form_instance": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_form_instance",
    "formtools.wizard.views.wizardview.get_form_kwargs": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_form_kwargs",
    "formtools.wizard.views.wizardview.get_form_prefix": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_form_prefix",
    "formtools.wizard.views.wizardview.get_form_step_data": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_form_step_data",
    "formtools.wizard.views.wizardview.get_form_step_files": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_form_step_files",
    "formtools.wizard.views.wizardview.get_prefix": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.get_prefix",
    "formtools.wizard.views.wizardview.initial_dict": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.initial_dict",
    "formtools.wizard.views.wizardview.instance_dict": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.instance_dict",
    "formtools.wizard.views.wizardview.process_step": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.process_step",
    "formtools.wizard.views.wizardview.process_step_files": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.process_step_files",
    "formtools.wizard.views.wizardview.render": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.render",
    "formtools.wizard.views.wizardview.render_goto_step": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.render_goto_step",
    "formtools.wizard.views.wizardview.render_revalidation_failure": "https://django-formtools.readthedocs.io/en/stable/wizard.html#formtools.wizard.views.WizardView.render_revalidation_failure",
}
