VERSION = "0.4.0"

# fmt: off
MAPPING = {
    "graphql_jwt": "https://django-graphql-jwt.domake.io/",
    "graphql_jwt.decorators": "https://django-graphql-jwt.domake.io/decorators.html",
    "graphql_jwt.decorators.login_required": "https://django-graphql-jwt.domake.io/decorators.html#graphql_jwt.decorators.login_required",
    "graphql_jwt.decorators.permission_required": "https://django-graphql-jwt.domake.io/decorators.html#graphql_jwt.decorators.permission_required",
    "graphql_jwt.decorators.staff_member_required": "https://django-graphql-jwt.domake.io/decorators.html#graphql_jwt.decorators.staff_member_required",
    "graphql_jwt.decorators.superuser_required": "https://django-graphql-jwt.domake.io/decorators.html#graphql_jwt.decorators.superuser_required",
    "graphql_jwt.decorators.user_passes_test": "https://django-graphql-jwt.domake.io/decorators.html#graphql_jwt.decorators.user_passes_test",
    "graphql_jwt.jsonwebtokenmutation": "https://django-graphql-jwt.domake.io/customizing.html#graphql_jwt.JSONWebTokenMutation",
    "graphql_jwt.middleware": "https://django-graphql-jwt.domake.io/settings.html",
    "graphql_jwt.middleware.allow_any": "https://django-graphql-jwt.domake.io/settings.html#graphql_jwt.middleware.allow_any",
    "graphql_jwt.mutations": "https://django-graphql-jwt.domake.io/customizing.html",
    "graphql_jwt.mutations.jsonwebtokenmutation": "https://django-graphql-jwt.domake.io/customizing.html#graphql_jwt.JSONWebTokenMutation",
    "graphql_jwt.refresh_token.management": "https://django-graphql-jwt.domake.io/refresh_token.html",
    "graphql_jwt.refresh_token.management.commands": "https://django-graphql-jwt.domake.io/refresh_token.html",
    "graphql_jwt.refresh_token.management.commands.cleartokens": "https://django-graphql-jwt.domake.io/refresh_token.html",
    "graphql_jwt.refresh_token.management.commands.cleartokens.command": "https://django-graphql-jwt.domake.io/refresh_token.html",
    "graphql_jwt.refresh_token.management.commands.cleartokens.command.handle": "https://django-graphql-jwt.domake.io/refresh_token.html#graphql_jwt.refresh_token.management.commands.cleartokens.Command.handle",
    "graphql_jwt.refresh_token.models": "https://django-graphql-jwt.domake.io/settings.html",
    "graphql_jwt.refresh_token.models.refreshtoken": "https://django-graphql-jwt.domake.io/settings.html#graphql_jwt.refresh_token.models.RefreshToken",
    "graphql_jwt.refresh_token.utils": "https://django-graphql-jwt.domake.io/settings.html",
    "graphql_jwt.refresh_token.utils.get_refresh_token_by_model": "https://django-graphql-jwt.domake.io/settings.html#graphql_jwt.refresh_token.utils.get_refresh_token_by_model",
    "graphql_jwt.relay": "https://django-graphql-jwt.domake.io/relay.html",
    "graphql_jwt.relay.jsonwebtokenmutation": "https://django-graphql-jwt.domake.io/relay.html#graphql_jwt.relay.JSONWebTokenMutation",
    "graphql_jwt.testcases": "https://django-graphql-jwt.domake.io/tests.html",
    "graphql_jwt.testcases.jsonwebtokentestcase": "https://django-graphql-jwt.domake.io/tests.html#graphql_jwt.testcases.JSONWebTokenTestCase",
    "graphql_jwt.utils": "https://django-graphql-jwt.domake.io/settings.html",
    "graphql_jwt.utils.get_user_by_natural_key": "https://django-graphql-jwt.domake.io/settings.html#graphql_jwt.utils.get_user_by_natural_key",
    "graphql_jwt.utils.jwt_decode": "https://django-graphql-jwt.domake.io/settings.html#graphql_jwt.utils.jwt_decode",
    "graphql_jwt.utils.jwt_encode": "https://django-graphql-jwt.domake.io/settings.html#graphql_jwt.utils.jwt_encode",
    "graphql_jwt.utils.jwt_payload": "https://django-graphql-jwt.domake.io/settings.html#graphql_jwt.utils.jwt_payload",
    "graphql_jwt.utils.refresh_has_expired": "https://django-graphql-jwt.domake.io/settings.html#graphql_jwt.utils.refresh_has_expired",
}
