VERSION = "0.4.5"

# fmt: off
MAPPING = {
    "dm_pix": "https://dm-pix.readthedocs.io/en/stable/",
    "dm_pix.adjust_brightness": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.adjust_brightness",
    "dm_pix.adjust_contrast": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.adjust_contrast",
    "dm_pix.adjust_gamma": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.adjust_gamma",
    "dm_pix.adjust_hue": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.adjust_hue",
    "dm_pix.adjust_saturation": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.adjust_saturation",
    "dm_pix.affine_transform": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.affine_transform",
    "dm_pix.center_crop": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.center_crop",
    "dm_pix.depth_to_space": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.depth_to_space",
    "dm_pix.elastic_deformation": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.elastic_deformation",
    "dm_pix.extract_patches": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.extract_patches",
    "dm_pix.flat_nd_linear_interpolate": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.flat_nd_linear_interpolate",
    "dm_pix.flat_nd_linear_interpolate_constant": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.flat_nd_linear_interpolate_constant",
    "dm_pix.flip_left_right": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.flip_left_right",
    "dm_pix.flip_up_down": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.flip_up_down",
    "dm_pix.gaussian_blur": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.gaussian_blur",
    "dm_pix.hsl_to_rgb": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.hsl_to_rgb",
    "dm_pix.hsv_to_rgb": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.hsv_to_rgb",
    "dm_pix.mae": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.mae",
    "dm_pix.mse": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.mse",
    "dm_pix.pad_to_size": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.pad_to_size",
    "dm_pix.psnr": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.psnr",
    "dm_pix.random_brightness": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.random_brightness",
    "dm_pix.random_contrast": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.random_contrast",
    "dm_pix.random_crop": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.random_crop",
    "dm_pix.random_flip_left_right": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.random_flip_left_right",
    "dm_pix.random_flip_up_down": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.random_flip_up_down",
    "dm_pix.random_gamma": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.random_gamma",
    "dm_pix.random_hue": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.random_hue",
    "dm_pix.random_saturation": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.random_saturation",
    "dm_pix.resize_with_crop_or_pad": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.resize_with_crop_or_pad",
    "dm_pix.rgb_to_grayscale": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.rgb_to_grayscale",
    "dm_pix.rgb_to_hsl": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.rgb_to_hsl",
    "dm_pix.rgb_to_hsv": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.rgb_to_hsv",
    "dm_pix.rmse": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.rmse",
    "dm_pix.rot90": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.rot90",
    "dm_pix.rotate": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.rotate",
    "dm_pix.simse": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.simse",
    "dm_pix.solarize": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.solarize",
    "dm_pix.space_to_depth": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.space_to_depth",
    "dm_pix.ssim": "https://dm-pix.readthedocs.io/en/stable/api.html#dm_pix.ssim",
}
