VERSION = "0.3.2"

# fmt: off
MAPPING = {
    "docrep": "https://docrep.readthedocs.io/en/stable/",
    "docrep.delete_kwargs": "https://docrep.readthedocs.io/en/stable/index.html#docrep.delete_kwargs",
    "docrep.delete_params": "https://docrep.readthedocs.io/en/stable/index.html#docrep.delete_params",
    "docrep.delete_types": "https://docrep.readthedocs.io/en/stable/index.html#docrep.delete_types",
    "docrep.docstringprocessor": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor",
    "docrep.docstringprocessor.dedent": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.dedent",
    "docrep.docstringprocessor.dedents": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.dedents",
    "docrep.docstringprocessor.delete_kwargs": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.delete_kwargs",
    "docrep.docstringprocessor.delete_kwargs_s": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.delete_kwargs_s",
    "docrep.docstringprocessor.delete_params": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.delete_params",
    "docrep.docstringprocessor.delete_params_s": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.delete_params_s",
    "docrep.docstringprocessor.delete_types": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.delete_types",
    "docrep.docstringprocessor.delete_types_s": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.delete_types_s",
    "docrep.docstringprocessor.get_docstring": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.get_docstring",
    "docrep.docstringprocessor.get_extended_summary": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.get_extended_summary",
    "docrep.docstringprocessor.get_extended_summaryf": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.get_extended_summaryf",
    "docrep.docstringprocessor.get_full_description": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.get_full_description",
    "docrep.docstringprocessor.get_full_descriptionf": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.get_full_descriptionf",
    "docrep.docstringprocessor.get_sections": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.get_sections",
    "docrep.docstringprocessor.get_sectionsf": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.get_sectionsf",
    "docrep.docstringprocessor.get_summary": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.get_summary",
    "docrep.docstringprocessor.get_summaryf": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.get_summaryf",
    "docrep.docstringprocessor.keep_params": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.keep_params",
    "docrep.docstringprocessor.keep_params_s": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.keep_params_s",
    "docrep.docstringprocessor.keep_types": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.keep_types",
    "docrep.docstringprocessor.keep_types_s": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.keep_types_s",
    "docrep.docstringprocessor.param_like_sections": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.param_like_sections",
    "docrep.docstringprocessor.params": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.params",
    "docrep.docstringprocessor.patterns": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.patterns",
    "docrep.docstringprocessor.python2_classes": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.python2_classes",
    "docrep.docstringprocessor.save_docstring": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.save_docstring",
    "docrep.docstringprocessor.text_sections": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.text_sections",
    "docrep.docstringprocessor.with_indent": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.with_indent",
    "docrep.docstringprocessor.with_indents": "https://docrep.readthedocs.io/en/stable/index.html#docrep.DocstringProcessor.with_indents",
    "docrep.keep_params": "https://docrep.readthedocs.io/en/stable/index.html#docrep.keep_params",
    "docrep.keep_types": "https://docrep.readthedocs.io/en/stable/index.html#docrep.keep_types",
    "docrep.safe_modulo": "https://docrep.readthedocs.io/en/stable/index.html#docrep.safe_modulo",
}
