VERSION = "2.3.2"

# fmt: off
MAPPING = {
    "docstr_coverage": "https://docstr-coverage.readthedocs.io/en/stable/",
    "docstr_coverage.aggregatedcount": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.AggregatedCount",
    "docstr_coverage.analyze": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.analyze",
    "docstr_coverage.coverage": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#module-docstr_coverage.coverage",
    "docstr_coverage.coverage.analyze": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.coverage.analyze",
    "docstr_coverage.coverage.get_docstring_coverage": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.coverage.get_docstring_coverage",
    "docstr_coverage.expecteddocstring": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.ExpectedDocstring",
    "docstr_coverage.filecount": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.FileCount",
    "docstr_coverage.filecount.found_empty_file": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.FileCount.found_empty_file",
    "docstr_coverage.filecount.found_needed_docstr": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.FileCount.found_needed_docstr",
    "docstr_coverage.filecount.missed_needed_docstring": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.FileCount.missed_needed_docstring",
    "docstr_coverage.get_docstring_coverage": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.get_docstring_coverage",
    "docstr_coverage.ignoreconfig": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig",
    "docstr_coverage.ignoreconfig.ignore_names": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig.ignore_names",
    "docstr_coverage.ignoreconfig.skip_class_def": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig.skip_class_def",
    "docstr_coverage.ignoreconfig.skip_deleter": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig.skip_deleter",
    "docstr_coverage.ignoreconfig.skip_file_docstring": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig.skip_file_docstring",
    "docstr_coverage.ignoreconfig.skip_init": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig.skip_init",
    "docstr_coverage.ignoreconfig.skip_magic": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig.skip_magic",
    "docstr_coverage.ignoreconfig.skip_private": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig.skip_private",
    "docstr_coverage.ignoreconfig.skip_property": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig.skip_property",
    "docstr_coverage.ignoreconfig.skip_setter": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.IgnoreConfig.skip_setter",
    "docstr_coverage.legacyprinter": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.LegacyPrinter",
    "docstr_coverage.legacyprinter.print": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.LegacyPrinter.print",
    "docstr_coverage.resultcollection": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.ResultCollection",
    "docstr_coverage.resultcollection.count_aggregate": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.ResultCollection.count_aggregate",
    "docstr_coverage.resultcollection.files": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.ResultCollection.files",
    "docstr_coverage.resultcollection.get_file": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.ResultCollection.get_file",
    "docstr_coverage.resultcollection.to_legacy": "https://docstr-coverage.readthedocs.io/en/stable/source/docstr_coverage.html#docstr_coverage.ResultCollection.to_legacy",
}
