VERSION = "0.12.0"

# fmt: off
MAPPING = {
    "etcd3": "https://python-etcd3.readthedocs.io/en/stable/",
    "etcd3.etcd3client": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client",
    "etcd3.etcd3client.add_member": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.add_member",
    "etcd3.etcd3client.add_watch_callback": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.add_watch_callback",
    "etcd3.etcd3client.cancel_watch": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.cancel_watch",
    "etcd3.etcd3client.compact": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.compact",
    "etcd3.etcd3client.create_alarm": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.create_alarm",
    "etcd3.etcd3client.defragment": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.defragment",
    "etcd3.etcd3client.delete": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.delete",
    "etcd3.etcd3client.delete_prefix": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.delete_prefix",
    "etcd3.etcd3client.disarm_alarm": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.disarm_alarm",
    "etcd3.etcd3client.get": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.get",
    "etcd3.etcd3client.get_all": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.get_all",
    "etcd3.etcd3client.get_prefix": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.get_prefix",
    "etcd3.etcd3client.hash": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.hash",
    "etcd3.etcd3client.lease": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.lease",
    "etcd3.etcd3client.list_alarms": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.list_alarms",
    "etcd3.etcd3client.lock": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.lock",
    "etcd3.etcd3client.members": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.members",
    "etcd3.etcd3client.put": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.put",
    "etcd3.etcd3client.remove_member": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.remove_member",
    "etcd3.etcd3client.replace": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.replace",
    "etcd3.etcd3client.revoke_lease": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.revoke_lease",
    "etcd3.etcd3client.snapshot": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.snapshot",
    "etcd3.etcd3client.status": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.status",
    "etcd3.etcd3client.transaction": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.transaction",
    "etcd3.etcd3client.update_member": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.update_member",
    "etcd3.etcd3client.watch": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.watch",
    "etcd3.etcd3client.watch_once": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.watch_once",
    "etcd3.etcd3client.watch_prefix": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.watch_prefix",
    "etcd3.etcd3client.watch_prefix_once": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Etcd3Client.watch_prefix_once",
    "etcd3.lease": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Lease",
    "etcd3.lease.refresh": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Lease.refresh",
    "etcd3.lease.revoke": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Lease.revoke",
    "etcd3.lock": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Lock",
    "etcd3.lock.acquire": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Lock.acquire",
    "etcd3.lock.is_acquired": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Lock.is_acquired",
    "etcd3.lock.refresh": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Lock.refresh",
    "etcd3.lock.release": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Lock.release",
    "etcd3.member": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Member",
    "etcd3.member.active_alarms": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Member.active_alarms",
    "etcd3.member.remove": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Member.remove",
    "etcd3.member.update": "https://python-etcd3.readthedocs.io/en/stable/usage.html#etcd3.Member.update",
}
