VERSION = "0.8.0"

# fmt: off
MAPPING = {
    "eth_hash": "https://eth-hash.readthedocs.io/en/stable/",
    "eth_hash.auto": "https://eth-hash.readthedocs.io/en/stable/eth_hash.html#module-eth_hash.auto",
    "eth_hash.backends": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#module-eth_hash.backends",
    "eth_hash.backends.auto": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#module-eth_hash.backends.auto",
    "eth_hash.backends.auto.autobackend": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.auto.AutoBackend",
    "eth_hash.backends.auto.autobackend.keccak256": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.auto.AutoBackend.keccak256",
    "eth_hash.backends.auto.autobackend.preimage": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.auto.AutoBackend.preimage",
    "eth_hash.backends.pycryptodome": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#module-eth_hash.backends.pycryptodome",
    "eth_hash.backends.pycryptodome.cryptodomebackend": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pycryptodome.CryptodomeBackend",
    "eth_hash.backends.pycryptodome.cryptodomebackend.keccak256": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pycryptodome.CryptodomeBackend.keccak256",
    "eth_hash.backends.pycryptodome.cryptodomebackend.preimage": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pycryptodome.CryptodomeBackend.preimage",
    "eth_hash.backends.pycryptodome.cryptodomepreimage": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pycryptodome.CryptodomePreimage",
    "eth_hash.backends.pycryptodome.cryptodomepreimage.copy": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pycryptodome.CryptodomePreimage.copy",
    "eth_hash.backends.pycryptodome.cryptodomepreimage.digest": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pycryptodome.CryptodomePreimage.digest",
    "eth_hash.backends.pycryptodome.cryptodomepreimage.update": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pycryptodome.CryptodomePreimage.update",
    "eth_hash.backends.pycryptodome.keccak256": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pycryptodome.keccak256",
    "eth_hash.backends.pycryptodome.preimage": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pycryptodome.preimage",
    "eth_hash.backends.pysha3": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#module-eth_hash.backends.pysha3",
    "eth_hash.backends.pysha3.keccak256": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pysha3.keccak256",
    "eth_hash.backends.pysha3.preimage": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pysha3.preimage",
    "eth_hash.backends.pysha3.pysha3backend": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pysha3.PySha3Backend",
    "eth_hash.backends.pysha3.pysha3backend.keccak256": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pysha3.PySha3Backend.keccak256",
    "eth_hash.backends.pysha3.pysha3backend.preimage": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pysha3.PySha3Backend.preimage",
    "eth_hash.backends.pysha3.pysha3preimage": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pysha3.Pysha3Preimage",
    "eth_hash.backends.pysha3.pysha3preimage.copy": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pysha3.Pysha3Preimage.copy",
    "eth_hash.backends.pysha3.pysha3preimage.digest": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pysha3.Pysha3Preimage.digest",
    "eth_hash.backends.pysha3.pysha3preimage.update": "https://eth-hash.readthedocs.io/en/stable/eth_hash.backends.html#eth_hash.backends.pysha3.Pysha3Preimage.update",
    "eth_hash.main": "https://eth-hash.readthedocs.io/en/stable/eth_hash.html#module-eth_hash.main",
    "eth_hash.main.keccak256": "https://eth-hash.readthedocs.io/en/stable/eth_hash.html#eth_hash.main.Keccak256",
    "eth_hash.main.keccak256.new": "https://eth-hash.readthedocs.io/en/stable/eth_hash.html#eth_hash.main.Keccak256.new",
}
