VERSION = "0.9.0"

# fmt: off
MAPPING = {
    "expects": "https://expects.readthedocs.io/en/latest/",
    "expects.aliases": "https://expects.readthedocs.io/en/latest/aliases/#module-expects.aliases",
    "expects.aliases.a": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.a",
    "expects.aliases.above": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.above",
    "expects.aliases.above_or_equal": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.above_or_equal",
    "expects.aliases.an": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.an",
    "expects.aliases.below": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.below",
    "expects.aliases.below_or_equal": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.below_or_equal",
    "expects.matchers": "https://expects.readthedocs.io/en/latest/custom-matchers/#module-expects.matchers",
    "expects.matchers._and": "https://expects.readthedocs.io/en/latest/custom-matchers/#expects.matchers._And",
    "expects.matchers._and._match": "https://expects.readthedocs.io/en/latest/custom-matchers/#expects.matchers._And._match",
    "expects.matchers._or": "https://expects.readthedocs.io/en/latest/custom-matchers/#expects.matchers._Or",
    "expects.matchers._or._match": "https://expects.readthedocs.io/en/latest/custom-matchers/#expects.matchers._Or._match",
    "expects.matchers.built_in": "https://expects.readthedocs.io/en/latest/aliases/",
    "expects.matchers.built_in.be_a": "https://expects.readthedocs.io/en/latest/aliases/",
    "expects.matchers.built_in.be_a.a": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.a",
    "expects.matchers.built_in.be_a.an": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.an",
    "expects.matchers.built_in.be_above": "https://expects.readthedocs.io/en/latest/aliases/",
    "expects.matchers.built_in.be_above.above": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.above",
    "expects.matchers.built_in.be_above_or_equal": "https://expects.readthedocs.io/en/latest/aliases/",
    "expects.matchers.built_in.be_above_or_equal.above_or_equal": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.above_or_equal",
    "expects.matchers.built_in.be_below": "https://expects.readthedocs.io/en/latest/aliases/",
    "expects.matchers.built_in.be_below.below": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.below",
    "expects.matchers.built_in.be_below_or_equal": "https://expects.readthedocs.io/en/latest/aliases/",
    "expects.matchers.built_in.be_below_or_equal.below_or_equal": "https://expects.readthedocs.io/en/latest/aliases/#expects.aliases.below_or_equal",
    "expects.matchers.matcher": "https://expects.readthedocs.io/en/latest/custom-matchers/#expects.matchers.Matcher",
    "expects.matchers.matcher._failure_message": "https://expects.readthedocs.io/en/latest/custom-matchers/#expects.matchers.Matcher._failure_message",
    "expects.matchers.matcher._failure_message_negated": "https://expects.readthedocs.io/en/latest/custom-matchers/#expects.matchers.Matcher._failure_message_negated",
    "expects.matchers.matcher._match": "https://expects.readthedocs.io/en/latest/custom-matchers/#expects.matchers.Matcher._match",
    "expects.matchers.matcher._match_negated": "https://expects.readthedocs.io/en/latest/custom-matchers/#expects.matchers.Matcher._match_negated",
    "expects.testing": "https://expects.readthedocs.io/en/latest/custom-matchers/#module-expects.testing",
}
