VERSION = "3.5.1.4"

# fmt: off
MAPPING = {
    "fastjet": "https://fastjet.readthedocs.io/en/stable/",
    "fastjet.clustersequence": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence",
    "fastjet.clustersequence.childless_pseudojets": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.childless_pseudojets",
    "fastjet.clustersequence.constituent_index": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.constituent_index",
    "fastjet.clustersequence.constituents": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.constituents",
    "fastjet.clustersequence.exclusive_dmerge": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_dmerge",
    "fastjet.clustersequence.exclusive_dmerge_max": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_dmerge_max",
    "fastjet.clustersequence.exclusive_jets": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_jets",
    "fastjet.clustersequence.exclusive_jets_constituents": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_jets_constituents",
    "fastjet.clustersequence.exclusive_jets_constituents_index": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_jets_constituents_index",
    "fastjet.clustersequence.exclusive_jets_energy_correlator": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_jets_energy_correlator",
    "fastjet.clustersequence.exclusive_jets_lund_declusterings": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_jets_lund_declusterings",
    "fastjet.clustersequence.exclusive_jets_ycut": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_jets_ycut",
    "fastjet.clustersequence.exclusive_subdmerge": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_subdmerge",
    "fastjet.clustersequence.exclusive_subdmerge_max": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_subdmerge_max",
    "fastjet.clustersequence.exclusive_subjets": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_subjets",
    "fastjet.clustersequence.exclusive_subjets_up_to": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_subjets_up_to",
    "fastjet.clustersequence.exclusive_ymerge": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_ymerge",
    "fastjet.clustersequence.exclusive_ymerge_max": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.exclusive_ymerge_max",
    "fastjet.clustersequence.get_child": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.get_child",
    "fastjet.clustersequence.get_parents": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.get_parents",
    "fastjet.clustersequence.has_child": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.has_child",
    "fastjet.clustersequence.has_parents": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.has_parents",
    "fastjet.clustersequence.inclusive_jets": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.inclusive_jets",
    "fastjet.clustersequence.jet_def": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.jet_def",
    "fastjet.clustersequence.jet_scale_for_algorithm": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.jet_scale_for_algorithm",
    "fastjet.clustersequence.jets": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.jets",
    "fastjet.clustersequence.n_exclusive_jets": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.n_exclusive_jets",
    "fastjet.clustersequence.n_exclusive_subjets": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.n_exclusive_subjets",
    "fastjet.clustersequence.n_particles": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.n_particles",
    "fastjet.clustersequence.q": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.Q",
    "fastjet.clustersequence.q2": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.Q2",
    "fastjet.clustersequence.unclustered_particles": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.unclustered_particles",
    "fastjet.clustersequence.unique_history_order": "https://fastjet.readthedocs.io/en/stable/clustersequence.html#fastjet.ClusterSequence.unique_history_order",
}
