VERSION = "1.12.2"

# fmt: off
MAPPING = {
    "fastavro": "https://fastavro.readthedocs.io/en/stable/",
    "fastavro._read_py": "https://fastavro.readthedocs.io/en/stable/reader.html",
    "fastavro._read_py.block": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.Block",
    "fastavro._read_py.block.num_records": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.Block.num_records",
    "fastavro._read_py.block.offset": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.Block.offset",
    "fastavro._read_py.block.reader_schema": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.Block.reader_schema",
    "fastavro._read_py.block.size": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.Block.size",
    "fastavro._read_py.block.writer_schema": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.Block.writer_schema",
    "fastavro._read_py.block_reader": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.block_reader",
    "fastavro._read_py.block_reader.codec": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.block_reader.codec",
    "fastavro._read_py.block_reader.metadata": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.block_reader.metadata",
    "fastavro._read_py.block_reader.reader_schema": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.block_reader.reader_schema",
    "fastavro._read_py.block_reader.writer_schema": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.block_reader.writer_schema",
    "fastavro._read_py.is_avro": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.is_avro",
    "fastavro._read_py.reader": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.reader",
    "fastavro._read_py.reader.codec": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.reader.codec",
    "fastavro._read_py.reader.metadata": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.reader.metadata",
    "fastavro._read_py.reader.reader_schema": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.reader.reader_schema",
    "fastavro._read_py.reader.writer_schema": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.reader.writer_schema",
    "fastavro._read_py.schemaless_reader": "https://fastavro.readthedocs.io/en/stable/reader.html#fastavro._read_py.schemaless_reader",
    "fastavro._schema_py": "https://fastavro.readthedocs.io/en/stable/schema.html",
    "fastavro._schema_py.expand_schema": "https://fastavro.readthedocs.io/en/stable/schema.html#fastavro._schema_py.expand_schema",
    "fastavro._schema_py.fingerprint": "https://fastavro.readthedocs.io/en/stable/schema.html#fastavro._schema_py.fingerprint",
    "fastavro._schema_py.fullname": "https://fastavro.readthedocs.io/en/stable/schema.html#fastavro._schema_py.fullname",
    "fastavro._schema_py.load_schema": "https://fastavro.readthedocs.io/en/stable/schema.html#fastavro._schema_py.load_schema",
    "fastavro._schema_py.load_schema_ordered": "https://fastavro.readthedocs.io/en/stable/schema.html#fastavro._schema_py.load_schema_ordered",
    "fastavro._schema_py.parse_schema": "https://fastavro.readthedocs.io/en/stable/schema.html#fastavro._schema_py.parse_schema",
    "fastavro._schema_py.to_parsing_canonical_form": "https://fastavro.readthedocs.io/en/stable/schema.html#fastavro._schema_py.to_parsing_canonical_form",
    "fastavro._validation_py": "https://fastavro.readthedocs.io/en/stable/validation.html",
    "fastavro._validation_py.validate": "https://fastavro.readthedocs.io/en/stable/validation.html#fastavro._validation_py.validate",
    "fastavro._validation_py.validate_many": "https://fastavro.readthedocs.io/en/stable/validation.html#fastavro._validation_py.validate_many",
    "fastavro._write_py": "https://fastavro.readthedocs.io/en/stable/writer.html",
    "fastavro._write_py.schemaless_writer": "https://fastavro.readthedocs.io/en/stable/writer.html#fastavro._write_py.schemaless_writer",
    "fastavro._write_py.writer": "https://fastavro.readthedocs.io/en/stable/writer.html#fastavro._write_py.writer",
    "fastavro.io.json_decoder": "https://fastavro.readthedocs.io/en/stable/io/json_decoder.html",
    "fastavro.io.json_decoder.avrojsondecoder": "https://fastavro.readthedocs.io/en/stable/io/json_decoder.html#fastavro.io.json_decoder.AvroJSONDecoder",
    "fastavro.io.json_encoder": "https://fastavro.readthedocs.io/en/stable/io/json_encoder.html",
    "fastavro.io.json_encoder.avrojsonencoder": "https://fastavro.readthedocs.io/en/stable/io/json_encoder.html#fastavro.io.json_encoder.AvroJSONEncoder",
    "fastavro.json_read": "https://fastavro.readthedocs.io/en/stable/json_reader.html",
    "fastavro.json_read.json_reader": "https://fastavro.readthedocs.io/en/stable/json_reader.html#fastavro.json_read.json_reader",
    "fastavro.json_write": "https://fastavro.readthedocs.io/en/stable/json_writer.html",
    "fastavro.json_write.json_writer": "https://fastavro.readthedocs.io/en/stable/json_writer.html#fastavro.json_write.json_writer",
    "fastavro.repository": "https://fastavro.readthedocs.io/en/stable/repository/base.html",
    "fastavro.repository.base": "https://fastavro.readthedocs.io/en/stable/repository/base.html",
    "fastavro.repository.base.abstractschemarepository": "https://fastavro.readthedocs.io/en/stable/repository/base.html#fastavro.repository.base.AbstractSchemaRepository",
    "fastavro.utils": "https://fastavro.readthedocs.io/en/stable/utils.html",
    "fastavro.utils.anonymize_schema": "https://fastavro.readthedocs.io/en/stable/utils.html#fastavro.utils.anonymize_schema",
    "fastavro.utils.generate_many": "https://fastavro.readthedocs.io/en/stable/utils.html#fastavro.utils.generate_many",
    "fastavro.utils.generate_one": "https://fastavro.readthedocs.io/en/stable/utils.html#fastavro.utils.generate_one",
}
