VERSION = "0.13.1"

# fmt: off
MAPPING = {
    "findiff": "https://findiff.readthedocs.io/en/stable/",
    "findiff.coefs": "https://findiff.readthedocs.io/en/stable/source/coefs.html#module-findiff.coefs",
    "findiff.coefs.coefficients": "https://findiff.readthedocs.io/en/stable/source/coefs.html#findiff.coefs.coefficients",
    "findiff.coefs.coefficients_non_uni": "https://findiff.readthedocs.io/en/stable/source/coefs.html#findiff.coefs.coefficients_non_uni",
    "findiff.coefs.compute_inverse_vandermonde": "https://findiff.readthedocs.io/en/stable/source/coefs.html#findiff.coefs.compute_inverse_Vandermonde",
    "findiff.curl": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Curl",
    "findiff.diff": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Diff",
    "findiff.diff.default_acc": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Diff.DEFAULT_ACC",
    "findiff.diff.grid": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Diff.grid",
    "findiff.diff.matrix": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Diff.matrix",
    "findiff.diff.order": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Diff.order",
    "findiff.diff.set_accuracy": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Diff.set_accuracy",
    "findiff.diff.set_grid": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Diff.set_grid",
    "findiff.diff.stencil": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Diff.stencil",
    "findiff.divergence": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Divergence",
    "findiff.gradient": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Gradient",
    "findiff.laplacian": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Laplacian",
    "findiff.operators": "https://findiff.readthedocs.io/en/stable/source/diff.html",
    "findiff.operators.diff": "https://findiff.readthedocs.io/en/stable/source/diff.html#findiff.Diff",
    "findiff.pde": "https://findiff.readthedocs.io/en/stable/source/pde.html#module-findiff.pde",
    "findiff.pde.boundaryconditions": "https://findiff.readthedocs.io/en/stable/source/pde.html#findiff.pde.BoundaryConditions",
    "findiff.pde.pde": "https://findiff.readthedocs.io/en/stable/source/pde.html#findiff.pde.PDE",
    "findiff.pde.pde.solve": "https://findiff.readthedocs.io/en/stable/source/pde.html#findiff.pde.PDE.solve",
    "findiff.stencils": "https://findiff.readthedocs.io/en/stable/source/stencils.html#module-findiff.stencils",
    "findiff.stencils.stencilset": "https://findiff.readthedocs.io/en/stable/source/stencils.html#findiff.stencils.StencilSet",
    "findiff.stencils.stencilset.apply": "https://findiff.readthedocs.io/en/stable/source/stencils.html#findiff.stencils.StencilSet.apply",
    "findiff.stencils.stencilset.apply_all": "https://findiff.readthedocs.io/en/stable/source/stencils.html#findiff.stencils.StencilSet.apply_all",
    "findiff.vector": "https://findiff.readthedocs.io/en/stable/source/vector.html#module-findiff.vector",
    "findiff.vector.curl": "https://findiff.readthedocs.io/en/stable/source/vector.html#findiff.vector.Curl",
    "findiff.vector.divergence": "https://findiff.readthedocs.io/en/stable/source/vector.html#findiff.vector.Divergence",
    "findiff.vector.gradient": "https://findiff.readthedocs.io/en/stable/source/vector.html#findiff.vector.Gradient",
    "findiff.vector.laplacian": "https://findiff.readthedocs.io/en/stable/source/vector.html#findiff.vector.Laplacian",
    "findiff.vector.vectoroperator": "https://findiff.readthedocs.io/en/stable/source/vector.html#findiff.vector.VectorOperator",
    "findiff.vector.wrap_in_ndarray": "https://findiff.readthedocs.io/en/stable/source/vector.html#findiff.vector.wrap_in_ndarray",
}
