VERSION = "0.6.0"

# fmt: off
MAPPING = {
    "flake8_dunder_all": "https://flake8-dunder-all.readthedocs.io/en/stable/",
    "flake8_dunder_all.__init__": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#module-flake8_dunder_all.__init__",
    "flake8_dunder_all.__init__.alphabeticaloptions": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.AlphabeticalOptions",
    "flake8_dunder_all.__init__.check_and_add_all": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.check_and_add_all",
    "flake8_dunder_all.__init__.plugin": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Plugin",
    "flake8_dunder_all.__init__.plugin.run": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Plugin.run",
    "flake8_dunder_all.__init__.plugin.version": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Plugin.version",
    "flake8_dunder_all.__init__.visitor": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor",
    "flake8_dunder_all.__init__.visitor.all_lineno": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.all_lineno",
    "flake8_dunder_all.__init__.visitor.all_members": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.all_members",
    "flake8_dunder_all.__init__.visitor.found_all": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.found_all",
    "flake8_dunder_all.__init__.visitor.found_dir": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.found_dir",
    "flake8_dunder_all.__init__.visitor.generic_visit": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.generic_visit",
    "flake8_dunder_all.__init__.visitor.handle_def": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.handle_def",
    "flake8_dunder_all.__init__.visitor.handle_import": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.handle_import",
    "flake8_dunder_all.__init__.visitor.last_import": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.last_import",
    "flake8_dunder_all.__init__.visitor.members": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.members",
    "flake8_dunder_all.__init__.visitor.visit": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.visit",
    "flake8_dunder_all.__init__.visitor.visit_asyncfunctiondef": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.visit_AsyncFunctionDef",
    "flake8_dunder_all.__init__.visitor.visit_classdef": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.visit_ClassDef",
    "flake8_dunder_all.__init__.visitor.visit_functiondef": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.visit_FunctionDef",
    "flake8_dunder_all.__init__.visitor.visit_if": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.visit_If",
    "flake8_dunder_all.__init__.visitor.visit_import": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.visit_Import",
    "flake8_dunder_all.__init__.visitor.visit_importfrom": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.visit_ImportFrom",
    "flake8_dunder_all.__init__.visitor.visit_try": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.__init__.Visitor.visit_Try",
    "flake8_dunder_all.__main__": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#module-flake8_dunder_all.__main__",
    "flake8_dunder_all.utils": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#module-flake8_dunder_all.utils",
    "flake8_dunder_all.utils.get_docstring_lineno": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.utils.get_docstring_lineno",
    "flake8_dunder_all.utils.mark_text_ranges": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.utils.mark_text_ranges",
    "flake8_dunder_all.utils.tidy_docstring": "https://flake8-dunder-all.readthedocs.io/en/stable/docs.html#flake8_dunder_all.utils.tidy_docstring",
}
