VERSION = "1.0.0"

# fmt: off
MAPPING = {
    "flask_executor": "https://flask-executor.readthedocs.io/en/stable/",
    "flask_executor.Executor": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.Executor",
    "flask_executor.executor": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#module-flask_executor.executor",
    "flask_executor.executor.add_default_done_callback": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.Executor.add_default_done_callback",
    "flask_executor.executor.copy_current_app_context": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.copy_current_app_context",
    "flask_executor.executor.default_workers": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.default_workers",
    "flask_executor.executor.executor": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.Executor",
    "flask_executor.executor.executor.add_default_done_callback": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.Executor.add_default_done_callback",
    "flask_executor.executor.executor.init_app": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.Executor.init_app",
    "flask_executor.executor.executor.job": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.Executor.job",
    "flask_executor.executor.executor.map": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.Executor.map",
    "flask_executor.executor.executor.submit": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.Executor.submit",
    "flask_executor.executor.executor.submit_stored": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.Executor.submit_stored",
    "flask_executor.executor.executorjob": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.ExecutorJob",
    "flask_executor.executor.executorjob.map": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.ExecutorJob.map",
    "flask_executor.executor.executorjob.submit": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.ExecutorJob.submit",
    "flask_executor.executor.executorjob.submit_stored": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.ExecutorJob.submit_stored",
    "flask_executor.executor.init_app": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.Executor.init_app",
    "flask_executor.executor.job": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.Executor.job",
    "flask_executor.executor.map": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.Executor.map",
    "flask_executor.executor.propagate_exceptions_callback": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.executor.propagate_exceptions_callback",
    "flask_executor.executor.submit": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.Executor.submit",
    "flask_executor.executor.submit_stored": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.Executor.submit_stored",
    "flask_executor.futures": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#module-flask_executor.futures",
    "flask_executor.futures.futurecollection": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.futures.FutureCollection",
    "flask_executor.futures.futurecollection.add": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.futures.FutureCollection.add",
    "flask_executor.futures.futurecollection.pop": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.futures.FutureCollection.pop",
    "flask_executor.futures.futureproxy": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.futures.FutureProxy",
    "flask_executor.futures.futureproxy.add_done_callback": "https://flask-executor.readthedocs.io/en/stable/api/flask_executor.html#flask_executor.futures.FutureProxy.add_done_callback",
}
