VERSION = "2.4.1"

# fmt: off
MAPPING = {
    "flask_caching": "https://flask-caching.readthedocs.io/en/latest/",
    "flask_caching.backends": "https://flask-caching.readthedocs.io/en/latest/backends/",
    "flask_caching.backends.base": "https://flask-caching.readthedocs.io/en/latest/backends/",
    "flask_caching.backends.base.basecache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.base.BaseCache",
    "flask_caching.backends.filesystemcache": "https://flask-caching.readthedocs.io/en/latest/backends/",
    "flask_caching.backends.filesystemcache.filesystemcache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.filesystemcache.FileSystemCache",
    "flask_caching.backends.memcache": "https://flask-caching.readthedocs.io/en/latest/backends/",
    "flask_caching.backends.memcache.memcachedcache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.memcache.MemcachedCache",
    "flask_caching.backends.memcache.saslmemcachedcache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.memcache.SASLMemcachedCache",
    "flask_caching.backends.memcache.spreadsaslmemcachedcache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.memcache.SpreadSASLMemcachedCache",
    "flask_caching.backends.nullcache": "https://flask-caching.readthedocs.io/en/latest/backends/",
    "flask_caching.backends.nullcache.nullcache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.nullcache.NullCache",
    "flask_caching.backends.rediscache": "https://flask-caching.readthedocs.io/en/latest/backends/",
    "flask_caching.backends.rediscache.rediscache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.rediscache.RedisCache",
    "flask_caching.backends.rediscache.redisclustercache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.rediscache.RedisClusterCache",
    "flask_caching.backends.rediscache.redissentinelcache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.rediscache.RedisSentinelCache",
    "flask_caching.backends.simplecache": "https://flask-caching.readthedocs.io/en/latest/backends/",
    "flask_caching.backends.simplecache.simplecache": "https://flask-caching.readthedocs.io/en/latest/backends/#flask_caching.backends.simplecache.SimpleCache",
    "flask_caching.cache": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache",
    "flask_caching.cache.add": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.add",
    "flask_caching.cache.cache": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.cache",
    "flask_caching.cache.cached": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.cached",
    "flask_caching.cache.clear": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.clear",
    "flask_caching.cache.delete": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.delete",
    "flask_caching.cache.delete_many": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.delete_many",
    "flask_caching.cache.delete_memoized": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.delete_memoized",
    "flask_caching.cache.delete_memoized_verhash": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.delete_memoized_verhash",
    "flask_caching.cache.get": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.get",
    "flask_caching.cache.get_dict": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.get_dict",
    "flask_caching.cache.get_many": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.get_many",
    "flask_caching.cache.has": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.has",
    "flask_caching.cache.init_app": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.init_app",
    "flask_caching.cache.memoize": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.memoize",
    "flask_caching.cache.set": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.set",
    "flask_caching.cache.set_many": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.set_many",
    "flask_caching.cache.unlink": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.Cache.unlink",
    "flask_caching.cache_memoize_hit": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.cache_memoize_hit",
    "flask_caching.cache_memoize_miss": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.cache_memoize_miss",
    "flask_caching.cache_view_hit": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.cache_view_hit",
    "flask_caching.cache_view_miss": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.cache_view_miss",
    "flask_caching.cachedresponse": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.CachedResponse",
    "flask_caching.make_template_fragment_key": "https://flask-caching.readthedocs.io/en/latest/api/#flask_caching.make_template_fragment_key",
}
