VERSION = "4.0.0"

# fmt: off
MAPPING = {
    "flask_babel": "https://python-babel.github.io/flask-babel/",
    "flask_babel.babel": "https://python-babel.github.io/flask-babel/index.html#flask_babel.Babel",
    "flask_babel.babel.default_locale": "https://python-babel.github.io/flask-babel/index.html#flask_babel.Babel.default_locale",
    "flask_babel.babel.default_timezone": "https://python-babel.github.io/flask-babel/index.html#flask_babel.Babel.default_timezone",
    "flask_babel.babel.domain": "https://python-babel.github.io/flask-babel/index.html#flask_babel.Babel.domain",
    "flask_babel.babel.domain_instance": "https://python-babel.github.io/flask-babel/index.html#flask_babel.Babel.domain_instance",
    "flask_babel.babel.init_app": "https://python-babel.github.io/flask-babel/index.html#flask_babel.Babel.init_app",
    "flask_babel.babel.list_translations": "https://python-babel.github.io/flask-babel/index.html#flask_babel.Babel.list_translations",
    "flask_babel.force_locale": "https://python-babel.github.io/flask-babel/index.html#flask_babel.force_locale",
    "flask_babel.format_currency": "https://python-babel.github.io/flask-babel/index.html#flask_babel.format_currency",
    "flask_babel.format_date": "https://python-babel.github.io/flask-babel/index.html#flask_babel.format_date",
    "flask_babel.format_datetime": "https://python-babel.github.io/flask-babel/index.html#flask_babel.format_datetime",
    "flask_babel.format_decimal": "https://python-babel.github.io/flask-babel/index.html#flask_babel.format_decimal",
    "flask_babel.format_number": "https://python-babel.github.io/flask-babel/index.html#flask_babel.format_number",
    "flask_babel.format_percent": "https://python-babel.github.io/flask-babel/index.html#flask_babel.format_percent",
    "flask_babel.format_scientific": "https://python-babel.github.io/flask-babel/index.html#flask_babel.format_scientific",
    "flask_babel.format_time": "https://python-babel.github.io/flask-babel/index.html#flask_babel.format_time",
    "flask_babel.format_timedelta": "https://python-babel.github.io/flask-babel/index.html#flask_babel.format_timedelta",
    "flask_babel.get_locale": "https://python-babel.github.io/flask-babel/index.html#flask_babel.get_locale",
    "flask_babel.get_timezone": "https://python-babel.github.io/flask-babel/index.html#flask_babel.get_timezone",
    "flask_babel.get_translations": "https://python-babel.github.io/flask-babel/index.html#flask_babel.get_translations",
    "flask_babel.gettext": "https://python-babel.github.io/flask-babel/index.html#flask_babel.gettext",
    "flask_babel.lazy_gettext": "https://python-babel.github.io/flask-babel/index.html#flask_babel.lazy_gettext",
    "flask_babel.lazy_npgettext": "https://python-babel.github.io/flask-babel/index.html#flask_babel.lazy_npgettext",
    "flask_babel.lazy_pgettext": "https://python-babel.github.io/flask-babel/index.html#flask_babel.lazy_pgettext",
    "flask_babel.ngettext": "https://python-babel.github.io/flask-babel/index.html#flask_babel.ngettext",
    "flask_babel.npgettext": "https://python-babel.github.io/flask-babel/index.html#flask_babel.npgettext",
    "flask_babel.pgettext": "https://python-babel.github.io/flask-babel/index.html#flask_babel.pgettext",
    "flask_babel.refresh": "https://python-babel.github.io/flask-babel/index.html#flask_babel.refresh",
    "flask_babel.to_user_timezone": "https://python-babel.github.io/flask-babel/index.html#flask_babel.to_user_timezone",
    "flask_babel.to_utc": "https://python-babel.github.io/flask-babel/index.html#flask_babel.to_utc",
}
