VERSION = "0.6.3"

# fmt: off
MAPPING = {
    "flask_login": "https://flask-login.readthedocs.io/en/latest/",
    "flask_login.anonymoususermixin": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.AnonymousUserMixin",
    "flask_login.confirm_login": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.confirm_login",
    "flask_login.current_user": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.current_user",
    "flask_login.flaskloginclient": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.FlaskLoginClient",
    "flask_login.fresh_login_required": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.fresh_login_required",
    "flask_login.login_fresh": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.login_fresh",
    "flask_login.login_manager": "https://flask-login.readthedocs.io/en/latest/objects.inv",
    "flask_login.login_manager.loginmanager": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager",
    "flask_login.login_remembered": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.login_remembered",
    "flask_login.login_required": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.login_required",
    "flask_login.login_url": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.login_url",
    "flask_login.login_user": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.login_user",
    "flask_login.loginmanager": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager",
    "flask_login.loginmanager.anonymous_user": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.anonymous_user",
    "flask_login.loginmanager.blueprint_login_views": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.blueprint_login_views",
    "flask_login.loginmanager.init_app": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.init_app",
    "flask_login.loginmanager.login_message": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.login_message",
    "flask_login.loginmanager.login_view": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.login_view",
    "flask_login.loginmanager.needs_refresh": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.needs_refresh",
    "flask_login.loginmanager.needs_refresh_handler": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.needs_refresh_handler",
    "flask_login.loginmanager.needs_refresh_message": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.needs_refresh_message",
    "flask_login.loginmanager.refresh_view": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.refresh_view",
    "flask_login.loginmanager.request_loader": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.request_loader",
    "flask_login.loginmanager.unauthorized": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.unauthorized",
    "flask_login.loginmanager.unauthorized_handler": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.unauthorized_handler",
    "flask_login.loginmanager.user_loader": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.LoginManager.user_loader",
    "flask_login.logout_user": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.logout_user",
    "flask_login.mixins": "https://flask-login.readthedocs.io/en/latest/objects.inv",
    "flask_login.mixins.anonymoususermixin": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.AnonymousUserMixin",
    "flask_login.mixins.usermixin": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.UserMixin",
    "flask_login.session_protected": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.session_protected",
    "flask_login.test_client": "https://flask-login.readthedocs.io/en/latest/objects.inv",
    "flask_login.test_client.flaskloginclient": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.FlaskLoginClient",
    "flask_login.user_logged_in": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.user_logged_in",
    "flask_login.user_logged_out": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.user_logged_out",
    "flask_login.user_login_confirmed": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.user_login_confirmed",
    "flask_login.user_needs_refresh": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.user_needs_refresh",
    "flask_login.user_unauthorized": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.user_unauthorized",
    "flask_login.usermixin": "https://flask-login.readthedocs.io/en/latest/objects.inv#flask_login.UserMixin",
}
