VERSION = "1.3.0"

# fmt: off
MAPPING = {
    "flask_wtf": "https://flask-wtf.readthedocs.io/en/1.2.x/",
    "flask_wtf.csrf": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#module-flask_wtf.csrf",
    "flask_wtf.csrf.csrferror": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.csrf.CSRFError",
    "flask_wtf.csrf.csrfprotect": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.csrf.CSRFProtect",
    "flask_wtf.csrf.csrfprotect.exempt": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.csrf.CSRFProtect.exempt",
    "flask_wtf.csrf.generate_csrf": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.csrf.generate_csrf",
    "flask_wtf.csrf.validate_csrf": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.csrf.validate_csrf",
    "flask_wtf.file": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#module-flask_wtf.file",
    "flask_wtf.file.fileallowed": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.file.FileAllowed",
    "flask_wtf.file.filefield": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.file.FileField",
    "flask_wtf.file.filerequired": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.file.FileRequired",
    "flask_wtf.flaskform": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm",
    "flask_wtf.flaskform.hidden_tag": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm.hidden_tag",
    "flask_wtf.flaskform.is_submitted": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm.is_submitted",
    "flask_wtf.flaskform.meta": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm.Meta",
    "flask_wtf.flaskform.meta.csrf": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm.Meta.csrf",
    "flask_wtf.flaskform.meta.csrf_field_name": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm.Meta.csrf_field_name",
    "flask_wtf.flaskform.meta.get_translations": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm.Meta.get_translations",
    "flask_wtf.flaskform.meta.wrap_formdata": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm.Meta.wrap_formdata",
    "flask_wtf.flaskform.validate_on_submit": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm.validate_on_submit",
    "flask_wtf.form": "https://flask-wtf.readthedocs.io/en/1.2.x/api/",
    "flask_wtf.Form": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.Form",
    "flask_wtf.form.flaskform": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm",
    "flask_wtf.form.flaskform.meta": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.FlaskForm.Meta",
    "flask_wtf.recaptcha": "https://flask-wtf.readthedocs.io/en/1.2.x/api/",
    "flask_wtf.Recaptcha": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.Recaptcha",
    "flask_wtf.recaptcha.fields": "https://flask-wtf.readthedocs.io/en/1.2.x/api/",
    "flask_wtf.recaptcha.fields.recaptchafield": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.RecaptchaField",
    "flask_wtf.recaptcha.validators": "https://flask-wtf.readthedocs.io/en/1.2.x/api/",
    "flask_wtf.recaptcha.validators.recaptcha": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.Recaptcha",
    "flask_wtf.recaptcha.widgets": "https://flask-wtf.readthedocs.io/en/1.2.x/api/",
    "flask_wtf.recaptcha.widgets.recaptchawidget": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.RecaptchaWidget",
    "flask_wtf.recaptchafield": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.RecaptchaField",
    "flask_wtf.recaptchawidget": "https://flask-wtf.readthedocs.io/en/1.2.x/api/#flask_wtf.RecaptchaWidget",
}
