VERSION = "3.2.0"

# fmt: off
MAPPING = {
    "flask_alembic": "https://flask-alembic.readthedocs.io/en/stable/",
    "flask_alembic.Alembic": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic",
    "flask_alembic.ALEMBIC": "https://flask-alembic.readthedocs.io/en/stable/config/#flask_alembic.ALEMBIC",
    "flask_alembic.alembic": "https://flask-alembic.readthedocs.io/en/stable/config/#flask_alembic.ALEMBIC",
    "flask_alembic.alembic.branches": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.branches",
    "flask_alembic.alembic.compare_metadata": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.compare_metadata",
    "flask_alembic.alembic.config": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.config",
    "flask_alembic.alembic.current": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.current",
    "flask_alembic.alembic.downgrade": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.downgrade",
    "flask_alembic.alembic.environment_context": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.environment_context",
    "flask_alembic.alembic.heads": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.heads",
    "flask_alembic.alembic.init_app": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.init_app",
    "flask_alembic.alembic.log": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.log",
    "flask_alembic.alembic.merge": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.merge",
    "flask_alembic.alembic.migration_context": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.migration_context",
    "flask_alembic.alembic.migration_contexts": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.migration_contexts",
    "flask_alembic.alembic.mkdir": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.mkdir",
    "flask_alembic.alembic.needs_revision": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.needs_revision",
    "flask_alembic.alembic.needs_upgrade": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.needs_upgrade",
    "flask_alembic.alembic.op": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.op",
    "flask_alembic.alembic.ops": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.ops",
    "flask_alembic.alembic.produce_migrations": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.produce_migrations",
    "flask_alembic.alembic.rev_id": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.rev_id",
    "flask_alembic.alembic.revision": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.revision",
    "flask_alembic.alembic.run_migrations": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.run_migrations",
    "flask_alembic.alembic.script_directory": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.script_directory",
    "flask_alembic.alembic.stamp": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.stamp",
    "flask_alembic.alembic.upgrade": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic.upgrade",
    "flask_alembic.alembic_context": "https://flask-alembic.readthedocs.io/en/stable/config/#flask_alembic.ALEMBIC_CONTEXT",
    "flask_alembic.extension": "https://flask-alembic.readthedocs.io/en/stable/api/",
    "flask_alembic.extension.alembic": "https://flask-alembic.readthedocs.io/en/stable/api/#flask_alembic.Alembic",
}
