VERSION = "4.0.1"

# fmt: off
MAPPING = {
    "flatdict": "https://github.com/gmr/flatdict",
    "flatdict.flatdict": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.as_dict": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.clear": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.copy": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.get": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.items": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.iteritems": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.iterkeys": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.itervalues": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.keys": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.pop": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.popitem": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.set_delimiter": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.setdefault": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.update": "https://github.com/gmr/flatdict",
    "flatdict.flatdict.values": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.as_dict": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.clear": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.copy": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.get": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.items": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.iteritems": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.iterkeys": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.itervalues": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.keys": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.pop": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.popitem": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.set_delimiter": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.setdefault": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.update": "https://github.com/gmr/flatdict",
    "flatdict.flatterdict.values": "https://github.com/gmr/flatdict",
}
