VERSION = "9.1.0"

# fmt: off
MAPPING = {
    "flufl": "https://flufllock.readthedocs.io/en/stable/",
    "flufl.lock": "https://flufllock.readthedocs.io/en/stable/apiref.html",
    "flufl.lock._lockfile": "https://flufllock.readthedocs.io/en/stable/apiref.html",
    "flufl.lock._lockfile.alreadylockederror": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.AlreadyLockedError",
    "flufl.lock._lockfile.lock": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock",
    "flufl.lock._lockfile.lockerror": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockError",
    "flufl.lock._lockfile.lockstate": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockState",
    "flufl.lock._lockfile.notlockederror": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.NotLockedError",
    "flufl.lock._lockfile.timeouterror": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.TimeOutError",
    "flufl.lock.alreadylockederror": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.AlreadyLockedError",
    "flufl.lock.lock": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock",
    "flufl.lock.lock.claimfile": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.claimfile",
    "flufl.lock.lock.details": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.details",
    "flufl.lock.lock.expiration": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.expiration",
    "flufl.lock.lock.hostname": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.hostname",
    "flufl.lock.lock.is_locked": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.is_locked",
    "flufl.lock.lock.lifetime": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.lifetime",
    "flufl.lock.lock.lock": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.lock",
    "flufl.lock.lock.lockfile": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.lockfile",
    "flufl.lock.lock.refresh": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.refresh",
    "flufl.lock.lock.retry_errnos": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.retry_errnos",
    "flufl.lock.lock.state": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.state",
    "flufl.lock.lock.unlock": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.Lock.unlock",
    "flufl.lock.lockerror": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockError",
    "flufl.lock.lockstate": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockState",
    "flufl.lock.lockstate.ours": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockState.ours",
    "flufl.lock.lockstate.ours_expired": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockState.ours_expired",
    "flufl.lock.lockstate.stale": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockState.stale",
    "flufl.lock.lockstate.theirs_expired": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockState.theirs_expired",
    "flufl.lock.lockstate.unknown": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockState.unknown",
    "flufl.lock.lockstate.unlocked": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.LockState.unlocked",
    "flufl.lock.notlockederror": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.NotLockedError",
    "flufl.lock.timeouterror": "https://flufllock.readthedocs.io/en/stable/apiref.html#flufl.lock.TimeOutError",
}
