VERSION = "6.3.1"

# fmt: off
MAPPING = {
    "ftfy": "https://ftfy.readthedocs.io/en/stable/",
    "ftfy.apply_plan": "https://ftfy.readthedocs.io/en/stable/explain.html#ftfy.apply_plan",
    "ftfy.bad_codecs": "https://ftfy.readthedocs.io/en/stable/bad_encodings.html#module-ftfy.bad_codecs",
    "ftfy.bad_codecs.sloppy": "https://ftfy.readthedocs.io/en/stable/bad_encodings.html#module-ftfy.bad_codecs.sloppy",
    "ftfy.bad_codecs.utf8_variants": "https://ftfy.readthedocs.io/en/stable/bad_encodings.html#module-ftfy.bad_codecs.utf8_variants",
    "ftfy.badness": "https://ftfy.readthedocs.io/en/stable/heuristic.html#module-ftfy.badness",
    "ftfy.badness.badness": "https://ftfy.readthedocs.io/en/stable/heuristic.html#ftfy.badness.badness",
    "ftfy.badness.is_bad": "https://ftfy.readthedocs.io/en/stable/heuristic.html#ftfy.badness.is_bad",
    "ftfy.explain_unicode": "https://ftfy.readthedocs.io/en/stable/explain.html#ftfy.explain_unicode",
    "ftfy.explainedtext": "https://ftfy.readthedocs.io/en/stable/explain.html#ftfy.ExplainedText",
    "ftfy.fix_and_explain": "https://ftfy.readthedocs.io/en/stable/explain.html#ftfy.fix_and_explain",
    "ftfy.fix_encoding": "https://ftfy.readthedocs.io/en/stable/explain.html#ftfy.fix_encoding",
    "ftfy.fix_encoding_and_explain": "https://ftfy.readthedocs.io/en/stable/explain.html#ftfy.fix_encoding_and_explain",
    "ftfy.fix_text": "https://ftfy.readthedocs.io/en/stable/explain.html#ftfy.fix_text",
    "ftfy.fixes": "https://ftfy.readthedocs.io/en/stable/fixes.html#module-ftfy.fixes",
    "ftfy.fixes.decode_escapes": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.decode_escapes",
    "ftfy.fixes.decode_inconsistent_utf8": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.decode_inconsistent_utf8",
    "ftfy.fixes.fix_c1_controls": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.fix_c1_controls",
    "ftfy.fixes.fix_character_width": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.fix_character_width",
    "ftfy.fixes.fix_latin_ligatures": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.fix_latin_ligatures",
    "ftfy.fixes.fix_line_breaks": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.fix_line_breaks",
    "ftfy.fixes.fix_surrogates": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.fix_surrogates",
    "ftfy.fixes.remove_control_chars": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.remove_control_chars",
    "ftfy.fixes.remove_terminal_escapes": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.remove_terminal_escapes",
    "ftfy.fixes.replace_lossy_sequences": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.replace_lossy_sequences",
    "ftfy.fixes.restore_byte_a0": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.restore_byte_a0",
    "ftfy.fixes.uncurl_quotes": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.uncurl_quotes",
    "ftfy.fixes.unescape_html": "https://ftfy.readthedocs.io/en/stable/fixes.html#ftfy.fixes.unescape_html",
    "ftfy.guess_bytes": "https://ftfy.readthedocs.io/en/stable/detect.html#ftfy.guess_bytes",
    "ftfy.textfixerconfig": "https://ftfy.readthedocs.io/en/stable/config.html#ftfy.TextFixerConfig",
}
