VERSION = "0.4.0"

# fmt: off
MAPPING = {
    "gorilla": "https://gorilla.readthedocs.io/en/stable/",
    "gorilla.apply": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.apply",
    "gorilla.create_patches": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.create_patches",
    "gorilla.decoratordata": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.DecoratorData",
    "gorilla.decoratordata.__init__": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.DecoratorData.__init__",
    "gorilla.decoratordata.filter": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.DecoratorData.filter",
    "gorilla.decoratordata.override": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.DecoratorData.override",
    "gorilla.decoratordata.patches": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.DecoratorData.patches",
    "gorilla.default_filter": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.default_filter",
    "gorilla.destination": "https://gorilla.readthedocs.io/en/stable/decorators.html#gorilla.destination",
    "gorilla.filter": "https://gorilla.readthedocs.io/en/stable/decorators.html#gorilla.filter",
    "gorilla.find_patches": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.find_patches",
    "gorilla.get_attribute": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.get_attribute",
    "gorilla.get_decorator_data": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.get_decorator_data",
    "gorilla.get_original_attribute": "https://gorilla.readthedocs.io/en/stable/utilities.html#gorilla.get_original_attribute",
    "gorilla.name": "https://gorilla.readthedocs.io/en/stable/decorators.html#gorilla.name",
    "gorilla.Patch": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Patch",
    "gorilla.patch": "https://gorilla.readthedocs.io/en/stable/decorators.html#gorilla.patch",
    "gorilla.patch.__init__": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Patch.__init__",
    "gorilla.patch.destination": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Patch.destination",
    "gorilla.patch.name": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Patch.name",
    "gorilla.patch.obj": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Patch.obj",
    "gorilla.patch.settings": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Patch.settings",
    "gorilla.patches": "https://gorilla.readthedocs.io/en/stable/decorators.html#gorilla.patches",
    "gorilla.revert": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.revert",
    "gorilla.Settings": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Settings",
    "gorilla.settings": "https://gorilla.readthedocs.io/en/stable/decorators.html#gorilla.settings",
    "gorilla.settings.__init__": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Settings.__init__",
    "gorilla.settings.allow_hit": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Settings.allow_hit",
    "gorilla.settings.store_hit": "https://gorilla.readthedocs.io/en/stable/core.html#gorilla.Settings.store_hit",
}
