VERSION = "1.0.1"

# fmt: off
MAPPING = {
    "grappa": "https://grappa.readthedocs.io/en/stable/",
    "grappa.attribute": "https://grappa.readthedocs.io/en/stable/api.html#grappa.attribute",
    "grappa.Operator": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator",
    "grappa.operator": "https://grappa.readthedocs.io/en/stable/api.html#grappa.operator",
    "grappa.operator.aliases": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.aliases",
    "grappa.operator.chainable": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.chainable",
    "grappa.operator.ctx": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.ctx",
    "grappa.operator.dsl": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.Dsl",
    "grappa.operator.expected": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.expected",
    "grappa.operator.expected_message": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.expected_message",
    "grappa.operator.information": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.information",
    "grappa.operator.kind": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.kind",
    "grappa.operator.match": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.match",
    "grappa.operator.observe": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.observe",
    "grappa.operator.operator_name": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.operator_name",
    "grappa.operator.operators": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.operators",
    "grappa.operator.run": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.run",
    "grappa.operator.run_matcher": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.run_matcher",
    "grappa.operator.subject_message": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.subject_message",
    "grappa.operator.suboperators": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.suboperators",
    "grappa.operator.type": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.Type",
    "grappa.operator.value": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Operator.value",
    "grappa.register": "https://grappa.readthedocs.io/en/stable/api.html#grappa.register",
    "grappa.test": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Test",
    "grappa.test.all": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Test.all",
    "grappa.test.any": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Test.any",
    "grappa.test.expect": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Test.expect",
    "grappa.test.should": "https://grappa.readthedocs.io/en/stable/api.html#grappa.Test.should",
    "grappa.use": "https://grappa.readthedocs.io/en/stable/api.html#grappa.use",
}
