VERSION = "0.6.1"

# fmt: off
MAPPING = {
    "gsheets": "https://gsheets.readthedocs.io/en/stable/",
    "gsheets.api": "https://gsheets.readthedocs.io/en/stable/api.html",
    "gsheets.api.sheets": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets",
    "gsheets.build_service": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.build_service",
    "gsheets.get_credentials": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.get_credentials",
    "gsheets.models": "https://gsheets.readthedocs.io/en/stable/api.html",
    "gsheets.models.sheetsview": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SheetsView",
    "gsheets.models.sheetsview.__getitem__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SheetsView.__getitem__",
    "gsheets.models.sheetsview.ids": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SheetsView.ids",
    "gsheets.models.sheetsview.titles": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SheetsView.titles",
    "gsheets.models.spreadsheet": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet",
    "gsheets.models.spreadsheet.__contains__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.__contains__",
    "gsheets.models.spreadsheet.__getitem__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.__getitem__",
    "gsheets.models.spreadsheet.__iter__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.__iter__",
    "gsheets.models.spreadsheet.__len__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.__len__",
    "gsheets.models.spreadsheet.find": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.find",
    "gsheets.models.spreadsheet.findall": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.findall",
    "gsheets.models.spreadsheet.first_sheet": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.first_sheet",
    "gsheets.models.spreadsheet.get": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.get",
    "gsheets.models.spreadsheet.id": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.id",
    "gsheets.models.spreadsheet.sheets": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.sheets",
    "gsheets.models.spreadsheet.title": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.title",
    "gsheets.models.spreadsheet.to_csv": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.to_csv",
    "gsheets.models.spreadsheet.url": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.SpreadSheet.url",
    "gsheets.models.worksheet": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet",
    "gsheets.models.worksheet.__getitem__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.__getitem__",
    "gsheets.models.worksheet.at": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.at",
    "gsheets.models.worksheet.id": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.id",
    "gsheets.models.worksheet.index": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.index",
    "gsheets.models.worksheet.ncells": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.ncells",
    "gsheets.models.worksheet.ncols": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.ncols",
    "gsheets.models.worksheet.nrows": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.nrows",
    "gsheets.models.worksheet.spreadsheet": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.spreadsheet",
    "gsheets.models.worksheet.title": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.title",
    "gsheets.models.worksheet.to_csv": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.to_csv",
    "gsheets.models.worksheet.to_frame": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.to_frame",
    "gsheets.models.worksheet.url": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.url",
    "gsheets.models.worksheet.values": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.models.WorkSheet.values",
    "gsheets.sheets": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets",
    "gsheets.sheets.__contains__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.__contains__",
    "gsheets.sheets.__getitem__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.__getitem__",
    "gsheets.sheets.__iter__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.__iter__",
    "gsheets.sheets.__len__": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.__len__",
    "gsheets.sheets.find": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.find",
    "gsheets.sheets.findall": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.findall",
    "gsheets.sheets.from_developer_key": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.from_developer_key",
    "gsheets.sheets.from_files": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.from_files",
    "gsheets.sheets.get": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.get",
    "gsheets.sheets.ids": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.ids",
    "gsheets.sheets.iterfiles": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.iterfiles",
    "gsheets.sheets.titles": "https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.titles",
}
