VERSION = "4.2.1"

# fmt: off
MAPPING = {
    "gspread_pandas": "https://gspread-pandas.readthedocs.io/en/stable/",
    "gspread_pandas.client": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#module-gspread_pandas.client",
    "gspread_pandas.client.client": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client",
    "gspread_pandas.client.client.create_folder": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.create_folder",
    "gspread_pandas.client.client.directories": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.directories",
    "gspread_pandas.client.client.email": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.email",
    "gspread_pandas.client.client.find_folders": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.find_folders",
    "gspread_pandas.client.client.find_spreadsheet_files_in_folders": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.find_spreadsheet_files_in_folders",
    "gspread_pandas.client.client.list_spreadsheet_files": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.list_spreadsheet_files",
    "gspread_pandas.client.client.list_spreadsheet_files_in_folder": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.list_spreadsheet_files_in_folder",
    "gspread_pandas.client.client.login": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.login",
    "gspread_pandas.client.client.move_file": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.move_file",
    "gspread_pandas.client.client.open": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.open",
    "gspread_pandas.client.client.refresh_directories": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.refresh_directories",
    "gspread_pandas.client.client.root": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.root",
    "gspread_pandas.client.client.scope": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.client.Client.scope",
    "gspread_pandas.conf": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#module-gspread_pandas.conf",
    "gspread_pandas.conf.get_config": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.conf.get_config",
    "gspread_pandas.conf.get_creds": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.conf.get_creds",
    "gspread_pandas.spread": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#module-gspread_pandas.spread",
    "gspread_pandas.spread.spread": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread",
    "gspread_pandas.spread.spread.add_filter": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.add_filter",
    "gspread_pandas.spread.spread.add_permission": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.add_permission",
    "gspread_pandas.spread.spread.add_permissions": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.add_permissions",
    "gspread_pandas.spread.spread.clear_sheet": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.clear_sheet",
    "gspread_pandas.spread.spread.client": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.client",
    "gspread_pandas.spread.spread.create_sheet": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.create_sheet",
    "gspread_pandas.spread.spread.delete_sheet": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.delete_sheet",
    "gspread_pandas.spread.spread.df_to_sheet": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.df_to_sheet",
    "gspread_pandas.spread.spread.email": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.email",
    "gspread_pandas.spread.spread.find_sheet": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.find_sheet",
    "gspread_pandas.spread.spread.freeze": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.freeze",
    "gspread_pandas.spread.spread.get_sheet_dims": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.get_sheet_dims",
    "gspread_pandas.spread.spread.list_permissions": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.list_permissions",
    "gspread_pandas.spread.spread.merge_cells": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.merge_cells",
    "gspread_pandas.spread.spread.move": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.move",
    "gspread_pandas.spread.spread.open": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.open",
    "gspread_pandas.spread.spread.open_sheet": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.open_sheet",
    "gspread_pandas.spread.spread.open_spread": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.open_spread",
    "gspread_pandas.spread.spread.refresh_spread_metadata": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.refresh_spread_metadata",
    "gspread_pandas.spread.spread.sheet": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.sheet",
    "gspread_pandas.spread.spread.sheet_to_df": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.sheet_to_df",
    "gspread_pandas.spread.spread.sheets": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.sheets",
    "gspread_pandas.spread.spread.spread": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.spread",
    "gspread_pandas.spread.spread.unmerge_cells": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.unmerge_cells",
    "gspread_pandas.spread.spread.update_cells": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.update_cells",
    "gspread_pandas.spread.spread.url": "https://gspread-pandas.readthedocs.io/en/stable/gspread_pandas.html#gspread_pandas.spread.Spread.url",
}
