VERSION = "2.9.2"

# fmt: off
MAPPING = {
    "habanero": "https://habanero.readthedocs.io/en/stable/",
    "habanero.cn": "https://habanero.readthedocs.io/en/stable/modules/cn.html",
    "habanero.cn.content_negotiation": "https://habanero.readthedocs.io/en/stable/modules/cn.html#habanero.cn.content_negotiation",
    "habanero.cn.csl_styles": "https://habanero.readthedocs.io/en/stable/modules/cn.html#habanero.cn.csl_styles",
    "habanero.counts": "https://habanero.readthedocs.io/en/stable/modules/counts.html",
    "habanero.counts.citation_count": "https://habanero.readthedocs.io/en/stable/modules/counts.html#habanero.counts.citation_count",
    "habanero.crossref": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref",
    "habanero.crossref.crossref": "https://habanero.readthedocs.io/en/stable/modules/crossref.html",
    "habanero.crossref.crossref.crossref": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref",
    "habanero.crossref.filter_details": "https://habanero.readthedocs.io/en/stable/modules/filters.html#habanero.Crossref.filter_details",
    "habanero.crossref.filter_names": "https://habanero.readthedocs.io/en/stable/modules/filters.html#habanero.Crossref.filter_names",
    "habanero.crossref.funders": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref.funders",
    "habanero.crossref.journals": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref.journals",
    "habanero.crossref.licenses": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref.licenses",
    "habanero.crossref.members": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref.members",
    "habanero.crossref.prefixes": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref.prefixes",
    "habanero.crossref.random_dois": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref.random_dois",
    "habanero.crossref.registration_agency": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref.registration_agency",
    "habanero.crossref.types": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref.types",
    "habanero.crossref.works": "https://habanero.readthedocs.io/en/stable/modules/crossref.html#habanero.Crossref.works",
    "habanero.crossref.workscontainer": "https://habanero.readthedocs.io/en/stable/modules/workscontainer.html",
    "habanero.crossref.workscontainer.workscontainer": "https://habanero.readthedocs.io/en/stable/modules/workscontainer.html#habanero.WorksContainer",
    "habanero.crossref.worksquery": "https://habanero.readthedocs.io/en/stable/modules/worksquery.html",
    "habanero.crossref.worksquery.worksquery": "https://habanero.readthedocs.io/en/stable/modules/worksquery.html#habanero.WorksQuery",
    "habanero.exceptions": "https://habanero.readthedocs.io/en/stable/exceptions.html",
    "habanero.exceptions.requesterror": "https://habanero.readthedocs.io/en/stable/exceptions.html#habanero.RequestError",
    "habanero.requesterror": "https://habanero.readthedocs.io/en/stable/exceptions.html#habanero.RequestError",
    "habanero.workscontainer": "https://habanero.readthedocs.io/en/stable/modules/workscontainer.html#habanero.WorksContainer",
    "habanero.worksquery": "https://habanero.readthedocs.io/en/stable/modules/worksquery.html#habanero.WorksQuery",
}
