VERSION = "0.9.1"

# fmt: off
MAPPING = {
    "hatch_jupyter_builder": "https://hatch-jupyter-builder.readthedocs.io/en/stable/",
    "hatch_jupyter_builder.cli": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#module-hatch_jupyter_builder.cli",
    "hatch_jupyter_builder.cli.make_parser": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.cli.make_parser",
    "hatch_jupyter_builder.cli.run": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.cli.run",
    "hatch_jupyter_builder.compare_migrated": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.compare_migrated.html#module-hatch_jupyter_builder.compare_migrated",
    "hatch_jupyter_builder.compare_migrated.cli": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.compare_migrated.html#module-hatch_jupyter_builder.compare_migrated.cli",
    "hatch_jupyter_builder.compare_migrated.cli.build_file": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.compare_migrated.html#hatch_jupyter_builder.compare_migrated.cli.build_file",
    "hatch_jupyter_builder.compare_migrated.cli.filter_file": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.compare_migrated.html#hatch_jupyter_builder.compare_migrated.cli.filter_file",
    "hatch_jupyter_builder.compare_migrated.cli.get_tar_names": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.compare_migrated.html#hatch_jupyter_builder.compare_migrated.cli.get_tar_names",
    "hatch_jupyter_builder.compare_migrated.cli.get_zip_names": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.compare_migrated.html#hatch_jupyter_builder.compare_migrated.cli.get_zip_names",
    "hatch_jupyter_builder.compare_migrated.cli.main": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.compare_migrated.html#hatch_jupyter_builder.compare_migrated.cli.main",
    "hatch_jupyter_builder.compare_migrated.cli.make_parser": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.compare_migrated.html#hatch_jupyter_builder.compare_migrated.cli.make_parser",
    "hatch_jupyter_builder.compare_migrated.cli.run": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.compare_migrated.html#hatch_jupyter_builder.compare_migrated.cli.run",
    "hatch_jupyter_builder.hooks": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#module-hatch_jupyter_builder.hooks",
    "hatch_jupyter_builder.hooks.hatch_register_build_hook": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.hooks.hatch_register_build_hook",
    "hatch_jupyter_builder.migrate": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.migrate.html#module-hatch_jupyter_builder.migrate",
    "hatch_jupyter_builder.migrate.cli": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.migrate.html#module-hatch_jupyter_builder.migrate.cli",
    "hatch_jupyter_builder.migrate.cli.main": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.migrate.html#hatch_jupyter_builder.migrate.cli.main",
    "hatch_jupyter_builder.migrate.cli.make_parser": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.migrate.html#hatch_jupyter_builder.migrate.cli.make_parser",
    "hatch_jupyter_builder.migrate.cli.run": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.migrate.html#hatch_jupyter_builder.migrate.cli.run",
    "hatch_jupyter_builder.plugin": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#module-hatch_jupyter_builder.plugin",
    "hatch_jupyter_builder.plugin.jupyterbuildconfig": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildConfig",
    "hatch_jupyter_builder.plugin.jupyterbuildconfig.build_function": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildConfig.build_function",
    "hatch_jupyter_builder.plugin.jupyterbuildconfig.build_kwargs": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildConfig.build_kwargs",
    "hatch_jupyter_builder.plugin.jupyterbuildconfig.editable_build_kwargs": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildConfig.editable_build_kwargs",
    "hatch_jupyter_builder.plugin.jupyterbuildconfig.ensured_targets": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildConfig.ensured_targets",
    "hatch_jupyter_builder.plugin.jupyterbuildconfig.install_pre_commit_hook": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildConfig.install_pre_commit_hook",
    "hatch_jupyter_builder.plugin.jupyterbuildconfig.optional_editable_build": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildConfig.optional_editable_build",
    "hatch_jupyter_builder.plugin.jupyterbuildconfig.skip_if_exists": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildConfig.skip_if_exists",
    "hatch_jupyter_builder.plugin.jupyterbuildhook": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildHook",
    "hatch_jupyter_builder.plugin.jupyterbuildhook.initialize": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildHook.initialize",
    "hatch_jupyter_builder.plugin.jupyterbuildhook.plugin_name": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.plugin.JupyterBuildHook.PLUGIN_NAME",
    "hatch_jupyter_builder.utils": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#module-hatch_jupyter_builder.utils",
    "hatch_jupyter_builder.utils.compare_recursive_mtime": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.compare_recursive_mtime",
    "hatch_jupyter_builder.utils.ensure_targets": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.ensure_targets",
    "hatch_jupyter_builder.utils.get_build_func": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.get_build_func",
    "hatch_jupyter_builder.utils.install_pre_commit_hook": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.install_pre_commit_hook",
    "hatch_jupyter_builder.utils.is_stale": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.is_stale",
    "hatch_jupyter_builder.utils.list2cmdline": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.list2cmdline",
    "hatch_jupyter_builder.utils.mtime": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.mtime",
    "hatch_jupyter_builder.utils.normalize_cmd": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.normalize_cmd",
    "hatch_jupyter_builder.utils.normalize_kwargs": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.normalize_kwargs",
    "hatch_jupyter_builder.utils.npm_builder": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.npm_builder",
    "hatch_jupyter_builder.utils.recursive_mtime": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.recursive_mtime",
    "hatch_jupyter_builder.utils.run": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.run",
    "hatch_jupyter_builder.utils.should_skip": "https://hatch-jupyter-builder.readthedocs.io/en/stable/source/reference/api/hatch_jupyter_builder.html#hatch_jupyter_builder.utils.should_skip",
}
