VERSION = "1.5.4"

# fmt: off
MAPPING = {
    "hpgeom": "https://hpgeom.readthedocs.io/en/stable/",
    "hpgeom.healpy_compat": "https://hpgeom.readthedocs.io/en/stable/modules.html#module-hpgeom.healpy_compat",
    "hpgeom.healpy_compat.ang2pix": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.ang2pix",
    "hpgeom.healpy_compat.ang2vec": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.ang2vec",
    "hpgeom.healpy_compat.boundaries": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.boundaries",
    "hpgeom.healpy_compat.get_all_neighbours": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.get_all_neighbours",
    "hpgeom.healpy_compat.get_interp_weights": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.get_interp_weights",
    "hpgeom.healpy_compat.max_pixrad": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.max_pixrad",
    "hpgeom.healpy_compat.nest2ring": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.nest2ring",
    "hpgeom.healpy_compat.npix2nside": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.npix2nside",
    "hpgeom.healpy_compat.nside2npix": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.nside2npix",
    "hpgeom.healpy_compat.nside2order": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.nside2order",
    "hpgeom.healpy_compat.nside2pixarea": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.nside2pixarea",
    "hpgeom.healpy_compat.nside2resol": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.nside2resol",
    "hpgeom.healpy_compat.order2nside": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.order2nside",
    "hpgeom.healpy_compat.pix2ang": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.pix2ang",
    "hpgeom.healpy_compat.pix2vec": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.pix2vec",
    "hpgeom.healpy_compat.query_disc": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.query_disc",
    "hpgeom.healpy_compat.query_polygon": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.query_polygon",
    "hpgeom.healpy_compat.ring2nest": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.ring2nest",
    "hpgeom.healpy_compat.vec2ang": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.vec2ang",
    "hpgeom.healpy_compat.vec2pix": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.healpy_compat.vec2pix",
    "hpgeom.hpgeom": "https://hpgeom.readthedocs.io/en/stable/modules.html#module-hpgeom.hpgeom",
    "hpgeom.hpgeom.angle_to_pixel": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.angle_to_pixel",
    "hpgeom.hpgeom.angle_to_vector": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.angle_to_vector",
    "hpgeom.hpgeom.boundaries": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.boundaries",
    "hpgeom.hpgeom.get_interpolation_weights": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.get_interpolation_weights",
    "hpgeom.hpgeom.lonlat_to_thetaphi": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.lonlat_to_thetaphi",
    "hpgeom.hpgeom.max_pixel_radius": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.max_pixel_radius",
    "hpgeom.hpgeom.neighbors": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.neighbors",
    "hpgeom.hpgeom.nest_to_ring": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.nest_to_ring",
    "hpgeom.hpgeom.npixel_to_nside": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.npixel_to_nside",
    "hpgeom.hpgeom.nside_to_npixel": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.nside_to_npixel",
    "hpgeom.hpgeom.nside_to_order": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.nside_to_order",
    "hpgeom.hpgeom.nside_to_pixel_area": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.nside_to_pixel_area",
    "hpgeom.hpgeom.nside_to_resolution": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.nside_to_resolution",
    "hpgeom.hpgeom.order_to_nside": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.order_to_nside",
    "hpgeom.hpgeom.pixel_ranges_to_pixels": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.pixel_ranges_to_pixels",
    "hpgeom.hpgeom.pixel_to_angle": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.pixel_to_angle",
    "hpgeom.hpgeom.pixel_to_vector": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.pixel_to_vector",
    "hpgeom.hpgeom.query_box": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.query_box",
    "hpgeom.hpgeom.query_circle": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.query_circle",
    "hpgeom.hpgeom.query_circle_vec": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.query_circle_vec",
    "hpgeom.hpgeom.query_ellipse": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.query_ellipse",
    "hpgeom.hpgeom.query_polygon": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.query_polygon",
    "hpgeom.hpgeom.query_polygon_vec": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.query_polygon_vec",
    "hpgeom.hpgeom.reorder": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.reorder",
    "hpgeom.hpgeom.ring_to_nest": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.ring_to_nest",
    "hpgeom.hpgeom.thetaphi_to_lonlat": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.thetaphi_to_lonlat",
    "hpgeom.hpgeom.upgrade_pixel_ranges": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.upgrade_pixel_ranges",
    "hpgeom.hpgeom.upgrade_pixels": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.upgrade_pixels",
    "hpgeom.hpgeom.vector_to_angle": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.vector_to_angle",
    "hpgeom.hpgeom.vector_to_pixel": "https://hpgeom.readthedocs.io/en/stable/modules.html#hpgeom.hpgeom.vector_to_pixel",
}
