VERSION = "0.6.0"

# fmt: off
MAPPING = {
    "httpx_retries": "https://will-ockmore.github.io/httpx-retries/",
    "httpx_retries.aretry_request": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.aretry_request",
    "httpx_retries.helpers": "https://will-ockmore.github.io/httpx-retries/api/",
    "httpx_retries.helpers.aretry_request": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.aretry_request",
    "httpx_retries.helpers.retry_request": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.retry_request",
    "httpx_retries.retry": "https://will-ockmore.github.io/httpx-retries/api/",
    "httpx_retries.Retry": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry",
    "httpx_retries.retry.asleep": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.asleep",
    "httpx_retries.retry.backoff_strategy": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.backoff_strategy",
    "httpx_retries.retry.copy_with": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.copy_with",
    "httpx_retries.retry.increment": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.increment",
    "httpx_retries.retry.is_exhausted": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_exhausted",
    "httpx_retries.retry.is_retry": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_retry",
    "httpx_retries.retry.is_retryable_exception": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_retryable_exception",
    "httpx_retries.retry.is_retryable_method": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_retryable_method",
    "httpx_retries.retry.is_retryable_status_code": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_retryable_status_code",
    "httpx_retries.retry.parse_retry_after": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.parse_retry_after",
    "httpx_retries.retry.retry": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry",
    "httpx_retries.retry.retry.asleep": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.asleep",
    "httpx_retries.retry.retry.backoff_strategy": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.backoff_strategy",
    "httpx_retries.retry.retry.copy_with": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.copy_with",
    "httpx_retries.retry.retry.increment": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.increment",
    "httpx_retries.retry.retry.is_exhausted": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_exhausted",
    "httpx_retries.retry.retry.is_retry": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_retry",
    "httpx_retries.retry.retry.is_retryable_exception": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_retryable_exception",
    "httpx_retries.retry.retry.is_retryable_method": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_retryable_method",
    "httpx_retries.retry.retry.is_retryable_status_code": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.is_retryable_status_code",
    "httpx_retries.retry.retry.parse_retry_after": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.parse_retry_after",
    "httpx_retries.retry.retry.sleep": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.sleep",
    "httpx_retries.retry.sleep": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.Retry.sleep",
    "httpx_retries.retry_request": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.retry_request",
    "httpx_retries.retrytransport": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport",
    "httpx_retries.retrytransport.aclose": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport.aclose",
    "httpx_retries.retrytransport.close": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport.close",
    "httpx_retries.retrytransport.handle_async_request": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport.handle_async_request",
    "httpx_retries.retrytransport.handle_request": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport.handle_request",
    "httpx_retries.transport": "https://will-ockmore.github.io/httpx-retries/api/",
    "httpx_retries.transport.retrytransport": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport",
    "httpx_retries.transport.retrytransport.aclose": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport.aclose",
    "httpx_retries.transport.retrytransport.close": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport.close",
    "httpx_retries.transport.retrytransport.handle_async_request": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport.handle_async_request",
    "httpx_retries.transport.retrytransport.handle_request": "https://will-ockmore.github.io/httpx-retries/api/#httpx_retries.RetryTransport.handle_request",
}
