VERSION = "0.2.6"

# fmt: off
MAPPING = {
    "humiolib": "https://python-humio.readthedocs.io/en/latest/",
    "humiolib.humioclient": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#module-humiolib.HumioClient",
    "humiolib.humioclient.basehumioclient": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.BaseHumioClient",
    "humiolib.humioclient.humioclient": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient",
    "humiolib.humioclient.humioclient.add_file_contents": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.add_file_contents",
    "humiolib.humioclient.humioclient.create_file": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.create_file",
    "humiolib.humioclient.humioclient.create_queryjob": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.create_queryjob",
    "humiolib.humioclient.humioclient.create_user": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.create_user",
    "humiolib.humioclient.humioclient.delete_file": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.delete_file",
    "humiolib.humioclient.humioclient.delete_user_by_email": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.delete_user_by_email",
    "humiolib.humioclient.humioclient.delete_user_by_id": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.delete_user_by_id",
    "humiolib.humioclient.humioclient.get_file": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.get_file",
    "humiolib.humioclient.humioclient.get_file_content": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.get_file_content",
    "humiolib.humioclient.humioclient.get_status": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.get_status",
    "humiolib.humioclient.humioclient.get_user_by_email": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.get_user_by_email",
    "humiolib.humioclient.humioclient.get_users": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.get_users",
    "humiolib.humioclient.humioclient.ingest_json_data": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.ingest_json_data",
    "humiolib.humioclient.humioclient.ingest_messages": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.ingest_messages",
    "humiolib.humioclient.humioclient.list_files": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.list_files",
    "humiolib.humioclient.humioclient.remove_file_contents": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.remove_file_contents",
    "humiolib.humioclient.humioclient.streaming_query": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioClient.streaming_query",
    "humiolib.humioclient.humioingestclient": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioIngestClient",
    "humiolib.humioclient.humioingestclient.ingest_json_data": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioIngestClient.ingest_json_data",
    "humiolib.humioclient.humioingestclient.ingest_messages": "https://python-humio.readthedocs.io/en/latest/reference/humioclient.html#humiolib.HumioClient.HumioIngestClient.ingest_messages",
    "humiolib.humioexceptions": "https://python-humio.readthedocs.io/en/latest/reference/humioexceptions.html#module-humiolib.HumioExceptions",
    "humiolib.humioexceptions.humioconnectiondroppedexception": "https://python-humio.readthedocs.io/en/latest/reference/humioexceptions.html#humiolib.HumioExceptions.HumioConnectionDroppedException",
    "humiolib.humioexceptions.humioconnectionexception": "https://python-humio.readthedocs.io/en/latest/reference/humioexceptions.html#humiolib.HumioExceptions.HumioConnectionException",
    "humiolib.humioexceptions.humioexception": "https://python-humio.readthedocs.io/en/latest/reference/humioexceptions.html#humiolib.HumioExceptions.HumioException",
    "humiolib.humioexceptions.humiohttpexception": "https://python-humio.readthedocs.io/en/latest/reference/humioexceptions.html#humiolib.HumioExceptions.HumioHTTPException",
    "humiolib.humioexceptions.humioqueryjobexhaustedexception": "https://python-humio.readthedocs.io/en/latest/reference/humioexceptions.html#humiolib.HumioExceptions.HumioQueryJobExhaustedException",
    "humiolib.humioexceptions.humioqueryjobexpiredexception": "https://python-humio.readthedocs.io/en/latest/reference/humioexceptions.html#humiolib.HumioExceptions.HumioQueryJobExpiredException",
    "humiolib.humioexceptions.humiotimeoutexception": "https://python-humio.readthedocs.io/en/latest/reference/humioexceptions.html#humiolib.HumioExceptions.HumioTimeoutException",
    "humiolib.queryjob": "https://python-humio.readthedocs.io/en/latest/reference/queryjob.html#module-humiolib.QueryJob",
    "humiolib.queryjob.basequeryjob": "https://python-humio.readthedocs.io/en/latest/reference/queryjob.html#humiolib.QueryJob.BaseQueryJob",
    "humiolib.queryjob.basequeryjob.poll": "https://python-humio.readthedocs.io/en/latest/reference/queryjob.html#humiolib.QueryJob.BaseQueryJob.poll",
    "humiolib.queryjob.livequeryjob": "https://python-humio.readthedocs.io/en/latest/reference/queryjob.html#humiolib.QueryJob.LiveQueryJob",
    "humiolib.queryjob.pollresult": "https://python-humio.readthedocs.io/en/latest/reference/queryjob.html#humiolib.QueryJob.PollResult",
    "humiolib.queryjob.staticqueryjob": "https://python-humio.readthedocs.io/en/latest/reference/queryjob.html#humiolib.QueryJob.StaticQueryJob",
    "humiolib.queryjob.staticqueryjob.poll": "https://python-humio.readthedocs.io/en/latest/reference/queryjob.html#humiolib.QueryJob.StaticQueryJob.poll",
    "humiolib.queryjob.staticqueryjob.poll_until_done": "https://python-humio.readthedocs.io/en/latest/reference/queryjob.html#humiolib.QueryJob.StaticQueryJob.poll_until_done",
    "humiolib.webcaller": "https://python-humio.readthedocs.io/en/latest/reference/webcaller.html#module-humiolib.WebCaller",
    "humiolib.webcaller.webcaller": "https://python-humio.readthedocs.io/en/latest/reference/webcaller.html#humiolib.WebCaller.WebCaller",
    "humiolib.webcaller.webcaller.call_graphql": "https://python-humio.readthedocs.io/en/latest/reference/webcaller.html#humiolib.WebCaller.WebCaller.call_graphql",
    "humiolib.webcaller.webcaller.call_rest": "https://python-humio.readthedocs.io/en/latest/reference/webcaller.html#humiolib.WebCaller.WebCaller.call_rest",
    "humiolib.webcaller.webcaller.response_as_json": "https://python-humio.readthedocs.io/en/latest/reference/webcaller.html#humiolib.WebCaller.WebCaller.response_as_json",
    "humiolib.webcaller.webstreamer": "https://python-humio.readthedocs.io/en/latest/reference/webcaller.html#humiolib.WebCaller.WebStreamer",
}
