VERSION = "2.7.3"

# fmt: off
MAPPING = {
    "icontract": "https://icontract.readthedocs.io/en/stable/",
    "icontract._decorators": "https://icontract.readthedocs.io/en/stable/api.html",
    "icontract._decorators.ensure": "https://icontract.readthedocs.io/en/stable/api.html#icontract.ensure",
    "icontract._decorators.invariant": "https://icontract.readthedocs.io/en/stable/api.html#icontract.invariant",
    "icontract._decorators.require": "https://icontract.readthedocs.io/en/stable/api.html#icontract.require",
    "icontract._decorators.snapshot": "https://icontract.readthedocs.io/en/stable/api.html#icontract.snapshot",
    "icontract._metaclass": "https://icontract.readthedocs.io/en/stable/api.html",
    "icontract._metaclass.dbc": "https://icontract.readthedocs.io/en/stable/api.html#icontract.DBC",
    "icontract._metaclass.dbcmeta": "https://icontract.readthedocs.io/en/stable/api.html#icontract.DBCMeta",
    "icontract._types": "https://icontract.readthedocs.io/en/stable/api.html",
    "icontract._types.invariantcheckevent": "https://icontract.readthedocs.io/en/stable/api.html#icontract.InvariantCheckEvent",
    "icontract.dbc": "https://icontract.readthedocs.io/en/stable/api.html#icontract.DBC",
    "icontract.dbcmeta": "https://icontract.readthedocs.io/en/stable/api.html#icontract.DBCMeta",
    "icontract.ensure": "https://icontract.readthedocs.io/en/stable/api.html#icontract.ensure",
    "icontract.ensure.__call__": "https://icontract.readthedocs.io/en/stable/api.html#icontract.ensure.__call__",
    "icontract.ensure.__init__": "https://icontract.readthedocs.io/en/stable/api.html#icontract.ensure.__init__",
    "icontract.errors": "https://icontract.readthedocs.io/en/stable/api.html",
    "icontract.errors.violationerror": "https://icontract.readthedocs.io/en/stable/api.html#icontract.ViolationError",
    "icontract.invariant": "https://icontract.readthedocs.io/en/stable/api.html#icontract.invariant",
    "icontract.invariant.__call__": "https://icontract.readthedocs.io/en/stable/api.html#icontract.invariant.__call__",
    "icontract.invariant.__init__": "https://icontract.readthedocs.io/en/stable/api.html#icontract.invariant.__init__",
    "icontract.invariantcheckevent": "https://icontract.readthedocs.io/en/stable/api.html#icontract.InvariantCheckEvent",
    "icontract.invariantcheckevent.all": "https://icontract.readthedocs.io/en/stable/api.html#icontract.InvariantCheckEvent.ALL",
    "icontract.invariantcheckevent.call": "https://icontract.readthedocs.io/en/stable/api.html#icontract.InvariantCheckEvent.CALL",
    "icontract.invariantcheckevent.setattr": "https://icontract.readthedocs.io/en/stable/api.html#icontract.InvariantCheckEvent.SETATTR",
    "icontract.require": "https://icontract.readthedocs.io/en/stable/api.html#icontract.require",
    "icontract.require.__call__": "https://icontract.readthedocs.io/en/stable/api.html#icontract.require.__call__",
    "icontract.require.__init__": "https://icontract.readthedocs.io/en/stable/api.html#icontract.require.__init__",
    "icontract.snapshot": "https://icontract.readthedocs.io/en/stable/api.html#icontract.snapshot",
    "icontract.snapshot.__call__": "https://icontract.readthedocs.io/en/stable/api.html#icontract.snapshot.__call__",
    "icontract.snapshot.__init__": "https://icontract.readthedocs.io/en/stable/api.html#icontract.snapshot.__init__",
    "icontract.violationerror": "https://icontract.readthedocs.io/en/stable/api.html#icontract.ViolationError",
}
