VERSION = "3.1.0"

# fmt: off
MAPPING = {
    "idf_component_tools": "https://docs.espressif.com/projects/idf-component-manager/en/latest/",
    "idf_component_tools.environment": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html",
    "idf_component_tools.environment.componentmanagerenvvariables": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_api_timeout": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_API_TIMEOUT",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_api_token": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_API_TOKEN",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_cache_http_requests": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_CACHE_HTTP_REQUESTS",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_cache_path": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_CACHE_PATH",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_check_new_version": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_CHECK_NEW_VERSION",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_constraint_files": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_CONSTRAINT_FILES",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_constraints": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_CONSTRAINTS",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_debug_mode": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_DEBUG_MODE",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_local_storage_url": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_LOCAL_STORAGE_URL",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_no_colors": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_NO_COLORS",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_no_hints": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_NO_HINTS",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_overwrite_managed_components": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_OVERWRITE_MANAGED_COMPONENTS",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_profile": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_PROFILE",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_registry_url": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_REGISTRY_URL",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_storage_url": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_STORAGE_URL",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_strict_checksum": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_STRICT_CHECKSUM",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_suppress_unknown_file_warnings": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_SUPPRESS_UNKNOWN_FILE_WARNINGS",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_verify_ssl": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_VERIFY_SSL",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_version_process_timeout": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_VERSION_PROCESS_TIMEOUT",
    "idf_component_tools.environment.componentmanagerenvvariables.idf_component_wrapper": "https://docs.espressif.com/projects/idf-component-manager/en/latest/use/how_to_configuration.html#idf_component_tools.environment.ComponentManagerEnvVariables.IDF_COMPONENT_WRAPPER",
}
