VERSION = "1.7.0"

# fmt: off
MAPPING = {
    "idutils": "https://idutils.readthedocs.io/en/stable/",
    "idutils.detect_identifier_schemes": "https://idutils.readthedocs.io/en/stable/index.html#idutils.detect_identifier_schemes",
    "idutils.ext": "https://idutils.readthedocs.io/en/stable/index.html#module-idutils.ext",
    "idutils.ext.customschemesregistry": "https://idutils.readthedocs.io/en/stable/index.html#idutils.ext.CustomSchemesRegistry",
    "idutils.ext.customschemesregistry.custom_schemes": "https://idutils.readthedocs.io/en/stable/index.html#idutils.ext.CustomSchemesRegistry.custom_schemes",
    "idutils.ext.customschemesregistry.pick_scheme_key": "https://idutils.readthedocs.io/en/stable/index.html#idutils.ext.CustomSchemesRegistry.pick_scheme_key",
    "idutils.ext.entry_points": "https://idutils.readthedocs.io/en/stable/index.html#idutils.ext.entry_points",
    "idutils.is_ads": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_ads",
    "idutils.is_arrayexpress_array": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_arrayexpress_array",
    "idutils.is_arrayexpress_experiment": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_arrayexpress_experiment",
    "idutils.is_arxiv": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_arxiv",
    "idutils.is_arxiv_post_2007": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_arxiv_post_2007",
    "idutils.is_arxiv_pre_2007": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_arxiv_pre_2007",
    "idutils.is_bioproject": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_bioproject",
    "idutils.is_biosample": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_biosample",
    "idutils.is_doi": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_doi",
    "idutils.is_ean": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_ean",
    "idutils.is_ean13": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_ean13",
    "idutils.is_ean8": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_ean8",
    "idutils.is_ensembl": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_ensembl",
    "idutils.is_genome": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_genome",
    "idutils.is_geo": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_geo",
    "idutils.is_gnd": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_gnd",
    "idutils.is_handle": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_handle",
    "idutils.is_isbn": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_isbn",
    "idutils.is_isbn10": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_isbn10",
    "idutils.is_isbn13": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_isbn13",
    "idutils.is_isni": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_isni",
    "idutils.is_issn": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_issn",
    "idutils.is_istc": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_istc",
    "idutils.is_lsid": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_lsid",
    "idutils.is_orcid": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_orcid",
    "idutils.is_pmcid": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_pmcid",
    "idutils.is_pmid": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_pmid",
    "idutils.is_purl": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_purl",
    "idutils.is_refseq": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_refseq",
    "idutils.is_sra": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_sra",
    "idutils.is_uniprot": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_uniprot",
    "idutils.is_url": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_url",
    "idutils.is_urn": "https://idutils.readthedocs.io/en/stable/index.html#idutils.is_urn",
    "idutils.normalize_ads": "https://idutils.readthedocs.io/en/stable/index.html#idutils.normalize_ads",
    "idutils.normalize_arxiv": "https://idutils.readthedocs.io/en/stable/index.html#idutils.normalize_arxiv",
    "idutils.normalize_doi": "https://idutils.readthedocs.io/en/stable/index.html#idutils.normalize_doi",
    "idutils.normalize_gnd": "https://idutils.readthedocs.io/en/stable/index.html#idutils.normalize_gnd",
    "idutils.normalize_handle": "https://idutils.readthedocs.io/en/stable/index.html#idutils.normalize_handle",
    "idutils.normalize_orcid": "https://idutils.readthedocs.io/en/stable/index.html#idutils.normalize_orcid",
    "idutils.normalize_pid": "https://idutils.readthedocs.io/en/stable/index.html#idutils.normalize_pid",
    "idutils.normalize_pmid": "https://idutils.readthedocs.io/en/stable/index.html#idutils.normalize_pmid",
    "idutils.to_url": "https://idutils.readthedocs.io/en/stable/index.html#idutils.to_url",
}
