VERSION = "1.4.0"

# fmt: off
MAPPING = {
    "igwn_auth_utils": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/",
    "igwn_auth_utils.error": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.IgwnAuthError/",
    "igwn_auth_utils.error.igwnautherror": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.IgwnAuthError/#igwn_auth_utils.IgwnAuthError",
    "igwn_auth_utils.find_scitoken": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.find_scitoken/#igwn_auth_utils.find_scitoken",
    "igwn_auth_utils.find_x509_credentials": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.find_x509_credentials/#igwn_auth_utils.find_x509_credentials",
    "igwn_auth_utils.get": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.get/#igwn_auth_utils.get",
    "igwn_auth_utils.get_scitoken": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.get_scitoken/#igwn_auth_utils.get_scitoken",
    "igwn_auth_utils.httpscitokenauth": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.HTTPSciTokenAuth/#igwn_auth_utils.HTTPSciTokenAuth",
    "igwn_auth_utils.igwnautherror": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.IgwnAuthError/#igwn_auth_utils.IgwnAuthError",
    "igwn_auth_utils.kerberos": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.kerberos/#module-igwn_auth_utils.kerberos",
    "igwn_auth_utils.kinit": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.kinit/#igwn_auth_utils.kinit",
    "igwn_auth_utils.request": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.request/#igwn_auth_utils.request",
    "igwn_auth_utils.requests": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.requests/#module-igwn_auth_utils.requests",
    "igwn_auth_utils.requests.delete": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.requests.delete/#igwn_auth_utils.requests.delete",
    "igwn_auth_utils.requests.head": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.requests.head/#igwn_auth_utils.requests.head",
    "igwn_auth_utils.requests.httpscitokenauth": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.HTTPSciTokenAuth/#igwn_auth_utils.HTTPSciTokenAuth",
    "igwn_auth_utils.requests.patch": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.requests.patch/#igwn_auth_utils.requests.patch",
    "igwn_auth_utils.requests.post": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.requests.post/#igwn_auth_utils.requests.post",
    "igwn_auth_utils.requests.put": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.requests.put/#igwn_auth_utils.requests.put",
    "igwn_auth_utils.requests.session": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.Session/#igwn_auth_utils.Session",
    "igwn_auth_utils.requests.sessionauthmixin": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.SessionAuthMixin/#igwn_auth_utils.SessionAuthMixin",
    "igwn_auth_utils.requests.sessionerrormixin": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.SessionErrorMixin/#igwn_auth_utils.SessionErrorMixin",
    "igwn_auth_utils.scitoken_authorization_header": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.scitoken_authorization_header/#igwn_auth_utils.scitoken_authorization_header",
    "igwn_auth_utils.scitokens": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.scitokens/#module-igwn_auth_utils.scitokens",
    "igwn_auth_utils.scitokens.default_bearer_token_file": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.scitokens.default_bearer_token_file/#igwn_auth_utils.scitokens.default_bearer_token_file",
    "igwn_auth_utils.scitokens.deserialize_token": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.scitokens.deserialize_token/#igwn_auth_utils.scitokens.deserialize_token",
    "igwn_auth_utils.scitokens.enforcer": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.scitokens.Enforcer/#igwn_auth_utils.scitokens.Enforcer",
    "igwn_auth_utils.scitokens.get_scitoken": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.scitokens.get_scitoken/#igwn_auth_utils.scitokens.get_scitoken",
    "igwn_auth_utils.scitokens.is_valid_token": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.scitokens.is_valid_token/#igwn_auth_utils.scitokens.is_valid_token",
    "igwn_auth_utils.scitokens.load_token_file": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.scitokens.load_token_file/#igwn_auth_utils.scitokens.load_token_file",
    "igwn_auth_utils.scitokens.target_audience": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.scitokens.target_audience/#igwn_auth_utils.scitokens.target_audience",
    "igwn_auth_utils.session": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.Session/#igwn_auth_utils.Session",
    "igwn_auth_utils.sessionauthmixin": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.SessionAuthMixin/#igwn_auth_utils.SessionAuthMixin",
    "igwn_auth_utils.sessionerrormixin": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.SessionErrorMixin/#igwn_auth_utils.SessionErrorMixin",
    "igwn_auth_utils.x509": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.x509/#module-igwn_auth_utils.x509",
    "igwn_auth_utils.x509.is_valid_certificate": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.x509.is_valid_certificate/#igwn_auth_utils.x509.is_valid_certificate",
    "igwn_auth_utils.x509.load_x509_certificate_file": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.x509.load_x509_certificate_file/#igwn_auth_utils.x509.load_x509_certificate_file",
    "igwn_auth_utils.x509.validate_certificate": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.x509.validate_certificate/#igwn_auth_utils.x509.validate_certificate",
    "igwn_auth_utils.x509.x509_deprecation": "https://rtd.igwn.org/projects/igwn-auth-utils/en/stable/api/igwn_auth_utils.x509.x509_deprecation/#igwn_auth_utils.x509.x509_deprecation",
}
