VERSION = "5.3.2"

# fmt: off
MAPPING = {
    "influxdb": "https://influxdb-python.readthedocs.io/en/stable/",
    "influxdb.dataframeclient": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.DataFrameClient",
    "influxdb.dataframeclient.epoch": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.DataFrameClient.EPOCH",
    "influxdb.dataframeclient.query": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.DataFrameClient.query",
    "influxdb.dataframeclient.write_points": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.DataFrameClient.write_points",
    "influxdb.exceptions": "https://influxdb-python.readthedocs.io/en/stable/exceptions.html",
    "influxdb.exceptions.influxdbclienterror": "https://influxdb-python.readthedocs.io/en/stable/exceptions.html#influxdb.exceptions.InfluxDBClientError",
    "influxdb.exceptions.influxdbservererror": "https://influxdb-python.readthedocs.io/en/stable/exceptions.html#influxdb.exceptions.InfluxDBServerError",
    "influxdb.influxdbclient": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient",
    "influxdb.influxdbclient.alter_retention_policy": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.alter_retention_policy",
    "influxdb.influxdbclient.close": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.close",
    "influxdb.influxdbclient.create_continuous_query": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.create_continuous_query",
    "influxdb.influxdbclient.create_database": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.create_database",
    "influxdb.influxdbclient.create_retention_policy": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.create_retention_policy",
    "influxdb.influxdbclient.create_user": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.create_user",
    "influxdb.influxdbclient.delete_series": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.delete_series",
    "influxdb.influxdbclient.drop_continuous_query": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.drop_continuous_query",
    "influxdb.influxdbclient.drop_database": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.drop_database",
    "influxdb.influxdbclient.drop_measurement": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.drop_measurement",
    "influxdb.influxdbclient.drop_retention_policy": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.drop_retention_policy",
    "influxdb.influxdbclient.drop_user": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.drop_user",
    "influxdb.influxdbclient.from_dsn": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.from_dsn",
    "influxdb.influxdbclient.get_list_continuous_queries": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.get_list_continuous_queries",
    "influxdb.influxdbclient.get_list_database": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.get_list_database",
    "influxdb.influxdbclient.get_list_measurements": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.get_list_measurements",
    "influxdb.influxdbclient.get_list_privileges": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.get_list_privileges",
    "influxdb.influxdbclient.get_list_retention_policies": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.get_list_retention_policies",
    "influxdb.influxdbclient.get_list_series": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.get_list_series",
    "influxdb.influxdbclient.get_list_users": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.get_list_users",
    "influxdb.influxdbclient.grant_admin_privileges": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.grant_admin_privileges",
    "influxdb.influxdbclient.grant_privilege": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.grant_privilege",
    "influxdb.influxdbclient.ping": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.ping",
    "influxdb.influxdbclient.query": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.query",
    "influxdb.influxdbclient.request": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.request",
    "influxdb.influxdbclient.revoke_admin_privileges": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.revoke_admin_privileges",
    "influxdb.influxdbclient.revoke_privilege": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.revoke_privilege",
    "influxdb.influxdbclient.send_packet": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.send_packet",
    "influxdb.influxdbclient.set_user_password": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.set_user_password",
    "influxdb.influxdbclient.switch_database": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.switch_database",
    "influxdb.influxdbclient.switch_user": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.switch_user",
    "influxdb.influxdbclient.write": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.write",
    "influxdb.influxdbclient.write_points": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.InfluxDBClient.write_points",
    "influxdb.resultset": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html",
    "influxdb.resultset.resultset": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.resultset.ResultSet",
    "influxdb.resultset.resultset.error": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.resultset.ResultSet.error",
    "influxdb.resultset.resultset.get_points": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.resultset.ResultSet.get_points",
    "influxdb.resultset.resultset.items": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.resultset.ResultSet.items",
    "influxdb.resultset.resultset.keys": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.resultset.ResultSet.keys",
    "influxdb.resultset.resultset.point_from_cols_vals": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.resultset.ResultSet.point_from_cols_vals",
    "influxdb.resultset.resultset.raw": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.resultset.ResultSet.raw",
    "influxdb.serieshelper": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.SeriesHelper",
    "influxdb.serieshelper.commit": "https://influxdb-python.readthedocs.io/en/stable/api-documentation.html#influxdb.SeriesHelper.commit",
}
