VERSION = "0.7.0"

# fmt: off
MAPPING = {
    "ipysheet": "https://ipysheet.readthedocs.io/en/stable/",
    "ipysheet.easy": "https://ipysheet.readthedocs.io/en/stable/api.html#module-ipysheet.easy",
    "ipysheet.easy.calculation": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.easy.calculation",
    "ipysheet.easy.cell": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.easy.cell",
    "ipysheet.easy.cell_range": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.easy.cell_range",
    "ipysheet.easy.column": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.easy.column",
    "ipysheet.easy.current": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.easy.current",
    "ipysheet.easy.hold_cells": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.easy.hold_cells",
    "ipysheet.easy.renderer": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.easy.renderer",
    "ipysheet.easy.row": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.easy.row",
    "ipysheet.easy.sheet": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.easy.sheet",
    "ipysheet.numpy_loader": "https://ipysheet.readthedocs.io/en/stable/api.html#module-ipysheet.numpy_loader",
    "ipysheet.numpy_loader.from_array": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.numpy_loader.from_array",
    "ipysheet.numpy_loader.to_array": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.numpy_loader.to_array",
    "ipysheet.pandas_loader": "https://ipysheet.readthedocs.io/en/stable/api.html#module-ipysheet.pandas_loader",
    "ipysheet.pandas_loader.from_dataframe": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.pandas_loader.from_dataframe",
    "ipysheet.pandas_loader.to_dataframe": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.pandas_loader.to_dataframe",
    "ipysheet.sheet": "https://ipysheet.readthedocs.io/en/stable/api.html#module-ipysheet.sheet",
    "ipysheet.sheet.cell": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell",
    "ipysheet.sheet.cell.choice": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.choice",
    "ipysheet.sheet.cell.column_end": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.column_end",
    "ipysheet.sheet.cell.column_start": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.column_start",
    "ipysheet.sheet.cell.date_format": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.date_format",
    "ipysheet.sheet.cell.name": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.name",
    "ipysheet.sheet.cell.numeric_format": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.numeric_format",
    "ipysheet.sheet.cell.read_only": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.read_only",
    "ipysheet.sheet.cell.renderer": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.renderer",
    "ipysheet.sheet.cell.row_end": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.row_end",
    "ipysheet.sheet.cell.row_start": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.row_start",
    "ipysheet.sheet.cell.squeeze_column": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.squeeze_column",
    "ipysheet.sheet.cell.squeeze_row": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.squeeze_row",
    "ipysheet.sheet.cell.style": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.style",
    "ipysheet.sheet.cell.time_format": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.time_format",
    "ipysheet.sheet.cell.transpose": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.transpose",
    "ipysheet.sheet.cell.type": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.type",
    "ipysheet.sheet.cell.value": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Cell.value",
    "ipysheet.sheet.range": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Range",
    "ipysheet.sheet.range.value": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Range.value",
    "ipysheet.sheet.sheet": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet",
    "ipysheet.sheet.sheet.cells": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.cells",
    "ipysheet.sheet.sheet.column_headers": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.column_headers",
    "ipysheet.sheet.sheet.column_resizing": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.column_resizing",
    "ipysheet.sheet.sheet.column_width": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.column_width",
    "ipysheet.sheet.sheet.columns": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.columns",
    "ipysheet.sheet.sheet.named_cells": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.named_cells",
    "ipysheet.sheet.sheet.row_headers": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.row_headers",
    "ipysheet.sheet.sheet.row_resizing": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.row_resizing",
    "ipysheet.sheet.sheet.rows": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.rows",
    "ipysheet.sheet.sheet.search_token": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.search_token",
    "ipysheet.sheet.sheet.stretch_headers": "https://ipysheet.readthedocs.io/en/stable/api.html#ipysheet.sheet.Sheet.stretch_headers",
}
