VERSION = "1.8.0"

# fmt: off
MAPPING = {
    "isal": "https://python-isal.readthedocs.io/en/latest/",
    "isal.igzip": "https://python-isal.readthedocs.io/en/latest/index.html#module-isal.igzip",
    "isal.igzip.badgzipfile": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip.BadGzipFile",
    "isal.igzip.compress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip.compress",
    "isal.igzip.decompress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip.decompress",
    "isal.igzip.gzipfile": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip.GzipFile",
    "isal.igzip.igzipfile": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip.IGzipFile",
    "isal.igzip.igzipfile.__init__": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip.IGzipFile.__init__",
    "isal.igzip.igzipfile.write": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip.IGzipFile.write",
    "isal.igzip.open": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip.open",
    "isal.igzip_lib": "https://python-isal.readthedocs.io/en/latest/index.html#module-isal.igzip_lib",
    "isal.igzip_lib.compress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip_lib.compress",
    "isal.igzip_lib.decompress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip_lib.decompress",
    "isal.igzip_lib.igzipdecompressor": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip_lib.IgzipDecompressor",
    "isal.igzip_lib.igzipdecompressor.crc": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip_lib.IgzipDecompressor.crc",
    "isal.igzip_lib.igzipdecompressor.decompress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip_lib.IgzipDecompressor.decompress",
    "isal.igzip_lib.igzipdecompressor.eof": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip_lib.IgzipDecompressor.eof",
    "isal.igzip_lib.igzipdecompressor.needs_input": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip_lib.IgzipDecompressor.needs_input",
    "isal.igzip_lib.igzipdecompressor.unused_data": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip_lib.IgzipDecompressor.unused_data",
    "isal.igzip_threaded": "https://python-isal.readthedocs.io/en/latest/index.html#module-isal.igzip_threaded",
    "isal.igzip_threaded.open": "https://python-isal.readthedocs.io/en/latest/index.html#isal.igzip_threaded.open",
    "isal.isal_zlib": "https://python-isal.readthedocs.io/en/latest/index.html#module-isal.isal_zlib",
    "isal.isal_zlib.adler32": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.adler32",
    "isal.isal_zlib.Compress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.Compress",
    "isal.isal_zlib.compress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.compress",
    "isal.isal_zlib.compress.compress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.Compress.compress",
    "isal.isal_zlib.compress.flush": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.Compress.flush",
    "isal.isal_zlib.compressobj": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.compressobj",
    "isal.isal_zlib.crc32": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.crc32",
    "isal.isal_zlib.crc32_combine": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.crc32_combine",
    "isal.isal_zlib.Decompress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.Decompress",
    "isal.isal_zlib.decompress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.decompress",
    "isal.isal_zlib.decompress.decompress": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.Decompress.decompress",
    "isal.isal_zlib.decompress.eof": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.Decompress.eof",
    "isal.isal_zlib.decompress.flush": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.Decompress.flush",
    "isal.isal_zlib.decompress.unconsumed_tail": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.Decompress.unconsumed_tail",
    "isal.isal_zlib.decompress.unused_data": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.Decompress.unused_data",
    "isal.isal_zlib.decompressobj": "https://python-isal.readthedocs.io/en/latest/index.html#isal.isal_zlib.decompressobj",
}
