VERSION = "2.1.0"

# fmt: off
MAPPING = {
    "jinxed": "https://jinxed.readthedocs.io/en/stable/",
    "jinxed._terminal": "https://jinxed.readthedocs.io/en/stable/api.html",
    "jinxed._terminal.terminal": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.Terminal",
    "jinxed._util": "https://jinxed.readthedocs.io/en/stable/api.html",
    "jinxed._util.error": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.error",
    "jinxed.error": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.error",
    "jinxed.setupterm": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.setupterm",
    "jinxed.terminal": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.Terminal",
    "jinxed.terminal.overlay_capabilities": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.Terminal.overlay_capabilities",
    "jinxed.terminal.tigetflag": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.Terminal.tigetflag",
    "jinxed.terminal.tigetnum": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.Terminal.tigetnum",
    "jinxed.terminal.tigetstr": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.Terminal.tigetstr",
    "jinxed.tigetflag": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.tigetflag",
    "jinxed.tigetnum": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.tigetnum",
    "jinxed.tigetstr": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.tigetstr",
    "jinxed.tparm": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.tparm",
    "jinxed.win32": "https://jinxed.readthedocs.io/en/stable/api.html#module-jinxed.win32",
    "jinxed.win32.consoleinput": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.ConsoleInput",
    "jinxed.win32.consoleinput.fd": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.ConsoleInput.fd",
    "jinxed.win32.consoleinput.handle": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.ConsoleInput.handle",
    "jinxed.win32.consoleinput.peek": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.ConsoleInput.peek",
    "jinxed.win32.consoleinput.read": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.ConsoleInput.read",
    "jinxed.win32.consoleinput.wait": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.ConsoleInput.wait",
    "jinxed.win32.consolescreenbufferinfo": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.ConsoleScreenBufferInfo",
    "jinxed.win32.enable_vt_mode": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.enable_vt_mode",
    "jinxed.win32.flush_and_set_console": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.flush_and_set_console",
    "jinxed.win32.get_console_input_encoding": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.get_console_input_encoding",
    "jinxed.win32.get_console_mode": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.get_console_mode",
    "jinxed.win32.get_csbi": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.get_csbi",
    "jinxed.win32.get_term": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.get_term",
    "jinxed.win32.get_terminal_size": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.get_terminal_size",
    "jinxed.win32.set_console_mode": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.set_console_mode",
    "jinxed.win32.setcbreak": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.setcbreak",
    "jinxed.win32.setraw": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.setraw",
    "jinxed.win32.vtmode_supported": "https://jinxed.readthedocs.io/en/stable/api.html#jinxed.win32.VTMODE_SUPPORTED",
}
