VERSION = "1.15.0"

# fmt: off
MAPPING = {
    "jsonrpc": "https://json-rpc.readthedocs.io/en/stable/",
    "jsonrpc.dispatcher": "https://json-rpc.readthedocs.io/en/stable/dispatcher.html#module-jsonrpc.dispatcher",
    "jsonrpc.dispatcher.dispatcher": "https://json-rpc.readthedocs.io/en/stable/dispatcher.html#jsonrpc.dispatcher.Dispatcher",
    "jsonrpc.dispatcher.dispatcher.__init__": "https://json-rpc.readthedocs.io/en/stable/dispatcher.html#jsonrpc.dispatcher.Dispatcher.__init__",
    "jsonrpc.dispatcher.dispatcher.add_method": "https://json-rpc.readthedocs.io/en/stable/dispatcher.html#jsonrpc.dispatcher.Dispatcher.add_method",
    "jsonrpc.dispatcher.dispatcher.build_method_map": "https://json-rpc.readthedocs.io/en/stable/dispatcher.html#jsonrpc.dispatcher.Dispatcher.build_method_map",
    "jsonrpc.exceptions": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#module-jsonrpc.exceptions",
    "jsonrpc.exceptions.jsonrpcdispatchexception": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCDispatchException",
    "jsonrpc.exceptions.jsonrpcerror": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCError",
    "jsonrpc.exceptions.jsonrpcerror.code": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCError.code",
    "jsonrpc.exceptions.jsonrpcerror.data": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCError.data",
    "jsonrpc.exceptions.jsonrpcerror.deserialize": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCError.deserialize",
    "jsonrpc.exceptions.jsonrpcerror.from_json": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCError.from_json",
    "jsonrpc.exceptions.jsonrpcerror.json": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCError.json",
    "jsonrpc.exceptions.jsonrpcerror.message": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCError.message",
    "jsonrpc.exceptions.jsonrpcerror.serialize": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCError.serialize",
    "jsonrpc.exceptions.jsonrpcexception": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCException",
    "jsonrpc.exceptions.jsonrpcinternalerror": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInternalError",
    "jsonrpc.exceptions.jsonrpcinternalerror.code": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInternalError.CODE",
    "jsonrpc.exceptions.jsonrpcinternalerror.message": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInternalError.MESSAGE",
    "jsonrpc.exceptions.jsonrpcinvalidparams": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInvalidParams",
    "jsonrpc.exceptions.jsonrpcinvalidparams.code": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInvalidParams.CODE",
    "jsonrpc.exceptions.jsonrpcinvalidparams.message": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInvalidParams.MESSAGE",
    "jsonrpc.exceptions.jsonrpcinvalidrequest": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInvalidRequest",
    "jsonrpc.exceptions.jsonrpcinvalidrequest.code": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInvalidRequest.CODE",
    "jsonrpc.exceptions.jsonrpcinvalidrequest.message": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInvalidRequest.MESSAGE",
    "jsonrpc.exceptions.jsonrpcinvalidrequestexception": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCInvalidRequestException",
    "jsonrpc.exceptions.jsonrpcmethodnotfound": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCMethodNotFound",
    "jsonrpc.exceptions.jsonrpcmethodnotfound.code": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCMethodNotFound.CODE",
    "jsonrpc.exceptions.jsonrpcmethodnotfound.message": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCMethodNotFound.MESSAGE",
    "jsonrpc.exceptions.jsonrpcparseerror": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCParseError",
    "jsonrpc.exceptions.jsonrpcparseerror.code": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCParseError.CODE",
    "jsonrpc.exceptions.jsonrpcparseerror.message": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCParseError.MESSAGE",
    "jsonrpc.exceptions.jsonrpcservererror": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCServerError",
    "jsonrpc.exceptions.jsonrpcservererror.code": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCServerError.CODE",
    "jsonrpc.exceptions.jsonrpcservererror.message": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.exceptions.JSONRPCServerError.MESSAGE",
    "jsonrpc.jsonrpc": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#module-jsonrpc.jsonrpc",
    "jsonrpc.jsonrpc.jsonrpcrequest": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.jsonrpc.JSONRPCRequest",
    "jsonrpc.jsonrpc.jsonrpcrequest.from_data": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.jsonrpc.JSONRPCRequest.from_data",
    "jsonrpc.jsonrpc.jsonrpcrequest.from_json": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.jsonrpc.JSONRPCRequest.from_json",
    "jsonrpc.manager": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#module-jsonrpc.manager",
    "jsonrpc.manager.jsonrpcresponsemanager": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.manager.JSONRPCResponseManager",
    "jsonrpc.manager.jsonrpcresponsemanager.handle": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.manager.JSONRPCResponseManager.handle",
    "jsonrpc.manager.jsonrpcresponsemanager.handle_request": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.manager.JSONRPCResponseManager.handle_request",
    "jsonrpc.manager.jsonrpcresponsemanager.response_class_map": "https://json-rpc.readthedocs.io/en/stable/jsonrpc.html#jsonrpc.manager.JSONRPCResponseManager.RESPONSE_CLASS_MAP",
}
