VERSION = "1.6.5"

# fmt: off
MAPPING = {
    "jumpssh": "https://jumpssh.readthedocs.io/en/stable/",
    "jumpssh.exception": "https://jumpssh.readthedocs.io/en/stable/api.html#module-jumpssh.exception",
    "jumpssh.exception.connectionerror": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.exception.ConnectionError",
    "jumpssh.exception.restclienterror": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.exception.RestClientError",
    "jumpssh.exception.runcmderror": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.exception.RunCmdError",
    "jumpssh.exception.sshexception": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.exception.SSHException",
    "jumpssh.exception.timeouterror": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.exception.TimeoutError",
    "jumpssh.restclient": "https://jumpssh.readthedocs.io/en/stable/api.html#module-jumpssh.restclient",
    "jumpssh.restclient.httpresponse": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.HTTPResponse",
    "jumpssh.restclient.httpresponse.check_for_success": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.HTTPResponse.check_for_success",
    "jumpssh.restclient.httpresponse.is_valid_json_body": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.HTTPResponse.is_valid_json_body",
    "jumpssh.restclient.httpresponse.json": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.HTTPResponse.json",
    "jumpssh.restclient.restsshclient": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.RestSshClient",
    "jumpssh.restclient.restsshclient.delete": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.RestSshClient.delete",
    "jumpssh.restclient.restsshclient.get": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.RestSshClient.get",
    "jumpssh.restclient.restsshclient.head": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.RestSshClient.head",
    "jumpssh.restclient.restsshclient.options": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.RestSshClient.options",
    "jumpssh.restclient.restsshclient.patch": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.RestSshClient.patch",
    "jumpssh.restclient.restsshclient.post": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.RestSshClient.post",
    "jumpssh.restclient.restsshclient.put": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.RestSshClient.put",
    "jumpssh.restclient.restsshclient.request": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.restclient.RestSshClient.request",
    "jumpssh.session": "https://jumpssh.readthedocs.io/en/stable/api.html#module-jumpssh.session",
    "jumpssh.session.runcmdresult": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.RunCmdResult",
    "jumpssh.session.runsshcmdresult": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.RunSSHCmdResult",
    "jumpssh.session.runsshcmdresult.exit_code": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.RunSSHCmdResult.exit_code",
    "jumpssh.session.runsshcmdresult.output": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.RunSSHCmdResult.output",
    "jumpssh.session.sshsession": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession",
    "jumpssh.session.sshsession.close": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.close",
    "jumpssh.session.sshsession.exists": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.exists",
    "jumpssh.session.sshsession.file": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.file",
    "jumpssh.session.sshsession.get": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.get",
    "jumpssh.session.sshsession.get_cmd_output": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.get_cmd_output",
    "jumpssh.session.sshsession.get_exit_code": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.get_exit_code",
    "jumpssh.session.sshsession.get_remote_session": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.get_remote_session",
    "jumpssh.session.sshsession.get_sftp_client": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.get_sftp_client",
    "jumpssh.session.sshsession.is_active": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.is_active",
    "jumpssh.session.sshsession.open": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.open",
    "jumpssh.session.sshsession.put": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.put",
    "jumpssh.session.sshsession.run_cmd": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.session.SSHSession.run_cmd",
    "jumpssh.util": "https://jumpssh.readthedocs.io/en/stable/api.html#module-jumpssh.util",
    "jumpssh.util.id_generator": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.util.id_generator",
    "jumpssh.util.yes_no_query": "https://jumpssh.readthedocs.io/en/stable/api.html#jumpssh.util.yes_no_query",
}
