VERSION = "0.2.10"

# fmt: off
MAPPING = {
    "kerchunk": "https://fsspec.github.io/kerchunk/",
    "kerchunk.codecs": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.codecs.asciitablecodec": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.AsciiTableCodec",
    "kerchunk.codecs.asciitablecodec.__init__": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.AsciiTableCodec.__init__",
    "kerchunk.codecs.fillstringscodec": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.FillStringsCodec",
    "kerchunk.codecs.fillstringscodec.__init__": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.FillStringsCodec.__init__",
    "kerchunk.codecs.gribcodec": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.GRIBCodec",
    "kerchunk.codecs.gribcodec.__init__": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.GRIBCodec.__init__",
    "kerchunk.codecs.recordarraymember": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.RecordArrayMember",
    "kerchunk.codecs.recordarraymember.__init__": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.RecordArrayMember.__init__",
    "kerchunk.codecs.vararrcodec": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.VarArrCodec",
    "kerchunk.codecs.vararrcodec.__init__": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.VarArrCodec.__init__",
    "kerchunk.codecs.zlibcodec": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.ZlibCodec",
    "kerchunk.codecs.zlibcodec.__init__": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.codecs.ZlibCodec.__init__",
    "kerchunk.combine": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.combine.auto_dask": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.auto_dask",
    "kerchunk.combine.concatenate_arrays": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.concatenate_arrays",
    "kerchunk.combine.drop": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.drop",
    "kerchunk.combine.merge_vars": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.merge_vars",
    "kerchunk.combine.multizarrtozarr": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.MultiZarrToZarr",
    "kerchunk.combine.multizarrtozarr.__init__": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.MultiZarrToZarr.__init__",
    "kerchunk.combine.multizarrtozarr.append": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.MultiZarrToZarr.append",
    "kerchunk.combine.multizarrtozarr.translate": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.MultiZarrToZarr.translate",
    "kerchunk.df": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.df.refs_to_dataframe": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.df.refs_to_dataframe",
    "kerchunk.fits": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.fits.process_file": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.fits.process_file",
    "kerchunk.grib2": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.grib2.scan_grib": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.grib2.scan_grib",
    "kerchunk.hdf": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.hdf.singlehdf5tozarr": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.hdf.SingleHdf5ToZarr",
    "kerchunk.hdf.singlehdf5tozarr.translate": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.hdf.SingleHdf5ToZarr.translate",
    "kerchunk.hdf4": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.hdf4.hdf4tozarr": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.hdf4.HDF4ToZarr",
    "kerchunk.hdf4.hdf4tozarr.__init__": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.hdf4.HDF4ToZarr.__init__",
    "kerchunk.hdf4.hdf4tozarr.translate": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.hdf4.HDF4ToZarr.translate",
    "kerchunk.netcdf3": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.netcdf3.netcdf3tozarr": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.netCDF3.NetCDF3ToZarr",
    "kerchunk.netcdf3.netcdf3tozarr.__init__": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.netCDF3.NetCDF3ToZarr.__init__",
    "kerchunk.netcdf3.netcdf3tozarr.translate": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.netCDF3.NetCDF3ToZarr.translate",
    "kerchunk.tiff": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.tiff.generate_coords": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.tiff.generate_coords",
    "kerchunk.tiff.tiff_to_zarr": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.tiff.tiff_to_zarr",
    "kerchunk.utils": "https://fsspec.github.io/kerchunk/reference.html",
    "kerchunk.utils.consolidate": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.utils.consolidate",
    "kerchunk.utils.dereference_archives": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.utils.dereference_archives",
    "kerchunk.utils.do_inline": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.utils.do_inline",
    "kerchunk.utils.inline_array": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.utils.inline_array",
    "kerchunk.utils.rename_target": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.utils.rename_target",
    "kerchunk.utils.rename_target_files": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.utils.rename_target_files",
    "kerchunk.utils.subchunk": "https://fsspec.github.io/kerchunk/reference.html#kerchunk.utils.subchunk",
}
