VERSION = "0.9.0"

# fmt: off
MAPPING = {
    "keybert": "https://maartengr.github.io/KeyBERT/",
    "keybert._llm": "https://maartengr.github.io/KeyBERT/api/keyllm.html",
    "keybert._llm.keyllm": "https://maartengr.github.io/KeyBERT/api/keyllm.html#keybert._llm.KeyLLM",
    "keybert._llm.keyllm.__init__": "https://maartengr.github.io/KeyBERT/api/keyllm.html#keybert._llm.KeyLLM.__init__",
    "keybert._llm.keyllm.extract_keywords": "https://maartengr.github.io/KeyBERT/api/keyllm.html#keybert._llm.KeyLLM.extract_keywords",
    "keybert._maxsum": "https://maartengr.github.io/KeyBERT/api/maxsum.html",
    "keybert._maxsum.max_sum_distance": "https://maartengr.github.io/KeyBERT/api/maxsum.html#keybert._maxsum.max_sum_distance",
    "keybert._mmr": "https://maartengr.github.io/KeyBERT/api/mmr.html",
    "keybert._mmr.mmr": "https://maartengr.github.io/KeyBERT/api/mmr.html#keybert._mmr.mmr",
    "keybert._model": "https://maartengr.github.io/KeyBERT/api/keybert.html",
    "keybert._model.keybert": "https://maartengr.github.io/KeyBERT/api/keybert.html#keybert._model.KeyBERT",
    "keybert._model.keybert.__init__": "https://maartengr.github.io/KeyBERT/api/keybert.html#keybert._model.KeyBERT.__init__",
    "keybert._model.keybert.extract_embeddings": "https://maartengr.github.io/KeyBERT/api/keybert.html#keybert._model.KeyBERT.extract_embeddings",
    "keybert._model.keybert.extract_keywords": "https://maartengr.github.io/KeyBERT/api/keybert.html#keybert._model.KeyBERT.extract_keywords",
    "keybert.keybert": "https://maartengr.github.io/KeyBERT/api/keybert.html#keybert._model.KeyBERT",
    "keybert.keyllm": "https://maartengr.github.io/KeyBERT/api/keyllm.html#keybert._llm.KeyLLM",
    "keybert.llm._cohere": "https://maartengr.github.io/KeyBERT/api/cohere.html",
    "keybert.llm._cohere.cohere": "https://maartengr.github.io/KeyBERT/api/cohere.html#keybert.llm._cohere.Cohere",
    "keybert.llm._cohere.cohere.extract_keywords": "https://maartengr.github.io/KeyBERT/api/cohere.html#keybert.llm._cohere.Cohere.extract_keywords",
    "keybert.llm._langchain": "https://maartengr.github.io/KeyBERT/api/langchain.html",
    "keybert.llm._langchain.langchain": "https://maartengr.github.io/KeyBERT/api/langchain.html#keybert.llm._langchain.LangChain",
    "keybert.llm._langchain.langchain.extract_keywords": "https://maartengr.github.io/KeyBERT/api/langchain.html#keybert.llm._langchain.LangChain.extract_keywords",
    "keybert.llm._litellm": "https://maartengr.github.io/KeyBERT/api/litellm.html",
    "keybert.llm._litellm.litellm": "https://maartengr.github.io/KeyBERT/api/litellm.html#keybert.llm._litellm.LiteLLM",
    "keybert.llm._litellm.litellm.extract_keywords": "https://maartengr.github.io/KeyBERT/api/litellm.html#keybert.llm._litellm.LiteLLM.extract_keywords",
    "keybert.llm._openai": "https://maartengr.github.io/KeyBERT/api/openai.html",
    "keybert.llm._openai.openai": "https://maartengr.github.io/KeyBERT/api/openai.html#keybert.llm._openai.OpenAI",
    "keybert.llm._openai.openai.extract_keywords": "https://maartengr.github.io/KeyBERT/api/openai.html#keybert.llm._openai.OpenAI.extract_keywords",
    "keybert.llm._textgeneration": "https://maartengr.github.io/KeyBERT/api/textgeneration.html",
    "keybert.llm._textgeneration.textgeneration": "https://maartengr.github.io/KeyBERT/api/textgeneration.html#keybert.llm._textgeneration.TextGeneration",
    "keybert.llm._textgeneration.textgeneration.extract_keywords": "https://maartengr.github.io/KeyBERT/api/textgeneration.html#keybert.llm._textgeneration.TextGeneration.extract_keywords",
    "keybert.llm.cohere": "https://maartengr.github.io/KeyBERT/api/cohere.html#keybert.llm._cohere.Cohere",
    "keybert.llm.langchain": "https://maartengr.github.io/KeyBERT/api/langchain.html#keybert.llm._langchain.LangChain",
    "keybert.llm.litellm": "https://maartengr.github.io/KeyBERT/api/litellm.html#keybert.llm._litellm.LiteLLM",
    "keybert.llm.openai": "https://maartengr.github.io/KeyBERT/api/openai.html#keybert.llm._openai.OpenAI",
    "keybert.llm.textgeneration": "https://maartengr.github.io/KeyBERT/api/textgeneration.html#keybert.llm._textgeneration.TextGeneration",
}
