VERSION = "5.7.0"

# fmt: off
MAPPING = {
    "konoha": "https://konoha.readthedocs.io/en/stable/",
    "konoha.data": "https://konoha.readthedocs.io/en/stable/reference/data/index.html#module-konoha.data",
    "konoha.data.resource": "https://konoha.readthedocs.io/en/stable/reference/data/resource.html#module-konoha.data.resource",
    "konoha.data.resource.resource": "https://konoha.readthedocs.io/en/stable/reference/data/resource.html#konoha.data.resource.Resource",
    "konoha.data.resource.resource.download_from_s3": "https://konoha.readthedocs.io/en/stable/reference/data/resource.html#konoha.data.resource.Resource.download_from_s3",
    "konoha.data.token": "https://konoha.readthedocs.io/en/stable/reference/data/token.html#module-konoha.data.token",
    "konoha.data.token.token": "https://konoha.readthedocs.io/en/stable/reference/data/token.html#konoha.data.token.Token",
    "konoha.konoha_token": "https://konoha.readthedocs.io/en/stable/reference/konoha_token.html#module-konoha.konoha_token",
    "konoha.sentence_tokenizer": "https://konoha.readthedocs.io/en/stable/reference/sentence_tokenizer.html#module-konoha.sentence_tokenizer",
    "konoha.sentence_tokenizer.sentencetokenizer": "https://konoha.readthedocs.io/en/stable/reference/sentence_tokenizer.html#konoha.sentence_tokenizer.SentenceTokenizer",
    "konoha.word_tokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizer.html#module-konoha.word_tokenizer",
    "konoha.word_tokenizer.wordtokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizer.html#konoha.word_tokenizer.WordTokenizer",
    "konoha.word_tokenizer.wordtokenizer.batch_tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizer.html#konoha.word_tokenizer.WordTokenizer.batch_tokenize",
    "konoha.word_tokenizer.wordtokenizer.tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizer.html#konoha.word_tokenizer.WordTokenizer.tokenize",
    "konoha.word_tokenizers": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/index.html#module-konoha.word_tokenizers",
    "konoha.word_tokenizers.character_tokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/character_tokenizer.html#module-konoha.word_tokenizers.character_tokenizer",
    "konoha.word_tokenizers.character_tokenizer.charactertokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/character_tokenizer.html#konoha.word_tokenizers.character_tokenizer.CharacterTokenizer",
    "konoha.word_tokenizers.character_tokenizer.charactertokenizer.tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/character_tokenizer.html#konoha.word_tokenizers.character_tokenizer.CharacterTokenizer.tokenize",
    "konoha.word_tokenizers.janome_tokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/janome_tokenizer.html#module-konoha.word_tokenizers.janome_tokenizer",
    "konoha.word_tokenizers.janome_tokenizer.janometokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/janome_tokenizer.html#konoha.word_tokenizers.janome_tokenizer.JanomeTokenizer",
    "konoha.word_tokenizers.janome_tokenizer.janometokenizer.tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/janome_tokenizer.html#konoha.word_tokenizers.janome_tokenizer.JanomeTokenizer.tokenize",
    "konoha.word_tokenizers.mecab_tokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/mecab_tokenizer.html#module-konoha.word_tokenizers.mecab_tokenizer",
    "konoha.word_tokenizers.mecab_tokenizer.mecabtokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/mecab_tokenizer.html#konoha.word_tokenizers.mecab_tokenizer.MeCabTokenizer",
    "konoha.word_tokenizers.mecab_tokenizer.mecabtokenizer.tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/mecab_tokenizer.html#konoha.word_tokenizers.mecab_tokenizer.MeCabTokenizer.tokenize",
    "konoha.word_tokenizers.nagisa_tokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/nagisa_tokenizer.html#module-konoha.word_tokenizers.nagisa_tokenizer",
    "konoha.word_tokenizers.nagisa_tokenizer.nagisatokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/nagisa_tokenizer.html#konoha.word_tokenizers.nagisa_tokenizer.NagisaTokenizer",
    "konoha.word_tokenizers.nagisa_tokenizer.nagisatokenizer.tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/nagisa_tokenizer.html#konoha.word_tokenizers.nagisa_tokenizer.NagisaTokenizer.tokenize",
    "konoha.word_tokenizers.sentencepiece_tokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/sentencepiece_tokenizer.html#module-konoha.word_tokenizers.sentencepiece_tokenizer",
    "konoha.word_tokenizers.sentencepiece_tokenizer.sentencepiecetokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/sentencepiece_tokenizer.html#konoha.word_tokenizers.sentencepiece_tokenizer.SentencepieceTokenizer",
    "konoha.word_tokenizers.sentencepiece_tokenizer.sentencepiecetokenizer.tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/sentencepiece_tokenizer.html#konoha.word_tokenizers.sentencepiece_tokenizer.SentencepieceTokenizer.tokenize",
    "konoha.word_tokenizers.sudachi_tokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/sudachi_tokenizer.html#module-konoha.word_tokenizers.sudachi_tokenizer",
    "konoha.word_tokenizers.sudachi_tokenizer.sudachitokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/sudachi_tokenizer.html#konoha.word_tokenizers.sudachi_tokenizer.SudachiTokenizer",
    "konoha.word_tokenizers.sudachi_tokenizer.sudachitokenizer.tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/sudachi_tokenizer.html#konoha.word_tokenizers.sudachi_tokenizer.SudachiTokenizer.tokenize",
    "konoha.word_tokenizers.tokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/tokenizer.html#module-konoha.word_tokenizers.tokenizer",
    "konoha.word_tokenizers.tokenizer.basetokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/tokenizer.html#konoha.word_tokenizers.tokenizer.BaseTokenizer",
    "konoha.word_tokenizers.tokenizer.basetokenizer.name": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/tokenizer.html#konoha.word_tokenizers.tokenizer.BaseTokenizer.name",
    "konoha.word_tokenizers.tokenizer.basetokenizer.tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/tokenizer.html#konoha.word_tokenizers.tokenizer.BaseTokenizer.tokenize",
    "konoha.word_tokenizers.whitespace_tokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/whitespace_tokenizer.html#module-konoha.word_tokenizers.whitespace_tokenizer",
    "konoha.word_tokenizers.whitespace_tokenizer.whitespacetokenizer": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/whitespace_tokenizer.html#konoha.word_tokenizers.whitespace_tokenizer.WhitespaceTokenizer",
    "konoha.word_tokenizers.whitespace_tokenizer.whitespacetokenizer.tokenize": "https://konoha.readthedocs.io/en/stable/reference/word_tokenizers/whitespace_tokenizer.html#konoha.word_tokenizers.whitespace_tokenizer.WhitespaceTokenizer.tokenize",
}
