VERSION = "0.14.0"

# fmt: off
MAPPING = {
    "lakefs_spec": "https://lakefs-spec.org/latest/",
    "lakefs_spec.errors": "https://lakefs-spec.org/latest/reference/lakefs_spec/errors/#lakefs_spec.errors",
    "lakefs_spec.errors.translate_lakefs_error": "https://lakefs-spec.org/latest/reference/lakefs_spec/errors/#lakefs_spec.errors.translate_lakefs_error",
    "lakefs_spec.lakefsfilesystem": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem",
    "lakefs_spec.lakefstransaction": "https://lakefs-spec.org/latest/reference/lakefs_spec/transaction/#lakefs_spec.transaction.LakeFSTransaction",
    "lakefs_spec.spec": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec",
    "lakefs_spec.spec.lakefsfilesystem": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem",
    "lakefs_spec.spec.lakefsfilesystem.checksum": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.checksum",
    "lakefs_spec.spec.lakefsfilesystem.cp_file": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.cp_file",
    "lakefs_spec.spec.lakefsfilesystem.created": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.created",
    "lakefs_spec.spec.lakefsfilesystem.exists": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.exists",
    "lakefs_spec.spec.lakefsfilesystem.get_file": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.get_file",
    "lakefs_spec.spec.lakefsfilesystem.info": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.info",
    "lakefs_spec.spec.lakefsfilesystem.ls": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.ls",
    "lakefs_spec.spec.lakefsfilesystem.modified": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.modified",
    "lakefs_spec.spec.lakefsfilesystem.open": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.open",
    "lakefs_spec.spec.lakefsfilesystem.put_file": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.put_file",
    "lakefs_spec.spec.lakefsfilesystem.rm": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.rm",
    "lakefs_spec.spec.lakefsfilesystem.rm_file": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.rm_file",
    "lakefs_spec.spec.lakefsfilesystem.tail": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.tail",
    "lakefs_spec.spec.lakefsfilesystem.touch": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.touch",
    "lakefs_spec.spec.lakefsfilesystem.wrapped_api_call": "https://lakefs-spec.org/latest/reference/lakefs_spec/spec/#lakefs_spec.spec.LakeFSFileSystem.wrapped_api_call",
    "lakefs_spec.spec.lakefstransaction": "https://lakefs-spec.org/latest/reference/lakefs_spec/transaction/#lakefs_spec.transaction.LakeFSTransaction",
    "lakefs_spec.spec.md5_checksum": "https://lakefs-spec.org/latest/reference/lakefs_spec/util/#lakefs_spec.util.md5_checksum",
    "lakefs_spec.spec.parse": "https://lakefs-spec.org/latest/reference/lakefs_spec/util/#lakefs_spec.util.parse",
    "lakefs_spec.spec.requestconfig": "https://lakefs-spec.org/latest/reference/lakefs_spec/types/#lakefs_spec.types.RequestConfig",
    "lakefs_spec.transaction": "https://lakefs-spec.org/latest/reference/lakefs_spec/transaction/#lakefs_spec.transaction",
    "lakefs_spec.transaction.lakefstransaction": "https://lakefs-spec.org/latest/reference/lakefs_spec/transaction/#lakefs_spec.transaction.LakeFSTransaction",
    "lakefs_spec.transaction.lakefstransaction.commit": "https://lakefs-spec.org/latest/reference/lakefs_spec/transaction/#lakefs_spec.transaction.LakeFSTransaction.commit",
    "lakefs_spec.transaction.lakefstransaction.merge": "https://lakefs-spec.org/latest/reference/lakefs_spec/transaction/#lakefs_spec.transaction.LakeFSTransaction.merge",
    "lakefs_spec.transaction.lakefstransaction.rev_parse": "https://lakefs-spec.org/latest/reference/lakefs_spec/transaction/#lakefs_spec.transaction.LakeFSTransaction.rev_parse",
    "lakefs_spec.transaction.lakefstransaction.revert": "https://lakefs-spec.org/latest/reference/lakefs_spec/transaction/#lakefs_spec.transaction.LakeFSTransaction.revert",
    "lakefs_spec.transaction.lakefstransaction.tag": "https://lakefs-spec.org/latest/reference/lakefs_spec/transaction/#lakefs_spec.transaction.LakeFSTransaction.tag",
    "lakefs_spec.transaction.mergekwargs": "https://lakefs-spec.org/latest/reference/lakefs_spec/types/#lakefs_spec.types.MergeKwargs",
    "lakefs_spec.types": "https://lakefs-spec.org/latest/reference/lakefs_spec/types/#lakefs_spec.types",
    "lakefs_spec.types.mergekwargs": "https://lakefs-spec.org/latest/reference/lakefs_spec/types/#lakefs_spec.types.MergeKwargs",
    "lakefs_spec.types.requestconfig": "https://lakefs-spec.org/latest/reference/lakefs_spec/types/#lakefs_spec.types.RequestConfig",
    "lakefs_spec.util": "https://lakefs-spec.org/latest/reference/lakefs_spec/util/#lakefs_spec.util",
    "lakefs_spec.util.depaginate": "https://lakefs-spec.org/latest/reference/lakefs_spec/util/#lakefs_spec.util.depaginate",
    "lakefs_spec.util.md5_checksum": "https://lakefs-spec.org/latest/reference/lakefs_spec/util/#lakefs_spec.util.md5_checksum",
    "lakefs_spec.util.parse": "https://lakefs-spec.org/latest/reference/lakefs_spec/util/#lakefs_spec.util.parse",
}
