VERSION = "1.1.2"

# fmt: off
MAPPING = {
    "lbox": "https://labelbox-python.readthedocs.io/en/latest/",
    "lbox.exceptions": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#module-lbox.exceptions",
    "lbox.exceptions.apilimiterror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.ApiLimitError",
    "lbox.exceptions.authenticationerror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.AuthenticationError",
    "lbox.exceptions.authorizationerror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.AuthorizationError",
    "lbox.exceptions.confidencenotsupportedexception": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.ConfidenceNotSupportedException",
    "lbox.exceptions.custommetricsnotsupportedexception": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.CustomMetricsNotSupportedException",
    "lbox.exceptions.error_message_for_unparsed_graphql_error": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.error_message_for_unparsed_graphql_error",
    "lbox.exceptions.inconsistentontologyexception": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.InconsistentOntologyException",
    "lbox.exceptions.internalservererror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.InternalServerError",
    "lbox.exceptions.invalidattributeerror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.InvalidAttributeError",
    "lbox.exceptions.invalidqueryerror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.InvalidQueryError",
    "lbox.exceptions.labelboxerror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.LabelboxError",
    "lbox.exceptions.malformedqueryexception": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.MalformedQueryException",
    "lbox.exceptions.malvalidationerror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.MALValidationError",
    "lbox.exceptions.networkerror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.NetworkError",
    "lbox.exceptions.operationnotallowedexception": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.OperationNotAllowedException",
    "lbox.exceptions.operationnotsupportedexception": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.OperationNotSupportedException",
    "lbox.exceptions.processingwaittimeout": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.ProcessingWaitTimeout",
    "lbox.exceptions.resourceconflict": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.ResourceConflict",
    "lbox.exceptions.resourcecreationerror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.ResourceCreationError",
    "lbox.exceptions.resourcenotfounderror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.ResourceNotFoundError",
    "lbox.exceptions.timeouterror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.TimeoutError",
    "lbox.exceptions.unprocessableentityerror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.UnprocessableEntityError",
    "lbox.exceptions.uuiderror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.UuidError",
    "lbox.exceptions.validationfailederror": "https://labelbox-python.readthedocs.io/en/latest/exceptions.html#lbox.exceptions.ValidationFailedError",
    "lbox.request_client": "https://labelbox-python.readthedocs.io/en/latest/request-client.html#module-lbox.request_client",
    "lbox.request_client.requestclient": "https://labelbox-python.readthedocs.io/en/latest/request-client.html#lbox.request_client.RequestClient",
    "lbox.request_client.requestclient.execute": "https://labelbox-python.readthedocs.io/en/latest/request-client.html#lbox.request_client.RequestClient.execute",
}
