VERSION = "0.8.0"

# fmt: off
MAPPING = {
    "livy": "https://pylivy.readthedocs.io/en/stable/",
    "livy.batch": "https://pylivy.readthedocs.io/en/stable/api/batch.html#module-livy.batch",
    "livy.batch.livybatch": "https://pylivy.readthedocs.io/en/stable/api/batch.html#livy.batch.LivyBatch",
    "livy.batch.livybatch.create": "https://pylivy.readthedocs.io/en/stable/api/batch.html#livy.batch.LivyBatch.create",
    "livy.batch.livybatch.kill": "https://pylivy.readthedocs.io/en/stable/api/batch.html#livy.batch.LivyBatch.kill",
    "livy.batch.livybatch.log": "https://pylivy.readthedocs.io/en/stable/api/batch.html#livy.batch.LivyBatch.log",
    "livy.batch.livybatch.state": "https://pylivy.readthedocs.io/en/stable/api/batch.html#livy.batch.LivyBatch.state",
    "livy.batch.livybatch.wait": "https://pylivy.readthedocs.io/en/stable/api/batch.html#livy.batch.LivyBatch.wait",
    "livy.client": "https://pylivy.readthedocs.io/en/stable/api/client.html#module-livy.client",
    "livy.client.livyclient": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient",
    "livy.client.livyclient.close": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.close",
    "livy.client.livyclient.create_batch": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.create_batch",
    "livy.client.livyclient.create_session": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.create_session",
    "livy.client.livyclient.create_statement": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.create_statement",
    "livy.client.livyclient.delete_batch": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.delete_batch",
    "livy.client.livyclient.delete_session": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.delete_session",
    "livy.client.livyclient.get_batch": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.get_batch",
    "livy.client.livyclient.get_batch_log": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.get_batch_log",
    "livy.client.livyclient.get_session": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.get_session",
    "livy.client.livyclient.get_statement": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.get_statement",
    "livy.client.livyclient.legacy_server": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.legacy_server",
    "livy.client.livyclient.list_batches": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.list_batches",
    "livy.client.livyclient.list_sessions": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.list_sessions",
    "livy.client.livyclient.list_statements": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.list_statements",
    "livy.client.livyclient.server_version": "https://pylivy.readthedocs.io/en/stable/api/client.html#livy.client.LivyClient.server_version",
    "livy.session": "https://pylivy.readthedocs.io/en/stable/api/session.html#module-livy.session",
    "livy.session.livysession": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession",
    "livy.session.livysession.close": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.close",
    "livy.session.livysession.create": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.create",
    "livy.session.livysession.download": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.download",
    "livy.session.livysession.download_sql": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.download_sql",
    "livy.session.livysession.read": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.read",
    "livy.session.livysession.read_sql": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.read_sql",
    "livy.session.livysession.run": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.run",
    "livy.session.livysession.state": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.state",
    "livy.session.livysession.upload": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.upload",
    "livy.session.livysession.wait": "https://pylivy.readthedocs.io/en/stable/api/session.html#livy.session.LivySession.wait",
}
