VERSION = "0.8.7"

# fmt: off
MAPPING = {
    "logomaker": "https://logomaker.readthedocs.io/en/latest/",
    "logomaker.alignment_to_matrix": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.alignment_to_matrix",
    "logomaker.demo": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.demo",
    "logomaker.get_example_matrix": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.get_example_matrix",
    "logomaker.glyph": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Glyph",
    "logomaker.glyph.__init__": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Glyph.__init__",
    "logomaker.glyph.draw": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Glyph.draw",
    "logomaker.glyph.set_attributes": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Glyph.set_attributes",
    "logomaker.list_example_datafiles": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.list_example_datafiles",
    "logomaker.list_example_matrices": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.list_example_matrices",
    "logomaker.logo": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo",
    "logomaker.logo.__init__": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.__init__",
    "logomaker.logo.draw": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.draw",
    "logomaker.logo.draw_baseline": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.draw_baseline",
    "logomaker.logo.fade_glyphs_in_probability_logo": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.fade_glyphs_in_probability_logo",
    "logomaker.logo.highlight_position": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.highlight_position",
    "logomaker.logo.highlight_position_range": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.highlight_position_range",
    "logomaker.logo.style_glyphs": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.style_glyphs",
    "logomaker.logo.style_glyphs_below": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.style_glyphs_below",
    "logomaker.logo.style_glyphs_in_sequence": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.style_glyphs_in_sequence",
    "logomaker.logo.style_single_glyph": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.style_single_glyph",
    "logomaker.logo.style_spines": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.style_spines",
    "logomaker.logo.style_xticks": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo.style_xticks",
    "logomaker.open_example_datafile": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.open_example_datafile",
    "logomaker.saliency_to_matrix": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.saliency_to_matrix",
    "logomaker.sequence_to_matrix": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.sequence_to_matrix",
    "logomaker.src": "https://logomaker.readthedocs.io/en/latest/implementation.html",
    "logomaker.src.glyph": "https://logomaker.readthedocs.io/en/latest/implementation.html",
    "logomaker.src.glyph.glyph": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Glyph",
    "logomaker.src.logo": "https://logomaker.readthedocs.io/en/latest/implementation.html",
    "logomaker.src.logo.logo": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.Logo",
    "logomaker.transform_matrix": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.transform_matrix",
    "logomaker.validate_matrix": "https://logomaker.readthedocs.io/en/latest/implementation.html#logomaker.validate_matrix",
}
