VERSION = "3.3.5"

# fmt: off
MAPPING = {
    "mailmanclient": "https://docs.mailman3.org/projects/mailmanclient/en/stable/",
    "mailmanclient.asynclient": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#module-mailmanclient.asynclient",
    "mailmanclient.asynclient.asyncclient": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asynclient.AsyncClient",
    "mailmanclient.asynclient.asyncclient.addresses": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asynclient.AsyncClient.addresses",
    "mailmanclient.asynclient.asyncclient.domains": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asynclient.AsyncClient.domains",
    "mailmanclient.asynclient.asyncclient.find_members": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asynclient.AsyncClient.find_members",
    "mailmanclient.asynclient.asyncclient.lists": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asynclient.AsyncClient.lists",
    "mailmanclient.asynclient.asyncclient.members": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asynclient.AsyncClient.members",
    "mailmanclient.asynclient.asyncclient.system": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asynclient.AsyncClient.system",
    "mailmanclient.asynclient.asyncclient.users": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asynclient.AsyncClient.users",
    "mailmanclient.asyncobjects": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html",
    "mailmanclient.asyncobjects.address": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html",
    "mailmanclient.asyncobjects.address.address": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.address.Address",
    "mailmanclient.asyncobjects.address.address.delete": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.address.Address.delete",
    "mailmanclient.asyncobjects.address.address.preferences": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.address.Address.preferences",
    "mailmanclient.asyncobjects.address.address.save": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.address.Address.save",
    "mailmanclient.asyncobjects.domain": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html",
    "mailmanclient.asyncobjects.domain.domain": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.domain.Domain",
    "mailmanclient.asyncobjects.domain.domain.delete": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.domain.Domain.delete",
    "mailmanclient.asyncobjects.domain.domain.save": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.domain.Domain.save",
    "mailmanclient.asyncobjects.mailinglist": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html",
    "mailmanclient.asyncobjects.mailinglist.mailinglist": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.mailinglist.MailingList",
    "mailmanclient.asyncobjects.mailinglist.mailinglist.config": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.mailinglist.MailingList.config",
    "mailmanclient.asyncobjects.mailinglist.mailinglist.delete": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.mailinglist.MailingList.delete",
    "mailmanclient.asyncobjects.mailinglist.mailinglist.get_roster": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.mailinglist.MailingList.get_roster",
    "mailmanclient.asyncobjects.mailinglist.mailinglist.members": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.mailinglist.MailingList.members",
    "mailmanclient.asyncobjects.mailinglist.mailinglist.moderators": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.mailinglist.MailingList.moderators",
    "mailmanclient.asyncobjects.mailinglist.mailinglist.nonmember": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.mailinglist.MailingList.nonmember",
    "mailmanclient.asyncobjects.mailinglist.mailinglist.owners": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.mailinglist.MailingList.owners",
    "mailmanclient.asyncobjects.mailinglist.mailinglist.save": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.mailinglist.MailingList.save",
    "mailmanclient.asyncobjects.member": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html",
    "mailmanclient.asyncobjects.member.member": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.member.Member",
    "mailmanclient.asyncobjects.member.member.delete": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.member.Member.delete",
    "mailmanclient.asyncobjects.member.member.preferences": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.member.Member.preferences",
    "mailmanclient.asyncobjects.member.member.save": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.member.Member.save",
    "mailmanclient.asyncobjects.preferences": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html",
    "mailmanclient.asyncobjects.preferences.preferences": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.preferences.Preferences",
    "mailmanclient.asyncobjects.preferences.preferences.delete": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.preferences.Preferences.delete",
    "mailmanclient.asyncobjects.preferences.preferences.save": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.preferences.Preferences.save",
    "mailmanclient.asyncobjects.user": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html",
    "mailmanclient.asyncobjects.user.user": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.user.User",
    "mailmanclient.asyncobjects.user.user.addresses": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.user.User.addresses",
    "mailmanclient.asyncobjects.user.user.delete": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.user.User.delete",
    "mailmanclient.asyncobjects.user.user.preferences": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.user.User.preferences",
    "mailmanclient.asyncobjects.user.user.save": "https://docs.mailman3.org/projects/mailmanclient/en/stable/src/mailmanclient/docs/async.html#mailmanclient.asyncobjects.user.User.save",
}
