VERSION = "0.6.1"

# fmt: off
MAPPING = {
    "manimpango": "https://manimpango.manim.community/en/stable/",
    "manimpango.cmanimpango.markuputils": "https://manimpango.manim.community/en/stable/reference/manimpango.MarkupUtils.html#manimpango.MarkupUtils",
    "manimpango.cmanimpango.textsetting": "https://manimpango.manim.community/en/stable/reference/manimpango.TextSetting.html#manimpango.TextSetting",
    "manimpango.enums.style": "https://manimpango.manim.community/en/stable/reference/manimpango.Style.html#manimpango.Style",
    "manimpango.enums.variant": "https://manimpango.manim.community/en/stable/reference/manimpango.Variant.html#manimpango.Variant",
    "manimpango.enums.weight": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight",
    "manimpango.fc_register_font": "https://manimpango.manim.community/en/stable/reference/manimpango.fc_register_font.html#manimpango.fc_register_font",
    "manimpango.fc_unregister_font": "https://manimpango.manim.community/en/stable/reference/manimpango.fc_unregister_font.html#manimpango.fc_unregister_font",
    "manimpango.list_fonts": "https://manimpango.manim.community/en/stable/reference/manimpango.list_fonts.html#manimpango.list_fonts",
    "manimpango.markuputils": "https://manimpango.manim.community/en/stable/reference/manimpango.MarkupUtils.html#manimpango.MarkupUtils",
    "manimpango.markuputils.text2svg": "https://manimpango.manim.community/en/stable/reference/manimpango.MarkupUtils.html#manimpango.MarkupUtils.text2svg",
    "manimpango.markuputils.validate": "https://manimpango.manim.community/en/stable/reference/manimpango.MarkupUtils.html#manimpango.MarkupUtils.validate",
    "manimpango.pangoutils": "https://manimpango.manim.community/en/stable/reference/manimpango.PangoUtils.html#manimpango.PangoUtils",
    "manimpango.pangoutils.remove_last_m": "https://manimpango.manim.community/en/stable/reference/manimpango.PangoUtils.html#manimpango.PangoUtils.remove_last_M",
    "manimpango.pangoutils.str2style": "https://manimpango.manim.community/en/stable/reference/manimpango.PangoUtils.html#manimpango.PangoUtils.str2style",
    "manimpango.pangoutils.str2weight": "https://manimpango.manim.community/en/stable/reference/manimpango.PangoUtils.html#manimpango.PangoUtils.str2weight",
    "manimpango.register_font": "https://manimpango.manim.community/en/stable/reference/manimpango.register_font.html#manimpango.register_font",
    "manimpango.style": "https://manimpango.manim.community/en/stable/reference/manimpango.Style.html#manimpango.Style",
    "manimpango.style.italic": "https://manimpango.manim.community/en/stable/reference/manimpango.Style.html#manimpango.Style.ITALIC",
    "manimpango.style.normal": "https://manimpango.manim.community/en/stable/reference/manimpango.Style.html#manimpango.Style.NORMAL",
    "manimpango.style.oblique": "https://manimpango.manim.community/en/stable/reference/manimpango.Style.html#manimpango.Style.OBLIQUE",
    "manimpango.text2svg": "https://manimpango.manim.community/en/stable/reference/manimpango.text2svg.html#manimpango.text2svg",
    "manimpango.textsetting": "https://manimpango.manim.community/en/stable/reference/manimpango.TextSetting.html#manimpango.TextSetting",
    "manimpango.unregister_font": "https://manimpango.manim.community/en/stable/reference/manimpango.unregister_font.html#manimpango.unregister_font",
    "manimpango.utils": "https://manimpango.manim.community/en/stable/reference/manimpango.PangoUtils.html",
    "manimpango.utils.pangoutils": "https://manimpango.manim.community/en/stable/reference/manimpango.PangoUtils.html#manimpango.PangoUtils",
    "manimpango.variant": "https://manimpango.manim.community/en/stable/reference/manimpango.Variant.html#manimpango.Variant",
    "manimpango.variant.normal": "https://manimpango.manim.community/en/stable/reference/manimpango.Variant.html#manimpango.Variant.NORMAL",
    "manimpango.variant.small_caps": "https://manimpango.manim.community/en/stable/reference/manimpango.Variant.html#manimpango.Variant.SMALL_CAPS",
    "manimpango.weight": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight",
    "manimpango.weight.bold": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.BOLD",
    "manimpango.weight.book": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.BOOK",
    "manimpango.weight.heavy": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.HEAVY",
    "manimpango.weight.light": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.LIGHT",
    "manimpango.weight.medium": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.MEDIUM",
    "manimpango.weight.normal": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.NORMAL",
    "manimpango.weight.semibold": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.SEMIBOLD",
    "manimpango.weight.thin": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.THIN",
    "manimpango.weight.ultrabold": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.ULTRABOLD",
    "manimpango.weight.ultraheavy": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.ULTRAHEAVY",
    "manimpango.weight.ultralight": "https://manimpango.manim.community/en/stable/reference/manimpango.Weight.html#manimpango.Weight.ULTRALIGHT",
}
