VERSION = "1.5.0"

# fmt: off
MAPPING = {
    "marshmallow_sqlalchemy": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/",
    "marshmallow_sqlalchemy.auto_field": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.auto_field",
    "marshmallow_sqlalchemy.column2field": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.column2field",
    "marshmallow_sqlalchemy.convert": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html",
    "marshmallow_sqlalchemy.convert.modelconverter": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.ModelConverter",
    "marshmallow_sqlalchemy.exceptions": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html",
    "marshmallow_sqlalchemy.exceptions.modelconversionerror": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.ModelConversionError",
    "marshmallow_sqlalchemy.field_for": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.field_for",
    "marshmallow_sqlalchemy.fields": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#module-marshmallow_sqlalchemy.fields",
    "marshmallow_sqlalchemy.fields.nested": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.fields.Nested",
    "marshmallow_sqlalchemy.fields.related": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.fields.Related",
    "marshmallow_sqlalchemy.fields.relatedlist": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.fields.RelatedList",
    "marshmallow_sqlalchemy.fields_for_model": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.fields_for_model",
    "marshmallow_sqlalchemy.modelconversionerror": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.ModelConversionError",
    "marshmallow_sqlalchemy.modelconverter": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.ModelConverter",
    "marshmallow_sqlalchemy.modelconverter.column2field": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.ModelConverter.column2field",
    "marshmallow_sqlalchemy.modelconverter.field_for": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.ModelConverter.field_for",
    "marshmallow_sqlalchemy.modelconverter.fields_for_model": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.ModelConverter.fields_for_model",
    "marshmallow_sqlalchemy.modelconverter.property2field": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.ModelConverter.property2field",
    "marshmallow_sqlalchemy.property2field": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.property2field",
    "marshmallow_sqlalchemy.schema": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html",
    "marshmallow_sqlalchemy.schema.sqlalchemyautoschema": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchema",
    "marshmallow_sqlalchemy.schema.sqlalchemyautoschemaopts": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchemaOpts",
    "marshmallow_sqlalchemy.schema.sqlalchemyschema": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchema",
    "marshmallow_sqlalchemy.schema.sqlalchemyschemaopts": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchemaOpts",
    "marshmallow_sqlalchemy.sqlalchemyautoschema": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchema",
    "marshmallow_sqlalchemy.sqlalchemyautoschema.get_instance": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchema.get_instance",
    "marshmallow_sqlalchemy.sqlalchemyautoschema.load": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchema.load",
    "marshmallow_sqlalchemy.sqlalchemyautoschema.make_instance": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchema.make_instance",
    "marshmallow_sqlalchemy.sqlalchemyautoschema.session": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchema.session",
    "marshmallow_sqlalchemy.sqlalchemyautoschema.transient": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchema.transient",
    "marshmallow_sqlalchemy.sqlalchemyautoschema.validate": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchema.validate",
    "marshmallow_sqlalchemy.sqlalchemyautoschemaopts": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemyAutoSchemaOpts",
    "marshmallow_sqlalchemy.sqlalchemyschema": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchema",
    "marshmallow_sqlalchemy.sqlalchemyschema.get_instance": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchema.get_instance",
    "marshmallow_sqlalchemy.sqlalchemyschema.load": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchema.load",
    "marshmallow_sqlalchemy.sqlalchemyschema.make_instance": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchema.make_instance",
    "marshmallow_sqlalchemy.sqlalchemyschema.session": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchema.session",
    "marshmallow_sqlalchemy.sqlalchemyschema.transient": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchema.transient",
    "marshmallow_sqlalchemy.sqlalchemyschema.validate": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchema.validate",
    "marshmallow_sqlalchemy.sqlalchemyschemaopts": "https://marshmallow-sqlalchemy.readthedocs.io/en/stable/api_reference.html#marshmallow_sqlalchemy.SQLAlchemySchemaOpts",
}
