VERSION = "0.24.0"

# fmt: off
MAPPING = {
    "marshmallow_jsonapi": "https://marshmallow-jsonapi.readthedocs.io/en/latest/",
    "marshmallow_jsonapi.exceptions": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#module-marshmallow_jsonapi.exceptions",
    "marshmallow_jsonapi.exceptions.incorrecttypeerror": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.exceptions.IncorrectTypeError",
    "marshmallow_jsonapi.exceptions.incorrecttypeerror.messages": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.exceptions.IncorrectTypeError.messages",
    "marshmallow_jsonapi.exceptions.jsonapierror": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.exceptions.JSONAPIError",
    "marshmallow_jsonapi.fields": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#module-marshmallow_jsonapi.fields",
    "marshmallow_jsonapi.fields.baserelationship": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.fields.BaseRelationship",
    "marshmallow_jsonapi.fields.documentmeta": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.fields.DocumentMeta",
    "marshmallow_jsonapi.fields.relationship": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.fields.Relationship",
    "marshmallow_jsonapi.fields.relationship.deserialize": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.fields.Relationship.deserialize",
    "marshmallow_jsonapi.fields.relationship.extract_value": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.fields.Relationship.extract_value",
    "marshmallow_jsonapi.fields.relationship.serialize": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.fields.Relationship.serialize",
    "marshmallow_jsonapi.fields.resourcemeta": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.fields.ResourceMeta",
    "marshmallow_jsonapi.flask": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#module-marshmallow_jsonapi.flask",
    "marshmallow_jsonapi.flask.relationship": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.flask.Relationship",
    "marshmallow_jsonapi.flask.schema": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.flask.Schema",
    "marshmallow_jsonapi.flask.schema.generate_url": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.flask.Schema.generate_url",
    "marshmallow_jsonapi.flask.schema.meta": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.flask.Schema.Meta",
    "marshmallow_jsonapi.flask.schema.meta.self_url": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.flask.Schema.Meta.self_url",
    "marshmallow_jsonapi.flask.schema.meta.self_url_kwargs": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.flask.Schema.Meta.self_url_kwargs",
    "marshmallow_jsonapi.flask.schema.meta.self_url_many": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.flask.Schema.Meta.self_url_many",
    "marshmallow_jsonapi.flask.schema.options_class": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.flask.Schema.OPTIONS_CLASS",
    "marshmallow_jsonapi.flask.schemaopts": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.flask.SchemaOpts",
    "marshmallow_jsonapi.schema": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema",
    "marshmallow_jsonapi.schema.check_relations": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.check_relations",
    "marshmallow_jsonapi.schema.format_error": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.format_error",
    "marshmallow_jsonapi.schema.format_errors": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.format_errors",
    "marshmallow_jsonapi.schema.format_item": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.format_item",
    "marshmallow_jsonapi.schema.format_items": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.format_items",
    "marshmallow_jsonapi.schema.format_json_api_response": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.format_json_api_response",
    "marshmallow_jsonapi.schema.generate_url": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.generate_url",
    "marshmallow_jsonapi.schema.get_resource_links": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.get_resource_links",
    "marshmallow_jsonapi.schema.get_top_level_links": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.get_top_level_links",
    "marshmallow_jsonapi.schema.inflect": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.inflect",
    "marshmallow_jsonapi.schema.meta": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.Meta",
    "marshmallow_jsonapi.schema.on_bind_field": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.on_bind_field",
    "marshmallow_jsonapi.schema.options_class": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.OPTIONS_CLASS",
    "marshmallow_jsonapi.schema.wrap_response": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.Schema.wrap_response",
    "marshmallow_jsonapi.schemaopts": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.SchemaOpts",
    "marshmallow_jsonapi.utils": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#module-marshmallow_jsonapi.utils",
    "marshmallow_jsonapi.utils.resolve_params": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.utils.resolve_params",
    "marshmallow_jsonapi.utils.tpl": "https://marshmallow-jsonapi.readthedocs.io/en/latest/api_reference.html#marshmallow_jsonapi.utils.tpl",
}
