VERSION = "2.4.0"

# fmt: off
MAPPING = {
    "marshmallow_annotations": "https://marshmallow-annotations.readthedocs.io/en/stable/",
    "marshmallow_annotations.base": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html",
    "marshmallow_annotations.base.abstractconverter": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.AbstractConverter",
    "marshmallow_annotations.base.abstractconverter.convert": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.AbstractConverter.convert",
    "marshmallow_annotations.base.abstractconverter.convert_all": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.AbstractConverter.convert_all",
    "marshmallow_annotations.base.abstractconverter.is_scheme": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.AbstractConverter.is_scheme",
    "marshmallow_annotations.base.typeregistry": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.TypeRegistry",
    "marshmallow_annotations.base.typeregistry.field_factory": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.TypeRegistry.field_factory",
    "marshmallow_annotations.base.typeregistry.get": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.TypeRegistry.get",
    "marshmallow_annotations.base.typeregistry.has": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.TypeRegistry.has",
    "marshmallow_annotations.base.typeregistry.register": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.TypeRegistry.register",
    "marshmallow_annotations.base.typeregistry.register_field_for_type": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.TypeRegistry.register_field_for_type",
    "marshmallow_annotations.base.typeregistry.register_scheme_factory": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.base.TypeRegistry.register_scheme_factory",
    "marshmallow_annotations.converter": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html",
    "marshmallow_annotations.converter.baseconverter": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.converter.BaseConverter",
    "marshmallow_annotations.converter.baseconverter._get_field_defaults": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.converter.BaseConverter._get_field_defaults",
    "marshmallow_annotations.converter.baseconverter._postprocess_typehint": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.converter.BaseConverter._postprocess_typehint",
    "marshmallow_annotations.converter.baseconverter._preprocess_typehint": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.converter.BaseConverter._preprocess_typehint",
    "marshmallow_annotations.exceptions": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html",
    "marshmallow_annotations.exceptions.annotationconversionerror": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.exceptions.AnnotationConversionError",
    "marshmallow_annotations.exceptions.marshmallowannotationerror": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.exceptions.MarshmallowAnnotationError",
    "marshmallow_annotations.ext.attrs": "https://marshmallow-annotations.readthedocs.io/en/stable/ext/attrs.html",
    "marshmallow_annotations.ext.attrs.attrsconverter": "https://marshmallow-annotations.readthedocs.io/en/stable/ext/attrs.html#marshmallow_annotations.ext.attrs.AttrsConverter",
    "marshmallow_annotations.ext.attrs.attrsschema": "https://marshmallow-annotations.readthedocs.io/en/stable/ext/attrs.html#marshmallow_annotations.ext.attrs.AttrsSchema",
    "marshmallow_annotations.ext.namedtuple": "https://marshmallow-annotations.readthedocs.io/en/stable/ext/namedtuple.html",
    "marshmallow_annotations.ext.namedtuple.namedtupleconverter": "https://marshmallow-annotations.readthedocs.io/en/stable/ext/namedtuple.html#marshmallow_annotations.ext.namedtuple.NamedTupleConverter",
    "marshmallow_annotations.ext.namedtuple.namedtupleschema": "https://marshmallow-annotations.readthedocs.io/en/stable/ext/namedtuple.html#marshmallow_annotations.ext.namedtuple.NamedTupleSchema",
    "marshmallow_annotations.ext.namedtuple.namedtupleschemaopts": "https://marshmallow-annotations.readthedocs.io/en/stable/ext/namedtuple.html#marshmallow_annotations.ext.namedtuple.NamedTupleSchemaOpts",
    "marshmallow_annotations.registry": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html",
    "marshmallow_annotations.registry.defaulttyperegistry": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.registry.DefaultTypeRegistry",
    "marshmallow_annotations.registry.field_factory": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.registry.field_factory",
    "marshmallow_annotations.registry.scheme_factory": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.registry.scheme_factory",
    "marshmallow_annotations.scheme": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html",
    "marshmallow_annotations.scheme.annotationschema": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.scheme.AnnotationSchema",
    "marshmallow_annotations.scheme.annotationschemameta": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.scheme.AnnotationSchemaMeta",
    "marshmallow_annotations.scheme.annotationschemaopts": "https://marshmallow-annotations.readthedocs.io/en/stable/api.html#marshmallow_annotations.scheme.AnnotationSchemaOpts",
}
