VERSION = "0.6.1"

# fmt: off
MAPPING = {
    "mdit_py_plugins": "https://mdit-py-plugins.readthedocs.io/en/stable/",
    "mdit_py_plugins.admon": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.admon.admon_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.admon.admon_plugin",
    "mdit_py_plugins.amsmath": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.amsmath.amsmath_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.amsmath.amsmath_plugin",
    "mdit_py_plugins.anchors": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.anchors.anchors_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.anchors.anchors_plugin",
    "mdit_py_plugins.attrs": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.attrs.attrs_block_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.attrs.attrs_block_plugin",
    "mdit_py_plugins.attrs.attrs_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.attrs.attrs_plugin",
    "mdit_py_plugins.container": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.container.container_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.container.container_plugin",
    "mdit_py_plugins.deflist": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.deflist.deflist_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.deflist.deflist_plugin",
    "mdit_py_plugins.dollarmath": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.dollarmath.dollarmath_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.dollarmath.dollarmath_plugin",
    "mdit_py_plugins.field_list": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.field_list.fieldlist_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.field_list.fieldlist_plugin",
    "mdit_py_plugins.footnote": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.footnote.footnote_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.footnote.footnote_plugin",
    "mdit_py_plugins.front_matter": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.front_matter.front_matter_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.front_matter.front_matter_plugin",
    "mdit_py_plugins.gfm": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.gfm.gfm_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.gfm.gfm_plugin",
    "mdit_py_plugins.gfm_autolink": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.gfm_autolink.gfm_autolink_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.gfm_autolink.gfm_autolink_plugin",
    "mdit_py_plugins.myst_blocks": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.myst_blocks.myst_block_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.myst_blocks.myst_block_plugin",
    "mdit_py_plugins.myst_role": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.myst_role.myst_role_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.myst_role.myst_role_plugin",
    "mdit_py_plugins.subscript": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.subscript.sub_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.subscript.sub_plugin",
    "mdit_py_plugins.superscript": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.superscript.superscript_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.superscript.superscript_plugin",
    "mdit_py_plugins.tasklists": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.tasklists.tasklists_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.tasklists.tasklists_plugin",
    "mdit_py_plugins.texmath": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.texmath.texmath_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.texmath.texmath_plugin",
    "mdit_py_plugins.wordcount": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html",
    "mdit_py_plugins.wordcount.wordcount_plugin": "https://mdit-py-plugins.readthedocs.io/en/stable/index.html#mdit_py_plugins.wordcount.wordcount_plugin",
}
