VERSION = "0.17.0"

# fmt: off
MAPPING = {
    "mediafile": "https://mediafile.readthedocs.io/en/stable/",
    "mediafile.exceptions": "https://mediafile.readthedocs.io/en/stable/index.html",
    "mediafile.exceptions.filetypeerror": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.FileTypeError",
    "mediafile.exceptions.mutagenerror": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MutagenError",
    "mediafile.exceptions.unreadablefileerror": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.UnreadableFileError",
    "mediafile.fields": "https://mediafile.readthedocs.io/en/stable/index.html",
    "mediafile.fields.mediafield": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MediaField",
    "mediafile.filetypeerror": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.FileTypeError",
    "mediafile.mediafield": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MediaField",
    "mediafile.mediafield.__init__": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MediaField.__init__",
    "mediafile.mediafile": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MediaFile",
    "mediafile.mediafile.__init__": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MediaFile.__init__",
    "mediafile.mediafile.fields": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MediaFile.fields",
    "mediafile.mediafile.readable_fields": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MediaFile.readable_fields",
    "mediafile.mediafile.save": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MediaFile.save",
    "mediafile.mediafile.update": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MediaFile.update",
    "mediafile.mutagenerror": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.MutagenError",
    "mediafile.storage": "https://mediafile.readthedocs.io/en/stable/index.html",
    "mediafile.storage.base": "https://mediafile.readthedocs.io/en/stable/index.html",
    "mediafile.storage.base.storagestyle": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle",
    "mediafile.storagestyle": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle",
    "mediafile.storagestyle.delete": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle.delete",
    "mediafile.storagestyle.deserialize": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle.deserialize",
    "mediafile.storagestyle.fetch": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle.fetch",
    "mediafile.storagestyle.formats": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle.formats",
    "mediafile.storagestyle.get": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle.get",
    "mediafile.storagestyle.serialize": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle.serialize",
    "mediafile.storagestyle.set": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle.set",
    "mediafile.storagestyle.store": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.StorageStyle.store",
    "mediafile.unreadablefileerror": "https://mediafile.readthedocs.io/en/stable/index.html#mediafile.UnreadableFileError",
}
