VERSION = "2.1.1"

# fmt: off
MAPPING = {
    "minimalmodbus": "https://minimalmodbus.readthedocs.io/en/stable/",
    "minimalmodbus.byteorder_big": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.BYTEORDER_BIG",
    "minimalmodbus.byteorder_big_swap": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.BYTEORDER_BIG_SWAP",
    "minimalmodbus.byteorder_little": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.BYTEORDER_LITTLE",
    "minimalmodbus.byteorder_little_swap": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.BYTEORDER_LITTLE_SWAP",
    "minimalmodbus.illegalrequesterror": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.IllegalRequestError",
    "minimalmodbus.instrument": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument",
    "minimalmodbus.instrument.address": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.address",
    "minimalmodbus.instrument.clear_buffers_before_each_transaction": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.clear_buffers_before_each_transaction",
    "minimalmodbus.instrument.close_port_after_each_call": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.close_port_after_each_call",
    "minimalmodbus.instrument.debug": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.debug",
    "minimalmodbus.instrument.handle_local_echo": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.handle_local_echo",
    "minimalmodbus.instrument.mode": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.mode",
    "minimalmodbus.instrument.precalculate_read_size": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.precalculate_read_size",
    "minimalmodbus.instrument.read_bit": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.read_bit",
    "minimalmodbus.instrument.read_bits": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.read_bits",
    "minimalmodbus.instrument.read_float": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.read_float",
    "minimalmodbus.instrument.read_long": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.read_long",
    "minimalmodbus.instrument.read_register": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.read_register",
    "minimalmodbus.instrument.read_registers": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.read_registers",
    "minimalmodbus.instrument.read_string": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.read_string",
    "minimalmodbus.instrument.roundtrip_time": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.roundtrip_time",
    "minimalmodbus.instrument.serial": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.serial",
    "minimalmodbus.instrument.write_bit": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.write_bit",
    "minimalmodbus.instrument.write_bits": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.write_bits",
    "minimalmodbus.instrument.write_float": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.write_float",
    "minimalmodbus.instrument.write_long": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.write_long",
    "minimalmodbus.instrument.write_register": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.write_register",
    "minimalmodbus.instrument.write_registers": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.write_registers",
    "minimalmodbus.instrument.write_string": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.Instrument.write_string",
    "minimalmodbus.invalidresponseerror": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.InvalidResponseError",
    "minimalmodbus.localechoerror": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.LocalEchoError",
    "minimalmodbus.masterreportedexception": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.MasterReportedException",
    "minimalmodbus.modbusexception": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.ModbusException",
    "minimalmodbus.mode_ascii": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.MODE_ASCII",
    "minimalmodbus.mode_rtu": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.MODE_RTU",
    "minimalmodbus.negativeacknowledgeerror": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.NegativeAcknowledgeError",
    "minimalmodbus.noresponseerror": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.NoResponseError",
    "minimalmodbus.slavedevicebusyerror": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.SlaveDeviceBusyError",
    "minimalmodbus.slavereportedexception": "https://minimalmodbus.readthedocs.io/en/stable/apiminimalmodbus.html#minimalmodbus.SlaveReportedException",
}
