VERSION = "0.2.6"

# fmt: off
MAPPING = {
    "mock_alchemy": "https://mock-alchemy.readthedocs.io/en/stable/",
    "mock_alchemy.comparison": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.comparison.html#module-mock_alchemy.comparison",
    "mock_alchemy.comparison.expressionmatcher": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.comparison.html#mock_alchemy.comparison.ExpressionMatcher",
    "mock_alchemy.comparison.prettyexpression": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.comparison.html#mock_alchemy.comparison.PrettyExpression",
    "mock_alchemy.comparison.prettyexpression.expr": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.comparison.html#mock_alchemy.comparison.PrettyExpression.expr",
    "mock_alchemy.mocking": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#module-mock_alchemy.mocking",
    "mock_alchemy.mocking.alchemymagicmock": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.AlchemyMagicMock",
    "mock_alchemy.mocking.alchemymagicmock.__init__": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.AlchemyMagicMock.__init__",
    "mock_alchemy.mocking.alchemymagicmock._format_mock_call_signature": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.AlchemyMagicMock._format_mock_call_signature",
    "mock_alchemy.mocking.alchemymagicmock.assert_any_call": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.AlchemyMagicMock.assert_any_call",
    "mock_alchemy.mocking.alchemymagicmock.assert_called_with": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.AlchemyMagicMock.assert_called_with",
    "mock_alchemy.mocking.alchemymagicmock.assert_has_calls": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.AlchemyMagicMock.assert_has_calls",
    "mock_alchemy.mocking.sqlalchemy_call": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.sqlalchemy_call",
    "mock_alchemy.mocking.unifiedalchemymagicmock": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock",
    "mock_alchemy.mocking.unifiedalchemymagicmock.__init__": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock.__init__",
    "mock_alchemy.mocking.unifiedalchemymagicmock._get_data": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock._get_data",
    "mock_alchemy.mocking.unifiedalchemymagicmock._get_previous_call": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock._get_previous_call",
    "mock_alchemy.mocking.unifiedalchemymagicmock._get_previous_calls": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock._get_previous_calls",
    "mock_alchemy.mocking.unifiedalchemymagicmock._mutate_data": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock._mutate_data",
    "mock_alchemy.mocking.unifiedalchemymagicmock._unify": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock._unify",
    "mock_alchemy.mocking.unifiedalchemymagicmock.boundary": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock.boundary",
    "mock_alchemy.mocking.unifiedalchemymagicmock.mutate": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock.mutate",
    "mock_alchemy.mocking.unifiedalchemymagicmock.unify": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnifiedAlchemyMagicMock.unify",
    "mock_alchemy.mocking.unorderedcall": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnorderedCall",
    "mock_alchemy.mocking.unorderedcall.__eq__": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnorderedCall.__eq__",
    "mock_alchemy.mocking.unorderedcall.__hash__": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnorderedCall.__hash__",
    "mock_alchemy.mocking.unorderedtuple": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnorderedTuple",
    "mock_alchemy.mocking.unorderedtuple.__eq__": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnorderedTuple.__eq__",
    "mock_alchemy.mocking.unorderedtuple.__hash__": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.mocking.html#mock_alchemy.mocking.UnorderedTuple.__hash__",
    "mock_alchemy.unittests": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.unittests.html#module-mock_alchemy.unittests",
    "mock_alchemy.unittests.alchemyunittestmixin": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.unittests.html#mock_alchemy.unittests.AlchemyUnittestMixin",
    "mock_alchemy.unittests.alchemyunittestmixin.assert_alchemy_expression_equal": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.unittests.html#mock_alchemy.unittests.AlchemyUnittestMixin.assert_alchemy_expression_equal",
    "mock_alchemy.utils": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.utils.html#module-mock_alchemy.utils",
    "mock_alchemy.utils.build_identity_map": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.utils.html#mock_alchemy.utils.build_identity_map",
    "mock_alchemy.utils.copy_and_update": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.utils.html#mock_alchemy.utils.copy_and_update",
    "mock_alchemy.utils.get_item_attr": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.utils.html#mock_alchemy.utils.get_item_attr",
    "mock_alchemy.utils.get_scalar": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.utils.html#mock_alchemy.utils.get_scalar",
    "mock_alchemy.utils.indexof": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.utils.html#mock_alchemy.utils.indexof",
    "mock_alchemy.utils.match_type": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.utils.html#mock_alchemy.utils.match_type",
    "mock_alchemy.utils.raiser": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.utils.html#mock_alchemy.utils.raiser",
    "mock_alchemy.utils.setattr_tmp": "https://mock-alchemy.readthedocs.io/en/stable/api_reference/mock_alchemy.utils.html#mock_alchemy.utils.setattr_tmp",
}
