VERSION = "23.3.0"

# fmt: off
MAPPING = {
    "monkeytype": "https://monkeytype.readthedocs.io/en/stable/",
    "monkeytype.config": "https://monkeytype.readthedocs.io/en/stable/configuration.html#module-monkeytype.config",
    "monkeytype.config.config": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.Config",
    "monkeytype.config.config.cli_context": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.Config.cli_context",
    "monkeytype.config.config.code_filter": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.Config.code_filter",
    "monkeytype.config.config.max_typed_dict_size": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.Config.max_typed_dict_size",
    "monkeytype.config.config.query_limit": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.Config.query_limit",
    "monkeytype.config.config.sample_rate": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.Config.sample_rate",
    "monkeytype.config.config.trace_logger": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.Config.trace_logger",
    "monkeytype.config.config.trace_store": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.Config.trace_store",
    "monkeytype.config.config.type_rewriter": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.Config.type_rewriter",
    "monkeytype.config.defaultconfig": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.DefaultConfig",
    "monkeytype.config.defaultconfig.code_filter": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.DefaultConfig.code_filter",
    "monkeytype.config.defaultconfig.trace_store": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.DefaultConfig.trace_store",
    "monkeytype.config.defaultconfig.type_rewriter": "https://monkeytype.readthedocs.io/en/stable/configuration.html#monkeytype.config.DefaultConfig.type_rewriter",
    "monkeytype.db.base": "https://monkeytype.readthedocs.io/en/stable/stores.html#module-monkeytype.db.base",
    "monkeytype.db.base.calltracestore": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.base.CallTraceStore",
    "monkeytype.db.base.calltracestore.add": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.base.CallTraceStore.add",
    "monkeytype.db.base.calltracestore.filter": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.base.CallTraceStore.filter",
    "monkeytype.db.base.calltracestore.list_modules": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.base.CallTraceStore.list_modules",
    "monkeytype.db.base.calltracestore.make_store": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.base.CallTraceStore.make_store",
    "monkeytype.db.base.calltracestorelogger": "https://monkeytype.readthedocs.io/en/stable/tracing.html#monkeytype.db.base.CallTraceStoreLogger",
    "monkeytype.db.base.calltracethunk": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.base.CallTraceThunk",
    "monkeytype.db.base.calltracethunk.to_trace": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.base.CallTraceThunk.to_trace",
    "monkeytype.db.sqlite": "https://monkeytype.readthedocs.io/en/stable/stores.html#module-monkeytype.db.sqlite",
    "monkeytype.db.sqlite.sqlitestore": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.sqlite.SQLiteStore",
    "monkeytype.db.sqlite.sqlitestore.add": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.sqlite.SQLiteStore.add",
    "monkeytype.db.sqlite.sqlitestore.filter": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.sqlite.SQLiteStore.filter",
    "monkeytype.db.sqlite.sqlitestore.make_store": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.db.sqlite.SQLiteStore.make_store",
    "monkeytype.encoding": "https://monkeytype.readthedocs.io/en/stable/stores.html#module-monkeytype.encoding",
    "monkeytype.encoding.calltracerow": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.encoding.CallTraceRow",
    "monkeytype.encoding.calltracerow.from_trace": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.encoding.CallTraceRow.from_trace",
    "monkeytype.encoding.calltracerow.to_trace": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.encoding.CallTraceRow.to_trace",
    "monkeytype.encoding.serialize_traces": "https://monkeytype.readthedocs.io/en/stable/stores.html#monkeytype.encoding.serialize_traces",
    "monkeytype.trace": "https://monkeytype.readthedocs.io/en/stable/tracing.html#monkeytype.trace",
    "monkeytype.tracing": "https://monkeytype.readthedocs.io/en/stable/tracing.html#module-monkeytype.tracing",
    "monkeytype.tracing.calltrace": "https://monkeytype.readthedocs.io/en/stable/tracing.html#monkeytype.tracing.CallTrace",
    "monkeytype.tracing.calltracelogger": "https://monkeytype.readthedocs.io/en/stable/tracing.html#monkeytype.tracing.CallTraceLogger",
    "monkeytype.tracing.calltracelogger.flush": "https://monkeytype.readthedocs.io/en/stable/tracing.html#monkeytype.tracing.CallTraceLogger.flush",
    "monkeytype.tracing.calltracelogger.log": "https://monkeytype.readthedocs.io/en/stable/tracing.html#monkeytype.tracing.CallTraceLogger.log",
    "monkeytype.tracing.calltracer": "https://monkeytype.readthedocs.io/en/stable/tracing.html#monkeytype.tracing.CallTracer",
    "monkeytype.typing": "https://monkeytype.readthedocs.io/en/stable/generation.html#module-monkeytype.typing",
    "monkeytype.typing.chainedrewriter": "https://monkeytype.readthedocs.io/en/stable/generation.html#monkeytype.typing.ChainedRewriter",
    "monkeytype.typing.nooprewriter": "https://monkeytype.readthedocs.io/en/stable/generation.html#monkeytype.typing.NoOpRewriter",
    "monkeytype.typing.removeemptycontainers": "https://monkeytype.readthedocs.io/en/stable/generation.html#monkeytype.typing.RemoveEmptyContainers",
    "monkeytype.typing.rewriteconfigdict": "https://monkeytype.readthedocs.io/en/stable/generation.html#monkeytype.typing.RewriteConfigDict",
    "monkeytype.typing.rewritelargeunion": "https://monkeytype.readthedocs.io/en/stable/generation.html#monkeytype.typing.RewriteLargeUnion",
    "monkeytype.typing.typerewriter": "https://monkeytype.readthedocs.io/en/stable/generation.html#monkeytype.typing.TypeRewriter",
    "monkeytype.typing.typerewriter.generic_rewrite": "https://monkeytype.readthedocs.io/en/stable/generation.html#monkeytype.typing.TypeRewriter.generic_rewrite",
    "monkeytype.typing.typerewriter.rewrite": "https://monkeytype.readthedocs.io/en/stable/generation.html#monkeytype.typing.TypeRewriter.rewrite",
}
