VERSION = "1.2.2"

# fmt: off
MAPPING = {
    "msgpack": "https://msgpack-python.readthedocs.io/en/stable/",
    "msgpack._cmsgpack": "https://msgpack-python.readthedocs.io/en/stable/api.html",
    "msgpack._cmsgpack.packer": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer",
    "msgpack._cmsgpack.unpacker": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Unpacker",
    "msgpack.exceptions": "https://msgpack-python.readthedocs.io/en/stable/api.html#module-msgpack.exceptions",
    "msgpack.exceptions.bufferfull": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.exceptions.BufferFull",
    "msgpack.exceptions.extradata": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.exceptions.ExtraData",
    "msgpack.exceptions.formaterror": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.exceptions.FormatError",
    "msgpack.exceptions.outofdata": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.exceptions.OutOfData",
    "msgpack.exceptions.stackerror": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.exceptions.StackError",
    "msgpack.exceptions.unpackexception": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.exceptions.UnpackException",
    "msgpack.ext": "https://msgpack-python.readthedocs.io/en/stable/api.html",
    "msgpack.ext.exttype": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.ExtType",
    "msgpack.ext.timestamp": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp",
    "msgpack.exttype": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.ExtType",
    "msgpack.pack": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.pack",
    "msgpack.packb": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.packb",
    "msgpack.packer": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer",
    "msgpack.packer.bytes": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer.bytes",
    "msgpack.packer.getbuffer": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer.getbuffer",
    "msgpack.packer.pack": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer.pack",
    "msgpack.packer.pack_array_header": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer.pack_array_header",
    "msgpack.packer.pack_ext_type": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer.pack_ext_type",
    "msgpack.packer.pack_map_header": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer.pack_map_header",
    "msgpack.packer.pack_map_pairs": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer.pack_map_pairs",
    "msgpack.packer.reset": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Packer.reset",
    "msgpack.timestamp": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp",
    "msgpack.timestamp.__init__": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp.__init__",
    "msgpack.timestamp.from_bytes": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp.from_bytes",
    "msgpack.timestamp.from_datetime": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp.from_datetime",
    "msgpack.timestamp.from_unix": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp.from_unix",
    "msgpack.timestamp.from_unix_nano": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp.from_unix_nano",
    "msgpack.timestamp.to_bytes": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp.to_bytes",
    "msgpack.timestamp.to_datetime": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp.to_datetime",
    "msgpack.timestamp.to_unix": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp.to_unix",
    "msgpack.timestamp.to_unix_nano": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Timestamp.to_unix_nano",
    "msgpack.unpack": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.unpack",
    "msgpack.unpackb": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.unpackb",
    "msgpack.unpacker": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Unpacker",
    "msgpack.unpacker.feed": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Unpacker.feed",
    "msgpack.unpacker.read_array_header": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Unpacker.read_array_header",
    "msgpack.unpacker.read_bytes": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Unpacker.read_bytes",
    "msgpack.unpacker.read_map_header": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Unpacker.read_map_header",
    "msgpack.unpacker.skip": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Unpacker.skip",
    "msgpack.unpacker.tell": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Unpacker.tell",
    "msgpack.unpacker.unpack": "https://msgpack-python.readthedocs.io/en/stable/api.html#msgpack.Unpacker.unpack",
}
