VERSION = "1.4.0"

# fmt: off
MAPPING = {
    "nagiosplugin": "https://nagiosplugin.readthedocs.io/en/stable/",
    "nagiosplugin.check": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#module-nagiosplugin.check",
    "nagiosplugin.check.check": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#nagiosplugin.check.Check",
    "nagiosplugin.check.check.__call__": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#nagiosplugin.check.Check.__call__",
    "nagiosplugin.check.check.name": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#nagiosplugin.check.Check.name",
    "nagiosplugin.check.check.results": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#nagiosplugin.check.Check.results",
    "nagiosplugin.context": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#module-nagiosplugin.context",
    "nagiosplugin.context.context": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#nagiosplugin.context.Context",
    "nagiosplugin.context.scalarcontext": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#nagiosplugin.context.ScalarContext",
    "nagiosplugin.cookie": "https://nagiosplugin.readthedocs.io/en/stable/api/auxiliary.html#module-nagiosplugin.cookie",
    "nagiosplugin.cookie.cookie": "https://nagiosplugin.readthedocs.io/en/stable/api/auxiliary.html#nagiosplugin.cookie.Cookie",
    "nagiosplugin.cookie.cookie.__enter__": "https://nagiosplugin.readthedocs.io/en/stable/api/auxiliary.html#nagiosplugin.cookie.Cookie.__enter__",
    "nagiosplugin.logtail": "https://nagiosplugin.readthedocs.io/en/stable/api/auxiliary.html#module-nagiosplugin.logtail",
    "nagiosplugin.logtail.logtail": "https://nagiosplugin.readthedocs.io/en/stable/api/auxiliary.html#nagiosplugin.logtail.LogTail",
    "nagiosplugin.logtail.logtail.__enter__": "https://nagiosplugin.readthedocs.io/en/stable/api/auxiliary.html#nagiosplugin.logtail.LogTail.__enter__",
    "nagiosplugin.metric": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#module-nagiosplugin.metric",
    "nagiosplugin.metric.metric": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.metric.Metric",
    "nagiosplugin.metric.metric.__new__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.metric.Metric.__new__",
    "nagiosplugin.metric.metric.__str__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.metric.Metric.__str__",
    "nagiosplugin.performance": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#module-nagiosplugin.performance",
    "nagiosplugin.performance.performance": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.performance.Performance",
    "nagiosplugin.performance.performance.__new__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.performance.Performance.__new__",
    "nagiosplugin.performance.performance.__str__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.performance.Performance.__str__",
    "nagiosplugin.range": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#module-nagiosplugin.range",
    "nagiosplugin.range.range": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.range.Range",
    "nagiosplugin.range.range.__new__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.range.Range.__new__",
    "nagiosplugin.range.range.__repr__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.range.Range.__repr__",
    "nagiosplugin.range.range.__str__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.range.Range.__str__",
    "nagiosplugin.resource": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#module-nagiosplugin.resource",
    "nagiosplugin.resource.resource": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#nagiosplugin.resource.Resource",
    "nagiosplugin.result": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#module-nagiosplugin.result",
    "nagiosplugin.result.result": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.result.Result",
    "nagiosplugin.result.result.__new__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.result.Result.__new__",
    "nagiosplugin.result.result.__str__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.result.Result.__str__",
    "nagiosplugin.result.results": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.result.Results",
    "nagiosplugin.result.results.__contains__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.result.Results.__contains__",
    "nagiosplugin.result.results.__getitem__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.result.Results.__getitem__",
    "nagiosplugin.result.results.__iter__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.result.Results.__iter__",
    "nagiosplugin.result.results.__len__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.result.Results.__len__",
    "nagiosplugin.result.scalarresult": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.result.ScalarResult",
    "nagiosplugin.runtime": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#module-nagiosplugin.runtime",
    "nagiosplugin.runtime.guarded": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#nagiosplugin.runtime.guarded",
    "nagiosplugin.state": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#module-nagiosplugin.state",
    "nagiosplugin.state.critical": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.state.Critical",
    "nagiosplugin.state.ok": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.state.Ok",
    "nagiosplugin.state.servicestate": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.state.ServiceState",
    "nagiosplugin.state.servicestate.__int__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.state.ServiceState.__int__",
    "nagiosplugin.state.servicestate.__str__": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.state.ServiceState.__str__",
    "nagiosplugin.state.unknown": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.state.Unknown",
    "nagiosplugin.state.warn": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.state.Warn",
    "nagiosplugin.state.worst": "https://nagiosplugin.readthedocs.io/en/stable/api/intermediate.html#nagiosplugin.state.worst",
    "nagiosplugin.summary": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#module-nagiosplugin.summary",
    "nagiosplugin.summary.summary": "https://nagiosplugin.readthedocs.io/en/stable/api/core.html#nagiosplugin.summary.Summary",
}
