VERSION = "1.4.2"

# fmt: off
MAPPING = {
    "named": "https://nekitdev.github.io/named/",
    "named.core": "https://nekitdev.github.io/named/reference/",
    "named.core.get_module": "https://nekitdev.github.io/named/reference/#named.get_module",
    "named.core.get_name": "https://nekitdev.github.io/named/reference/#named.get_name",
    "named.core.get_type_module": "https://nekitdev.github.io/named/reference/#named.get_type_module",
    "named.core.get_type_name": "https://nekitdev.github.io/named/reference/#named.get_type_name",
    "named.core.has_module": "https://nekitdev.github.io/named/reference/#named.has_module",
    "named.core.has_name": "https://nekitdev.github.io/named/reference/#named.has_name",
    "named.core.is_moduled": "https://nekitdev.github.io/named/reference/#named.is_moduled",
    "named.core.is_named": "https://nekitdev.github.io/named/reference/#named.is_named",
    "named.core.module": "https://nekitdev.github.io/named/reference/#named.MODULE",
    "named.core.moduled": "https://nekitdev.github.io/named/reference/#named.Moduled",
    "named.core.name": "https://nekitdev.github.io/named/reference/#named.NAME",
    "named.core.named": "https://nekitdev.github.io/named/reference/#named.Named",
    "named.core.set_module": "https://nekitdev.github.io/named/reference/#named.set_module",
    "named.core.set_name": "https://nekitdev.github.io/named/reference/#named.set_name",
    "named.core.set_type_module": "https://nekitdev.github.io/named/reference/#named.set_type_module",
    "named.core.set_type_name": "https://nekitdev.github.io/named/reference/#named.set_type_name",
    "named.get_module": "https://nekitdev.github.io/named/reference/#named.get_module",
    "named.get_name": "https://nekitdev.github.io/named/reference/#named.get_name",
    "named.get_type_module": "https://nekitdev.github.io/named/reference/#named.get_type_module",
    "named.get_type_name": "https://nekitdev.github.io/named/reference/#named.get_type_name",
    "named.has_module": "https://nekitdev.github.io/named/reference/#named.has_module",
    "named.has_name": "https://nekitdev.github.io/named/reference/#named.has_name",
    "named.is_moduled": "https://nekitdev.github.io/named/reference/#named.is_moduled",
    "named.is_named": "https://nekitdev.github.io/named/reference/#named.is_named",
    "named.module": "https://nekitdev.github.io/named/reference/#named.MODULE",
    "named.moduled": "https://nekitdev.github.io/named/reference/#named.Moduled",
    "named.name": "https://nekitdev.github.io/named/reference/#named.NAME",
    "named.named": "https://nekitdev.github.io/named/reference/#named.Named",
    "named.set_module": "https://nekitdev.github.io/named/reference/#named.set_module",
    "named.set_name": "https://nekitdev.github.io/named/reference/#named.set_name",
    "named.set_type_module": "https://nekitdev.github.io/named/reference/#named.set_type_module",
    "named.set_type_name": "https://nekitdev.github.io/named/reference/#named.set_type_name",
}
