VERSION = "3.6.0"

# fmt: off
MAPPING = {
    "netconf_client": "https://adtran.github.io/netconf_client/",
    "netconf_client.connect": "https://adtran.github.io/netconf_client/api.html#module-netconf_client.connect",
    "netconf_client.connect.callhomemanager": "https://adtran.github.io/netconf_client/api.html#netconf_client.connect.CallhomeManager",
    "netconf_client.connect.callhomemanager.accept_one": "https://adtran.github.io/netconf_client/api.html#netconf_client.connect.CallhomeManager.accept_one",
    "netconf_client.connect.callhomemanager.accept_one_ssh": "https://adtran.github.io/netconf_client/api.html#netconf_client.connect.CallhomeManager.accept_one_ssh",
    "netconf_client.connect.callhomemanager.accept_one_tls": "https://adtran.github.io/netconf_client/api.html#netconf_client.connect.CallhomeManager.accept_one_tls",
    "netconf_client.connect.connect_ssh": "https://adtran.github.io/netconf_client/api.html#netconf_client.connect.connect_ssh",
    "netconf_client.connect.connect_tls": "https://adtran.github.io/netconf_client/api.html#netconf_client.connect.connect_tls",
    "netconf_client.error": "https://adtran.github.io/netconf_client/api.html#module-netconf_client.error",
    "netconf_client.error.invalidsshhostkey": "https://adtran.github.io/netconf_client/api.html#netconf_client.error.InvalidSSHHostkey",
    "netconf_client.error.netconfclientexception": "https://adtran.github.io/netconf_client/api.html#netconf_client.error.NetconfClientException",
    "netconf_client.error.netconfprotocolerror": "https://adtran.github.io/netconf_client/api.html#netconf_client.error.NetconfProtocolError",
    "netconf_client.error.rpcerror": "https://adtran.github.io/netconf_client/api.html#netconf_client.error.RpcError",
    "netconf_client.error.sessionclosedexception": "https://adtran.github.io/netconf_client/api.html#netconf_client.error.SessionClosedException",
    "netconf_client.ncclient": "https://adtran.github.io/netconf_client/api.html#module-netconf_client.ncclient",
    "netconf_client.ncclient.datareply": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.DataReply",
    "netconf_client.ncclient.manager": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager",
    "netconf_client.ncclient.manager.cancel_commit": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.cancel_commit",
    "netconf_client.ncclient.manager.close_session": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.close_session",
    "netconf_client.ncclient.manager.commit": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.commit",
    "netconf_client.ncclient.manager.copy_config": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.copy_config",
    "netconf_client.ncclient.manager.create_subscription": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.create_subscription",
    "netconf_client.ncclient.manager.delete_config": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.delete_config",
    "netconf_client.ncclient.manager.discard_changes": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.discard_changes",
    "netconf_client.ncclient.manager.dispatch": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.dispatch",
    "netconf_client.ncclient.manager.edit_config": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.edit_config",
    "netconf_client.ncclient.manager.get": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.get",
    "netconf_client.ncclient.manager.get_config": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.get_config",
    "netconf_client.ncclient.manager.get_data": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.get_data",
    "netconf_client.ncclient.manager.kill_session": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.kill_session",
    "netconf_client.ncclient.manager.lock": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.lock",
    "netconf_client.ncclient.manager.logger": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.logger",
    "netconf_client.ncclient.manager.session_id": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.session_id",
    "netconf_client.ncclient.manager.set_rpc_timeout": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.set_rpc_timeout",
    "netconf_client.ncclient.manager.take_notification": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.take_notification",
    "netconf_client.ncclient.manager.unlock": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.unlock",
    "netconf_client.ncclient.manager.validate": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Manager.validate",
    "netconf_client.ncclient.notification": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.Notification",
    "netconf_client.ncclient.rpcreply": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.RPCReply",
    "netconf_client.ncclient.to_ele": "https://adtran.github.io/netconf_client/api.html#netconf_client.ncclient.to_ele",
    "netconf_client.session": "https://adtran.github.io/netconf_client/api.html#module-netconf_client.session",
    "netconf_client.session.session": "https://adtran.github.io/netconf_client/api.html#netconf_client.session.Session",
    "netconf_client.session.session.close": "https://adtran.github.io/netconf_client/api.html#netconf_client.session.Session.close",
    "netconf_client.session.session.send_msg": "https://adtran.github.io/netconf_client/api.html#netconf_client.session.Session.send_msg",
    "netconf_client.session.session.send_rpc": "https://adtran.github.io/netconf_client/api.html#netconf_client.session.Session.send_rpc",
}
