VERSION = "9.0.2"

# fmt: off
MAPPING = {
    "neuron": "https://www.neuronsimulator.org/en/latest/",
    "neuron._neuron_interface": "https://www.neuronsimulator.org/en/latest/progref/programming/hoc-from-python.html#neuron._NEURON_INTERFACE",
    "neuron.hoc": "https://www.neuronsimulator.org/en/latest/progref/programming/hoc-from-python.html",
    "neuron.hoc.execute": "https://www.neuronsimulator.org/en/latest/progref/programming/hoc-from-python.html#neuron.hoc.execute",
    "neuron.hoc.hoc_ac": "https://www.neuronsimulator.org/en/latest/progref/programming/hoc-from-python.html#neuron.hoc.hoc_ac",
    "neuron.n": "https://www.neuronsimulator.org/en/latest/progref/programming/hoc-from-python.html",
    "neuron.n.cas": "https://www.neuronsimulator.org/en/latest/progref/programming/hoc-from-python.html#neuron.n.cas",
    "neuron.n.section": "https://www.neuronsimulator.org/en/latest/progref/programming/hoc-from-python.html#neuron.n.Section",
    "neuron.nmodl": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#module-neuron.nmodl",
    "neuron.nmodl._nmodl": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html",
    "neuron.nmodl._nmodl.nmodldriver": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.NmodlDriver",
    "neuron.nmodl.ast": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#module-neuron.nmodl.ast",
    "neuron.nmodl.ast.view": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ast.view",
    "neuron.nmodl.dsl": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#module-neuron.nmodl.dsl",
    "neuron.nmodl.dsl.list_examples": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.dsl.list_examples",
    "neuron.nmodl.dsl.load_example": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.dsl.load_example",
    "neuron.nmodl.nmodldriver": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.NmodlDriver",
    "neuron.nmodl.nmodldriver.get_ast": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.NmodlDriver.get_ast",
    "neuron.nmodl.nmodldriver.parse_file": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.NmodlDriver.parse_file",
    "neuron.nmodl.nmodldriver.parse_stream": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.NmodlDriver.parse_stream",
    "neuron.nmodl.nmodldriver.parse_string": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.NmodlDriver.parse_string",
    "neuron.nmodl.ode": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#module-neuron.nmodl.ode",
    "neuron.nmodl.ode.demangle_protected_identifiers": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.demangle_protected_identifiers",
    "neuron.nmodl.ode.differentiate2c": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.differentiate2c",
    "neuron.nmodl.ode.discretize_derivative": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.discretize_derivative",
    "neuron.nmodl.ode.finite_difference_step_variable": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.finite_difference_step_variable",
    "neuron.nmodl.ode.forwards_euler2c": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.forwards_euler2c",
    "neuron.nmodl.ode.integrate2c": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.integrate2c",
    "neuron.nmodl.ode.make_symbol": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.make_symbol",
    "neuron.nmodl.ode.mangle_protected_identifiers": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.mangle_protected_identifiers",
    "neuron.nmodl.ode.needs_finite_differences": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.needs_finite_differences",
    "neuron.nmodl.ode.solve_lin_system": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.solve_lin_system",
    "neuron.nmodl.ode.solve_non_lin_system": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.solve_non_lin_system",
    "neuron.nmodl.ode.transform_expression": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.transform_expression",
    "neuron.nmodl.ode.transform_matrix_elements": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.ode.transform_matrix_elements",
    "neuron.nmodl.symtab": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#module-neuron.nmodl.symtab",
    "neuron.nmodl.to_json": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.to_json",
    "neuron.nmodl.to_nmodl": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#neuron.nmodl.to_nmodl",
    "neuron.nmodl.visitor": "https://www.neuronsimulator.org/en/latest/nmodl/transpiler/nmodl.html#module-neuron.nmodl.visitor",
}
