VERSION = "1.0.2"

# fmt: off
MAPPING = {
    "nfoursid": "https://nfoursid.readthedocs.io/en/latest/",
    "nfoursid.kalman": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#module-nfoursid.kalman",
    "nfoursid.kalman.kalman": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman",
    "nfoursid.kalman.kalman.actual_label": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.actual_label",
    "nfoursid.kalman.kalman.extrapolate": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.extrapolate",
    "nfoursid.kalman.kalman.filtered_label": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.filtered_label",
    "nfoursid.kalman.kalman.next_predicted_corrected_label": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.next_predicted_corrected_label",
    "nfoursid.kalman.kalman.next_predicted_label": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.next_predicted_label",
    "nfoursid.kalman.kalman.output_label": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.output_label",
    "nfoursid.kalman.kalman.plot_filtered": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.plot_filtered",
    "nfoursid.kalman.kalman.plot_predicted": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.plot_predicted",
    "nfoursid.kalman.kalman.standard_deviation_label": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.standard_deviation_label",
    "nfoursid.kalman.kalman.step": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.step",
    "nfoursid.kalman.kalman.to_dataframe": "https://nfoursid.readthedocs.io/en/latest/source/kalman.html#nfoursid.kalman.Kalman.to_dataframe",
    "nfoursid.nfoursid": "https://nfoursid.readthedocs.io/en/latest/source/nfoursid.html#module-nfoursid.nfoursid",
    "nfoursid.nfoursid.nfoursid": "https://nfoursid.readthedocs.io/en/latest/source/nfoursid.html#nfoursid.nfoursid.NFourSID",
    "nfoursid.nfoursid.nfoursid.plot_eigenvalues": "https://nfoursid.readthedocs.io/en/latest/source/nfoursid.html#nfoursid.nfoursid.NFourSID.plot_eigenvalues",
    "nfoursid.nfoursid.nfoursid.subspace_identification": "https://nfoursid.readthedocs.io/en/latest/source/nfoursid.html#nfoursid.nfoursid.NFourSID.subspace_identification",
    "nfoursid.nfoursid.nfoursid.system_identification": "https://nfoursid.readthedocs.io/en/latest/source/nfoursid.html#nfoursid.nfoursid.NFourSID.system_identification",
    "nfoursid.state_space": "https://nfoursid.readthedocs.io/en/latest/source/state_space.html#module-nfoursid.state_space",
    "nfoursid.state_space.statespace": "https://nfoursid.readthedocs.io/en/latest/source/state_space.html#nfoursid.state_space.StateSpace",
    "nfoursid.state_space.statespace.output": "https://nfoursid.readthedocs.io/en/latest/source/state_space.html#nfoursid.state_space.StateSpace.output",
    "nfoursid.state_space.statespace.plot_input_output": "https://nfoursid.readthedocs.io/en/latest/source/state_space.html#nfoursid.state_space.StateSpace.plot_input_output",
    "nfoursid.state_space.statespace.step": "https://nfoursid.readthedocs.io/en/latest/source/state_space.html#nfoursid.state_space.StateSpace.step",
    "nfoursid.state_space.statespace.to_dataframe": "https://nfoursid.readthedocs.io/en/latest/source/state_space.html#nfoursid.state_space.StateSpace.to_dataframe",
    "nfoursid.utils": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#module-nfoursid.utils",
    "nfoursid.utils.decomposition": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Decomposition",
    "nfoursid.utils.decomposition.eigenvalues": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Decomposition.eigenvalues",
    "nfoursid.utils.decomposition.left_orthogonal": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Decomposition.left_orthogonal",
    "nfoursid.utils.decomposition.right_orthogonal": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Decomposition.right_orthogonal",
    "nfoursid.utils.utils": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Utils",
    "nfoursid.utils.utils.block_hankel_matrix": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Utils.block_hankel_matrix",
    "nfoursid.utils.utils.eigenvalue_decomposition": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Utils.eigenvalue_decomposition",
    "nfoursid.utils.utils.reduce_decomposition": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Utils.reduce_decomposition",
    "nfoursid.utils.utils.unvectorize": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Utils.unvectorize",
    "nfoursid.utils.utils.validate_matrix_shape": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Utils.validate_matrix_shape",
    "nfoursid.utils.utils.vectorize": "https://nfoursid.readthedocs.io/en/latest/source/utils.html#nfoursid.utils.Utils.vectorize",
}
