VERSION = "4.0.3"

# fmt: off
MAPPING = {
    "ngram": "https://python-ngram.readthedocs.io/en/stable/",
    "ngram.ngram": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram",
    "ngram.ngram.add": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.add",
    "ngram.ngram.clear": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.clear",
    "ngram.ngram.compare": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.compare",
    "ngram.ngram.copy": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.copy",
    "ngram.ngram.difference": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.difference",
    "ngram.ngram.difference_update": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.difference_update",
    "ngram.ngram.discard": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.discard",
    "ngram.ngram.find": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.find",
    "ngram.ngram.finditem": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.finditem",
    "ngram.ngram.intersection": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.intersection",
    "ngram.ngram.intersection_update": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.intersection_update",
    "ngram.ngram.items_sharing_ngrams": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.items_sharing_ngrams",
    "ngram.ngram.key": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.key",
    "ngram.ngram.ngram_similarity": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.ngram_similarity",
    "ngram.ngram.ngrams": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.ngrams",
    "ngram.ngram.ngrams_pad": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.ngrams_pad",
    "ngram.ngram.pad": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.pad",
    "ngram.ngram.pop": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.pop",
    "ngram.ngram.remove": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.remove",
    "ngram.ngram.search": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.search",
    "ngram.ngram.searchitem": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.searchitem",
    "ngram.ngram.split": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.split",
    "ngram.ngram.splititem": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.splititem",
    "ngram.ngram.symmetric_difference": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.symmetric_difference",
    "ngram.ngram.symmetric_difference_update": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.symmetric_difference_update",
    "ngram.ngram.union": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.union",
    "ngram.ngram.update": "https://python-ngram.readthedocs.io/en/stable/ngram.html#ngram.NGram.update",
}
