VERSION = "2.2.1"

# fmt: off
MAPPING = {
    "nocasedict": "https://nocasedict.readthedocs.io/en/stable/",
    "nocasedict._hashable": "https://nocasedict.readthedocs.io/en/stable/reference.html",
    "nocasedict._hashable.hashablemixin": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.HashableMixin",
    "nocasedict._nocasedict": "https://nocasedict.readthedocs.io/en/stable/reference.html",
    "nocasedict._nocasedict.nocasedict": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict",
    "nocasedict._version": "https://nocasedict.readthedocs.io/en/stable/intro.html",
    "nocasedict._version.__version__": "https://nocasedict.readthedocs.io/en/stable/intro.html#nocasedict._version.__version__",
    "nocasedict.hashablemixin": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.HashableMixin",
    "nocasedict.hashablemixin.__hash__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.HashableMixin.__hash__",
    "nocasedict.keyablebymixin": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.KeyableByMixin",
    "nocasedict.nocasedict": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict",
    "nocasedict.nocasedict.__casefold__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__casefold__",
    "nocasedict.nocasedict.__contains__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__contains__",
    "nocasedict.nocasedict.__delitem__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__delitem__",
    "nocasedict.nocasedict.__eq__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__eq__",
    "nocasedict.nocasedict.__ge__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__ge__",
    "nocasedict.nocasedict.__getitem__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__getitem__",
    "nocasedict.nocasedict.__gt__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__gt__",
    "nocasedict.nocasedict.__ior__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__ior__",
    "nocasedict.nocasedict.__iter__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__iter__",
    "nocasedict.nocasedict.__le__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__le__",
    "nocasedict.nocasedict.__len__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__len__",
    "nocasedict.nocasedict.__lt__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__lt__",
    "nocasedict.nocasedict.__ne__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__ne__",
    "nocasedict.nocasedict.__or__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__or__",
    "nocasedict.nocasedict.__repr__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__repr__",
    "nocasedict.nocasedict.__reversed__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__reversed__",
    "nocasedict.nocasedict.__ror__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__ror__",
    "nocasedict.nocasedict.__setitem__": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.__setitem__",
    "nocasedict.nocasedict.clear": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.clear",
    "nocasedict.nocasedict.copy": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.copy",
    "nocasedict.nocasedict.fromkeys": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.fromkeys",
    "nocasedict.nocasedict.get": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.get",
    "nocasedict.nocasedict.items": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.items",
    "nocasedict.nocasedict.keys": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.keys",
    "nocasedict.nocasedict.keys_nocase": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.keys_nocase",
    "nocasedict.nocasedict.pop": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.pop",
    "nocasedict.nocasedict.popitem": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.popitem",
    "nocasedict.nocasedict.setdefault": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.setdefault",
    "nocasedict.nocasedict.update": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.update",
    "nocasedict.nocasedict.values": "https://nocasedict.readthedocs.io/en/stable/reference.html#nocasedict.NocaseDict.values",
}
