VERSION = "2026.8.17"

# fmt: off
MAPPING = {
    "nox": "https://nox.thea.codes/en/stable/",
    "nox.parametrize": "https://nox.thea.codes/en/stable/config.html#nox.parametrize",
    "nox.project": "https://nox.thea.codes/en/stable/config.html#module-nox.project",
    "nox.project.dependency_groups": "https://nox.thea.codes/en/stable/config.html#nox.project.dependency_groups",
    "nox.project.load_toml": "https://nox.thea.codes/en/stable/config.html#nox.project.load_toml",
    "nox.project.python_versions": "https://nox.thea.codes/en/stable/config.html#nox.project.python_versions",
    "nox.session": "https://nox.thea.codes/en/stable/config.html#nox.session",
    "nox.sessions": "https://nox.thea.codes/en/stable/config.html#module-nox.sessions",
    "nox.sessions.session": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session",
    "nox.sessions.session.bin": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.bin",
    "nox.sessions.session.bin_paths": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.bin_paths",
    "nox.sessions.session.cache_dir": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.cache_dir",
    "nox.sessions.session.cd": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.cd",
    "nox.sessions.session.chdir": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.chdir",
    "nox.sessions.session.conda_install": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.conda_install",
    "nox.sessions.session.create_tmp": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.create_tmp",
    "nox.sessions.session.debug": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.debug",
    "nox.sessions.session.env": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.env",
    "nox.sessions.session.env_dir": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.env_dir",
    "nox.sessions.session.error": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.error",
    "nox.sessions.session.install": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.install",
    "nox.sessions.session.install_and_run_script": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.install_and_run_script",
    "nox.sessions.session.interactive": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.interactive",
    "nox.sessions.session.invoked_from": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.invoked_from",
    "nox.sessions.session.log": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.log",
    "nox.sessions.session.name": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.name",
    "nox.sessions.session.notify": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.notify",
    "nox.sessions.session.posargs": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.posargs",
    "nox.sessions.session.python": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.python",
    "nox.sessions.session.run": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.run",
    "nox.sessions.session.run_install": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.run_install",
    "nox.sessions.session.skip": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.skip",
    "nox.sessions.session.venv_backend": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.venv_backend",
    "nox.sessions.session.virtualenv": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.virtualenv",
    "nox.sessions.session.warn": "https://nox.thea.codes/en/stable/config.html#nox.sessions.Session.warn",
}
