VERSION = "2.3.1"

# fmt: off
MAPPING = {
    "omegaconf": "https://omegaconf.readthedocs.io/en/latest/",
    "omegaconf.missing": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.MISSING",
    "omegaconf.omegaconf": "https://omegaconf.readthedocs.io/en/latest/api_reference.html",
    "omegaconf.OmegaConf": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf",
    "omegaconf.omegaconf.can_select": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.can_select",
    "omegaconf.omegaconf.clear_cache": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.clear_cache",
    "omegaconf.omegaconf.clear_resolver": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.clear_resolver",
    "omegaconf.omegaconf.clear_resolvers": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.clear_resolvers",
    "omegaconf.omegaconf.copy_cache": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.copy_cache",
    "omegaconf.omegaconf.create": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.create",
    "omegaconf.omegaconf.flag_override": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.omegaconf.flag_override",
    "omegaconf.omegaconf.from_cli": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.from_cli",
    "omegaconf.omegaconf.from_dotlist": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.from_dotlist",
    "omegaconf.omegaconf.get_cache": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.get_cache",
    "omegaconf.omegaconf.get_type": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.get_type",
    "omegaconf.omegaconf.has_resolver": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.has_resolver",
    "omegaconf.omegaconf.ii": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.omegaconf.II",
    "omegaconf.omegaconf.is_config": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.is_config",
    "omegaconf.omegaconf.is_dict": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.is_dict",
    "omegaconf.omegaconf.is_interpolation": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.is_interpolation",
    "omegaconf.omegaconf.is_list": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.is_list",
    "omegaconf.omegaconf.is_missing": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.is_missing",
    "omegaconf.omegaconf.is_readonly": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.is_readonly",
    "omegaconf.omegaconf.is_sequence": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.is_sequence",
    "omegaconf.omegaconf.is_struct": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.is_struct",
    "omegaconf.omegaconf.is_tuple": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.is_tuple",
    "omegaconf.omegaconf.load": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.load",
    "omegaconf.omegaconf.masked_copy": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.masked_copy",
    "omegaconf.omegaconf.merge": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.merge",
    "omegaconf.omegaconf.missing_keys": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.missing_keys",
    "omegaconf.omegaconf.omegaconf": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf",
    "omegaconf.omegaconf.open_dict": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.omegaconf.open_dict",
    "omegaconf.omegaconf.read_write": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.omegaconf.read_write",
    "omegaconf.omegaconf.register_resolver": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.register_resolver",
    "omegaconf.omegaconf.resolve": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.resolve",
    "omegaconf.omegaconf.save": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.save",
    "omegaconf.omegaconf.select": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.select",
    "omegaconf.omegaconf.set_cache": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.set_cache",
    "omegaconf.omegaconf.set_readonly": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.set_readonly",
    "omegaconf.omegaconf.set_struct": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.set_struct",
    "omegaconf.omegaconf.si": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.omegaconf.SI",
    "omegaconf.omegaconf.structural_equality": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.structural_equality",
    "omegaconf.omegaconf.structured": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.structured",
    "omegaconf.omegaconf.to_container": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.to_container",
    "omegaconf.omegaconf.to_object": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.to_object",
    "omegaconf.omegaconf.to_yaml": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.to_yaml",
    "omegaconf.omegaconf.typed_dict": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.typed_dict",
    "omegaconf.omegaconf.typed_list": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.typed_list",
    "omegaconf.omegaconf.typed_tuple": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.typed_tuple",
    "omegaconf.omegaconf.unsafe_merge": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.unsafe_merge",
    "omegaconf.omegaconf.update": "https://omegaconf.readthedocs.io/en/latest/api_reference.html#omegaconf.OmegaConf.update",
}
