VERSION = "2.3.3"

# fmt: off
MAPPING = {
    "openrouteservice": "https://openrouteservice-py.readthedocs.io/en/stable/",
    "openrouteservice.client": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.client",
    "openrouteservice.client.client": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.client.Client",
    "openrouteservice.client.client.req": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.client.Client.req",
    "openrouteservice.client.client.request": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.client.Client.request",
    "openrouteservice.convert": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.convert",
    "openrouteservice.convert.decode_polyline": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.convert.decode_polyline",
    "openrouteservice.directions": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.directions",
    "openrouteservice.directions.directions": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.directions.directions",
    "openrouteservice.distance_matrix": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.distance_matrix",
    "openrouteservice.distance_matrix.distance_matrix": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.distance_matrix.distance_matrix",
    "openrouteservice.elevation": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.elevation",
    "openrouteservice.elevation.elevation_line": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.elevation.elevation_line",
    "openrouteservice.elevation.elevation_point": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.elevation.elevation_point",
    "openrouteservice.exceptions": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.exceptions",
    "openrouteservice.exceptions.apierror": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.exceptions.ApiError",
    "openrouteservice.exceptions.httperror": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.exceptions.HTTPError",
    "openrouteservice.exceptions.timeout": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.exceptions.Timeout",
    "openrouteservice.exceptions.validationerror": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.exceptions.ValidationError",
    "openrouteservice.geocode": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.geocode",
    "openrouteservice.geocode.pelias_autocomplete": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.geocode.pelias_autocomplete",
    "openrouteservice.geocode.pelias_reverse": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.geocode.pelias_reverse",
    "openrouteservice.geocode.pelias_search": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.geocode.pelias_search",
    "openrouteservice.geocode.pelias_structured": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.geocode.pelias_structured",
    "openrouteservice.get_ordinal": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.get_ordinal",
    "openrouteservice.isochrones": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.isochrones",
    "openrouteservice.isochrones.isochrones": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.isochrones.isochrones",
    "openrouteservice.optimization": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.optimization",
    "openrouteservice.optimization.job": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.optimization.Job",
    "openrouteservice.optimization.optimization": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.optimization.optimization",
    "openrouteservice.optimization.shipment": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.optimization.Shipment",
    "openrouteservice.optimization.shipmentstep": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.optimization.ShipmentStep",
    "openrouteservice.optimization.vehicle": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.optimization.Vehicle",
    "openrouteservice.places": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#module-openrouteservice.places",
    "openrouteservice.places.places": "https://openrouteservice-py.readthedocs.io/en/stable/openrouteservice.html#openrouteservice.places.places",
}
