VERSION = "1.4.6"

# fmt: off
MAPPING = {
    "openslide": "https://openslide.org/api/python/",
    "openslide.abstractslide": "https://openslide.org/api/python/index.html#openslide.AbstractSlide",
    "openslide.deepzoom": "https://openslide.org/api/python/index.html#module-openslide.deepzoom",
    "openslide.deepzoom.deepzoomgenerator": "https://openslide.org/api/python/index.html#openslide.deepzoom.DeepZoomGenerator",
    "openslide.deepzoom.deepzoomgenerator.get_dzi": "https://openslide.org/api/python/index.html#openslide.deepzoom.DeepZoomGenerator.get_dzi",
    "openslide.deepzoom.deepzoomgenerator.get_tile": "https://openslide.org/api/python/index.html#openslide.deepzoom.DeepZoomGenerator.get_tile",
    "openslide.deepzoom.deepzoomgenerator.get_tile_coordinates": "https://openslide.org/api/python/index.html#openslide.deepzoom.DeepZoomGenerator.get_tile_coordinates",
    "openslide.deepzoom.deepzoomgenerator.get_tile_dimensions": "https://openslide.org/api/python/index.html#openslide.deepzoom.DeepZoomGenerator.get_tile_dimensions",
    "openslide.deepzoom.deepzoomgenerator.level_count": "https://openslide.org/api/python/index.html#openslide.deepzoom.DeepZoomGenerator.level_count",
    "openslide.deepzoom.deepzoomgenerator.level_dimensions": "https://openslide.org/api/python/index.html#openslide.deepzoom.DeepZoomGenerator.level_dimensions",
    "openslide.deepzoom.deepzoomgenerator.level_tiles": "https://openslide.org/api/python/index.html#openslide.deepzoom.DeepZoomGenerator.level_tiles",
    "openslide.deepzoom.deepzoomgenerator.tile_count": "https://openslide.org/api/python/index.html#openslide.deepzoom.DeepZoomGenerator.tile_count",
    "openslide.imageslide": "https://openslide.org/api/python/index.html#openslide.ImageSlide",
    "openslide.open_slide": "https://openslide.org/api/python/index.html#openslide.open_slide",
    "openslide.openslide": "https://openslide.org/api/python/index.html#openslide.OpenSlide",
    "openslide.openslide.associated_images": "https://openslide.org/api/python/index.html#openslide.OpenSlide.associated_images",
    "openslide.openslide.close": "https://openslide.org/api/python/index.html#openslide.OpenSlide.close",
    "openslide.openslide.color_profile": "https://openslide.org/api/python/index.html#openslide.OpenSlide.color_profile",
    "openslide.openslide.detect_format": "https://openslide.org/api/python/index.html#openslide.OpenSlide.detect_format",
    "openslide.openslide.dimensions": "https://openslide.org/api/python/index.html#openslide.OpenSlide.dimensions",
    "openslide.openslide.get_best_level_for_downsample": "https://openslide.org/api/python/index.html#openslide.OpenSlide.get_best_level_for_downsample",
    "openslide.openslide.get_thumbnail": "https://openslide.org/api/python/index.html#openslide.OpenSlide.get_thumbnail",
    "openslide.openslide.level_count": "https://openslide.org/api/python/index.html#openslide.OpenSlide.level_count",
    "openslide.openslide.level_dimensions": "https://openslide.org/api/python/index.html#openslide.OpenSlide.level_dimensions",
    "openslide.openslide.level_downsamples": "https://openslide.org/api/python/index.html#openslide.OpenSlide.level_downsamples",
    "openslide.openslide.properties": "https://openslide.org/api/python/index.html#openslide.OpenSlide.properties",
    "openslide.openslide.read_region": "https://openslide.org/api/python/index.html#openslide.OpenSlide.read_region",
    "openslide.openslide.set_cache": "https://openslide.org/api/python/index.html#openslide.OpenSlide.set_cache",
    "openslide.openslidecache": "https://openslide.org/api/python/index.html#openslide.OpenSlideCache",
    "openslide.openslideerror": "https://openslide.org/api/python/index.html#openslide.OpenSlideError",
    "openslide.openslideunsupportedformaterror": "https://openslide.org/api/python/index.html#openslide.OpenSlideUnsupportedFormatError",
    "openslide.openslideversionerror": "https://openslide.org/api/python/index.html#openslide.OpenSlideVersionError",
    "openslide.property_name_background_color": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_BACKGROUND_COLOR",
    "openslide.property_name_barcode": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_BARCODE",
    "openslide.property_name_bounds_height": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_BOUNDS_HEIGHT",
    "openslide.property_name_bounds_width": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_BOUNDS_WIDTH",
    "openslide.property_name_bounds_x": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_BOUNDS_X",
    "openslide.property_name_bounds_y": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_BOUNDS_Y",
    "openslide.property_name_comment": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_COMMENT",
    "openslide.property_name_mpp_x": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_MPP_X",
    "openslide.property_name_mpp_y": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_MPP_Y",
    "openslide.property_name_objective_power": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_OBJECTIVE_POWER",
    "openslide.property_name_quickhash1": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_QUICKHASH1",
    "openslide.property_name_vendor": "https://openslide.org/api/python/index.html#openslide.PROPERTY_NAME_VENDOR",
}
