VERSION = "0.21.0"

# fmt: off
MAPPING = {
    "parametrize_from_file": "https://parametrize-from-file.readthedocs.io/en/stable/",
    "parametrize_from_file.add_loader": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.add_loader.html#parametrize_from_file.add_loader",
    "parametrize_from_file.cast": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.cast.html#parametrize_from_file.cast",
    "parametrize_from_file.configerror": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.ConfigError.html#parametrize_from_file.ConfigError",
    "parametrize_from_file.defaults": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.defaults.html#parametrize_from_file.defaults",
    "parametrize_from_file.drop_loader": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.drop_loader.html#parametrize_from_file.drop_loader",
    "parametrize_from_file.error": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.error.html#parametrize_from_file.error",
    "parametrize_from_file.error_or": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.error_or.html#parametrize_from_file.error_or",
    "parametrize_from_file.fixture": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.fixture.html#parametrize_from_file.fixture",
    "parametrize_from_file.load_parameters": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.load_parameters.html#parametrize_from_file.load_parameters",
    "parametrize_from_file.namespace": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace",
    "parametrize_from_file.namespace.__abstractmethods__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__abstractmethods__",
    "parametrize_from_file.namespace.__contains__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__contains__",
    "parametrize_from_file.namespace.__eq__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__eq__",
    "parametrize_from_file.namespace.__getitem__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__getitem__",
    "parametrize_from_file.namespace.__hash__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__hash__",
    "parametrize_from_file.namespace.__init__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__init__",
    "parametrize_from_file.namespace.__iter__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__iter__",
    "parametrize_from_file.namespace.__len__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__len__",
    "parametrize_from_file.namespace.__repr__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__repr__",
    "parametrize_from_file.namespace.__reversed__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__reversed__",
    "parametrize_from_file.namespace.__slots__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__slots__",
    "parametrize_from_file.namespace.__subclasshook__": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.__subclasshook__",
    "parametrize_from_file.namespace._abc_impl": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace._abc_impl",
    "parametrize_from_file.namespace.copy": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.copy",
    "parametrize_from_file.namespace.error": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.error",
    "parametrize_from_file.namespace.error_or": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.error_or",
    "parametrize_from_file.namespace.eval": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.eval",
    "parametrize_from_file.namespace.exec": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.exec",
    "parametrize_from_file.namespace.fork": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.fork",
    "parametrize_from_file.namespace.get": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.get",
    "parametrize_from_file.namespace.items": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.items",
    "parametrize_from_file.namespace.keys": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.keys",
    "parametrize_from_file.namespace.values": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.Namespace.html#parametrize_from_file.Namespace.values",
    "parametrize_from_file.parametrize": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.parametrize.html#parametrize_from_file.parametrize",
    "parametrize_from_file.rename": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.rename.html#parametrize_from_file.rename",
    "parametrize_from_file.star": "https://parametrize-from-file.readthedocs.io/en/stable/api/parametrize_from_file.star.html#parametrize_from_file.star",
}
