VERSION = "1.0.2"

# fmt: off
MAPPING = {
    "passpy": "https://passpy.readthedocs.io/en/stable/",
    "passpy.git": "https://passpy.readthedocs.io/en/stable/reference.html#module-passpy.git",
    "passpy.git._git_commit": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.git._git_commit",
    "passpy.git.get_git_repository": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.git.get_git_repository",
    "passpy.git.git_add_path": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.git.git_add_path",
    "passpy.git.git_config": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.git.git_config",
    "passpy.git.git_init": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.git.git_init",
    "passpy.git.git_remove_path": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.git.git_remove_path",
    "passpy.gpg": "https://passpy.readthedocs.io/en/stable/reference.html#module-passpy.gpg",
    "passpy.gpg._get_gpg_recipients": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.gpg._get_gpg_recipients",
    "passpy.gpg._reencrypt_key": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.gpg._reencrypt_key",
    "passpy.gpg.read_key": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.gpg.read_key",
    "passpy.gpg.reencrypt_path": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.gpg.reencrypt_path",
    "passpy.gpg.write_key": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.gpg.write_key",
    "passpy.store": "https://passpy.readthedocs.io/en/stable/reference.html#module-passpy.store",
    "passpy.store.store": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store",
    "passpy.store.store.__init__": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.__init__",
    "passpy.store.store.__weakref__": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.__weakref__",
    "passpy.store.store._copy_move_path": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store._copy_move_path",
    "passpy.store.store._get_store_name": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store._get_store_name",
    "passpy.store.store.copy_path": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.copy_path",
    "passpy.store.store.find": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.find",
    "passpy.store.store.gen_key": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.gen_key",
    "passpy.store.store.get_key": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.get_key",
    "passpy.store.store.init_git": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.init_git",
    "passpy.store.store.init_store": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.init_store",
    "passpy.store.store.list_dir": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.list_dir",
    "passpy.store.store.move_path": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.move_path",
    "passpy.store.store.remove_path": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.remove_path",
    "passpy.store.store.search": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.search",
    "passpy.store.store.set_key": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.store.Store.set_key",
    "passpy.util": "https://passpy.readthedocs.io/en/stable/reference.html#module-passpy.util",
    "passpy.util.copy_move": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.util.copy_move",
    "passpy.util.gen_password": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.util.gen_password",
    "passpy.util.initialised": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.util.initialised",
    "passpy.util.trap": "https://passpy.readthedocs.io/en/stable/reference.html#passpy.util.trap",
}
