VERSION = "1.0.3"

# fmt: off
MAPPING = {
    "pcodec": "https://pcodec.readthedocs.io/en/stable/",
    "pcodec.chunkconfig": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ChunkConfig",
    "pcodec.chunkconfig.compression_level": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ChunkConfig.compression_level",
    "pcodec.chunkconfig.delta_spec": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ChunkConfig.delta_spec",
    "pcodec.chunkconfig.enable_8_bit": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ChunkConfig.enable_8_bit",
    "pcodec.chunkconfig.mode_spec": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ChunkConfig.mode_spec",
    "pcodec.chunkconfig.paging_spec": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ChunkConfig.paging_spec",
    "pcodec.deltaspec": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.DeltaSpec",
    "pcodec.deltaspec.auto": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.DeltaSpec.auto",
    "pcodec.deltaspec.no_op": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.DeltaSpec.no_op",
    "pcodec.deltaspec.try_consecutive": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.DeltaSpec.try_consecutive",
    "pcodec.deltaspec.try_conv1": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.DeltaSpec.try_conv1",
    "pcodec.deltaspec.try_lookback": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.DeltaSpec.try_lookback",
    "pcodec.modespec": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ModeSpec",
    "pcodec.modespec.auto": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ModeSpec.auto",
    "pcodec.modespec.classic": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ModeSpec.classic",
    "pcodec.modespec.try_dict": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ModeSpec.try_dict",
    "pcodec.modespec.try_float_mult": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ModeSpec.try_float_mult",
    "pcodec.modespec.try_float_quant": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ModeSpec.try_float_quant",
    "pcodec.modespec.try_int_mult": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.ModeSpec.try_int_mult",
    "pcodec.pagingspec": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.PagingSpec",
    "pcodec.pagingspec.equal_pages_up_to": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.PagingSpec.equal_pages_up_to",
    "pcodec.pagingspec.exact_page_sizes": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.PagingSpec.exact_page_sizes",
    "pcodec.progress": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.Progress",
    "pcodec.progress.finished": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.Progress.finished",
    "pcodec.progress.n_processed": "https://pcodec.readthedocs.io/en/stable/index.html#pcodec.Progress.n_processed",
    "pcodec.standalone": "https://pcodec.readthedocs.io/en/stable/standalone.html#module-pcodec.standalone",
    "pcodec.standalone.simple_compress": "https://pcodec.readthedocs.io/en/stable/standalone.html#pcodec.standalone.simple_compress",
    "pcodec.standalone.simple_decompress": "https://pcodec.readthedocs.io/en/stable/standalone.html#pcodec.standalone.simple_decompress",
    "pcodec.standalone.simple_decompress_into": "https://pcodec.readthedocs.io/en/stable/standalone.html#pcodec.standalone.simple_decompress_into",
    "pcodec.wrapped": "https://pcodec.readthedocs.io/en/stable/wrapped.html#module-pcodec.wrapped",
    "pcodec.wrapped.chunkcompressor": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.ChunkCompressor",
    "pcodec.wrapped.chunkcompressor.n_per_page": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.ChunkCompressor.n_per_page",
    "pcodec.wrapped.chunkcompressor.write_meta": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.ChunkCompressor.write_meta",
    "pcodec.wrapped.chunkcompressor.write_page": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.ChunkCompressor.write_page",
    "pcodec.wrapped.chunkdecompressor": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.ChunkDecompressor",
    "pcodec.wrapped.chunkdecompressor.read_page_into": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.ChunkDecompressor.read_page_into",
    "pcodec.wrapped.filecompressor": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.FileCompressor",
    "pcodec.wrapped.filecompressor.chunk_compressor": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.FileCompressor.chunk_compressor",
    "pcodec.wrapped.filecompressor.write_header": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.FileCompressor.write_header",
    "pcodec.wrapped.filedecompressor": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.FileDecompressor",
    "pcodec.wrapped.filedecompressor.chunk_decompressor": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.FileDecompressor.chunk_decompressor",
    "pcodec.wrapped.filedecompressor.new": "https://pcodec.readthedocs.io/en/stable/wrapped.html#pcodec.wrapped.FileDecompressor.new",
}
