VERSION = "2.4.9"

# fmt: off
MAPPING = {
    "pdm": "https://backend.pdm-project.org/",
    "pdm.backend": "https://backend.pdm-project.org/api/",
    "pdm.backend.config": "https://backend.pdm-project.org/api/#pdm.backend.config",
    "pdm.backend.config.buildconfig": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig",
    "pdm.backend.config.buildconfig.custom_hook": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig.custom_hook",
    "pdm.backend.config.buildconfig.editable_backend": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig.editable_backend",
    "pdm.backend.config.buildconfig.excludes": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig.excludes",
    "pdm.backend.config.buildconfig.includes": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig.includes",
    "pdm.backend.config.buildconfig.is_purelib": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig.is_purelib",
    "pdm.backend.config.buildconfig.package_dir": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig.package_dir",
    "pdm.backend.config.buildconfig.run_setuptools": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig.run_setuptools",
    "pdm.backend.config.buildconfig.source_includes": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig.source_includes",
    "pdm.backend.config.buildconfig.wheel_data": "https://backend.pdm-project.org/api/#pdm.backend.config.BuildConfig.wheel_data",
    "pdm.backend.config.config": "https://backend.pdm-project.org/api/#pdm.backend.config.Config",
    "pdm.backend.config.config.convert_package_paths": "https://backend.pdm-project.org/api/#pdm.backend.config.Config.convert_package_paths",
    "pdm.backend.config.config.for_hook": "https://backend.pdm-project.org/api/#pdm.backend.config.Config.for_hook",
    "pdm.backend.config.config.from_pyproject": "https://backend.pdm-project.org/api/#pdm.backend.config.Config.from_pyproject",
    "pdm.backend.config.config.validate": "https://backend.pdm-project.org/api/#pdm.backend.config.Config.validate",
    "pdm.backend.config.config.write_to": "https://backend.pdm-project.org/api/#pdm.backend.config.Config.write_to",
    "pdm.backend.hooks": "https://backend.pdm-project.org/api/",
    "pdm.backend.hooks.base": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base",
    "pdm.backend.hooks.base.buildhookinterface": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.BuildHookInterface",
    "pdm.backend.hooks.base.buildhookinterface.pdm_build_clean": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.BuildHookInterface.pdm_build_clean",
    "pdm.backend.hooks.base.buildhookinterface.pdm_build_finalize": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.BuildHookInterface.pdm_build_finalize",
    "pdm.backend.hooks.base.buildhookinterface.pdm_build_hook_enabled": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.BuildHookInterface.pdm_build_hook_enabled",
    "pdm.backend.hooks.base.buildhookinterface.pdm_build_initialize": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.BuildHookInterface.pdm_build_initialize",
    "pdm.backend.hooks.base.buildhookinterface.pdm_build_update_files": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.BuildHookInterface.pdm_build_update_files",
    "pdm.backend.hooks.base.buildhookinterface.pdm_build_update_setup_kwargs": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.BuildHookInterface.pdm_build_update_setup_kwargs",
    "pdm.backend.hooks.base.config": "https://backend.pdm-project.org/api/#pdm.backend.config.Config",
    "pdm.backend.hooks.base.context": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.Context",
    "pdm.backend.hooks.base.context.config": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.Context.config",
    "pdm.backend.hooks.base.context.config_settings": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.Context.config_settings",
    "pdm.backend.hooks.base.context.ensure_build_dir": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.Context.ensure_build_dir",
    "pdm.backend.hooks.base.context.root": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.Context.root",
    "pdm.backend.hooks.base.context.target": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.Context.target",
    "pdm.backend.hooks.buildhookinterface": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.BuildHookInterface",
    "pdm.backend.hooks.context": "https://backend.pdm-project.org/api/#pdm.backend.hooks.base.Context",
}
