VERSION = "0.5.0"

# fmt: off
MAPPING = {
    "permutation": "https://permutation.readthedocs.io/en/stable/",
    "permutation.permutation": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation",
    "permutation.permutation.__bool__": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.__bool__",
    "permutation.permutation.__call__": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.__call__",
    "permutation.permutation.__init__": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.__init__",
    "permutation.permutation.__mul__": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.__mul__",
    "permutation.permutation.__pow__": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.__pow__",
    "permutation.permutation.__str__": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.__str__",
    "permutation.permutation.cycle": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.cycle",
    "permutation.permutation.degree": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.degree",
    "permutation.permutation.from_cycles": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.from_cycles",
    "permutation.permutation.from_left_lehmer": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.from_left_lehmer",
    "permutation.permutation.from_lehmer": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.from_lehmer",
    "permutation.permutation.group": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.group",
    "permutation.permutation.inverse": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.inverse",
    "permutation.permutation.inversions": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.inversions",
    "permutation.permutation.is_even": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.is_even",
    "permutation.permutation.is_odd": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.is_odd",
    "permutation.permutation.isdisjoint": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.isdisjoint",
    "permutation.permutation.left_lehmer": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.left_lehmer",
    "permutation.permutation.lehmer": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.lehmer",
    "permutation.permutation.next_permutation": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.next_permutation",
    "permutation.permutation.order": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.order",
    "permutation.permutation.parse": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.parse",
    "permutation.permutation.permute": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.permute",
    "permutation.permutation.prev_permutation": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.prev_permutation",
    "permutation.permutation.right_inversion_count": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.right_inversion_count",
    "permutation.permutation.sign": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.sign",
    "permutation.permutation.to_cycles": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.to_cycles",
    "permutation.permutation.to_image": "https://permutation.readthedocs.io/en/stable/index.html#permutation.Permutation.to_image",
}
