VERSION = "4.0.0"

# fmt: off
MAPPING = {
    "picobox": "https://picobox.readthedocs.io/en/stable/",
    "picobox._box": "https://picobox.readthedocs.io/en/stable/index.html",
    "picobox._box.box": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Box",
    "picobox._box.chainbox": "https://picobox.readthedocs.io/en/stable/index.html#picobox.ChainBox",
    "picobox._scopes": "https://picobox.readthedocs.io/en/stable/index.html",
    "picobox._scopes.scope": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Scope",
    "picobox._stack": "https://picobox.readthedocs.io/en/stable/index.html",
    "picobox._stack.stack": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Stack",
    "picobox.box": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Box",
    "picobox.box.get": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Box.get",
    "picobox.box.pass_": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Box.pass_",
    "picobox.box.put": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Box.put",
    "picobox.chainbox": "https://picobox.readthedocs.io/en/stable/index.html#picobox.ChainBox",
    "picobox.chainbox.get": "https://picobox.readthedocs.io/en/stable/index.html#picobox.ChainBox.get",
    "picobox.chainbox.put": "https://picobox.readthedocs.io/en/stable/index.html#picobox.ChainBox.put",
    "picobox.contextvars": "https://picobox.readthedocs.io/en/stable/index.html#picobox.contextvars",
    "picobox.ext": "https://picobox.readthedocs.io/en/stable/index.html",
    "picobox.ext.flaskscopes": "https://picobox.readthedocs.io/en/stable/index.html",
    "picobox.ext.flaskscopes.application": "https://picobox.readthedocs.io/en/stable/index.html#picobox.ext.flaskscopes.application",
    "picobox.ext.flaskscopes.request": "https://picobox.readthedocs.io/en/stable/index.html#picobox.ext.flaskscopes.request",
    "picobox.get": "https://picobox.readthedocs.io/en/stable/index.html#picobox.get",
    "picobox.noscope": "https://picobox.readthedocs.io/en/stable/index.html#picobox.noscope",
    "picobox.pass_": "https://picobox.readthedocs.io/en/stable/index.html#picobox.pass_",
    "picobox.pop": "https://picobox.readthedocs.io/en/stable/index.html#picobox.pop",
    "picobox.push": "https://picobox.readthedocs.io/en/stable/index.html#picobox.push",
    "picobox.put": "https://picobox.readthedocs.io/en/stable/index.html#picobox.put",
    "picobox.scope": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Scope",
    "picobox.scope.get": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Scope.get",
    "picobox.scope.set": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Scope.set",
    "picobox.singleton": "https://picobox.readthedocs.io/en/stable/index.html#picobox.singleton",
    "picobox.stack": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Stack",
    "picobox.stack.get": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Stack.get",
    "picobox.stack.pass_": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Stack.pass_",
    "picobox.stack.pop": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Stack.pop",
    "picobox.stack.push": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Stack.push",
    "picobox.stack.put": "https://picobox.readthedocs.io/en/stable/index.html#picobox.Stack.put",
    "picobox.threadlocal": "https://picobox.readthedocs.io/en/stable/index.html#picobox.threadlocal",
}
