VERSION = "1.2.2"

# fmt: off
MAPPING = {
    "piplicenses_lib": "https://pip-licenses-lib.readthedocs.io/en/stable/",
    "piplicenses_lib.extract_homepage": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.extract_homepage",
    "piplicenses_lib.find_license_from_classifier": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.find_license_from_classifier",
    "piplicenses_lib.fromarg": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.FromArg",
    "piplicenses_lib.fromarg.all": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.FromArg.ALL",
    "piplicenses_lib.fromarg.classifier": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.FromArg.CLASSIFIER",
    "piplicenses_lib.fromarg.meta": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.FromArg.META",
    "piplicenses_lib.fromarg.mixed": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.FromArg.MIXED",
    "piplicenses_lib.get_package_included_files": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.get_package_included_files",
    "piplicenses_lib.get_package_info": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.get_package_info",
    "piplicenses_lib.get_packages": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.get_packages",
    "piplicenses_lib.get_python_sys_path": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.get_python_sys_path",
    "piplicenses_lib.license_unknown": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.LICENSE_UNKNOWN",
    "piplicenses_lib.normalize_package_name": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.normalize_package_name",
    "piplicenses_lib.packageinfo": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo",
    "piplicenses_lib.packageinfo.author": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.author",
    "piplicenses_lib.packageinfo.distribution": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.distribution",
    "piplicenses_lib.packageinfo.homepage": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.homepage",
    "piplicenses_lib.packageinfo.is_metadata_file": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.is_metadata_file",
    "piplicenses_lib.packageinfo.license": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.license",
    "piplicenses_lib.packageinfo.license_classifiers": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.license_classifiers",
    "piplicenses_lib.packageinfo.license_files": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.license_files",
    "piplicenses_lib.packageinfo.license_names": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.license_names",
    "piplicenses_lib.packageinfo.license_texts": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.license_texts",
    "piplicenses_lib.packageinfo.licenses": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.licenses",
    "piplicenses_lib.packageinfo.maintainer": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.maintainer",
    "piplicenses_lib.packageinfo.name": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.name",
    "piplicenses_lib.packageinfo.name_version": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.name_version",
    "piplicenses_lib.packageinfo.notice_files": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.notice_files",
    "piplicenses_lib.packageinfo.notice_texts": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.notice_texts",
    "piplicenses_lib.packageinfo.notices": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.notices",
    "piplicenses_lib.packageinfo.other_files": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.other_files",
    "piplicenses_lib.packageinfo.other_texts": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.other_texts",
    "piplicenses_lib.packageinfo.others": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.others",
    "piplicenses_lib.packageinfo.requirements": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.requirements",
    "piplicenses_lib.packageinfo.sbom_files": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.sbom_files",
    "piplicenses_lib.packageinfo.sbom_texts": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.sbom_texts",
    "piplicenses_lib.packageinfo.sboms": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.sboms",
    "piplicenses_lib.packageinfo.summary": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.summary",
    "piplicenses_lib.packageinfo.version": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.PackageInfo.version",
    "piplicenses_lib.read_file": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.read_file",
    "piplicenses_lib.select_license_by_source": "https://pip-licenses-lib.readthedocs.io/en/stable/api.html#piplicenses_lib.select_license_by_source",
}
