VERSION = "0.11.0"

# fmt: off
MAPPING = {
    "pluginlib": "https://pluginlib.readthedocs.io/en/stable/",
    "pluginlib._loader": "https://pluginlib.readthedocs.io/en/stable/api.html",
    "pluginlib._loader.pluginloader": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginLoader",
    "pluginlib._objects": "https://pluginlib.readthedocs.io/en/stable/api.html",
    "pluginlib._objects.blacklistentry": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.BlacklistEntry",
    "pluginlib._parent": "https://pluginlib.readthedocs.io/en/stable/api.html",
    "pluginlib._parent.plugin": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Plugin",
    "pluginlib._util": "https://pluginlib.readthedocs.io/en/stable/api.html",
    "pluginlib._util.abstractattribute": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.abstractattribute",
    "pluginlib.abstractattribute": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.abstractattribute",
    "pluginlib.abstractclassmethod": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.abstractclassmethod",
    "pluginlib.abstractmethod": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.abstractmethod",
    "pluginlib.abstractproperty": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.abstractproperty",
    "pluginlib.abstractstaticmethod": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.abstractstaticmethod",
    "pluginlib.blacklistentry": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.BlacklistEntry",
    "pluginlib.entrypointwarning": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.EntryPointWarning",
    "pluginlib.exceptions": "https://pluginlib.readthedocs.io/en/stable/api.html",
    "pluginlib.exceptions.entrypointwarning": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.EntryPointWarning",
    "pluginlib.exceptions.pluginimporterror": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginImportError",
    "pluginlib.exceptions.pluginliberror": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginlibError",
    "pluginlib.exceptions.pluginwarning": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginWarning",
    "pluginlib.parent": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Parent",
    "pluginlib.plugin": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Plugin",
    "pluginlib.plugin._alias_": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Plugin._alias_",
    "pluginlib.plugin._skipload_": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Plugin._skipload_",
    "pluginlib.plugin._version_": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Plugin._version_",
    "pluginlib.plugin.name": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Plugin.name",
    "pluginlib.plugin.plugin_group": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Plugin.plugin_group",
    "pluginlib.plugin.plugin_type": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Plugin.plugin_type",
    "pluginlib.plugin.version": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.Plugin.version",
    "pluginlib.pluginimporterror": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginImportError",
    "pluginlib.pluginimporterror.friendly": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginImportError.friendly",
    "pluginlib.pluginliberror": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginlibError",
    "pluginlib.pluginliberror.friendly": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginlibError.friendly",
    "pluginlib.pluginloader": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginLoader",
    "pluginlib.pluginloader.get_plugin": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginLoader.get_plugin",
    "pluginlib.pluginloader.load_modules": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginLoader.load_modules",
    "pluginlib.pluginloader.plugins": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginLoader.plugins",
    "pluginlib.pluginloader.plugins_all": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginLoader.plugins_all",
    "pluginlib.pluginwarning": "https://pluginlib.readthedocs.io/en/stable/api.html#pluginlib.PluginWarning",
}
