VERSION = "0.5.3"

# fmt: off
MAPPING = {
    "polars_distance": "https://ion-elgreco.github.io/polars-distance/",
    "polars_distance.distancepairwise": "https://ion-elgreco.github.io/polars-distance/api/dist/",
    "polars_distance.distancepairwise.haversine": "https://ion-elgreco.github.io/polars-distance/api/dist/#polars_distance.DistancePairWise.haversine",
    "polars_distance.distancepairwisearray": "https://ion-elgreco.github.io/polars-distance/api/array_distance/",
    "polars_distance.distancepairwisearray.bray_curtis": "https://ion-elgreco.github.io/polars-distance/api/array_distance/#polars_distance.DistancePairWiseArray.bray_curtis",
    "polars_distance.distancepairwisearray.canberra": "https://ion-elgreco.github.io/polars-distance/api/array_distance/#polars_distance.DistancePairWiseArray.canberra",
    "polars_distance.distancepairwisearray.chebyshev": "https://ion-elgreco.github.io/polars-distance/api/array_distance/#polars_distance.DistancePairWiseArray.chebyshev",
    "polars_distance.distancepairwisearray.cosine": "https://ion-elgreco.github.io/polars-distance/api/array_distance/#polars_distance.DistancePairWiseArray.cosine",
    "polars_distance.distancepairwisearray.euclidean": "https://ion-elgreco.github.io/polars-distance/api/array_distance/#polars_distance.DistancePairWiseArray.euclidean",
    "polars_distance.distancepairwisearray.l3_norm": "https://ion-elgreco.github.io/polars-distance/api/array_distance/#polars_distance.DistancePairWiseArray.l3_norm",
    "polars_distance.distancepairwisearray.l4_norm": "https://ion-elgreco.github.io/polars-distance/api/array_distance/#polars_distance.DistancePairWiseArray.l4_norm",
    "polars_distance.distancepairwisearray.manhatten": "https://ion-elgreco.github.io/polars-distance/api/array_distance/#polars_distance.DistancePairWiseArray.manhatten",
    "polars_distance.distancepairwisearray.minkowski": "https://ion-elgreco.github.io/polars-distance/api/array_distance/#polars_distance.DistancePairWiseArray.minkowski",
    "polars_distance.distancepairwiselist": "https://ion-elgreco.github.io/polars-distance/api/list_distance/",
    "polars_distance.distancepairwiselist.cosine": "https://ion-elgreco.github.io/polars-distance/api/list_distance/#polars_distance.DistancePairWiseList.cosine",
    "polars_distance.distancepairwiselist.jaccard_index": "https://ion-elgreco.github.io/polars-distance/api/list_distance/#polars_distance.DistancePairWiseList.jaccard_index",
    "polars_distance.distancepairwiselist.overlap_coef": "https://ion-elgreco.github.io/polars-distance/api/list_distance/#polars_distance.DistancePairWiseList.overlap_coef",
    "polars_distance.distancepairwiselist.sorensen_index": "https://ion-elgreco.github.io/polars-distance/api/list_distance/#polars_distance.DistancePairWiseList.sorensen_index",
    "polars_distance.distancepairwiselist.tversky_index": "https://ion-elgreco.github.io/polars-distance/api/list_distance/#polars_distance.DistancePairWiseList.tversky_index",
    "polars_distance.distancepairwisestring": "https://ion-elgreco.github.io/polars-distance/api/string_distance/",
    "polars_distance.distancepairwisestring.damerau_levenshtein": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.damerau_levenshtein",
    "polars_distance.distancepairwisestring.hamming": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.hamming",
    "polars_distance.distancepairwisestring.indel": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.indel",
    "polars_distance.distancepairwisestring.jaro": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.jaro",
    "polars_distance.distancepairwisestring.jaro_winkler": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.jaro_winkler",
    "polars_distance.distancepairwisestring.lcs_seq": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.lcs_seq",
    "polars_distance.distancepairwisestring.levenshtein": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.levenshtein",
    "polars_distance.distancepairwisestring.osa": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.osa",
    "polars_distance.distancepairwisestring.postfix": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.postfix",
    "polars_distance.distancepairwisestring.prefix": "https://ion-elgreco.github.io/polars-distance/api/string_distance/#polars_distance.DistancePairWiseString.prefix",
}
