VERSION = "4.2.2"

# fmt: off
MAPPING = {
    "products": "https://productspluggableauthservice.readthedocs.io/en/stable/",
    "products.pluggableauthservice.interfaces.authservice.ibasicuser": "https://productspluggableauthservice.readthedocs.io/en/stable/api/user.html#Products.PluggableAuthService.interfaces.authservice.IBasicUser",
    "products.pluggableauthservice.interfaces.authservice.ienumerableuserfolder": "https://productspluggableauthservice.readthedocs.io/en/stable/api/userfolder.html#Products.PluggableAuthService.interfaces.authservice.IEnumerableUserFolder",
    "products.pluggableauthservice.interfaces.authservice.imutableuserfolder": "https://productspluggableauthservice.readthedocs.io/en/stable/api/userfolder.html#Products.PluggableAuthService.interfaces.authservice.IMutableUserFolder",
    "products.pluggableauthservice.interfaces.authservice.ipluggableauthservice": "https://productspluggableauthservice.readthedocs.io/en/stable/api/userfolder.html#Products.PluggableAuthService.interfaces.authservice.IPluggableAuthService",
    "products.pluggableauthservice.interfaces.authservice.ipropertieduser": "https://productspluggableauthservice.readthedocs.io/en/stable/api/user.html#Products.PluggableAuthService.interfaces.authservice.IPropertiedUser",
    "products.pluggableauthservice.interfaces.authservice.iuserfolder": "https://productspluggableauthservice.readthedocs.io/en/stable/api/userfolder.html#Products.PluggableAuthService.interfaces.authservice.IUserFolder",
    "products.pluggableauthservice.interfaces.events": "https://productspluggableauthservice.readthedocs.io/en/stable/api/events.html",
    "products.pluggableauthservice.interfaces.events.icredentialsupdatedevent": "https://productspluggableauthservice.readthedocs.io/en/stable/api/events.html#Products.PluggableAuthService.interfaces.events.ICredentialsUpdatedEvent",
    "products.pluggableauthservice.interfaces.events.igroupdeletedevent": "https://productspluggableauthservice.readthedocs.io/en/stable/api/events.html#Products.PluggableAuthService.interfaces.events.IGroupDeletedEvent",
    "products.pluggableauthservice.interfaces.events.ipasevent": "https://productspluggableauthservice.readthedocs.io/en/stable/api/events.html#Products.PluggableAuthService.interfaces.events.IPASEvent",
    "products.pluggableauthservice.interfaces.events.iprincipalcreatedevent": "https://productspluggableauthservice.readthedocs.io/en/stable/api/events.html#Products.PluggableAuthService.interfaces.events.IPrincipalCreatedEvent",
    "products.pluggableauthservice.interfaces.events.iprincipaldeletedevent": "https://productspluggableauthservice.readthedocs.io/en/stable/api/events.html#Products.PluggableAuthService.interfaces.events.IPrincipalDeletedEvent",
    "products.pluggableauthservice.interfaces.events.ipropertiesupdatedevent": "https://productspluggableauthservice.readthedocs.io/en/stable/api/events.html#Products.PluggableAuthService.interfaces.events.IPropertiesUpdatedEvent",
    "products.pluggableauthservice.interfaces.events.iuserloggedinevent": "https://productspluggableauthservice.readthedocs.io/en/stable/api/events.html#Products.PluggableAuthService.interfaces.events.IUserLoggedInEvent",
    "products.pluggableauthservice.interfaces.events.iuserloggedoutevent": "https://productspluggableauthservice.readthedocs.io/en/stable/api/events.html#Products.PluggableAuthService.interfaces.events.IUserLoggedOutEvent",
    "products.pluggableauthservice.interfaces.plugins": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html",
    "products.pluggableauthservice.interfaces.plugins.ianonymoususerfactoryplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IAnonymousUserFactoryPlugin",
    "products.pluggableauthservice.interfaces.plugins.iauthenticationplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IAuthenticationPlugin",
    "products.pluggableauthservice.interfaces.plugins.ichallengeplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IChallengePlugin",
    "products.pluggableauthservice.interfaces.plugins.ichallengeprotocolchooser": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IChallengeProtocolChooser",
    "products.pluggableauthservice.interfaces.plugins.icredentialsresetplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.ICredentialsResetPlugin",
    "products.pluggableauthservice.interfaces.plugins.icredentialsupdateplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.ICredentialsUpdatePlugin",
    "products.pluggableauthservice.interfaces.plugins.iextractionplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IExtractionPlugin",
    "products.pluggableauthservice.interfaces.plugins.igroupenumerationplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IGroupEnumerationPlugin",
    "products.pluggableauthservice.interfaces.plugins.igroupsplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IGroupsPlugin",
    "products.pluggableauthservice.interfaces.plugins.iloginpasswordextractionplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.ILoginPasswordExtractionPlugin",
    "products.pluggableauthservice.interfaces.plugins.iloginpasswordhostextractionplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.ILoginPasswordHostExtractionPlugin",
    "products.pluggableauthservice.interfaces.plugins.inotcompetentplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.INotCompetentPlugin",
    "products.pluggableauthservice.interfaces.plugins.ipropertiesplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IPropertiesPlugin",
    "products.pluggableauthservice.interfaces.plugins.irequesttypesniffer": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IRequestTypeSniffer",
    "products.pluggableauthservice.interfaces.plugins.iroleassignerplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IRoleAssignerPlugin",
    "products.pluggableauthservice.interfaces.plugins.iroleenumerationplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IRoleEnumerationPlugin",
    "products.pluggableauthservice.interfaces.plugins.irolesplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IRolesPlugin",
    "products.pluggableauthservice.interfaces.plugins.iupdateplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IUpdatePlugin",
    "products.pluggableauthservice.interfaces.plugins.iuseradderplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IUserAdderPlugin",
    "products.pluggableauthservice.interfaces.plugins.iuserenumerationplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IUserEnumerationPlugin",
    "products.pluggableauthservice.interfaces.plugins.iuserfactoryplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IUserFactoryPlugin",
    "products.pluggableauthservice.interfaces.plugins.ivalidationplugin": "https://productspluggableauthservice.readthedocs.io/en/stable/api/plugins.html#Products.PluggableAuthService.interfaces.plugins.IValidationPlugin",
    "products.pluggableauthservice.interfaces.propertysheets": "https://productspluggableauthservice.readthedocs.io/en/stable/api/userproperties.html",
    "products.pluggableauthservice.interfaces.propertysheets.ipropertysheet": "https://productspluggableauthservice.readthedocs.io/en/stable/api/userproperties.html#Products.PluggableAuthService.interfaces.propertysheets.IPropertySheet",
    "products.pluggableauthservice.interfaces.request": "https://productspluggableauthservice.readthedocs.io/en/stable/api/request.html",
    "products.pluggableauthservice.interfaces.request.ibrowserrequest": "https://productspluggableauthservice.readthedocs.io/en/stable/api/request.html#Products.PluggableAuthService.interfaces.request.IBrowserRequest",
    "products.pluggableauthservice.interfaces.request.ihttprequest": "https://productspluggableauthservice.readthedocs.io/en/stable/api/request.html#Products.PluggableAuthService.interfaces.request.IHTTPRequest",
    "products.pluggableauthservice.interfaces.request.irequest": "https://productspluggableauthservice.readthedocs.io/en/stable/api/request.html#Products.PluggableAuthService.interfaces.request.IRequest",
    "products.pluggableauthservice.interfaces.request.iwebdavrequest": "https://productspluggableauthservice.readthedocs.io/en/stable/api/request.html#Products.PluggableAuthService.interfaces.request.IWebDAVRequest",
    "products.pluggableauthservice.interfaces.request.ixmlrpcrequest": "https://productspluggableauthservice.readthedocs.io/en/stable/api/request.html#Products.PluggableAuthService.interfaces.request.IXMLRPCRequest",
}
