VERSION = "0.7.2"

# fmt: off
MAPPING = {
    "prometheus_api_client": "https://prometheus-api-client-python.readthedocs.io/en/latest/",
    "prometheus_api_client.exceptions": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#module-prometheus_api_client.exceptions",
    "prometheus_api_client.exceptions.metricvalueconversionerror": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.exceptions.MetricValueConversionError",
    "prometheus_api_client.exceptions.prometheusapiclientexception": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.exceptions.PrometheusApiClientException",
    "prometheus_api_client.metric": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#module-prometheus_api_client.metric",
    "prometheus_api_client.metric.metric": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.metric.Metric",
    "prometheus_api_client.metric.metric.__add__": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.metric.Metric.__add__",
    "prometheus_api_client.metric.metric.__eq__": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.metric.Metric.__eq__",
    "prometheus_api_client.metric.metric.__str__": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.metric.Metric.__str__",
    "prometheus_api_client.metric.metric.plot": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.metric.Metric.plot",
    "prometheus_api_client.metric.metric.show": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.metric.Metric.show",
    "prometheus_api_client.metric_range_df": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#module-prometheus_api_client.metric_range_df",
    "prometheus_api_client.metric_range_df.metricrangedataframe": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.metric_range_df.MetricRangeDataFrame",
    "prometheus_api_client.metric_snapshot_df": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#module-prometheus_api_client.metric_snapshot_df",
    "prometheus_api_client.metric_snapshot_df.metricsnapshotdataframe": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.metric_snapshot_df.MetricSnapshotDataFrame",
    "prometheus_api_client.metrics_list": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#module-prometheus_api_client.metrics_list",
    "prometheus_api_client.metrics_list.metricslist": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.metrics_list.MetricsList",
    "prometheus_api_client.prometheus_connect": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#module-prometheus_api_client.prometheus_connect",
    "prometheus_api_client.prometheus_connect.prometheusconnect": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect",
    "prometheus_api_client.prometheus_connect.prometheusconnect.all_metrics": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.all_metrics",
    "prometheus_api_client.prometheus_connect.prometheusconnect.check_prometheus_connection": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.check_prometheus_connection",
    "prometheus_api_client.prometheus_connect.prometheusconnect.close": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.close",
    "prometheus_api_client.prometheus_connect.prometheusconnect.custom_query": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.custom_query",
    "prometheus_api_client.prometheus_connect.prometheusconnect.custom_query_range": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.custom_query_range",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_current_metric_value": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_current_metric_value",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_label_names": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_label_names",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_label_values": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_label_values",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_metric_aggregation": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_metric_aggregation",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_metric_metadata": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_metric_metadata",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_metric_range_data": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_metric_range_data",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_scrape_pools": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_scrape_pools",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_series": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_series",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_target_metadata": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_target_metadata",
    "prometheus_api_client.prometheus_connect.prometheusconnect.get_targets": "https://prometheus-api-client-python.readthedocs.io/en/latest/source/prometheus_api_client.html#prometheus_api_client.prometheus_connect.PrometheusConnect.get_targets",
}
