VERSION = "1.28.3"

# fmt: off
MAPPING = {
    "proto": "https://googleapis.dev/python/proto-plus/latest/",
    "proto.datetime_helpers": "https://googleapis.dev/python/proto-plus/latest/reference/datetime_helpers.html#module-proto.datetime_helpers",
    "proto.datetime_helpers.datetimewithnanoseconds": "https://googleapis.dev/python/proto-plus/latest/reference/datetime_helpers.html#proto.datetime_helpers.DatetimeWithNanoseconds",
    "proto.datetime_helpers.datetimewithnanoseconds.from_rfc3339": "https://googleapis.dev/python/proto-plus/latest/reference/datetime_helpers.html#proto.datetime_helpers.DatetimeWithNanoseconds.from_rfc3339",
    "proto.datetime_helpers.datetimewithnanoseconds.from_timestamp_pb": "https://googleapis.dev/python/proto-plus/latest/reference/datetime_helpers.html#proto.datetime_helpers.DatetimeWithNanoseconds.from_timestamp_pb",
    "proto.datetime_helpers.datetimewithnanoseconds.nanosecond": "https://googleapis.dev/python/proto-plus/latest/reference/datetime_helpers.html#proto.datetime_helpers.DatetimeWithNanoseconds.nanosecond",
    "proto.datetime_helpers.datetimewithnanoseconds.replace": "https://googleapis.dev/python/proto-plus/latest/reference/datetime_helpers.html#proto.datetime_helpers.DatetimeWithNanoseconds.replace",
    "proto.datetime_helpers.datetimewithnanoseconds.rfc3339": "https://googleapis.dev/python/proto-plus/latest/reference/datetime_helpers.html#proto.datetime_helpers.DatetimeWithNanoseconds.rfc3339",
    "proto.datetime_helpers.datetimewithnanoseconds.timestamp_pb": "https://googleapis.dev/python/proto-plus/latest/reference/datetime_helpers.html#proto.datetime_helpers.DatetimeWithNanoseconds.timestamp_pb",
    "proto.enums": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#module-proto.enums",
    "proto.enums.enum": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.enums.Enum",
    "proto.enums.protoenummeta": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.enums.ProtoEnumMeta",
    "proto.fields": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#module-proto.fields",
    "proto.fields.field": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.fields.Field",
    "proto.fields.field.descriptor": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.fields.Field.descriptor",
    "proto.fields.field.name": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.fields.Field.name",
    "proto.fields.field.package": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.fields.Field.package",
    "proto.fields.field.pb_type": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.fields.Field.pb_type",
    "proto.fields.mapfield": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.fields.MapField",
    "proto.fields.repeatedfield": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.fields.RepeatedField",
    "proto.marshal": "https://googleapis.dev/python/proto-plus/latest/reference/marshal.html#module-proto.marshal",
    "proto.marshal.marshal": "https://googleapis.dev/python/proto-plus/latest/reference/marshal.html",
    "proto.marshal.Marshal": "https://googleapis.dev/python/proto-plus/latest/reference/marshal.html#proto.marshal.Marshal",
    "proto.marshal.marshal.marshal": "https://googleapis.dev/python/proto-plus/latest/reference/marshal.html#proto.marshal.Marshal",
    "proto.message": "https://googleapis.dev/python/proto-plus/latest/reference/message.html",
    "proto.message.message": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.message.Message",
    "proto.message.message.copy_from": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.message.Message.copy_from",
    "proto.message.message.deserialize": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.message.Message.deserialize",
    "proto.message.message.from_json": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.message.Message.from_json",
    "proto.message.message.pb": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.message.Message.pb",
    "proto.message.message.serialize": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.message.Message.serialize",
    "proto.message.message.to_dict": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.message.Message.to_dict",
    "proto.message.message.to_json": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.message.Message.to_json",
    "proto.message.message.wrap": "https://googleapis.dev/python/proto-plus/latest/reference/message.html#proto.message.Message.wrap",
}
