VERSION = "0.7.0"

# fmt: off
MAPPING = {
    "pyclip": "https://pyclip.readthedocs.io/en/stable/",
    "pyclip.__init__": "https://pyclip.readthedocs.io/en/stable/api/index.html#module-pyclip.__init__",
    "pyclip.__init__.clear": "https://pyclip.readthedocs.io/en/stable/api/index.html#pyclip.__init__.clear",
    "pyclip.__init__.copy": "https://pyclip.readthedocs.io/en/stable/api/index.html#pyclip.__init__.copy",
    "pyclip.__init__.paste": "https://pyclip.readthedocs.io/en/stable/api/index.html#pyclip.__init__.paste",
    "pyclip.__init__.wrapif": "https://pyclip.readthedocs.io/en/stable/api/index.html#pyclip.__init__.wrapif",
    "pyclip.base": "https://pyclip.readthedocs.io/en/stable/api/base.html#module-pyclip.base",
    "pyclip.base.clipboardbase": "https://pyclip.readthedocs.io/en/stable/api/base.html#pyclip.base.ClipboardBase",
    "pyclip.base.clipboardbase.clear": "https://pyclip.readthedocs.io/en/stable/api/base.html#pyclip.base.ClipboardBase.clear",
    "pyclip.base.clipboardbase.copy": "https://pyclip.readthedocs.io/en/stable/api/base.html#pyclip.base.ClipboardBase.copy",
    "pyclip.base.clipboardbase.paste": "https://pyclip.readthedocs.io/en/stable/api/base.html#pyclip.base.ClipboardBase.paste",
    "pyclip.base.clipboardexception": "https://pyclip.readthedocs.io/en/stable/api/base.html#pyclip.base.ClipboardException",
    "pyclip.base.clipboardsetupexception": "https://pyclip.readthedocs.io/en/stable/api/base.html#pyclip.base.ClipboardSetupException",
    "pyclip.cli": "https://pyclip.readthedocs.io/en/stable/api/cli.html#module-pyclip.cli",
    "pyclip.cli.main": "https://pyclip.readthedocs.io/en/stable/api/cli.html#pyclip.cli.main",
    "pyclip.macos_clip": "https://pyclip.readthedocs.io/en/stable/api/macos_clip.html#module-pyclip.macos_clip",
    "pyclip.macos_clip.macosclip": "https://pyclip.readthedocs.io/en/stable/api/macos_clip.html#pyclip.macos_clip.MacOSClip",
    "pyclip.macos_clip.macosclip.clear": "https://pyclip.readthedocs.io/en/stable/api/macos_clip.html#pyclip.macos_clip.MacOSClip.clear",
    "pyclip.macos_clip.macosclip.copy": "https://pyclip.readthedocs.io/en/stable/api/macos_clip.html#pyclip.macos_clip.MacOSClip.copy",
    "pyclip.macos_clip.macosclip.paste": "https://pyclip.readthedocs.io/en/stable/api/macos_clip.html#pyclip.macos_clip.MacOSClip.paste",
    "pyclip.util": "https://pyclip.readthedocs.io/en/stable/api/util.html#module-pyclip.util",
    "pyclip.util.detect_clipboard": "https://pyclip.readthedocs.io/en/stable/api/util.html#pyclip.util.detect_clipboard",
    "pyclip.win_clip": "https://pyclip.readthedocs.io/en/stable/api/win_clip.html#module-pyclip.win_clip",
    "pyclip.win_clip.clipboardnottextformatexception": "https://pyclip.readthedocs.io/en/stable/api/win_clip.html#pyclip.win_clip.ClipboardNotTextFormatException",
    "pyclip.win_clip.unparsableclipboardformatexception": "https://pyclip.readthedocs.io/en/stable/api/win_clip.html#pyclip.win_clip.UnparsableClipboardFormatException",
    "pyclip.win_clip.windowsclipboard": "https://pyclip.readthedocs.io/en/stable/api/win_clip.html#pyclip.win_clip.WindowsClipboard",
    "pyclip.win_clip.windowsclipboard.clear": "https://pyclip.readthedocs.io/en/stable/api/win_clip.html#pyclip.win_clip.WindowsClipboard.clear",
    "pyclip.win_clip.windowsclipboard.copy": "https://pyclip.readthedocs.io/en/stable/api/win_clip.html#pyclip.win_clip.WindowsClipboard.copy",
    "pyclip.win_clip.windowsclipboard.paste": "https://pyclip.readthedocs.io/en/stable/api/win_clip.html#pyclip.win_clip.WindowsClipboard.paste",
    "pyclip.xclip_clip": "https://pyclip.readthedocs.io/en/stable/api/xclip_clip.html#module-pyclip.xclip_clip",
    "pyclip.xclip_clip.xclipclipboard": "https://pyclip.readthedocs.io/en/stable/api/xclip_clip.html#pyclip.xclip_clip.XclipClipboard",
    "pyclip.xclip_clip.xclipclipboard.clear": "https://pyclip.readthedocs.io/en/stable/api/xclip_clip.html#pyclip.xclip_clip.XclipClipboard.clear",
    "pyclip.xclip_clip.xclipclipboard.copy": "https://pyclip.readthedocs.io/en/stable/api/xclip_clip.html#pyclip.xclip_clip.XclipClipboard.copy",
    "pyclip.xclip_clip.xclipclipboard.paste": "https://pyclip.readthedocs.io/en/stable/api/xclip_clip.html#pyclip.xclip_clip.XclipClipboard.paste",
}
