VERSION = "0.2.0"

# fmt: off
MAPPING = {
    "pyclothoids": "https://pyclothoids.readthedocs.io/en/latest/",
    "pyclothoids.clothoid": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html",
    "pyclothoids.Clothoid": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid",
    "pyclothoids.clothoid.closestpoint": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.ClosestPoint",
    "pyclothoids.clothoid.closestpointarclength": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.ClosestPointArcLength",
    "pyclothoids.clothoid.clothoid": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid",
    "pyclothoids.clothoid.distance": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Distance",
    "pyclothoids.clothoid.dk": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.dk",
    "pyclothoids.clothoid.flip": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Flip",
    "pyclothoids.clothoid.forward": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Forward",
    "pyclothoids.clothoid.g1hermite": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.G1Hermite",
    "pyclothoids.clothoid.intersectionarclengths": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.IntersectionArcLengths",
    "pyclothoids.clothoid.intersectionpoints": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.IntersectionPoints",
    "pyclothoids.clothoid.kappaend": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.KappaEnd",
    "pyclothoids.clothoid.kappastart": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.KappaStart",
    "pyclothoids.clothoid.length": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.length",
    "pyclothoids.clothoid.parameters": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Parameters",
    "pyclothoids.clothoid.projectpointontoclothoid": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.ProjectPointOntoClothoid",
    "pyclothoids.clothoid.reverse": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Reverse",
    "pyclothoids.clothoid.rotate": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Rotate",
    "pyclothoids.clothoid.samplexy": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.SampleXY",
    "pyclothoids.clothoid.scale": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Scale",
    "pyclothoids.clothoid.setupprojectioncache": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.SetupProjectionCache",
    "pyclothoids.clothoid.standardparams": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.StandardParams",
    "pyclothoids.clothoid.theta": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Theta",
    "pyclothoids.clothoid.thetad": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.ThetaD",
    "pyclothoids.clothoid.thetadd": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.ThetaDD",
    "pyclothoids.clothoid.thetaddd": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.ThetaDDD",
    "pyclothoids.clothoid.thetaend": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.ThetaEnd",
    "pyclothoids.clothoid.thetastart": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.ThetaStart",
    "pyclothoids.clothoid.translate": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Translate",
    "pyclothoids.clothoid.trim": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Trim",
    "pyclothoids.clothoid.x": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.X",
    "pyclothoids.clothoid.xd": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.XD",
    "pyclothoids.clothoid.xdd": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.XDD",
    "pyclothoids.clothoid.xddd": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.XDDD",
    "pyclothoids.clothoid.xend": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.XEnd",
    "pyclothoids.clothoid.xstart": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.XStart",
    "pyclothoids.clothoid.y": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.Y",
    "pyclothoids.clothoid.yd": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.YD",
    "pyclothoids.clothoid.ydd": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.YDD",
    "pyclothoids.clothoid.yddd": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.YDDD",
    "pyclothoids.clothoid.yend": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.YEnd",
    "pyclothoids.clothoid.ystart": "https://pyclothoids.readthedocs.io/en/latest/clothoid.html#pyclothoids.Clothoid.YStart",
    "pyclothoids.solveg2": "https://pyclothoids.readthedocs.io/en/latest/solveg2.html#pyclothoids.SolveG2",
}
