VERSION = "3.1.0"

# fmt: off
MAPPING = {
    "pydantic_mongo": "https://pydantic-mongo.readthedocs.io/en/stable/",
    "pydantic_mongo.abstract_repository": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html",
    "pydantic_mongo.abstract_repository.abstractrepository": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository",
    "pydantic_mongo.abstract_repository.abstractrepository.meta": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.Meta",
    "pydantic_mongo.abstractrepository": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository",
    "pydantic_mongo.abstractrepository.delete": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.delete",
    "pydantic_mongo.abstractrepository.delete_by_id": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.delete_by_id",
    "pydantic_mongo.abstractrepository.find_by": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.find_by",
    "pydantic_mongo.abstractrepository.find_by_with_output_type": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.find_by_with_output_type",
    "pydantic_mongo.abstractrepository.find_one_by": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.find_one_by",
    "pydantic_mongo.abstractrepository.find_one_by_id": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.find_one_by_id",
    "pydantic_mongo.abstractrepository.get_collection": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.get_collection",
    "pydantic_mongo.abstractrepository.meta": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.Meta",
    "pydantic_mongo.abstractrepository.meta.collection_name": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.Meta.collection_name",
    "pydantic_mongo.abstractrepository.paginate": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.paginate",
    "pydantic_mongo.abstractrepository.paginate_with_output_type": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.paginate_with_output_type",
    "pydantic_mongo.abstractrepository.save": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.save",
    "pydantic_mongo.abstractrepository.save_many": "https://pydantic-mongo.readthedocs.io/en/stable/api/abstract_repository.html#pydantic_mongo.AbstractRepository.save_many",
    "pydantic_mongo.async_abstract_repository": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html",
    "pydantic_mongo.async_abstract_repository.asyncabstractrepository": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository",
    "pydantic_mongo.async_abstract_repository.asyncabstractrepository.meta": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.Meta",
    "pydantic_mongo.asyncabstractrepository": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository",
    "pydantic_mongo.asyncabstractrepository.delete": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.delete",
    "pydantic_mongo.asyncabstractrepository.delete_by_id": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.delete_by_id",
    "pydantic_mongo.asyncabstractrepository.find_by": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.find_by",
    "pydantic_mongo.asyncabstractrepository.find_by_with_output_type": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.find_by_with_output_type",
    "pydantic_mongo.asyncabstractrepository.find_one_by": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.find_one_by",
    "pydantic_mongo.asyncabstractrepository.find_one_by_id": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.find_one_by_id",
    "pydantic_mongo.asyncabstractrepository.get_collection": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.get_collection",
    "pydantic_mongo.asyncabstractrepository.meta": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.Meta",
    "pydantic_mongo.asyncabstractrepository.meta.collection_name": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.Meta.collection_name",
    "pydantic_mongo.asyncabstractrepository.paginate": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.paginate",
    "pydantic_mongo.asyncabstractrepository.paginate_with_output_type": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.paginate_with_output_type",
    "pydantic_mongo.asyncabstractrepository.save": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.save",
    "pydantic_mongo.asyncabstractrepository.save_many": "https://pydantic-mongo.readthedocs.io/en/stable/api/async_abstract_repository.html#pydantic_mongo.AsyncAbstractRepository.save_many",
    "pydantic_mongo.fields": "https://pydantic-mongo.readthedocs.io/en/stable/api/object_id_annotation.html",
    "pydantic_mongo.fields.objectidannotation": "https://pydantic-mongo.readthedocs.io/en/stable/api/object_id_annotation.html#pydantic_mongo.ObjectIdAnnotation",
    "pydantic_mongo.objectidannotation": "https://pydantic-mongo.readthedocs.io/en/stable/api/object_id_annotation.html#pydantic_mongo.ObjectIdAnnotation",
    "pydantic_mongo.objectidannotation.validate": "https://pydantic-mongo.readthedocs.io/en/stable/api/object_id_annotation.html#pydantic_mongo.ObjectIdAnnotation.validate",
    "pydantic_mongo.pydanticobjectid": "https://pydantic-mongo.readthedocs.io/en/stable/api/pydantic_object_id.html#pydantic_mongo.PydanticObjectId",
}
