VERSION = "0.10.0"

# fmt: off
MAPPING = {
    "pydantic_argparse": "https://pydantic-argparse.supimdos.com/",
    "pydantic_argparse.argparse.actions": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/actions/",
    "pydantic_argparse.argparse.actions.booleanoptionalaction": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/actions/#pydantic_argparse.argparse.actions.BooleanOptionalAction",
    "pydantic_argparse.argparse.actions.booleanoptionalaction.__call__": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/actions/#pydantic_argparse.argparse.actions.BooleanOptionalAction.__call__",
    "pydantic_argparse.argparse.actions.booleanoptionalaction.__init__": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/actions/#pydantic_argparse.argparse.actions.BooleanOptionalAction.__init__",
    "pydantic_argparse.argparse.actions.booleanoptionalaction.format_usage": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/actions/#pydantic_argparse.argparse.actions.BooleanOptionalAction.format_usage",
    "pydantic_argparse.argparse.actions.subparsersaction": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/actions/#pydantic_argparse.argparse.actions.SubParsersAction",
    "pydantic_argparse.argparse.actions.subparsersaction.__call__": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/actions/#pydantic_argparse.argparse.actions.SubParsersAction.__call__",
    "pydantic_argparse.argparse.parser": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/parser/",
    "pydantic_argparse.argparse.parser.argumentparser": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/parser/#pydantic_argparse.argparse.parser.ArgumentParser",
    "pydantic_argparse.argparse.parser.argumentparser.__init__": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/parser/#pydantic_argparse.argparse.parser.ArgumentParser.__init__",
    "pydantic_argparse.argparse.parser.argumentparser.add_argument": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/parser/#pydantic_argparse.argparse.parser.ArgumentParser.add_argument",
    "pydantic_argparse.argparse.parser.argumentparser.error": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/parser/#pydantic_argparse.argparse.parser.ArgumentParser.error",
    "pydantic_argparse.argparse.parser.argumentparser.parse_typed_args": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/argparse/parser/#pydantic_argparse.argparse.parser.ArgumentParser.parse_typed_args",
    "pydantic_argparse.parsers.boolean": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/boolean/",
    "pydantic_argparse.parsers.boolean.parse_field": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/boolean/#pydantic_argparse.parsers.boolean.parse_field",
    "pydantic_argparse.parsers.boolean.should_parse": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/boolean/#pydantic_argparse.parsers.boolean.should_parse",
    "pydantic_argparse.parsers.command": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/command/",
    "pydantic_argparse.parsers.command.parse_field": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/command/#pydantic_argparse.parsers.command.parse_field",
    "pydantic_argparse.parsers.command.should_parse": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/command/#pydantic_argparse.parsers.command.should_parse",
    "pydantic_argparse.parsers.container": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/container/",
    "pydantic_argparse.parsers.container.parse_field": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/container/#pydantic_argparse.parsers.container.parse_field",
    "pydantic_argparse.parsers.container.should_parse": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/container/#pydantic_argparse.parsers.container.should_parse",
    "pydantic_argparse.parsers.enum": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/enum/",
    "pydantic_argparse.parsers.enum.parse_field": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/enum/#pydantic_argparse.parsers.enum.parse_field",
    "pydantic_argparse.parsers.enum.should_parse": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/enum/#pydantic_argparse.parsers.enum.should_parse",
    "pydantic_argparse.parsers.literal": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/literal/",
    "pydantic_argparse.parsers.literal.parse_field": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/literal/#pydantic_argparse.parsers.literal.parse_field",
    "pydantic_argparse.parsers.literal.should_parse": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/literal/#pydantic_argparse.parsers.literal.should_parse",
    "pydantic_argparse.parsers.mapping": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/mapping/",
    "pydantic_argparse.parsers.mapping.parse_field": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/mapping/#pydantic_argparse.parsers.mapping.parse_field",
    "pydantic_argparse.parsers.mapping.should_parse": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/mapping/#pydantic_argparse.parsers.mapping.should_parse",
    "pydantic_argparse.parsers.standard": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/standard/",
    "pydantic_argparse.parsers.standard.parse_field": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/parsers/standard/#pydantic_argparse.parsers.standard.parse_field",
    "pydantic_argparse.utils.arguments": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/arguments/",
    "pydantic_argparse.utils.arguments.description": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/arguments/#pydantic_argparse.utils.arguments.description",
    "pydantic_argparse.utils.arguments.names": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/arguments/#pydantic_argparse.utils.arguments.names",
    "pydantic_argparse.utils.errors": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/errors/",
    "pydantic_argparse.utils.errors.format": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/errors/#pydantic_argparse.utils.errors.format",
    "pydantic_argparse.utils.namespaces": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/namespaces/",
    "pydantic_argparse.utils.namespaces.to_dict": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/namespaces/#pydantic_argparse.utils.namespaces.to_dict",
    "pydantic_argparse.utils.pydantic": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/pydantic/",
    "pydantic_argparse.utils.pydantic.as_validator": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/pydantic/#pydantic_argparse.utils.pydantic.as_validator",
    "pydantic_argparse.utils.pydantic.model_with_validators": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/pydantic/#pydantic_argparse.utils.pydantic.model_with_validators",
    "pydantic_argparse.utils.pydantic.update_validators": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/pydantic/#pydantic_argparse.utils.pydantic.update_validators",
    "pydantic_argparse.utils.types": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/types/",
    "pydantic_argparse.utils.types.is_field_a": "https://pydantic-argparse.supimdos.com/reference/pydantic_argparse/utils/types/#pydantic_argparse.utils.types.is_field_a",
}
