VERSION = "0.3.0"

# fmt: off
MAPPING = {
    "pyfortiapi": "https://pyfortiapi.readthedocs.io/en/stable/",
    "pyfortiapi.fortigate": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate",
    "pyfortiapi.fortigate.create_address_group": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.create_address_group",
    "pyfortiapi.fortigate.create_firewall_address": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.create_firewall_address",
    "pyfortiapi.fortigate.create_firewall_policy": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.create_firewall_policy",
    "pyfortiapi.fortigate.create_firewall_service": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.create_firewall_service",
    "pyfortiapi.fortigate.create_service_category": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.create_service_category",
    "pyfortiapi.fortigate.create_service_group": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.create_service_group",
    "pyfortiapi.fortigate.create_snmp_community": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.create_snmp_community",
    "pyfortiapi.fortigate.delete": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.delete",
    "pyfortiapi.fortigate.delete_address_group": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.delete_address_group",
    "pyfortiapi.fortigate.delete_firewall_address": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.delete_firewall_address",
    "pyfortiapi.fortigate.delete_firewall_policy": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.delete_firewall_policy",
    "pyfortiapi.fortigate.delete_firewall_service": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.delete_firewall_service",
    "pyfortiapi.fortigate.delete_service_category": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.delete_service_category",
    "pyfortiapi.fortigate.delete_service_group": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.delete_service_group",
    "pyfortiapi.fortigate.delete_snmp_community": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.delete_snmp_community",
    "pyfortiapi.fortigate.does_exist": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.does_exist",
    "pyfortiapi.fortigate.get": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.get",
    "pyfortiapi.fortigate.get_address_group": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.get_address_group",
    "pyfortiapi.fortigate.get_firewall_address": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.get_firewall_address",
    "pyfortiapi.fortigate.get_firewall_policy": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.get_firewall_policy",
    "pyfortiapi.fortigate.get_firewall_service": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.get_firewall_service",
    "pyfortiapi.fortigate.get_internet_services": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.get_internet_services",
    "pyfortiapi.fortigate.get_service_category": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.get_service_category",
    "pyfortiapi.fortigate.get_service_group": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.get_service_group",
    "pyfortiapi.fortigate.get_snmp_community": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.get_snmp_community",
    "pyfortiapi.fortigate.login": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.login",
    "pyfortiapi.fortigate.logout": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.logout",
    "pyfortiapi.fortigate.move_firewall_policy": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.move_firewall_policy",
    "pyfortiapi.fortigate.post": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.post",
    "pyfortiapi.fortigate.put": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.put",
    "pyfortiapi.fortigate.update_address_group": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.update_address_group",
    "pyfortiapi.fortigate.update_firewall_address": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.update_firewall_address",
    "pyfortiapi.fortigate.update_firewall_policy": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.update_firewall_policy",
    "pyfortiapi.fortigate.update_firewall_service": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.update_firewall_service",
    "pyfortiapi.fortigate.update_service_category": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.update_service_category",
    "pyfortiapi.fortigate.update_service_group": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.update_service_group",
    "pyfortiapi.fortigate.update_snmp_community": "https://pyfortiapi.readthedocs.io/en/stable/code.html#pyfortiapi.FortiGate.update_snmp_community",
}
