VERSION = "0.3.4"

# fmt: off
MAPPING = {
    "pyfume": "https://pyfume.readthedocs.io/en/latest/",
    "pyfume.buildtakagisugeno": "https://pyfume.readthedocs.io/en/latest/BTS.html#module-pyfume.BuildTakagiSugeno",
    "pyfume.buildtakagisugeno.buildtsfis": "https://pyfume.readthedocs.io/en/latest/BTS.html#pyfume.BuildTakagiSugeno.BuildTSFIS",
    "pyfume.clustering": "https://pyfume.readthedocs.io/en/latest/Clustering.html#module-pyfume.Clustering",
    "pyfume.clustering.clusterer": "https://pyfume.readthedocs.io/en/latest/Clustering.html#pyfume.Clustering.Clusterer",
    "pyfume.clustering.clusterer.cluster": "https://pyfume.readthedocs.io/en/latest/Clustering.html#pyfume.Clustering.Clusterer.cluster",
    "pyfume.estimateantecendentset": "https://pyfume.readthedocs.io/en/latest/AE.html#module-pyfume.EstimateAntecendentSet",
    "pyfume.estimateantecendentset.antecedentestimator": "https://pyfume.readthedocs.io/en/latest/AE.html#pyfume.EstimateAntecendentSet.AntecedentEstimator",
    "pyfume.estimateantecendentset.antecedentestimator.determinemf": "https://pyfume.readthedocs.io/en/latest/AE.html#pyfume.EstimateAntecendentSet.AntecedentEstimator.determineMF",
    "pyfume.estimateconsequentparameters": "https://pyfume.readthedocs.io/en/latest/CP.html#module-pyfume.EstimateConsequentParameters",
    "pyfume.estimateconsequentparameters.consequentestimator": "https://pyfume.readthedocs.io/en/latest/CP.html#pyfume.EstimateConsequentParameters.ConsequentEstimator",
    "pyfume.estimateconsequentparameters.consequentestimator.suglms": "https://pyfume.readthedocs.io/en/latest/CP.html#pyfume.EstimateConsequentParameters.ConsequentEstimator.suglms",
    "pyfume.estimateconsequentparameters.consequentestimator.zero_order": "https://pyfume.readthedocs.io/en/latest/CP.html#pyfume.EstimateConsequentParameters.ConsequentEstimator.zero_order",
    "pyfume.featureselection": "https://pyfume.readthedocs.io/en/latest/FS.html#module-pyfume.FeatureSelection",
    "pyfume.featureselection.featureselector": "https://pyfume.readthedocs.io/en/latest/FS.html#pyfume.FeatureSelection.FeatureSelector",
    "pyfume.featureselection.featureselector.fst_pso_feature_selection": "https://pyfume.readthedocs.io/en/latest/FS.html#pyfume.FeatureSelection.FeatureSelector.fst_pso_feature_selection",
    "pyfume.featureselection.featureselector.log_wrapper": "https://pyfume.readthedocs.io/en/latest/FS.html#pyfume.FeatureSelection.FeatureSelector.log_wrapper",
    "pyfume.featureselection.featureselector.wrapper": "https://pyfume.readthedocs.io/en/latest/FS.html#pyfume.FeatureSelection.FeatureSelector.wrapper",
    "pyfume.firestrengthcalculator": "https://pyfume.readthedocs.io/en/latest/FSC.html#module-pyfume.FireStrengthCalculator",
    "pyfume.firestrengthcalculator.firestrengthcalculator": "https://pyfume.readthedocs.io/en/latest/FSC.html#pyfume.FireStrengthCalculator.FireStrengthCalculator",
    "pyfume.firestrengthcalculator.firestrengthcalculator.calculate_fire_strength": "https://pyfume.readthedocs.io/en/latest/FSC.html#pyfume.FireStrengthCalculator.FireStrengthCalculator.calculate_fire_strength",
    "pyfume.loaddata": "https://pyfume.readthedocs.io/en/latest/DL.html#module-pyfume.LoadData",
    "pyfume.loaddata.dataloader": "https://pyfume.readthedocs.io/en/latest/DL.html#pyfume.LoadData.DataLoader",
    "pyfume.pyfume": "https://pyfume.readthedocs.io/en/latest/pyf.html#module-pyfume.pyfume",
    "pyfume.pyfume.pyfume": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME",
    "pyfume.pyfume.pyfume.calculate_error": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.calculate_error",
    "pyfume.pyfume.pyfume.denormalize_values": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.denormalize_values",
    "pyfume.pyfume.pyfume.get_cluster_centers": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.get_cluster_centers",
    "pyfume.pyfume.pyfume.get_data": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.get_data",
    "pyfume.pyfume.pyfume.get_firing_strengths": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.get_firing_strengths",
    "pyfume.pyfume.pyfume.get_fold_indices": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.get_fold_indices",
    "pyfume.pyfume.pyfume.get_model": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.get_model",
    "pyfume.pyfume.pyfume.get_performance_per_fold": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.get_performance_per_fold",
    "pyfume.pyfume.pyfume.normalize_values": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.normalize_values",
    "pyfume.pyfume.pyfume.predict_label": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.predict_label",
    "pyfume.pyfume.pyfume.predict_test_data": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.predict_test_data",
    "pyfume.pyfume.pyfume.test_model": "https://pyfume.readthedocs.io/en/latest/pyf.html#pyfume.pyfume.pyFUME.test_model",
    "pyfume.sampler": "https://pyfume.readthedocs.io/en/latest/Sampl.html#module-pyfume.Sampler",
    "pyfume.sampler.sampler": "https://pyfume.readthedocs.io/en/latest/Sampl.html#pyfume.Sampler.Sampler",
    "pyfume.sampler.sampler.oversample": "https://pyfume.readthedocs.io/en/latest/Sampl.html#pyfume.Sampler.Sampler.oversample",
    "pyfume.splitter": "https://pyfume.readthedocs.io/en/latest/DS.html#module-pyfume.Splitter",
    "pyfume.splitter.datasplitter": "https://pyfume.readthedocs.io/en/latest/DS.html#pyfume.Splitter.DataSplitter",
    "pyfume.splitter.datasplitter.holdout": "https://pyfume.readthedocs.io/en/latest/DS.html#pyfume.Splitter.DataSplitter.holdout",
    "pyfume.splitter.datasplitter.kfold": "https://pyfume.readthedocs.io/en/latest/DS.html#pyfume.Splitter.DataSplitter.kfold",
    "pyfume.tester": "https://pyfume.readthedocs.io/en/latest/tester.html#module-pyfume.Tester",
    "pyfume.tester.sugenofistester": "https://pyfume.readthedocs.io/en/latest/tester.html#pyfume.Tester.SugenoFISTester",
    "pyfume.tester.sugenofistester.calculate_mae": "https://pyfume.readthedocs.io/en/latest/tester.html#pyfume.Tester.SugenoFISTester.calculate_MAE",
    "pyfume.tester.sugenofistester.calculate_mape": "https://pyfume.readthedocs.io/en/latest/tester.html#pyfume.Tester.SugenoFISTester.calculate_MAPE",
    "pyfume.tester.sugenofistester.calculate_mse": "https://pyfume.readthedocs.io/en/latest/tester.html#pyfume.Tester.SugenoFISTester.calculate_MSE",
    "pyfume.tester.sugenofistester.calculate_performance": "https://pyfume.readthedocs.io/en/latest/tester.html#pyfume.Tester.SugenoFISTester.calculate_performance",
    "pyfume.tester.sugenofistester.calculate_rmse": "https://pyfume.readthedocs.io/en/latest/tester.html#pyfume.Tester.SugenoFISTester.calculate_RMSE",
    "pyfume.tester.sugenofistester.predict": "https://pyfume.readthedocs.io/en/latest/tester.html#pyfume.Tester.SugenoFISTester.predict",
}
