VERSION = "0.4.0"

# fmt: off
MAPPING = {
    "pygeofilter": "https://pygeofilter.readthedocs.io/en/stable/",
    "pygeofilter.backends": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.html#module-pygeofilter.backends",
    "pygeofilter.backends.geopandas": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#module-pygeofilter.backends.geopandas",
    "pygeofilter.backends.geopandas.filters": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#module-pygeofilter.backends.geopandas.filters",
    "pygeofilter.backends.geopandas.filters.arithmetic": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.arithmetic",
    "pygeofilter.backends.geopandas.filters.attribute": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.attribute",
    "pygeofilter.backends.geopandas.filters.bbox": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.bbox",
    "pygeofilter.backends.geopandas.filters.between": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.between",
    "pygeofilter.backends.geopandas.filters.combine": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.combine",
    "pygeofilter.backends.geopandas.filters.compare": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.compare",
    "pygeofilter.backends.geopandas.filters.contains": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.contains",
    "pygeofilter.backends.geopandas.filters.like": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.like",
    "pygeofilter.backends.geopandas.filters.negate": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.negate",
    "pygeofilter.backends.geopandas.filters.null": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.null",
    "pygeofilter.backends.geopandas.filters.spatial": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.spatial",
    "pygeofilter.backends.geopandas.filters.temporal": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.geopandas.html#pygeofilter.backends.geopandas.filters.temporal",
    "pygeofilter.backends.native": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.backends.native.html#module-pygeofilter.backends.native",
    "pygeofilter.parsers": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#module-pygeofilter.parsers",
    "pygeofilter.parsers.fes": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.fes.html#module-pygeofilter.parsers.fes",
    "pygeofilter.parsers.iso8601": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#module-pygeofilter.parsers.iso8601",
    "pygeofilter.parsers.iso8601.iso8601transformer": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.iso8601.ISO8601Transformer",
    "pygeofilter.parsers.iso8601.iso8601transformer.datetime": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.iso8601.ISO8601Transformer.DATETIME",
    "pygeofilter.parsers.iso8601.iso8601transformer.duration": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.iso8601.ISO8601Transformer.DURATION",
    "pygeofilter.parsers.wkt": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#module-pygeofilter.parsers.wkt",
    "pygeofilter.parsers.wkt.wkttransformer": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__coordinate": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__coordinate",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__coordinate_list": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__coordinate_list",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__coordinate_list_start": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__coordinate_list_start",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__coordinate_lists": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__coordinate_lists",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__geometry_with_srid": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__geometry_with_srid",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__geometrycollection": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__geometrycollection",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__linestring": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__linestring",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__multilinestring": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__multilinestring",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__multipoint": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__multipoint",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__multipoint_2": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__multipoint_2",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__multipolygon": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__multipolygon",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__number": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__NUMBER",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__point": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__point",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__polygon": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__polygon",
    "pygeofilter.parsers.wkt.wkttransformer.wkt__signed_number": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.parsers.html#pygeofilter.parsers.wkt.WKTTransformer.wkt__SIGNED_NUMBER",
    "pygeofilter.util": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.html#module-pygeofilter.util",
    "pygeofilter.util.like_pattern_to_re": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.html#pygeofilter.util.like_pattern_to_re",
    "pygeofilter.util.like_pattern_to_re_pattern": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.html#pygeofilter.util.like_pattern_to_re_pattern",
    "pygeofilter.util.parse_datetime": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.html#pygeofilter.util.parse_datetime",
    "pygeofilter.util.parse_duration": "https://pygeofilter.readthedocs.io/en/stable/api/pygeofilter.html#pygeofilter.util.parse_duration",
}
