VERSION = "2.1.8"

# fmt: off
MAPPING = {
    "pygrib": "https://jswhit.github.io/pygrib/",
    "pygrib._pygrib": "https://jswhit.github.io/pygrib/api.html",
    "pygrib._pygrib.gribmessage": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage",
    "pygrib._pygrib.index": "https://jswhit.github.io/pygrib/api.html#pygrib.index",
    "pygrib._pygrib.open": "https://jswhit.github.io/pygrib/api.html#pygrib.open",
    "pygrib.fromstring": "https://jswhit.github.io/pygrib/api.html#pygrib.fromstring",
    "pygrib.gaulats": "https://jswhit.github.io/pygrib/api.html#pygrib.gaulats",
    "pygrib.get_definitions_path": "https://jswhit.github.io/pygrib/api.html#pygrib.get_definitions_path",
    "pygrib.gribmessage": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage",
    "pygrib.gribmessage.data": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage.data",
    "pygrib.gribmessage.expand_grid": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage.expand_grid",
    "pygrib.gribmessage.has_key": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage.has_key",
    "pygrib.gribmessage.is_missing": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage.is_missing",
    "pygrib.gribmessage.keys": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage.keys",
    "pygrib.gribmessage.latlons": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage.latlons",
    "pygrib.gribmessage.tostring": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage.tostring",
    "pygrib.gribmessage.valid_key": "https://jswhit.github.io/pygrib/api.html#pygrib.gribmessage.valid_key",
    "pygrib.index": "https://jswhit.github.io/pygrib/api.html#pygrib.index",
    "pygrib.index.close": "https://jswhit.github.io/pygrib/api.html#pygrib.index.close",
    "pygrib.index.select": "https://jswhit.github.io/pygrib/api.html#pygrib.index.select",
    "pygrib.index.write": "https://jswhit.github.io/pygrib/api.html#pygrib.index.write",
    "pygrib.julian_to_datetime": "https://jswhit.github.io/pygrib/api.html#pygrib.julian_to_datetime",
    "pygrib.multi_support_off": "https://jswhit.github.io/pygrib/api.html#pygrib.multi_support_off",
    "pygrib.multi_support_on": "https://jswhit.github.io/pygrib/api.html#pygrib.multi_support_on",
    "pygrib.open": "https://jswhit.github.io/pygrib/api.html#pygrib.open",
    "pygrib.open.close": "https://jswhit.github.io/pygrib/api.html#pygrib.open.close",
    "pygrib.open.message": "https://jswhit.github.io/pygrib/api.html#pygrib.open.message",
    "pygrib.open.read": "https://jswhit.github.io/pygrib/api.html#pygrib.open.read",
    "pygrib.open.readline": "https://jswhit.github.io/pygrib/api.html#pygrib.open.readline",
    "pygrib.open.rewind": "https://jswhit.github.io/pygrib/api.html#pygrib.open.rewind",
    "pygrib.open.seek": "https://jswhit.github.io/pygrib/api.html#pygrib.open.seek",
    "pygrib.open.select": "https://jswhit.github.io/pygrib/api.html#pygrib.open.select",
    "pygrib.open.tell": "https://jswhit.github.io/pygrib/api.html#pygrib.open.tell",
    "pygrib.redtoreg": "https://jswhit.github.io/pygrib/api.html#pygrib.redtoreg",
    "pygrib.reload": "https://jswhit.github.io/pygrib/api.html#pygrib.reload",
    "pygrib.set_definitions_path": "https://jswhit.github.io/pygrib/api.html#pygrib.set_definitions_path",
    "pygrib.setdates": "https://jswhit.github.io/pygrib/api.html#pygrib.setdates",
    "pygrib.tolerate_badgrib_off": "https://jswhit.github.io/pygrib/api.html#pygrib.tolerate_badgrib_off",
    "pygrib.tolerate_badgrib_on": "https://jswhit.github.io/pygrib/api.html#pygrib.tolerate_badgrib_on",
}
