VERSION = "0.18.0"

# fmt: off
MAPPING = {
    "pyjls": "https://jls.readthedocs.io/en/stable/",
    "pyjls.binding": "https://jls.readthedocs.io/en/stable/py_api.html#module-pyjls.binding",
    "pyjls.binding.annotationtype": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.AnnotationType",
    "pyjls.binding.copy": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.copy",
    "pyjls.binding.datatype": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.DataType",
    "pyjls.binding.reader": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader",
    "pyjls.binding.reader.annotations": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.annotations",
    "pyjls.binding.reader.close": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.close",
    "pyjls.binding.reader.fsr": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.fsr",
    "pyjls.binding.reader.fsr_statistics": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.fsr_statistics",
    "pyjls.binding.reader.sample_id_to_timestamp": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.sample_id_to_timestamp",
    "pyjls.binding.reader.signal_lookup": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.signal_lookup",
    "pyjls.binding.reader.signals": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.signals",
    "pyjls.binding.reader.source_lookup": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.source_lookup",
    "pyjls.binding.reader.sources": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.sources",
    "pyjls.binding.reader.time_map_get": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.time_map_get",
    "pyjls.binding.reader.timestamp_to_sample_id": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.timestamp_to_sample_id",
    "pyjls.binding.reader.user_data": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.user_data",
    "pyjls.binding.reader.utc": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Reader.utc",
    "pyjls.binding.signaldef": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.SignalDef",
    "pyjls.binding.signaltype": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.SignalType",
    "pyjls.binding.sourcedef": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.SourceDef",
    "pyjls.binding.summaryfsr": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.SummaryFSR",
    "pyjls.binding.timemap": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.TimeMap",
    "pyjls.binding.writer": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer",
    "pyjls.binding.writer.annotation": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.annotation",
    "pyjls.binding.writer.close": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.close",
    "pyjls.binding.writer.flush": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.flush",
    "pyjls.binding.writer.fsr": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.fsr",
    "pyjls.binding.writer.fsr_f32": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.fsr_f32",
    "pyjls.binding.writer.signal_def": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.signal_def",
    "pyjls.binding.writer.signal_def_from_struct": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.signal_def_from_struct",
    "pyjls.binding.writer.source_def": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.source_def",
    "pyjls.binding.writer.source_def_from_struct": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.source_def_from_struct",
    "pyjls.binding.writer.user_data": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.user_data",
    "pyjls.binding.writer.utc": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.Writer.utc",
    "pyjls.structs": "https://jls.readthedocs.io/en/stable/py_api.html",
    "pyjls.structs.signaldef": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.SignalDef",
    "pyjls.structs.sourcedef": "https://jls.readthedocs.io/en/stable/py_api.html#pyjls.binding.SourceDef",
}
