VERSION = "2.4.0"

# fmt: off
MAPPING = {
    "pyjoulescope_driver": "https://joulescope-driver.readthedocs.io/en/stable/",
    "pyjoulescope_driver.binding": "https://joulescope-driver.readthedocs.io/en/stable/driver.html",
    "pyjoulescope_driver.binding.driver": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver",
    "pyjoulescope_driver.binding.elementtype": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.ElementType",
    "pyjoulescope_driver.binding.errorcode": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.ErrorCode",
    "pyjoulescope_driver.binding.field": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Field",
    "pyjoulescope_driver.binding.loglevel": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.LogLevel",
    "pyjoulescope_driver.binding.subscribeflags": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.SubscribeFlags",
    "pyjoulescope_driver.binding.timemap": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.TimeMap",
    "pyjoulescope_driver.driver": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver",
    "pyjoulescope_driver.driver.close": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.close",
    "pyjoulescope_driver.driver.device_paths": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.device_paths",
    "pyjoulescope_driver.driver.finalize": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.finalize",
    "pyjoulescope_driver.driver.log_level": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.log_level",
    "pyjoulescope_driver.driver.open": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.open",
    "pyjoulescope_driver.driver.publish": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.publish",
    "pyjoulescope_driver.driver.publish_and_wait": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.publish_and_wait",
    "pyjoulescope_driver.driver.query": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.query",
    "pyjoulescope_driver.driver.subscribe": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.subscribe",
    "pyjoulescope_driver.driver.unsubscribe": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.unsubscribe",
    "pyjoulescope_driver.driver.unsubscribe_all": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Driver.unsubscribe_all",
    "pyjoulescope_driver.elementtype": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.ElementType",
    "pyjoulescope_driver.errorcode": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.ErrorCode",
    "pyjoulescope_driver.field": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.Field",
    "pyjoulescope_driver.loglevel": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.LogLevel",
    "pyjoulescope_driver.mem_client": "https://joulescope-driver.readthedocs.io/en/stable/driver.html",
    "pyjoulescope_driver.mem_client.memclient": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.MemClient",
    "pyjoulescope_driver.memclient": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.MemClient",
    "pyjoulescope_driver.memclient.cmd": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.MemClient.cmd",
    "pyjoulescope_driver.memclient.erase_64k": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.MemClient.erase_64k",
    "pyjoulescope_driver.memclient.read": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.MemClient.read",
    "pyjoulescope_driver.memclient.read_personality": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.MemClient.read_personality",
    "pyjoulescope_driver.memclient.write_pages": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.MemClient.write_pages",
    "pyjoulescope_driver.memclient.write_verify": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.MemClient.write_verify",
    "pyjoulescope_driver.memclient.write_verify_records": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.MemClient.write_verify_records",
    "pyjoulescope_driver.program": "https://joulescope-driver.readthedocs.io/en/stable/program.html#module-pyjoulescope_driver.program",
    "pyjoulescope_driver.program.release_program": "https://joulescope-driver.readthedocs.io/en/stable/program.html#pyjoulescope_driver.program.release_program",
    "pyjoulescope_driver.program_js320": "https://joulescope-driver.readthedocs.io/en/stable/program.html#module-pyjoulescope_driver.program_js320",
    "pyjoulescope_driver.program_js320.program_js320": "https://joulescope-driver.readthedocs.io/en/stable/program.html#pyjoulescope_driver.program_js320.program_js320",
    "pyjoulescope_driver.stdmsg": "https://joulescope-driver.readthedocs.io/en/stable/driver.html",
    "pyjoulescope_driver.StdMsg": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.StdMsg",
    "pyjoulescope_driver.stdmsg.stdmsg": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.StdMsg",
    "pyjoulescope_driver.subscribeflags": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.SubscribeFlags",
    "pyjoulescope_driver.time64": "https://joulescope-driver.readthedocs.io/en/stable/time64.html#module-pyjoulescope_driver.time64",
    "pyjoulescope_driver.time64.as_datetime": "https://joulescope-driver.readthedocs.io/en/stable/time64.html#pyjoulescope_driver.time64.as_datetime",
    "pyjoulescope_driver.time64.as_isostr": "https://joulescope-driver.readthedocs.io/en/stable/time64.html#pyjoulescope_driver.time64.as_isostr",
    "pyjoulescope_driver.time64.as_time64": "https://joulescope-driver.readthedocs.io/en/stable/time64.html#pyjoulescope_driver.time64.as_time64",
    "pyjoulescope_driver.time64.as_timestamp": "https://joulescope-driver.readthedocs.io/en/stable/time64.html#pyjoulescope_driver.time64.as_timestamp",
    "pyjoulescope_driver.time64.duration_to_seconds": "https://joulescope-driver.readthedocs.io/en/stable/time64.html#pyjoulescope_driver.time64.duration_to_seconds",
    "pyjoulescope_driver.time64.filename": "https://joulescope-driver.readthedocs.io/en/stable/time64.html#pyjoulescope_driver.time64.filename",
    "pyjoulescope_driver.time64.now": "https://joulescope-driver.readthedocs.io/en/stable/time64.html#pyjoulescope_driver.time64.now",
    "pyjoulescope_driver.timemap": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.TimeMap",
    "pyjoulescope_driver.timemap.time_map_get": "https://joulescope-driver.readthedocs.io/en/stable/driver.html#pyjoulescope_driver.TimeMap.time_map_get",
}
