VERSION = "0.11.2"

# fmt: off
MAPPING = {
    "pykalman": "https://pykalman.readthedocs.io/en/latest/",
    "pykalman.additiveunscentedkalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.AdditiveUnscentedKalmanFilter",
    "pykalman.additiveunscentedkalmanfilter.filter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.AdditiveUnscentedKalmanFilter.filter",
    "pykalman.additiveunscentedkalmanfilter.filter_update": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.AdditiveUnscentedKalmanFilter.filter_update",
    "pykalman.additiveunscentedkalmanfilter.sample": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.AdditiveUnscentedKalmanFilter.sample",
    "pykalman.additiveunscentedkalmanfilter.smooth": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.AdditiveUnscentedKalmanFilter.smooth",
    "pykalman.kalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.KalmanFilter",
    "pykalman.kalmanfilter.em": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.KalmanFilter.em",
    "pykalman.kalmanfilter.filter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.KalmanFilter.filter",
    "pykalman.kalmanfilter.filter_update": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.KalmanFilter.filter_update",
    "pykalman.kalmanfilter.loglikelihood": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.KalmanFilter.loglikelihood",
    "pykalman.kalmanfilter.sample": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.KalmanFilter.sample",
    "pykalman.kalmanfilter.smooth": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.KalmanFilter.smooth",
    "pykalman.sqrt": "https://pykalman.readthedocs.io/en/latest/index.html",
    "pykalman.sqrt.additiveunscentedkalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.sqrt.AdditiveUnscentedKalmanFilter",
    "pykalman.sqrt.bierman": "https://pykalman.readthedocs.io/en/latest/index.html",
    "pykalman.sqrt.bierman.biermankalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.sqrt.BiermanKalmanFilter",
    "pykalman.sqrt.biermankalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.sqrt.BiermanKalmanFilter",
    "pykalman.sqrt.cholesky": "https://pykalman.readthedocs.io/en/latest/index.html",
    "pykalman.sqrt.cholesky.choleskykalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.sqrt.CholeskyKalmanFilter",
    "pykalman.sqrt.choleskykalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.sqrt.CholeskyKalmanFilter",
    "pykalman.sqrt.unscented": "https://pykalman.readthedocs.io/en/latest/index.html",
    "pykalman.sqrt.unscented.additiveunscentedkalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.sqrt.AdditiveUnscentedKalmanFilter",
    "pykalman.standard": "https://pykalman.readthedocs.io/en/latest/index.html",
    "pykalman.standard.kalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.KalmanFilter",
    "pykalman.unscented": "https://pykalman.readthedocs.io/en/latest/index.html",
    "pykalman.unscented.additiveunscentedkalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.AdditiveUnscentedKalmanFilter",
    "pykalman.unscented.unscentedkalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.UnscentedKalmanFilter",
    "pykalman.unscentedkalmanfilter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.UnscentedKalmanFilter",
    "pykalman.unscentedkalmanfilter.filter": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.UnscentedKalmanFilter.filter",
    "pykalman.unscentedkalmanfilter.filter_update": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.UnscentedKalmanFilter.filter_update",
    "pykalman.unscentedkalmanfilter.sample": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.UnscentedKalmanFilter.sample",
    "pykalman.unscentedkalmanfilter.smooth": "https://pykalman.readthedocs.io/en/latest/index.html#pykalman.UnscentedKalmanFilter.smooth",
}
