VERSION = "1.61"

# fmt: off
MAPPING = {
    "pylightxl": "https://pylightxl.readthedocs.io/en/stable/",
    "pylightxl.pylightxl.database": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database",
    "pylightxl.pylightxl.database.add_nr": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.add_nr",
    "pylightxl.pylightxl.database.add_ws": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.add_ws",
    "pylightxl.pylightxl.database.nr": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.nr",
    "pylightxl.pylightxl.database.nr_loc": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.nr_loc",
    "pylightxl.pylightxl.database.nr_names": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.nr_names",
    "pylightxl.pylightxl.database.remove_nr": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.remove_nr",
    "pylightxl.pylightxl.database.remove_ws": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.remove_ws",
    "pylightxl.pylightxl.database.rename_ws": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.rename_ws",
    "pylightxl.pylightxl.database.set_emptycell": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.set_emptycell",
    "pylightxl.pylightxl.database.update_nr": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.update_nr",
    "pylightxl.pylightxl.database.ws": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.ws",
    "pylightxl.pylightxl.database.ws_names": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Database.ws_names",
    "pylightxl.pylightxl.readxl": "https://pylightxl.readthedocs.io/en/stable/sourcecode/readxl.html#pylightxl.pylightxl.readxl",
    "pylightxl.pylightxl.utility_address2index": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.utility_address2index",
    "pylightxl.pylightxl.utility_columnletter2num": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.utility_columnletter2num",
    "pylightxl.pylightxl.utility_index2address": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.utility_index2address",
    "pylightxl.pylightxl.utility_num2columnletters": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.utility_num2columnletters",
    "pylightxl.pylightxl.worksheet": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet",
    "pylightxl.pylightxl.worksheet.address": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.address",
    "pylightxl.pylightxl.worksheet.col": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.col",
    "pylightxl.pylightxl.worksheet.cols": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.cols",
    "pylightxl.pylightxl.worksheet.index": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.index",
    "pylightxl.pylightxl.worksheet.keycol": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.keycol",
    "pylightxl.pylightxl.worksheet.keyrow": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.keyrow",
    "pylightxl.pylightxl.worksheet.range": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.range",
    "pylightxl.pylightxl.worksheet.row": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.row",
    "pylightxl.pylightxl.worksheet.rows": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.rows",
    "pylightxl.pylightxl.worksheet.set_emptycell": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.set_emptycell",
    "pylightxl.pylightxl.worksheet.size": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.size",
    "pylightxl.pylightxl.worksheet.ssd": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.ssd",
    "pylightxl.pylightxl.worksheet.update_address": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.update_address",
    "pylightxl.pylightxl.worksheet.update_index": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.update_index",
    "pylightxl.pylightxl.worksheet.update_range": "https://pylightxl.readthedocs.io/en/stable/sourcecode/database.html#pylightxl.pylightxl.Worksheet.update_range",
    "pylightxl.pylightxl.writexl": "https://pylightxl.readthedocs.io/en/stable/sourcecode/writexl.html#pylightxl.pylightxl.writexl",
}
