VERSION = "26.8.0"

# fmt: off
MAPPING = {
    "pylibraft": "https://docs.rapids.ai/api/raft/stable/",
    "pylibraft.common": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/",
    "pylibraft.common.cai_wrapper": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.cai_wrapper",
    "pylibraft.common.cai_wrapper.cai_wrapper": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.cai_wrapper",
    "pylibraft.common.cuda": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/",
    "pylibraft.common.cuda.stream": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.Stream",
    "pylibraft.common.device_ndarray": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.device_ndarray",
    "pylibraft.common.device_ndarray.c_contiguous": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.device_ndarray.c_contiguous",
    "pylibraft.common.device_ndarray.copy_to_host": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.device_ndarray.copy_to_host",
    "pylibraft.common.device_ndarray.device_ndarray": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.device_ndarray",
    "pylibraft.common.device_ndarray.dtype": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.device_ndarray.dtype",
    "pylibraft.common.device_ndarray.empty": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.device_ndarray.empty",
    "pylibraft.common.device_ndarray.f_contiguous": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.device_ndarray.f_contiguous",
    "pylibraft.common.device_ndarray.shape": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.device_ndarray.shape",
    "pylibraft.common.device_ndarray.strides": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.device_ndarray.strides",
    "pylibraft.common.deviceresources": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.DeviceResources",
    "pylibraft.common.deviceresources.gethandle": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.DeviceResources.getHandle",
    "pylibraft.common.deviceresources.sync": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.DeviceResources.sync",
    "pylibraft.common.handle": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/",
    "pylibraft.common.handle.deviceresources": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.DeviceResources",
    "pylibraft.common.interruptible": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/",
    "pylibraft.common.interruptible.cuda_interruptible": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.interruptible.cuda_interruptible",
    "pylibraft.common.interruptible.cuda_yield": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.interruptible.cuda_yield",
    "pylibraft.common.interruptible.synchronize": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.interruptible.synchronize",
    "pylibraft.common.stream": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.Stream",
    "pylibraft.common.stream.get_ptr": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.Stream.get_ptr",
    "pylibraft.common.stream.sync": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/common/#pylibraft.common.Stream.sync",
    "pylibraft.random": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/random/",
    "pylibraft.random.rmat": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/random/#pylibraft.random.rmat",
    "pylibraft.sparse": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/sparse/",
    "pylibraft.sparse.linalg": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/sparse/",
    "pylibraft.sparse.linalg.eigsh": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/sparse/#pylibraft.sparse.linalg.eigsh",
    "pylibraft.sparse.linalg.svds": "https://docs.rapids.ai/api/raft/stable/pylibraft_api/sparse/#pylibraft.sparse.linalg.svds",
}
