VERSION = "2.4.0"

# fmt: off
MAPPING = {
    "pymatching": "https://pymatching.readthedocs.io/en/stable/",
    "pymatching.matching": "https://pymatching.readthedocs.io/en/stable/api.html#module-pymatching.matching",
    "pymatching.matching.matching": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching",
    "pymatching.matching.matching.__init__": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.__init__",
    "pymatching.matching.matching.add_boundary_edge": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.add_boundary_edge",
    "pymatching.matching.matching.add_edge": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.add_edge",
    "pymatching.matching.matching.add_noise": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.add_noise",
    "pymatching.matching.matching.boundary": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.boundary",
    "pymatching.matching.matching.decode": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.decode",
    "pymatching.matching.matching.decode_batch": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.decode_batch",
    "pymatching.matching.matching.decode_to_edges_array": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.decode_to_edges_array",
    "pymatching.matching.matching.decode_to_matched_dets_array": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.decode_to_matched_dets_array",
    "pymatching.matching.matching.decode_to_matched_dets_dict": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.decode_to_matched_dets_dict",
    "pymatching.matching.matching.draw": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.draw",
    "pymatching.matching.matching.edges": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.edges",
    "pymatching.matching.matching.ensure_num_fault_ids": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.ensure_num_fault_ids",
    "pymatching.matching.matching.from_check_matrix": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.from_check_matrix",
    "pymatching.matching.matching.from_detector_error_model": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.from_detector_error_model",
    "pymatching.matching.matching.from_detector_error_model_file": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.from_detector_error_model_file",
    "pymatching.matching.matching.from_networkx": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.from_networkx",
    "pymatching.matching.matching.from_stim_circuit": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.from_stim_circuit",
    "pymatching.matching.matching.from_stim_circuit_file": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.from_stim_circuit_file",
    "pymatching.matching.matching.get_boundary_edge_data": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.get_boundary_edge_data",
    "pymatching.matching.matching.get_edge_data": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.get_edge_data",
    "pymatching.matching.matching.has_boundary_edge": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.has_boundary_edge",
    "pymatching.matching.matching.has_edge": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.has_edge",
    "pymatching.matching.matching.load_from_check_matrix": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.load_from_check_matrix",
    "pymatching.matching.matching.load_from_networkx": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.load_from_networkx",
    "pymatching.matching.matching.load_from_retworkx": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.load_from_retworkx",
    "pymatching.matching.matching.num_detectors": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.num_detectors",
    "pymatching.matching.matching.num_edges": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.num_edges",
    "pymatching.matching.matching.num_fault_ids": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.num_fault_ids",
    "pymatching.matching.matching.num_nodes": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.num_nodes",
    "pymatching.matching.matching.set_boundary_nodes": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.set_boundary_nodes",
    "pymatching.matching.matching.to_networkx": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.to_networkx",
    "pymatching.matching.matching.to_retworkx": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.Matching.to_retworkx",
    "pymatching.matching.pymatching": "https://pymatching.readthedocs.io/en/stable/api.html",
    "pymatching.matching.pymatching.cli": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.pymatching.cli",
    "pymatching.matching.pymatching.rand_float": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.pymatching.rand_float",
    "pymatching.matching.pymatching.randomize": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.pymatching.randomize",
    "pymatching.matching.pymatching.set_seed": "https://pymatching.readthedocs.io/en/stable/api.html#pymatching.matching.pymatching.set_seed",
}
