VERSION = "0.3.1"

# fmt: off
MAPPING = {
    "pyntcloud": "https://pyntcloud.readthedocs.io/en/stable/",
    "pyntcloud.filters": "https://pyntcloud.readthedocs.io/en/stable/filters_dev.html",
    "pyntcloud.filters.base": "https://pyntcloud.readthedocs.io/en/stable/filters_dev.html",
    "pyntcloud.filters.base.filter": "https://pyntcloud.readthedocs.io/en/stable/filters_dev.html#pyntcloud.filters.base.Filter",
    "pyntcloud.pyntcloud.add_structure": "https://pyntcloud.readthedocs.io/en/stable/structures.html#pyntcloud.PyntCloud.add_structure",
    "pyntcloud.pyntcloud.get_sample": "https://pyntcloud.readthedocs.io/en/stable/samplers.html#pyntcloud.PyntCloud.get_sample",
    "pyntcloud.pyntcloud.to_file": "https://pyntcloud.readthedocs.io/en/stable/io.html#pyntcloud.PyntCloud.to_file",
    "pyntcloud.samplers": "https://pyntcloud.readthedocs.io/en/stable/samplers_dev.html",
    "pyntcloud.samplers.base": "https://pyntcloud.readthedocs.io/en/stable/samplers_dev.html",
    "pyntcloud.samplers.base.sampler": "https://pyntcloud.readthedocs.io/en/stable/samplers_dev.html#pyntcloud.samplers.base.Sampler",
    "pyntcloud.scalar_fields.anisotropy": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.Anisotropy",
    "pyntcloud.scalar_fields.base": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields_dev.html",
    "pyntcloud.scalar_fields.base.scalarfield": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields_dev.html#pyntcloud.scalar_fields.base.ScalarField",
    "pyntcloud.scalar_fields.curvature": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.Curvature",
    "pyntcloud.scalar_fields.customfit": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.CustomFit",
    "pyntcloud.scalar_fields.eigendecomposition": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.EigenDecomposition",
    "pyntcloud.scalar_fields.eigenentropy": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.Eigenentropy",
    "pyntcloud.scalar_fields.eigensum": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.EigenSum",
    "pyntcloud.scalar_fields.eigenvalues": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.EigenValues",
    "pyntcloud.scalar_fields.euclideanclusters": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.EuclideanClusters",
    "pyntcloud.scalar_fields.huesaturationvalue": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.HueSaturationValue",
    "pyntcloud.scalar_fields.inclinationdegrees": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.InclinationDegrees",
    "pyntcloud.scalar_fields.inclinationradians": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.InclinationRadians",
    "pyntcloud.scalar_fields.linearity": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.Linearity",
    "pyntcloud.scalar_fields.omnivariance": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.Omnivariance",
    "pyntcloud.scalar_fields.orientationdegrees": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.OrientationDegrees",
    "pyntcloud.scalar_fields.orientationradians": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.OrientationRadians",
    "pyntcloud.scalar_fields.planarity": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.Planarity",
    "pyntcloud.scalar_fields.planefit": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.PlaneFit",
    "pyntcloud.scalar_fields.relativeluminance": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.RelativeLuminance",
    "pyntcloud.scalar_fields.rgbintensity": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.RGBIntensity",
    "pyntcloud.scalar_fields.spherefit": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.SphereFit",
    "pyntcloud.scalar_fields.sphericalcoordinates": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.SphericalCoordinates",
    "pyntcloud.scalar_fields.voxeln": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.VoxelN",
    "pyntcloud.scalar_fields.voxelx": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.VoxelX",
    "pyntcloud.scalar_fields.voxely": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.VoxelY",
    "pyntcloud.scalar_fields.voxelz": "https://pyntcloud.readthedocs.io/en/stable/scalar_fields.html#pyntcloud.scalar_fields.VoxelZ",
    "pyntcloud.structures": "https://pyntcloud.readthedocs.io/en/stable/structures.html",
    "pyntcloud.structures.convexhull": "https://pyntcloud.readthedocs.io/en/stable/structures.html#pyntcloud.structures.ConvexHull",
    "pyntcloud.structures.delaunay3d": "https://pyntcloud.readthedocs.io/en/stable/structures.html#pyntcloud.structures.Delaunay3D",
    "pyntcloud.structures.kdtree": "https://pyntcloud.readthedocs.io/en/stable/structures.html#pyntcloud.structures.KDTree",
    "pyntcloud.structures.voxelgrid": "https://pyntcloud.readthedocs.io/en/stable/structures.html#pyntcloud.structures.VoxelGrid",
}
