VERSION = "0.5.0.post1"

# fmt: off
MAPPING = {
    "pypi_json": "https://pypi-json.readthedocs.io/en/stable/",
    "pypi_json.projectmetadata": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata",
    "pypi_json.projectmetadata.get_latest_version": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.get_latest_version",
    "pypi_json.projectmetadata.get_releases": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.get_releases",
    "pypi_json.projectmetadata.get_releases_with_digests": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.get_releases_with_digests",
    "pypi_json.projectmetadata.get_wheel_tag_mapping": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.get_wheel_tag_mapping",
    "pypi_json.projectmetadata.info": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.info",
    "pypi_json.projectmetadata.last_serial": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.last_serial",
    "pypi_json.projectmetadata.name": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.name",
    "pypi_json.projectmetadata.ownership": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.ownership",
    "pypi_json.projectmetadata.releases": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.releases",
    "pypi_json.projectmetadata.urls": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.urls",
    "pypi_json.projectmetadata.version": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.version",
    "pypi_json.projectmetadata.vulnerabilities": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.ProjectMetadata.vulnerabilities",
    "pypi_json.pypijson": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.PyPIJSON",
    "pypi_json.pypijson.__repr__": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.PyPIJSON.__repr__",
    "pypi_json.pypijson.download_file": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.PyPIJSON.download_file",
    "pypi_json.pypijson.endpoint": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.PyPIJSON.endpoint",
    "pypi_json.pypijson.endpoint_url": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.PyPIJSON.endpoint_url",
    "pypi_json.pypijson.get_metadata": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.PyPIJSON.get_metadata",
    "pypi_json.pypijson.timeout": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.PyPIJSON.timeout",
    "pypi_json.typehints": "https://pypi-json.readthedocs.io/en/stable/api/typehints.html#module-pypi_json.typehints",
    "pypi_json.typehints.distributionpackagedict": "https://pypi-json.readthedocs.io/en/stable/api/typehints.html#pypi_json.typehints.DistributionPackageDict",
    "pypi_json.typehints.fileurl": "https://pypi-json.readthedocs.io/en/stable/api/typehints.html#pypi_json.typehints.FileURL",
    "pypi_json.typehints.ownershipinfodict": "https://pypi-json.readthedocs.io/en/stable/api/typehints.html#pypi_json.typehints.OwnershipInfoDict",
    "pypi_json.typehints.projectinfodict": "https://pypi-json.readthedocs.io/en/stable/api/typehints.html#pypi_json.typehints.ProjectInfoDict",
    "pypi_json.typehints.roleinfodict": "https://pypi-json.readthedocs.io/en/stable/api/typehints.html#pypi_json.typehints.RoleInfoDict",
    "pypi_json.typehints.vulnerabilityinfodict": "https://pypi-json.readthedocs.io/en/stable/api/typehints.html#pypi_json.typehints.VulnerabilityInfoDict",
    "pypi_json.user_agent": "https://pypi-json.readthedocs.io/en/stable/api/pypi-json.html#pypi_json.USER_AGENT",
}
