VERSION = "1.1.0"

# fmt: off
MAPPING = {
    "pyroaring": "https://pyroaringbitmap.readthedocs.io/en/stable/",
    "pyroaring.abstractbitmap": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap",
    "pyroaring.abstractbitmap.contains_range": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.contains_range",
    "pyroaring.abstractbitmap.copy": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.copy",
    "pyroaring.abstractbitmap.copy_on_write": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.copy_on_write",
    "pyroaring.abstractbitmap.deserialize": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.deserialize",
    "pyroaring.abstractbitmap.difference": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.difference",
    "pyroaring.abstractbitmap.difference_cardinality": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.difference_cardinality",
    "pyroaring.abstractbitmap.flip": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.flip",
    "pyroaring.abstractbitmap.get_statistics": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.get_statistics",
    "pyroaring.abstractbitmap.intersect": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.intersect",
    "pyroaring.abstractbitmap.intersection": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.intersection",
    "pyroaring.abstractbitmap.intersection_cardinality": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.intersection_cardinality",
    "pyroaring.abstractbitmap.isdisjoint": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.isdisjoint",
    "pyroaring.abstractbitmap.issubset": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.issubset",
    "pyroaring.abstractbitmap.issuperset": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.issuperset",
    "pyroaring.abstractbitmap.iter_equal_or_larger": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.iter_equal_or_larger",
    "pyroaring.abstractbitmap.jaccard_index": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.jaccard_index",
    "pyroaring.abstractbitmap.max": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.max",
    "pyroaring.abstractbitmap.min": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.min",
    "pyroaring.abstractbitmap.next_set_bit": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.next_set_bit",
    "pyroaring.abstractbitmap.range_cardinality": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.range_cardinality",
    "pyroaring.abstractbitmap.rank": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.rank",
    "pyroaring.abstractbitmap.run_optimize": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.run_optimize",
    "pyroaring.abstractbitmap.serialize": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.serialize",
    "pyroaring.abstractbitmap.shift": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.shift",
    "pyroaring.abstractbitmap.shrink_to_fit": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.shrink_to_fit",
    "pyroaring.abstractbitmap.symmetric_difference": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.symmetric_difference",
    "pyroaring.abstractbitmap.symmetric_difference_cardinality": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.symmetric_difference_cardinality",
    "pyroaring.abstractbitmap.to_array": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.to_array",
    "pyroaring.abstractbitmap.union": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.union",
    "pyroaring.abstractbitmap.union_cardinality": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.AbstractBitMap.union_cardinality",
    "pyroaring.bitmap": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap",
    "pyroaring.bitmap.add": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.add",
    "pyroaring.bitmap.add_checked": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.add_checked",
    "pyroaring.bitmap.add_range": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.add_range",
    "pyroaring.bitmap.clear": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.clear",
    "pyroaring.bitmap.difference_update": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.difference_update",
    "pyroaring.bitmap.discard": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.discard",
    "pyroaring.bitmap.flip_inplace": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.flip_inplace",
    "pyroaring.bitmap.intersection_update": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.intersection_update",
    "pyroaring.bitmap.overwrite": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.overwrite",
    "pyroaring.bitmap.pop": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.pop",
    "pyroaring.bitmap.remove": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.remove",
    "pyroaring.bitmap.remove_range": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.remove_range",
    "pyroaring.bitmap.symmetric_difference_update": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.symmetric_difference_update",
    "pyroaring.bitmap.update": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.BitMap.update",
    "pyroaring.frozenbitmap": "https://pyroaringbitmap.readthedocs.io/en/stable/index.html#pyroaring.FrozenBitMap",
}
