VERSION = "3.0.6"

# fmt: off
MAPPING = {
    "pysolarmanv5": "https://pysolarmanv5.readthedocs.io/en/stable/",
    "pysolarmanv5.nosocketavailableerror": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.NoSocketAvailableError",
    "pysolarmanv5.pysolarmanv5": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html",
    "pysolarmanv5.PySolarmanV5": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5",
    "pysolarmanv5.pysolarmanv5.disconnect": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.disconnect",
    "pysolarmanv5.pysolarmanv5.masked_write_holding_register": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.masked_write_holding_register",
    "pysolarmanv5.pysolarmanv5.nosocketavailableerror": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.NoSocketAvailableError",
    "pysolarmanv5.pysolarmanv5.pysolarmanv5": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5",
    "pysolarmanv5.pysolarmanv5.read_coils": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.read_coils",
    "pysolarmanv5.pysolarmanv5.read_discrete_inputs": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.read_discrete_inputs",
    "pysolarmanv5.pysolarmanv5.read_holding_register_formatted": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.read_holding_register_formatted",
    "pysolarmanv5.pysolarmanv5.read_holding_registers": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.read_holding_registers",
    "pysolarmanv5.pysolarmanv5.read_input_register_formatted": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.read_input_register_formatted",
    "pysolarmanv5.pysolarmanv5.read_input_registers": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.read_input_registers",
    "pysolarmanv5.pysolarmanv5.send_raw_modbus_frame": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.send_raw_modbus_frame",
    "pysolarmanv5.pysolarmanv5.send_raw_modbus_frame_parsed": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.send_raw_modbus_frame_parsed",
    "pysolarmanv5.pysolarmanv5.twos_complement": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.twos_complement",
    "pysolarmanv5.pysolarmanv5.v5frameerror": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.V5FrameError",
    "pysolarmanv5.pysolarmanv5.write_holding_register": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.write_holding_register",
    "pysolarmanv5.pysolarmanv5.write_multiple_coils": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.write_multiple_coils",
    "pysolarmanv5.pysolarmanv5.write_multiple_holding_registers": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.write_multiple_holding_registers",
    "pysolarmanv5.pysolarmanv5.write_single_coil": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.write_single_coil",
    "pysolarmanv5.pysolarmanv5_async": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html",
    "pysolarmanv5.pysolarmanv5_async.pysolarmanv5async": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async",
    "pysolarmanv5.pysolarmanv5async": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async",
    "pysolarmanv5.pysolarmanv5async.connect": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.connect",
    "pysolarmanv5.pysolarmanv5async.disconnect": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.disconnect",
    "pysolarmanv5.pysolarmanv5async.masked_write_holding_register": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.masked_write_holding_register",
    "pysolarmanv5.pysolarmanv5async.read_coils": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.read_coils",
    "pysolarmanv5.pysolarmanv5async.read_discrete_inputs": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.read_discrete_inputs",
    "pysolarmanv5.pysolarmanv5async.read_holding_register_formatted": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.read_holding_register_formatted",
    "pysolarmanv5.pysolarmanv5async.read_holding_registers": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.read_holding_registers",
    "pysolarmanv5.pysolarmanv5async.read_input_register_formatted": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.read_input_register_formatted",
    "pysolarmanv5.pysolarmanv5async.read_input_registers": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.read_input_registers",
    "pysolarmanv5.pysolarmanv5async.reconnect": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.reconnect",
    "pysolarmanv5.pysolarmanv5async.send_raw_modbus_frame": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.send_raw_modbus_frame",
    "pysolarmanv5.pysolarmanv5async.send_raw_modbus_frame_parsed": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.send_raw_modbus_frame_parsed",
    "pysolarmanv5.pysolarmanv5async.write_holding_register": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.write_holding_register",
    "pysolarmanv5.pysolarmanv5async.write_multiple_coils": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.write_multiple_coils",
    "pysolarmanv5.pysolarmanv5async.write_multiple_holding_registers": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.write_multiple_holding_registers",
    "pysolarmanv5.pysolarmanv5async.write_single_coil": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5Async.write_single_coil",
    "pysolarmanv5.v5frameerror": "https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.V5FrameError",
}
