VERSION = "0.9.0"

# fmt: off
MAPPING = {
    "spellchecker": "https://pyspellchecker.readthedocs.io/en/stable/",
    "spellchecker.spellchecker": "https://pyspellchecker.readthedocs.io/en/stable/code.html",
    "spellchecker.SpellChecker": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker",
    "spellchecker.spellchecker.candidates": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.candidates",
    "spellchecker.spellchecker.correction": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.correction",
    "spellchecker.spellchecker.distance": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.distance",
    "spellchecker.spellchecker.edit_distance_1": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.edit_distance_1",
    "spellchecker.spellchecker.edit_distance_2": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.edit_distance_2",
    "spellchecker.spellchecker.export": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.export",
    "spellchecker.spellchecker.known": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.known",
    "spellchecker.spellchecker.languages": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.languages",
    "spellchecker.spellchecker.spellchecker": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker",
    "spellchecker.spellchecker.split_words": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.split_words",
    "spellchecker.spellchecker.unknown": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.unknown",
    "spellchecker.spellchecker.word_frequency": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.word_frequency",
    "spellchecker.spellchecker.word_usage_frequency": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.SpellChecker.word_usage_frequency",
    "spellchecker.spellchecker.wordfrequency": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency",
    "spellchecker.wordfrequency": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency",
    "spellchecker.wordfrequency.add": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.add",
    "spellchecker.wordfrequency.dictionary": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.dictionary",
    "spellchecker.wordfrequency.items": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.items",
    "spellchecker.wordfrequency.keys": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.keys",
    "spellchecker.wordfrequency.letters": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.letters",
    "spellchecker.wordfrequency.load_dictionary": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.load_dictionary",
    "spellchecker.wordfrequency.load_json": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.load_json",
    "spellchecker.wordfrequency.load_text": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.load_text",
    "spellchecker.wordfrequency.load_text_file": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.load_text_file",
    "spellchecker.wordfrequency.load_words": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.load_words",
    "spellchecker.wordfrequency.longest_word_length": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.longest_word_length",
    "spellchecker.wordfrequency.pop": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.pop",
    "spellchecker.wordfrequency.remove": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.remove",
    "spellchecker.wordfrequency.remove_by_threshold": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.remove_by_threshold",
    "spellchecker.wordfrequency.remove_words": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.remove_words",
    "spellchecker.wordfrequency.tokenize": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.tokenize",
    "spellchecker.wordfrequency.total_words": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.total_words",
    "spellchecker.wordfrequency.unique_words": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.unique_words",
    "spellchecker.wordfrequency.words": "https://pyspellchecker.readthedocs.io/en/stable/code.html#spellchecker.WordFrequency.words",
}
