VERSION = "1.0.1"

# fmt: off
MAPPING = {
    "pytest_lsp": "https://lsp-devtools.readthedocs.io/en/latest/",
    "pytest_lsp.checks": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#module-pytest_lsp.checks",
    "pytest_lsp.checks.check_completion_item": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.check_completion_item",
    "pytest_lsp.checks.check_params_against_client_capabilities": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.check_params_against_client_capabilities",
    "pytest_lsp.checks.check_params_of": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.check_params_of",
    "pytest_lsp.checks.check_result_against_client_capabilities": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.check_result_against_client_capabilities",
    "pytest_lsp.checks.check_result_for": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.check_result_for",
    "pytest_lsp.checks.completion_item_resolve": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.completion_item_resolve",
    "pytest_lsp.checks.completion_items": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.completion_items",
    "pytest_lsp.checks.document_links": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.document_links",
    "pytest_lsp.checks.lspspecificationwarning": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.LspSpecificationWarning",
    "pytest_lsp.checks.work_done_progress_create": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.work_done_progress_create",
    "pytest_lsp.checks.workspace_configuration": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.checks.workspace_configuration",
    "pytest_lsp.client": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html",
    "pytest_lsp.client.default_client_features": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.client.DEFAULT_CLIENT_FEATURES",
    "pytest_lsp.client.languageclient": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient",
    "pytest_lsp.client.register_lsp_features": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.client.register_lsp_features",
    "pytest_lsp.client_capabilities": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.client_capabilities",
    "pytest_lsp.clientserverconfig": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.ClientServerConfig",
    "pytest_lsp.clientserverconfig.client_factory": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.ClientServerConfig.client_factory",
    "pytest_lsp.clientserverconfig.get_server_command": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.ClientServerConfig.get_server_command",
    "pytest_lsp.clientserverconfig.server_command": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.ClientServerConfig.server_command",
    "pytest_lsp.clientserverconfig.server_env": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.ClientServerConfig.server_env",
    "pytest_lsp.clientserverconfig.start": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.ClientServerConfig.start",
    "pytest_lsp.fixture": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.fixture",
    "pytest_lsp.languageclient": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient",
    "pytest_lsp.languageclient.capabilities": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.capabilities",
    "pytest_lsp.languageclient.diagnostic_refresh_count": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.diagnostic_refresh_count",
    "pytest_lsp.languageclient.diagnostics": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.diagnostics",
    "pytest_lsp.languageclient.error": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.error",
    "pytest_lsp.languageclient.get_configuration": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.get_configuration",
    "pytest_lsp.languageclient.initialize_session": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.initialize_session",
    "pytest_lsp.languageclient.log_messages": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.log_messages",
    "pytest_lsp.languageclient.messages": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.messages",
    "pytest_lsp.languageclient.progress_reports": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.progress_reports",
    "pytest_lsp.languageclient.report_server_error": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.report_server_error",
    "pytest_lsp.languageclient.server_exit": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.server_exit",
    "pytest_lsp.languageclient.set_configuration": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.set_configuration",
    "pytest_lsp.languageclient.shown_documents": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.shown_documents",
    "pytest_lsp.languageclient.shutdown_session": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.shutdown_session",
    "pytest_lsp.languageclient.start_io": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.start_io",
    "pytest_lsp.languageclient.wait_for_notification": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.LanguageClient.wait_for_notification",
    "pytest_lsp.make_test_lsp_client": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.make_test_lsp_client",
    "pytest_lsp.plugin": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html",
    "pytest_lsp.plugin.clientserverconfig": "https://lsp-devtools.readthedocs.io/en/latest/pytest-lsp/reference.html#pytest_lsp.ClientServerConfig",
}
