VERSION = "2.0.12"

# fmt: off
MAPPING = {
    "ffmpeg": "https://python-ffmpeg.readthedocs.io/en/stable/",
    "ffmpeg.asyncio": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio",
    "ffmpeg.asyncio.ffmpeg": "https://python-ffmpeg.readthedocs.io/en/stable/api/",
    "ffmpeg.asyncio.FFmpeg": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg",
    "ffmpeg.asyncio.ffmpeg.__init__": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.__init__",
    "ffmpeg.asyncio.ffmpeg.arguments": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.arguments",
    "ffmpeg.asyncio.ffmpeg.execute": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.execute",
    "ffmpeg.asyncio.ffmpeg.ffmpeg": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg",
    "ffmpeg.asyncio.ffmpeg.ffmpeg.__init__": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.__init__",
    "ffmpeg.asyncio.ffmpeg.ffmpeg.arguments": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.arguments",
    "ffmpeg.asyncio.ffmpeg.ffmpeg.execute": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.execute",
    "ffmpeg.asyncio.ffmpeg.ffmpeg.input": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.input",
    "ffmpeg.asyncio.ffmpeg.ffmpeg.option": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.option",
    "ffmpeg.asyncio.ffmpeg.ffmpeg.output": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.output",
    "ffmpeg.asyncio.ffmpeg.ffmpeg.terminate": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.terminate",
    "ffmpeg.asyncio.ffmpeg.input": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.input",
    "ffmpeg.asyncio.ffmpeg.option": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.option",
    "ffmpeg.asyncio.ffmpeg.output": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.output",
    "ffmpeg.asyncio.ffmpeg.terminate": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.asyncio.FFmpeg.terminate",
    "ffmpeg.errors": "https://python-ffmpeg.readthedocs.io/en/stable/api/",
    "ffmpeg.errors.ffmpegalreadyexecuted": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegAlreadyExecuted",
    "ffmpeg.errors.ffmpegerror": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegError",
    "ffmpeg.errors.ffmpegfilenotfound": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegFileNotFound",
    "ffmpeg.errors.ffmpeginvalidcommand": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegInvalidCommand",
    "ffmpeg.errors.ffmpegunsupportedcodec": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegUnsupportedCodec",
    "ffmpeg.ffmpeg": "https://python-ffmpeg.readthedocs.io/en/stable/api/",
    "ffmpeg.FFmpeg": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg",
    "ffmpeg.ffmpeg.__init__": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.__init__",
    "ffmpeg.ffmpeg.arguments": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.arguments",
    "ffmpeg.ffmpeg.execute": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.execute",
    "ffmpeg.ffmpeg.ffmpeg": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg",
    "ffmpeg.ffmpeg.ffmpeg.__init__": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.__init__",
    "ffmpeg.ffmpeg.ffmpeg.arguments": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.arguments",
    "ffmpeg.ffmpeg.ffmpeg.execute": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.execute",
    "ffmpeg.ffmpeg.ffmpeg.input": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.input",
    "ffmpeg.ffmpeg.ffmpeg.option": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.option",
    "ffmpeg.ffmpeg.ffmpeg.output": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.output",
    "ffmpeg.ffmpeg.ffmpeg.terminate": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.terminate",
    "ffmpeg.ffmpeg.input": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.input",
    "ffmpeg.ffmpeg.option": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.option",
    "ffmpeg.ffmpeg.output": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.output",
    "ffmpeg.ffmpeg.terminate": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpeg.terminate",
    "ffmpeg.ffmpegalreadyexecuted": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegAlreadyExecuted",
    "ffmpeg.ffmpegerror": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegError",
    "ffmpeg.ffmpegfilenotfound": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegFileNotFound",
    "ffmpeg.ffmpeginvalidcommand": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegInvalidCommand",
    "ffmpeg.ffmpegunsupportedcodec": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.FFmpegUnsupportedCodec",
    "ffmpeg.progress": "https://python-ffmpeg.readthedocs.io/en/stable/api/",
    "ffmpeg.Progress": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.Progress",
    "ffmpeg.progress.progress": "https://python-ffmpeg.readthedocs.io/en/stable/api/#ffmpeg.Progress",
}
