VERSION = "1.3.7"

# fmt: off
MAPPING = {
    "mecab": "https://python-mecab-ko.readthedocs.io/en/stable/",
    "mecab.dictionary": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Dictionary",
    "mecab.feature": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Feature",
    "mecab.mecab": "https://python-mecab-ko.readthedocs.io/en/stable/api/",
    "mecab.MeCab": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab",
    "mecab.mecab.__init__": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.__init__",
    "mecab.mecab.dictionary": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.dictionary",
    "mecab.mecab.mecab": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab",
    "mecab.mecab.mecab.__init__": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.__init__",
    "mecab.mecab.mecab.dictionary": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.dictionary",
    "mecab.mecab.mecab.morphs": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.morphs",
    "mecab.mecab.mecab.nouns": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.nouns",
    "mecab.mecab.mecab.parse": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.parse",
    "mecab.mecab.mecab.pos": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.pos",
    "mecab.mecab.mecaberror": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCabError",
    "mecab.mecab.morphs": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.morphs",
    "mecab.mecab.nouns": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.nouns",
    "mecab.mecab.parse": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.parse",
    "mecab.mecab.pos": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCab.pos",
    "mecab.mecaberror": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.MeCabError",
    "mecab.morpheme": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Morpheme",
    "mecab.morpheme.pos": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Morpheme.pos",
    "mecab.span": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Span",
    "mecab.types": "https://python-mecab-ko.readthedocs.io/en/stable/api/",
    "mecab.types.dictionary": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Dictionary",
    "mecab.types.feature": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Feature",
    "mecab.types.morpheme": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Morpheme",
    "mecab.types.morpheme.pos": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Morpheme.pos",
    "mecab.types.span": "https://python-mecab-ko.readthedocs.io/en/stable/api/#mecab.Span",
}
