VERSION = "2.1.0"

# fmt: off
MAPPING = {
    "statsd": "https://python-statsd.readthedocs.io/en/stable/",
    "statsd.client": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#module-statsd.client",
    "statsd.client.client": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#statsd.client.Client",
    "statsd.client.client.connection": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#statsd.client.Client.connection",
    "statsd.client.client.get_average": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#statsd.client.Client.get_average",
    "statsd.client.client.get_client": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#statsd.client.Client.get_client",
    "statsd.client.client.get_counter": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#statsd.client.Client.get_counter",
    "statsd.client.client.get_gauge": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#statsd.client.Client.get_gauge",
    "statsd.client.client.get_raw": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#statsd.client.Client.get_raw",
    "statsd.client.client.get_timer": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#statsd.client.Client.get_timer",
    "statsd.client.client.name": "https://python-statsd.readthedocs.io/en/stable/statsd.client.html#statsd.client.Client.name",
    "statsd.connection": "https://python-statsd.readthedocs.io/en/stable/statsd.connection.html#module-statsd.connection",
    "statsd.connection.connection": "https://python-statsd.readthedocs.io/en/stable/statsd.connection.html#statsd.connection.Connection",
    "statsd.connection.connection.send": "https://python-statsd.readthedocs.io/en/stable/statsd.connection.html#statsd.connection.Connection.send",
    "statsd.counter": "https://python-statsd.readthedocs.io/en/stable/statsd.counter.html#module-statsd.counter",
    "statsd.counter.counter": "https://python-statsd.readthedocs.io/en/stable/statsd.counter.html#statsd.counter.Counter",
    "statsd.counter.counter.decrement": "https://python-statsd.readthedocs.io/en/stable/statsd.counter.html#statsd.counter.Counter.decrement",
    "statsd.counter.counter.increment": "https://python-statsd.readthedocs.io/en/stable/statsd.counter.html#statsd.counter.Counter.increment",
    "statsd.counter.decrement": "https://python-statsd.readthedocs.io/en/stable/statsd.counter.html#statsd.counter.decrement",
    "statsd.counter.increment": "https://python-statsd.readthedocs.io/en/stable/statsd.counter.html#statsd.counter.increment",
    "statsd.gauge": "https://python-statsd.readthedocs.io/en/stable/statsd.gauge.html#module-statsd.gauge",
    "statsd.gauge.gauge": "https://python-statsd.readthedocs.io/en/stable/statsd.gauge.html#statsd.gauge.Gauge",
    "statsd.gauge.gauge.decrement": "https://python-statsd.readthedocs.io/en/stable/statsd.gauge.html#statsd.gauge.Gauge.decrement",
    "statsd.gauge.gauge.increment": "https://python-statsd.readthedocs.io/en/stable/statsd.gauge.html#statsd.gauge.Gauge.increment",
    "statsd.gauge.gauge.send": "https://python-statsd.readthedocs.io/en/stable/statsd.gauge.html#statsd.gauge.Gauge.send",
    "statsd.gauge.gauge.set": "https://python-statsd.readthedocs.io/en/stable/statsd.gauge.html#statsd.gauge.Gauge.set",
    "statsd.raw": "https://python-statsd.readthedocs.io/en/stable/statsd.raw.html#module-statsd.raw",
    "statsd.raw.raw": "https://python-statsd.readthedocs.io/en/stable/statsd.raw.html#statsd.raw.Raw",
    "statsd.raw.raw.send": "https://python-statsd.readthedocs.io/en/stable/statsd.raw.html#statsd.raw.Raw.send",
    "statsd.timer": "https://python-statsd.readthedocs.io/en/stable/statsd.timer.html#module-statsd.timer",
    "statsd.timer.timer": "https://python-statsd.readthedocs.io/en/stable/statsd.timer.html#statsd.timer.Timer",
    "statsd.timer.timer.decorate": "https://python-statsd.readthedocs.io/en/stable/statsd.timer.html#statsd.timer.Timer.decorate",
    "statsd.timer.timer.intermediate": "https://python-statsd.readthedocs.io/en/stable/statsd.timer.html#statsd.timer.Timer.intermediate",
    "statsd.timer.timer.send": "https://python-statsd.readthedocs.io/en/stable/statsd.timer.html#statsd.timer.Timer.send",
    "statsd.timer.timer.start": "https://python-statsd.readthedocs.io/en/stable/statsd.timer.html#statsd.timer.Timer.start",
    "statsd.timer.timer.stop": "https://python-statsd.readthedocs.io/en/stable/statsd.timer.html#statsd.timer.Timer.stop",
    "statsd.timer.timer.time": "https://python-statsd.readthedocs.io/en/stable/statsd.timer.html#statsd.timer.Timer.time",
}
