VERSION = "0.6.0"

# fmt: off
MAPPING = {
    "qiskit_qasm3_import": "https://qiskit.github.io/qiskit-qasm3-import/",
    "qiskit_qasm3_import.conversionerror": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.ConversionError",
    "qiskit_qasm3_import.convert": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.convert",
    "qiskit_qasm3_import.converter": "https://qiskit.github.io/qiskit-qasm3-import/index.html",
    "qiskit_qasm3_import.converter.convertvisitor": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.converter.ConvertVisitor",
    "qiskit_qasm3_import.converter.convertvisitor.convert": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.converter.ConvertVisitor.convert",
    "qiskit_qasm3_import.exceptions": "https://qiskit.github.io/qiskit-qasm3-import/index.html",
    "qiskit_qasm3_import.exceptions.conversionerror": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.ConversionError",
    "qiskit_qasm3_import.expression": "https://qiskit.github.io/qiskit-qasm3-import/index.html",
    "qiskit_qasm3_import.expression.resolve_condition": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.expression.resolve_condition",
    "qiskit_qasm3_import.expression.valueresolver": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.expression.ValueResolver",
    "qiskit_qasm3_import.expression.valueresolver.resolve": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.expression.ValueResolver.resolve",
    "qiskit_qasm3_import.parse": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.parse",
    "qiskit_qasm3_import.types": "https://qiskit.github.io/qiskit-qasm3-import/index.html#module-qiskit_qasm3_import.types",
    "qiskit_qasm3_import.types.angle": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Angle",
    "qiskit_qasm3_import.types.bit": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Bit",
    "qiskit_qasm3_import.types.bitarray": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.BitArray",
    "qiskit_qasm3_import.types.bool": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Bool",
    "qiskit_qasm3_import.types.duration": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Duration",
    "qiskit_qasm3_import.types.error": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Error",
    "qiskit_qasm3_import.types.float": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Float",
    "qiskit_qasm3_import.types.gate": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Gate",
    "qiskit_qasm3_import.types.hardwarequbit": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.HardwareQubit",
    "qiskit_qasm3_import.types.int": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Int",
    "qiskit_qasm3_import.types.never": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Never",
    "qiskit_qasm3_import.types.qubit": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Qubit",
    "qiskit_qasm3_import.types.qubitarray": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.QubitArray",
    "qiskit_qasm3_import.types.range": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Range",
    "qiskit_qasm3_import.types.sequence": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Sequence",
    "qiskit_qasm3_import.types.type": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Type",
    "qiskit_qasm3_import.types.type.pretty": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Type.pretty",
    "qiskit_qasm3_import.types.uint": "https://qiskit.github.io/qiskit-qasm3-import/index.html#qiskit_qasm3_import.types.Uint",
}
