VERSION = "0.16.4"

# fmt: off
MAPPING = {
    "qprompt": "https://qprompt.readthedocs.io/en/latest/",
    "qprompt.alert": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.alert",
    "qprompt.ask": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.ask",
    "qprompt.ask_captcha": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.ask_captcha",
    "qprompt.ask_float": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.ask_float",
    "qprompt.ask_int": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.ask_int",
    "qprompt.ask_pass": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.ask_pass",
    "qprompt.ask_str": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.ask_str",
    "qprompt.ask_yesno": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.ask_yesno",
    "qprompt.cast": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.cast",
    "qprompt.clear": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.clear",
    "qprompt.echo": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.echo",
    "qprompt.enum_menu": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.enum_menu",
    "qprompt.error": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.error",
    "qprompt.hrule": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.hrule",
    "qprompt.info": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.info",
    "qprompt.menu": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.Menu",
    "qprompt.menu.add": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.Menu.add",
    "qprompt.menu.enum": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.Menu.enum",
    "qprompt.menu.get": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.Menu.get",
    "qprompt.menu.main": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.Menu.main",
    "qprompt.menu.run": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.Menu.run",
    "qprompt.menu.show": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.Menu.show",
    "qprompt.menuentry": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.MenuEntry",
    "qprompt.pause": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.pause",
    "qprompt.setinput": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.setinput",
    "qprompt.show_limit": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.show_limit",
    "qprompt.show_menu": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.show_menu",
    "qprompt.status": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.status",
    "qprompt.stdinauto": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.StdinAuto",
    "qprompt.stdinsetup": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.StdinSetup",
    "qprompt.title": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.title",
    "qprompt.warn": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.warn",
    "qprompt.Wrap": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.Wrap",
    "qprompt.wrap": "https://qprompt.readthedocs.io/en/latest/index.html#qprompt.wrap",
}
