VERSION = "2.0.0"

# fmt: off
MAPPING = {
    "reactpy_router": "https://reactive-python.github.io/reactpy-router/latest/",
    "reactpy_router.browser_router": "https://reactive-python.github.io/reactpy-router/latest/reference/routers/#reactpy_router.browser_router",
    "reactpy_router.components": "https://reactive-python.github.io/reactpy-router/latest/reference/components/",
    "reactpy_router.components.link": "https://reactive-python.github.io/reactpy-router/latest/reference/components/#reactpy_router.link",
    "reactpy_router.components.navigate": "https://reactive-python.github.io/reactpy-router/latest/reference/components/#reactpy_router.navigate",
    "reactpy_router.components.route": "https://reactive-python.github.io/reactpy-router/latest/reference/components/#reactpy_router.route",
    "reactpy_router.converters": "https://reactive-python.github.io/reactpy-router/latest/reference/types/",
    "reactpy_router.converters.conversioninfo": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.ConversionInfo",
    "reactpy_router.hooks.routestate": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.RouteState",
    "reactpy_router.hooks.use_params": "https://reactive-python.github.io/reactpy-router/latest/reference/hooks/#reactpy_router.use_params",
    "reactpy_router.hooks.use_search_params": "https://reactive-python.github.io/reactpy-router/latest/reference/hooks/#reactpy_router.use_search_params",
    "reactpy_router.link": "https://reactive-python.github.io/reactpy-router/latest/reference/components/#reactpy_router.link",
    "reactpy_router.navigate": "https://reactive-python.github.io/reactpy-router/latest/reference/components/#reactpy_router.navigate",
    "reactpy_router.resolvers": "https://reactive-python.github.io/reactpy-router/latest/reference/types/",
    "reactpy_router.resolvers.conversioninfo": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.ConversionInfo",
    "reactpy_router.resolvers.convertermapping": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.ConverterMapping",
    "reactpy_router.resolvers.matchedroute": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.MatchedRoute",
    "reactpy_router.resolvers.route": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.Route",
    "reactpy_router.route": "https://reactive-python.github.io/reactpy-router/latest/reference/components/#reactpy_router.route",
    "reactpy_router.routers.browser_router": "https://reactive-python.github.io/reactpy-router/latest/reference/routers/#reactpy_router.browser_router",
    "reactpy_router.routers.compiledroute": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.CompiledRoute",
    "reactpy_router.routers.matchedroute": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.MatchedRoute",
    "reactpy_router.routers.resolver": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.Resolver",
    "reactpy_router.routers.route": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.Route",
    "reactpy_router.routers.router": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.Router",
    "reactpy_router.routers.routestate": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.RouteState",
    "reactpy_router.types": "https://reactive-python.github.io/reactpy-router/latest/reference/types/",
    "reactpy_router.types.compiledroute": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.CompiledRoute",
    "reactpy_router.types.compiledroute.resolve": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.CompiledRoute.resolve",
    "reactpy_router.types.conversionfunc": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.ConversionFunc",
    "reactpy_router.types.conversioninfo": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.ConversionInfo",
    "reactpy_router.types.convertermapping": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.ConverterMapping",
    "reactpy_router.types.matchedroute": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.MatchedRoute",
    "reactpy_router.types.resolver": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.Resolver",
    "reactpy_router.types.resolver.__call__": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.Resolver.__call__",
    "reactpy_router.types.route": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.Route",
    "reactpy_router.types.router": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.Router",
    "reactpy_router.types.router.__call__": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.Router.__call__",
    "reactpy_router.types.routestate": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.RouteState",
    "reactpy_router.types.routetype_contra": "https://reactive-python.github.io/reactpy-router/latest/reference/types/#reactpy_router.types.RouteType_contra",
    "reactpy_router.use_params": "https://reactive-python.github.io/reactpy-router/latest/reference/hooks/#reactpy_router.use_params",
    "reactpy_router.use_search_params": "https://reactive-python.github.io/reactpy-router/latest/reference/hooks/#reactpy_router.use_search_params",
}
