VERSION = "0.13.0"

# fmt: off
MAPPING = {
    "regionmask": "https://regionmask.readthedocs.io/en/stable/",
    "regionmask._oneregion": "https://regionmask.readthedocs.io/en/stable/generated/regionmask._OneRegion.html#regionmask._OneRegion",
    "regionmask._oneregion.__init__": "https://regionmask.readthedocs.io/en/stable/generated/regionmask._OneRegion.html#regionmask._OneRegion.__init__",
    "regionmask._oneregion.bounds": "https://regionmask.readthedocs.io/en/stable/generated/regionmask._OneRegion.bounds.html#regionmask._OneRegion.bounds",
    "regionmask._oneregion.coords": "https://regionmask.readthedocs.io/en/stable/generated/regionmask._OneRegion.coords.html#regionmask._OneRegion.coords",
    "regionmask.core.options": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.set_options.html",
    "regionmask.core.options.set_options": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.set_options.html#regionmask.set_options",
    "regionmask.core.regions._oneregion": "https://regionmask.readthedocs.io/en/stable/generated/regionmask._OneRegion.html#regionmask._OneRegion",
    "regionmask.core.regions.regions": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.html#regionmask.Regions",
    "regionmask.core.utils._is_180": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.core.utils._is_180.html#regionmask.core.utils._is_180",
    "regionmask.core.utils._wrapangle": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.core.utils._wrapAngle.html#regionmask.core.utils._wrapAngle",
    "regionmask.core.utils._wrapangle180": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.core.utils._wrapAngle180.html#regionmask.core.utils._wrapAngle180",
    "regionmask.core.utils._wrapangle360": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.core.utils._wrapAngle360.html#regionmask.core.utils._wrapAngle360",
    "regionmask.flatten_3d_mask": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.flatten_3D_mask.html#regionmask.flatten_3D_mask",
    "regionmask.from_geopandas": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.from_geopandas.html#regionmask.from_geopandas",
    "regionmask.get_options": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.get_options.html#regionmask.get_options",
    "regionmask.mask_3d_geopandas": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.mask_3D_geopandas.html#regionmask.mask_3D_geopandas",
    "regionmask.mask_geopandas": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.mask_geopandas.html#regionmask.mask_geopandas",
    "regionmask.plot_3d_mask": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.plot_3D_mask.html#regionmask.plot_3D_mask",
    "regionmask.regions": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.html#regionmask.Regions",
    "regionmask.regions.__getitem__": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.__getitem__.html#regionmask.Regions.__getitem__",
    "regionmask.regions.__init__": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.html#regionmask.Regions.__init__",
    "regionmask.regions.abbrevs": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.abbrevs.html#regionmask.Regions.abbrevs",
    "regionmask.regions.bounds": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.bounds.html#regionmask.Regions.bounds",
    "regionmask.regions.bounds_global": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.bounds_global.html#regionmask.Regions.bounds_global",
    "regionmask.regions.centroids": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.centroids.html#regionmask.Regions.centroids",
    "regionmask.regions.from_geodataframe": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.from_geodataframe.html#regionmask.Regions.from_geodataframe",
    "regionmask.regions.lon_180": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.lon_180.html#regionmask.Regions.lon_180",
    "regionmask.regions.lon_360": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.lon_360.html#regionmask.Regions.lon_360",
    "regionmask.regions.map_keys": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.map_keys.html#regionmask.Regions.map_keys",
    "regionmask.regions.mask": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.mask.html#regionmask.Regions.mask",
    "regionmask.regions.mask_3d": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.mask_3D.html#regionmask.Regions.mask_3D",
    "regionmask.regions.mask_3d_frac_approx": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.mask_3D_frac_approx.html#regionmask.Regions.mask_3D_frac_approx",
    "regionmask.regions.names": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.names.html#regionmask.Regions.names",
    "regionmask.regions.numbers": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.numbers.html#regionmask.Regions.numbers",
    "regionmask.regions.plot": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.plot.html#regionmask.Regions.plot",
    "regionmask.regions.plot_regions": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.plot_regions.html#regionmask.Regions.plot_regions",
    "regionmask.regions.polygons": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.polygons.html#regionmask.Regions.polygons",
    "regionmask.regions.to_dataframe": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.to_dataframe.html#regionmask.Regions.to_dataframe",
    "regionmask.regions.to_geodataframe": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.to_geodataframe.html#regionmask.Regions.to_geodataframe",
    "regionmask.regions.to_geoseries": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.Regions.to_geoseries.html#regionmask.Regions.to_geoseries",
    "regionmask.set_options": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.set_options.html#regionmask.set_options",
    "regionmask.set_options.__init__": "https://regionmask.readthedocs.io/en/stable/generated/regionmask.set_options.html#regionmask.set_options.__init__",
}
