VERSION = "5.1.2"

# fmt: off
MAPPING = {
    "cppheaderparser": "https://cppheaderparser.readthedocs.io/en/stable/",
    "cppheaderparser.cppheaderparser": "https://cppheaderparser.readthedocs.io/en/stable/api.html#module-CppHeaderParser.CppHeaderParser",
    "cppheaderparser.cppheaderparser.cppbasedecl": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppBaseDecl",
    "cppheaderparser.cppheaderparser.cppclass": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppClass",
    "cppheaderparser.cppheaderparser.cppclass.get_all_method_names": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppClass.get_all_method_names",
    "cppheaderparser.cppheaderparser.cppclass.get_all_methods": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppClass.get_all_methods",
    "cppheaderparser.cppheaderparser.cppclass.get_all_pure_virtual_methods": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppClass.get_all_pure_virtual_methods",
    "cppheaderparser.cppheaderparser.cppclass.get_method_names": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppClass.get_method_names",
    "cppheaderparser.cppheaderparser.cppclass.get_pure_virtual_methods": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppClass.get_pure_virtual_methods",
    "cppheaderparser.cppheaderparser.cppclass.show": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppClass.show",
    "cppheaderparser.cppheaderparser.cppenum": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppEnum",
    "cppheaderparser.cppheaderparser.cppheader": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader",
    "cppheaderparser.cppheaderparser.cppheader.classes": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.classes",
    "cppheaderparser.cppheaderparser.cppheader.defines": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.defines",
    "cppheaderparser.cppheaderparser.cppheader.defines_detail": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.defines_detail",
    "cppheaderparser.cppheaderparser.cppheader.enums": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.enums",
    "cppheaderparser.cppheaderparser.cppheader.functions": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.functions",
    "cppheaderparser.cppheaderparser.cppheader.headerfilenames": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.headerFileNames",
    "cppheaderparser.cppheaderparser.cppheader.ignore_names": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.IGNORE_NAMES",
    "cppheaderparser.cppheaderparser.cppheader.includes": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.includes",
    "cppheaderparser.cppheaderparser.cppheader.includes_detail": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.includes_detail",
    "cppheaderparser.cppheaderparser.cppheader.namespaces": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.nameSpaces",
    "cppheaderparser.cppheaderparser.cppheader.pragmas": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.pragmas",
    "cppheaderparser.cppheaderparser.cppheader.pragmas_detail": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.pragmas_detail",
    "cppheaderparser.cppheaderparser.cppheader.show": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.show",
    "cppheaderparser.cppheaderparser.cppheader.tojson": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.toJSON",
    "cppheaderparser.cppheaderparser.cppheader.using": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.using",
    "cppheaderparser.cppheaderparser.cppheader.variables": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppHeader.variables",
    "cppheaderparser.cppheaderparser.cppmethod": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppMethod",
    "cppheaderparser.cppheaderparser.cppmethod.show": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppMethod.show",
    "cppheaderparser.cppheaderparser.cppparseerror": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppParseError",
    "cppheaderparser.cppheaderparser.cpptemplateparam": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppTemplateParam",
    "cppheaderparser.cppheaderparser.cppunion": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppUnion",
    "cppheaderparser.cppheaderparser.cppunion.show": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppUnion.show",
    "cppheaderparser.cppheaderparser.cppunion.transform_to_union_keys": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppUnion.transform_to_union_keys",
    "cppheaderparser.cppheaderparser.cppvariable": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppVariable",
    "cppheaderparser.cppheaderparser.cppvariable.vars": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.CppVariable.Vars",
    "cppheaderparser.cppheaderparser.ignoresymbols": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.ignoreSymbols",
    "cppheaderparser.cppheaderparser.tagstr": "https://cppheaderparser.readthedocs.io/en/stable/api.html#CppHeaderParser.CppHeaderParser.TagStr",
}
