VERSION = "2.0.0"

# fmt: off
MAPPING = {
    "runstats": "https://grantjenks.com/docs/runstats/",
    "runstats.regression": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression",
    "runstats.regression.__add__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__add__",
    "runstats.regression.__copy__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__copy__",
    "runstats.regression.__deepcopy__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__deepcopy__",
    "runstats.regression.__eq__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__eq__",
    "runstats.regression.__iadd__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__iadd__",
    "runstats.regression.__init__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__init__",
    "runstats.regression.__len__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__len__",
    "runstats.regression.__ne__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__ne__",
    "runstats.regression.__reduce__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__reduce__",
    "runstats.regression.__weakref__": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.__weakref__",
    "runstats.regression.clear": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.clear",
    "runstats.regression.copy": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.copy",
    "runstats.regression.correlation": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.correlation",
    "runstats.regression.fromstate": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.fromstate",
    "runstats.regression.get_state": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.get_state",
    "runstats.regression.intercept": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.intercept",
    "runstats.regression.push": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.push",
    "runstats.regression.set_state": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.set_state",
    "runstats.regression.slope": "https://grantjenks.com/docs/runstats/api.html#runstats.Regression.slope",
    "runstats.statistics": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics",
    "runstats.statistics.__add__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__add__",
    "runstats.statistics.__copy__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__copy__",
    "runstats.statistics.__deepcopy__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__deepcopy__",
    "runstats.statistics.__eq__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__eq__",
    "runstats.statistics.__iadd__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__iadd__",
    "runstats.statistics.__imul__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__imul__",
    "runstats.statistics.__init__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__init__",
    "runstats.statistics.__len__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__len__",
    "runstats.statistics.__mul__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__mul__",
    "runstats.statistics.__ne__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__ne__",
    "runstats.statistics.__reduce__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__reduce__",
    "runstats.statistics.__rmul__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__rmul__",
    "runstats.statistics.__weakref__": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.__weakref__",
    "runstats.statistics.clear": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.clear",
    "runstats.statistics.copy": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.copy",
    "runstats.statistics.fromstate": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.fromstate",
    "runstats.statistics.get_state": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.get_state",
    "runstats.statistics.kurtosis": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.kurtosis",
    "runstats.statistics.maximum": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.maximum",
    "runstats.statistics.mean": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.mean",
    "runstats.statistics.minimum": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.minimum",
    "runstats.statistics.push": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.push",
    "runstats.statistics.set_state": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.set_state",
    "runstats.statistics.skewness": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.skewness",
    "runstats.statistics.stddev": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.stddev",
    "runstats.statistics.variance": "https://grantjenks.com/docs/runstats/api.html#runstats.Statistics.variance",
}
