VERSION = "0.2.4"

# fmt: off
MAPPING = {
    "samplerate": "https://python-samplerate.readthedocs.io/en/latest/",
    "samplerate.converters": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#module-samplerate.converters",
    "samplerate.converters.callbackresampler": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.CallbackResampler",
    "samplerate.converters.callbackresampler.ratio": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.CallbackResampler.ratio",
    "samplerate.converters.callbackresampler.read": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.CallbackResampler.read",
    "samplerate.converters.callbackresampler.reset": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.CallbackResampler.reset",
    "samplerate.converters.callbackresampler.set_starting_ratio": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.CallbackResampler.set_starting_ratio",
    "samplerate.converters.convertertype": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.ConverterType",
    "samplerate.converters.convertertype.linear": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.ConverterType.linear",
    "samplerate.converters.convertertype.sinc_best": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.ConverterType.sinc_best",
    "samplerate.converters.convertertype.sinc_fastest": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.ConverterType.sinc_fastest",
    "samplerate.converters.convertertype.sinc_medium": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.ConverterType.sinc_medium",
    "samplerate.converters.convertertype.zero_order_hold": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.ConverterType.zero_order_hold",
    "samplerate.converters.resample": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.resample",
    "samplerate.converters.resampler": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.Resampler",
    "samplerate.converters.resampler.channels": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.Resampler.channels",
    "samplerate.converters.resampler.converter_type": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.Resampler.converter_type",
    "samplerate.converters.resampler.process": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.Resampler.process",
    "samplerate.converters.resampler.reset": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.Resampler.reset",
    "samplerate.converters.resampler.set_ratio": "https://python-samplerate.readthedocs.io/en/latest/samplerate/converters.html#samplerate.converters.Resampler.set_ratio",
    "samplerate.exceptions": "https://python-samplerate.readthedocs.io/en/latest/samplerate/exceptions.html#module-samplerate.exceptions",
    "samplerate.exceptions.resamplingerror": "https://python-samplerate.readthedocs.io/en/latest/samplerate/exceptions.html#samplerate.exceptions.ResamplingError",
    "samplerate.lowlevel": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#module-samplerate.lowlevel",
    "samplerate.lowlevel.src_callback_new": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_callback_new",
    "samplerate.lowlevel.src_callback_read": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_callback_read",
    "samplerate.lowlevel.src_delete": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_delete",
    "samplerate.lowlevel.src_error": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_error",
    "samplerate.lowlevel.src_get_description": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_get_description",
    "samplerate.lowlevel.src_get_name": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_get_name",
    "samplerate.lowlevel.src_get_version": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_get_version",
    "samplerate.lowlevel.src_is_valid_ratio": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_is_valid_ratio",
    "samplerate.lowlevel.src_new": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_new",
    "samplerate.lowlevel.src_process": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_process",
    "samplerate.lowlevel.src_reset": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_reset",
    "samplerate.lowlevel.src_set_ratio": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_set_ratio",
    "samplerate.lowlevel.src_simple": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_simple",
    "samplerate.lowlevel.src_strerror": "https://python-samplerate.readthedocs.io/en/latest/samplerate/lowlevel.html#samplerate.lowlevel.src_strerror",
    "samplerate.samplerate": "https://python-samplerate.readthedocs.io/en/latest/samplerate/samplerate.html",
    "samplerate.samplerate.callbackresampler": "https://python-samplerate.readthedocs.io/en/latest/samplerate/samplerate.html#samplerate.samplerate.CallbackResampler",
    "samplerate.samplerate.resample": "https://python-samplerate.readthedocs.io/en/latest/samplerate/samplerate.html#samplerate.samplerate.resample",
    "samplerate.samplerate.resampler": "https://python-samplerate.readthedocs.io/en/latest/samplerate/samplerate.html#samplerate.samplerate.Resampler",
    "samplerate.samplerate.resamplingerror": "https://python-samplerate.readthedocs.io/en/latest/samplerate/samplerate.html#samplerate.samplerate.ResamplingError",
}
