VERSION = "1.0.2"

# fmt: off
MAPPING = {
    "sauceclient": "https://sauceclient.readthedocs.io/",
    "sauceclient.account": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account",
    "sauceclient.account.change_access_key": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account.change_access_key",
    "sauceclient.account.create_user": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account.create_user",
    "sauceclient.account.get_activity": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account.get_activity",
    "sauceclient.account.get_concurrency": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account.get_concurrency",
    "sauceclient.account.get_siblings": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account.get_siblings",
    "sauceclient.account.get_subaccount_info": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account.get_subaccount_info",
    "sauceclient.account.get_subaccounts": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account.get_subaccounts",
    "sauceclient.account.get_usage": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account.get_usage",
    "sauceclient.account.get_user": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Account.get_user",
    "sauceclient.analytics": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Analytics",
    "sauceclient.analytics.get_build_trends": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Analytics.get_build_trends",
    "sauceclient.analytics.get_concurrency": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Analytics.get_concurrency",
    "sauceclient.analytics.get_error_trends": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Analytics.get_error_trends",
    "sauceclient.analytics.get_test_trends": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Analytics.get_test_trends",
    "sauceclient.analytics.get_tests": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Analytics.get_tests",
    "sauceclient.information": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Information",
    "sauceclient.information.get_appium_eol_dates": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Information.get_appium_eol_dates",
    "sauceclient.information.get_platforms": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Information.get_platforms",
    "sauceclient.information.get_status": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Information.get_status",
    "sauceclient.javascripttests": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.JavaScriptTests",
    "sauceclient.javascripttests.js_tests": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.JavaScriptTests.js_tests",
    "sauceclient.javascripttests.js_tests_status": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.JavaScriptTests.js_tests_status",
    "sauceclient.jobs": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs",
    "sauceclient.jobs.delete_job": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs.delete_job",
    "sauceclient.jobs.delete_job_assets": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs.delete_job_assets",
    "sauceclient.jobs.get_auth_token": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs.get_auth_token",
    "sauceclient.jobs.get_job": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs.get_job",
    "sauceclient.jobs.get_job_asset_url": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs.get_job_asset_url",
    "sauceclient.jobs.get_job_assets": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs.get_job_assets",
    "sauceclient.jobs.get_jobs": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs.get_jobs",
    "sauceclient.jobs.stop_job": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs.stop_job",
    "sauceclient.jobs.update_job": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Jobs.update_job",
    "sauceclient.sauceclient": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.SauceClient",
    "sauceclient.sauceclient.get_auth_string": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.SauceClient.get_auth_string",
    "sauceclient.sauceclient.make_auth_headers": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.SauceClient.make_auth_headers",
    "sauceclient.sauceclient.make_headers": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.SauceClient.make_headers",
    "sauceclient.sauceclient.request": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.SauceClient.request",
    "sauceclient.sauceexception": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.SauceException",
    "sauceclient.storage": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Storage",
    "sauceclient.storage.get_stored_files": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Storage.get_stored_files",
    "sauceclient.storage.upload_file": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Storage.upload_file",
    "sauceclient.tunnels": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Tunnels",
    "sauceclient.tunnels.delete_tunnel": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Tunnels.delete_tunnel",
    "sauceclient.tunnels.get_tunnel": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Tunnels.get_tunnel",
    "sauceclient.tunnels.get_tunnels": "https://sauceclient.readthedocs.io/sauceclient.html#sauceclient.Tunnels.get_tunnels",
}
