VERSION = "0.3.7"

# fmt: off
MAPPING = {
    "scikitplot": "https://scikit-plot.readthedocs.io/en/stable/",
    "scikitplot.classifier_factory": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.classifier_factory",
    "scikitplot.classifiers": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#module-scikitplot.classifiers",
    "scikitplot.classifiers.plot_confusion_matrix_with_cv": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.classifiers.plot_confusion_matrix_with_cv",
    "scikitplot.classifiers.plot_feature_importances": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.classifiers.plot_feature_importances",
    "scikitplot.classifiers.plot_ks_statistic_with_cv": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.classifiers.plot_ks_statistic_with_cv",
    "scikitplot.classifiers.plot_learning_curve": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.classifiers.plot_learning_curve",
    "scikitplot.classifiers.plot_precision_recall_curve_with_cv": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.classifiers.plot_precision_recall_curve_with_cv",
    "scikitplot.classifiers.plot_roc_curve_with_cv": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.classifiers.plot_roc_curve_with_cv",
    "scikitplot.cluster": "https://scikit-plot.readthedocs.io/en/stable/cluster.html#module-scikitplot.cluster",
    "scikitplot.cluster.plot_elbow_curve": "https://scikit-plot.readthedocs.io/en/stable/cluster.html#scikitplot.cluster.plot_elbow_curve",
    "scikitplot.clustering": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#module-scikitplot.clustering",
    "scikitplot.clustering.plot_elbow_curve": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.clustering.plot_elbow_curve",
    "scikitplot.clustering.plot_silhouette": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.clustering.plot_silhouette",
    "scikitplot.clustering_factory": "https://scikit-plot.readthedocs.io/en/stable/apidocs.html#scikitplot.clustering_factory",
    "scikitplot.decomposition": "https://scikit-plot.readthedocs.io/en/stable/decomposition.html#module-scikitplot.decomposition",
    "scikitplot.decomposition.plot_pca_2d_projection": "https://scikit-plot.readthedocs.io/en/stable/decomposition.html#scikitplot.decomposition.plot_pca_2d_projection",
    "scikitplot.decomposition.plot_pca_component_variance": "https://scikit-plot.readthedocs.io/en/stable/decomposition.html#scikitplot.decomposition.plot_pca_component_variance",
    "scikitplot.estimators": "https://scikit-plot.readthedocs.io/en/stable/estimators.html#module-scikitplot.estimators",
    "scikitplot.estimators.plot_feature_importances": "https://scikit-plot.readthedocs.io/en/stable/estimators.html#scikitplot.estimators.plot_feature_importances",
    "scikitplot.estimators.plot_learning_curve": "https://scikit-plot.readthedocs.io/en/stable/estimators.html#scikitplot.estimators.plot_learning_curve",
    "scikitplot.metrics": "https://scikit-plot.readthedocs.io/en/stable/metrics.html#module-scikitplot.metrics",
    "scikitplot.metrics.plot_calibration_curve": "https://scikit-plot.readthedocs.io/en/stable/metrics.html#scikitplot.metrics.plot_calibration_curve",
    "scikitplot.metrics.plot_confusion_matrix": "https://scikit-plot.readthedocs.io/en/stable/metrics.html#scikitplot.metrics.plot_confusion_matrix",
    "scikitplot.metrics.plot_cumulative_gain": "https://scikit-plot.readthedocs.io/en/stable/metrics.html#scikitplot.metrics.plot_cumulative_gain",
    "scikitplot.metrics.plot_ks_statistic": "https://scikit-plot.readthedocs.io/en/stable/metrics.html#scikitplot.metrics.plot_ks_statistic",
    "scikitplot.metrics.plot_lift_curve": "https://scikit-plot.readthedocs.io/en/stable/metrics.html#scikitplot.metrics.plot_lift_curve",
    "scikitplot.metrics.plot_precision_recall": "https://scikit-plot.readthedocs.io/en/stable/metrics.html#scikitplot.metrics.plot_precision_recall",
    "scikitplot.metrics.plot_roc": "https://scikit-plot.readthedocs.io/en/stable/metrics.html#scikitplot.metrics.plot_roc",
    "scikitplot.metrics.plot_silhouette": "https://scikit-plot.readthedocs.io/en/stable/metrics.html#scikitplot.metrics.plot_silhouette",
    "scikitplot.plotters": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#module-scikitplot.plotters",
    "scikitplot.plotters.plot_confusion_matrix": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_confusion_matrix",
    "scikitplot.plotters.plot_elbow_curve": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_elbow_curve",
    "scikitplot.plotters.plot_feature_importances": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_feature_importances",
    "scikitplot.plotters.plot_ks_statistic": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_ks_statistic",
    "scikitplot.plotters.plot_learning_curve": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_learning_curve",
    "scikitplot.plotters.plot_pca_2d_projection": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_pca_2d_projection",
    "scikitplot.plotters.plot_pca_component_variance": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_pca_component_variance",
    "scikitplot.plotters.plot_precision_recall_curve": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_precision_recall_curve",
    "scikitplot.plotters.plot_roc_curve": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_roc_curve",
    "scikitplot.plotters.plot_silhouette": "https://scikit-plot.readthedocs.io/en/stable/functionsapidocs.html#scikitplot.plotters.plot_silhouette",
}
