VERSION = "0.5.2"

# fmt: off
MAPPING = {
    "skmisc": "https://has2k1.github.io/scikit-misc/stable/",
    "skmisc.loess": "https://has2k1.github.io/scikit-misc/stable/loess.html#module-skmisc.loess",
    "skmisc.loess.loess": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess.html#skmisc.loess.loess",
    "skmisc.loess.loess.fit": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess.html#skmisc.loess.loess.fit",
    "skmisc.loess.loess.input_summary": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess.html#skmisc.loess.loess.input_summary",
    "skmisc.loess.loess.output_summary": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess.html#skmisc.loess.loess.output_summary",
    "skmisc.loess.loess.predict": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess.html#skmisc.loess.loess.predict",
    "skmisc.loess.loess_anova": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_anova.html#skmisc.loess.loess_anova",
    "skmisc.loess.loess_confidence_intervals": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_confidence_intervals.html#skmisc.loess.loess_confidence_intervals",
    "skmisc.loess.loess_confidence_intervals.fit": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_confidence_intervals.html#skmisc.loess.loess_confidence_intervals.fit",
    "skmisc.loess.loess_confidence_intervals.lower": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_confidence_intervals.html#skmisc.loess.loess_confidence_intervals.lower",
    "skmisc.loess.loess_confidence_intervals.upper": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_confidence_intervals.html#skmisc.loess.loess_confidence_intervals.upper",
    "skmisc.loess.loess_control": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_control.html#skmisc.loess.loess_control",
    "skmisc.loess.loess_inputs": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_inputs.html#skmisc.loess.loess_inputs",
    "skmisc.loess.loess_inputs.n": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_inputs.html#skmisc.loess.loess_inputs.n",
    "skmisc.loess.loess_inputs.p": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_inputs.html#skmisc.loess.loess_inputs.p",
    "skmisc.loess.loess_inputs.x": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_inputs.html#skmisc.loess.loess_inputs.x",
    "skmisc.loess.loess_inputs.y": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_inputs.html#skmisc.loess.loess_inputs.y",
    "skmisc.loess.loess_model": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_model.html#skmisc.loess.loess_model",
    "skmisc.loess.loess_outputs": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs",
    "skmisc.loess.loess_outputs.diagonal": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.diagonal",
    "skmisc.loess.loess_outputs.divisor": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.divisor",
    "skmisc.loess.loess_outputs.enp": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.enp",
    "skmisc.loess.loess_outputs.fitted_residuals": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.fitted_residuals",
    "skmisc.loess.loess_outputs.fitted_values": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.fitted_values",
    "skmisc.loess.loess_outputs.one_delta": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.one_delta",
    "skmisc.loess.loess_outputs.pseudovalues": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.pseudovalues",
    "skmisc.loess.loess_outputs.residual_scale": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.residual_scale",
    "skmisc.loess.loess_outputs.robust": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.robust",
    "skmisc.loess.loess_outputs.trace_hat": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.trace_hat",
    "skmisc.loess.loess_outputs.two_delta": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_outputs.html#skmisc.loess.loess_outputs.two_delta",
    "skmisc.loess.loess_prediction": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_prediction.html#skmisc.loess.loess_prediction",
    "skmisc.loess.loess_prediction.confidence": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_prediction.html#skmisc.loess.loess_prediction.confidence",
    "skmisc.loess.loess_prediction.df": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_prediction.html#skmisc.loess.loess_prediction.df",
    "skmisc.loess.loess_prediction.m": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_prediction.html#skmisc.loess.loess_prediction.m",
    "skmisc.loess.loess_prediction.residual_scale": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_prediction.html#skmisc.loess.loess_prediction.residual_scale",
    "skmisc.loess.loess_prediction.stderr": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_prediction.html#skmisc.loess.loess_prediction.stderr",
    "skmisc.loess.loess_prediction.values": "https://has2k1.github.io/scikit-misc/stable/generated/skmisc.loess.loess_prediction.html#skmisc.loess.loess_prediction.values",
}
