VERSION = "0.7.0"

# fmt: off
MAPPING = {
    "scim2_filter_parser": "https://scim2-filter-parser.readthedocs.io/en/stable/",
    "scim2_filter_parser.ast": "https://scim2-filter-parser.readthedocs.io/en/stable/ast.html#module-scim2_filter_parser.ast",
    "scim2_filter_parser.ast.flatten": "https://scim2-filter-parser.readthedocs.io/en/stable/ast.html#scim2_filter_parser.ast.flatten",
    "scim2_filter_parser.ast.nodevisitor": "https://scim2-filter-parser.readthedocs.io/en/stable/ast.html#scim2_filter_parser.ast.NodeVisitor",
    "scim2_filter_parser.ast.nodevisitor.generic_visit": "https://scim2-filter-parser.readthedocs.io/en/stable/ast.html#scim2_filter_parser.ast.NodeVisitor.generic_visit",
    "scim2_filter_parser.ast.nodevisitor.visit": "https://scim2-filter-parser.readthedocs.io/en/stable/ast.html#scim2_filter_parser.ast.NodeVisitor.visit",
    "scim2_filter_parser.ast.visitdict": "https://scim2-filter-parser.readthedocs.io/en/stable/ast.html#scim2_filter_parser.ast.VisitDict",
    "scim2_filter_parser.attr_paths": "https://scim2-filter-parser.readthedocs.io/en/stable/attr_paths.html#module-scim2_filter_parser.attr_paths",
    "scim2_filter_parser.attr_paths.attrpath": "https://scim2-filter-parser.readthedocs.io/en/stable/attr_paths.html#scim2_filter_parser.attr_paths.AttrPath",
    "scim2_filter_parser.attr_paths.attrpath.first_path": "https://scim2-filter-parser.readthedocs.io/en/stable/attr_paths.html#scim2_filter_parser.attr_paths.AttrPath.first_path",
    "scim2_filter_parser.attr_paths.attrpath.is_complex": "https://scim2-filter-parser.readthedocs.io/en/stable/attr_paths.html#scim2_filter_parser.attr_paths.AttrPath.is_complex",
    "scim2_filter_parser.attr_paths.attrpath.params_by_attr_paths": "https://scim2-filter-parser.readthedocs.io/en/stable/attr_paths.html#scim2_filter_parser.attr_paths.AttrPath.params_by_attr_paths",
    "scim2_filter_parser.attr_paths.main": "https://scim2-filter-parser.readthedocs.io/en/stable/attr_paths.html#scim2_filter_parser.attr_paths.main",
    "scim2_filter_parser.lexer": "https://scim2-filter-parser.readthedocs.io/en/stable/lexer.html#module-scim2_filter_parser.lexer",
    "scim2_filter_parser.lexer.main": "https://scim2-filter-parser.readthedocs.io/en/stable/lexer.html#scim2_filter_parser.lexer.main",
    "scim2_filter_parser.parser": "https://scim2-filter-parser.readthedocs.io/en/stable/parser.html#module-scim2_filter_parser.parser",
    "scim2_filter_parser.parser.main": "https://scim2-filter-parser.readthedocs.io/en/stable/parser.html#scim2_filter_parser.parser.main",
    "scim2_filter_parser.parser.scimparsererror": "https://scim2-filter-parser.readthedocs.io/en/stable/parser.html#scim2_filter_parser.parser.SCIMParserError",
    "scim2_filter_parser.queries": "https://scim2-filter-parser.readthedocs.io/en/stable/queries/sql.html",
    "scim2_filter_parser.queries.sql": "https://scim2-filter-parser.readthedocs.io/en/stable/queries/sql.html#module-scim2_filter_parser.queries.sql",
    "scim2_filter_parser.queries.sql.main": "https://scim2-filter-parser.readthedocs.io/en/stable/queries/sql.html#scim2_filter_parser.queries.sql.main",
    "scim2_filter_parser.transpilers": "https://scim2-filter-parser.readthedocs.io/en/stable/transpilers/sql.html",
    "scim2_filter_parser.transpilers.sql": "https://scim2-filter-parser.readthedocs.io/en/stable/transpilers/sql.html#module-scim2_filter_parser.transpilers.sql",
    "scim2_filter_parser.transpilers.sql.attrpath": "https://scim2-filter-parser.readthedocs.io/en/stable/transpilers/sql.html#scim2_filter_parser.transpilers.sql.AttrPath",
    "scim2_filter_parser.transpilers.sql.attrpath.attr_name": "https://scim2-filter-parser.readthedocs.io/en/stable/transpilers/sql.html#scim2_filter_parser.transpilers.sql.AttrPath.attr_name",
    "scim2_filter_parser.transpilers.sql.attrpath.sub_attr": "https://scim2-filter-parser.readthedocs.io/en/stable/transpilers/sql.html#scim2_filter_parser.transpilers.sql.AttrPath.sub_attr",
    "scim2_filter_parser.transpilers.sql.attrpath.uri": "https://scim2-filter-parser.readthedocs.io/en/stable/transpilers/sql.html#scim2_filter_parser.transpilers.sql.AttrPath.uri",
    "scim2_filter_parser.transpilers.sql.main": "https://scim2-filter-parser.readthedocs.io/en/stable/transpilers/sql.html#scim2_filter_parser.transpilers.sql.main",
    "scim2_filter_parser.transpilers.sql.transpiler": "https://scim2-filter-parser.readthedocs.io/en/stable/transpilers/sql.html#scim2_filter_parser.transpilers.sql.Transpiler",
    "scim2_filter_parser.transpilers.sql.transpiler.visit_partialattrexpr": "https://scim2-filter-parser.readthedocs.io/en/stable/transpilers/sql.html#scim2_filter_parser.transpilers.sql.Transpiler.visit_PartialAttrExpr",
}
