VERSION = "1.6.0"

# fmt: off
MAPPING = {
    "scrapyd": "https://scrapyd.readthedocs.io/en/stable/",
    "scrapyd.config": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#module-scrapyd.config",
    "scrapyd.config.config": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.config.Config",
    "scrapyd.config.config.get": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.config.Config.get",
    "scrapyd.config.config.getboolean": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.config.Config.getboolean",
    "scrapyd.config.config.getfloat": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.config.Config.getfloat",
    "scrapyd.config.config.getint": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.config.Config.getint",
    "scrapyd.config.config.items": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.config.Config.items",
    "scrapyd.config.config.section": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.config.Config.SECTION",
    "scrapyd.exceptions": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#module-scrapyd.exceptions",
    "scrapyd.exceptions.badeggerror": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.exceptions.BadEggError",
    "scrapyd.exceptions.configerror": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.exceptions.ConfigError",
    "scrapyd.exceptions.directorytraversalerror": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.exceptions.DirectoryTraversalError",
    "scrapyd.exceptions.eggnotfounderror": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.exceptions.EggNotFoundError",
    "scrapyd.exceptions.invalidusernameerror": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.exceptions.InvalidUsernameError",
    "scrapyd.exceptions.projectnotfounderror": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.exceptions.ProjectNotFoundError",
    "scrapyd.exceptions.runnererror": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.exceptions.RunnerError",
    "scrapyd.exceptions.scrapyderror": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.exceptions.ScrapydError",
    "scrapyd.interfaces": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#module-scrapyd.interfaces",
    "scrapyd.interfaces.ieggstorage": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IEggStorage",
    "scrapyd.interfaces.ieggstorage.delete": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IEggStorage.delete",
    "scrapyd.interfaces.ieggstorage.get": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IEggStorage.get",
    "scrapyd.interfaces.ieggstorage.list": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IEggStorage.list",
    "scrapyd.interfaces.ieggstorage.list_projects": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IEggStorage.list_projects",
    "scrapyd.interfaces.ieggstorage.put": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IEggStorage.put",
    "scrapyd.interfaces.ienvironment": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IEnvironment",
    "scrapyd.interfaces.ienvironment.get_environment": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IEnvironment.get_environment",
    "scrapyd.interfaces.ienvironment.get_settings": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IEnvironment.get_settings",
    "scrapyd.interfaces.ijobstorage": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IJobStorage",
    "scrapyd.interfaces.ijobstorage.__iter__": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IJobStorage.__iter__",
    "scrapyd.interfaces.ijobstorage.__len__": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IJobStorage.__len__",
    "scrapyd.interfaces.ijobstorage.add": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IJobStorage.add",
    "scrapyd.interfaces.ijobstorage.list": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IJobStorage.list",
    "scrapyd.interfaces.ipoller": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IPoller",
    "scrapyd.interfaces.ipoller.next": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IPoller.next",
    "scrapyd.interfaces.ipoller.poll": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IPoller.poll",
    "scrapyd.interfaces.ipoller.queues": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IPoller.queues",
    "scrapyd.interfaces.ipoller.update_projects": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.IPoller.update_projects",
    "scrapyd.interfaces.ispiderqueue": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderQueue",
    "scrapyd.interfaces.ispiderqueue.add": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderQueue.add",
    "scrapyd.interfaces.ispiderqueue.clear": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderQueue.clear",
    "scrapyd.interfaces.ispiderqueue.count": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderQueue.count",
    "scrapyd.interfaces.ispiderqueue.list": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderQueue.list",
    "scrapyd.interfaces.ispiderqueue.pop": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderQueue.pop",
    "scrapyd.interfaces.ispiderqueue.remove": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderQueue.remove",
    "scrapyd.interfaces.ispiderscheduler": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderScheduler",
    "scrapyd.interfaces.ispiderscheduler.list_projects": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderScheduler.list_projects",
    "scrapyd.interfaces.ispiderscheduler.schedule": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderScheduler.schedule",
    "scrapyd.interfaces.ispiderscheduler.update_projects": "https://scrapyd.readthedocs.io/en/stable/contributing/api.html#scrapyd.interfaces.ISpiderScheduler.update_projects",
}
