VERSION = "0.4.3"

# fmt: off
MAPPING = {
    "seqlog": "https://seqlog.readthedocs.io/en/latest/",
    "seqlog.clear_global_log_properties": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.clear_global_log_properties",
    "seqlog.configure_from_dict": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.configure_from_dict",
    "seqlog.configure_from_file": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.configure_from_file",
    "seqlog.feature_flags": "https://seqlog.readthedocs.io/en/latest/feature_flags.html",
    "seqlog.feature_flags.configure_feature": "https://seqlog.readthedocs.io/en/latest/feature_flags.html#seqlog.feature_flags.configure_feature",
    "seqlog.feature_flags.disable_feature": "https://seqlog.readthedocs.io/en/latest/feature_flags.html#seqlog.feature_flags.disable_feature",
    "seqlog.feature_flags.enable_feature": "https://seqlog.readthedocs.io/en/latest/feature_flags.html#seqlog.feature_flags.enable_feature",
    "seqlog.feature_flags.featureflag": "https://seqlog.readthedocs.io/en/latest/feature_flags.html#seqlog.feature_flags.FeatureFlag",
    "seqlog.feature_flags.featureflag.extra_properties": "https://seqlog.readthedocs.io/en/latest/feature_flags.html#seqlog.feature_flags.FeatureFlag.EXTRA_PROPERTIES",
    "seqlog.feature_flags.featureflag.ignore_seq_submission_errors": "https://seqlog.readthedocs.io/en/latest/feature_flags.html#seqlog.feature_flags.FeatureFlag.IGNORE_SEQ_SUBMISSION_ERRORS",
    "seqlog.feature_flags.featureflag.stack_info": "https://seqlog.readthedocs.io/en/latest/feature_flags.html#seqlog.feature_flags.FeatureFlag.STACK_INFO",
    "seqlog.feature_flags.featureflag.use_clef": "https://seqlog.readthedocs.io/en/latest/feature_flags.html#seqlog.feature_flags.FeatureFlag.USE_CLEF",
    "seqlog.get_global_log_properties": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.get_global_log_properties",
    "seqlog.log_to_console": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.log_to_console",
    "seqlog.log_to_seq": "https://seqlog.readthedocs.io/en/latest/usage.html#seqlog.log_to_seq",
    "seqlog.reset_global_log_properties": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.reset_global_log_properties",
    "seqlog.set_callback_on_failure": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.set_callback_on_failure",
    "seqlog.set_global_log_properties": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.set_global_log_properties",
    "seqlog.structured_logging": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#module-seqlog.structured_logging",
    "seqlog.structured_logging.best_effort_json_encode": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.best_effort_json_encode",
    "seqlog.structured_logging.clear_global_log_properties": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.clear_global_log_properties",
    "seqlog.structured_logging.consolestructuredloghandler": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.ConsoleStructuredLogHandler",
    "seqlog.structured_logging.consolestructuredloghandler.emit": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.ConsoleStructuredLogHandler.emit",
    "seqlog.structured_logging.get_global_log_properties": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.get_global_log_properties",
    "seqlog.structured_logging.reset_global_log_properties": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.reset_global_log_properties",
    "seqlog.structured_logging.seqloghandler": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.SeqLogHandler",
    "seqlog.structured_logging.seqloghandler.close": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.SeqLogHandler.close",
    "seqlog.structured_logging.seqloghandler.emit": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.SeqLogHandler.emit",
    "seqlog.structured_logging.seqloghandler.flush": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.SeqLogHandler.flush",
    "seqlog.structured_logging.seqloghandler.handleerror": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.SeqLogHandler.handleError",
    "seqlog.structured_logging.seqloghandler.publish_log_batch": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.SeqLogHandler.publish_log_batch",
    "seqlog.structured_logging.seqloghandler.server_url": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.SeqLogHandler.server_url",
    "seqlog.structured_logging.set_callback_on_failure": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.set_callback_on_failure",
    "seqlog.structured_logging.set_global_log_properties": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.set_global_log_properties",
    "seqlog.structured_logging.structuredlogger": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.StructuredLogger",
    "seqlog.structured_logging.structuredlogger.makerecord": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.StructuredLogger.makeRecord",
    "seqlog.structured_logging.structuredlogrecord": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.StructuredLogRecord",
    "seqlog.structured_logging.structuredlogrecord.getmessage": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.StructuredLogRecord.getMessage",
    "seqlog.structured_logging.structuredlogrecord.getmessagetemplate": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.StructuredLogRecord.getMessageTemplate",
    "seqlog.structured_logging.structuredrootlogger": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.StructuredRootLogger",
    "seqlog.structured_logging.structuredrootlogger.makerecord": "https://seqlog.readthedocs.io/en/latest/api/seqlog.html#seqlog.structured_logging.StructuredRootLogger.makeRecord",
}
