VERSION = "2.12.3"

# fmt: off
MAPPING = {
    "setuptools_dso": "https://mdavidsaver.github.io/setuptools_dso/",
    "setuptools_dso.cythonize": "https://mdavidsaver.github.io/setuptools_dso/usage.html#setuptools_dso.cythonize",
    "setuptools_dso.dso": "https://mdavidsaver.github.io/setuptools_dso/usage.html#setuptools_dso.DSO",
    "setuptools_dso.dsocmd": "https://mdavidsaver.github.io/setuptools_dso/usage.html",
    "setuptools_dso.dsocmd.dso": "https://mdavidsaver.github.io/setuptools_dso/usage.html#setuptools_dso.DSO",
    "setuptools_dso.dsocmd.extension": "https://mdavidsaver.github.io/setuptools_dso/usage.html#setuptools_dso.Extension",
    "setuptools_dso.dylink_prepare_dso": "https://mdavidsaver.github.io/setuptools_dso/usage.html#setuptools_dso.dylink_prepare_dso",
    "setuptools_dso.extension": "https://mdavidsaver.github.io/setuptools_dso/usage.html#setuptools_dso.Extension",
    "setuptools_dso.find_dso": "https://mdavidsaver.github.io/setuptools_dso/usage.html#setuptools_dso.find_dso",
    "setuptools_dso.probe": "https://mdavidsaver.github.io/setuptools_dso/probe.html",
    "setuptools_dso.probe.probetoolchain": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain",
    "setuptools_dso.probe.toolchaininfo": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.probe.ToolchainInfo",
    "setuptools_dso.probe.toolchaininfo.address_width": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.probe.ToolchainInfo.address_width",
    "setuptools_dso.probe.toolchaininfo.compiler": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.probe.ToolchainInfo.compiler",
    "setuptools_dso.probe.toolchaininfo.compiler_type": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.probe.ToolchainInfo.compiler_type",
    "setuptools_dso.probe.toolchaininfo.compiler_version": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.probe.ToolchainInfo.compiler_version",
    "setuptools_dso.probe.toolchaininfo.endian": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.probe.ToolchainInfo.endian",
    "setuptools_dso.probe.toolchaininfo.gnuish": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.probe.ToolchainInfo.gnuish",
    "setuptools_dso.probe.toolchaininfo.target_arch": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.probe.ToolchainInfo.target_arch",
    "setuptools_dso.probe.toolchaininfo.target_os": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.probe.ToolchainInfo.target_os",
    "setuptools_dso.probetoolchain": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain",
    "setuptools_dso.probetoolchain.check_include": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain.check_include",
    "setuptools_dso.probetoolchain.check_includes": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain.check_includes",
    "setuptools_dso.probetoolchain.check_member": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain.check_member",
    "setuptools_dso.probetoolchain.check_symbol": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain.check_symbol",
    "setuptools_dso.probetoolchain.compile": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain.compile",
    "setuptools_dso.probetoolchain.eval_macros": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain.eval_macros",
    "setuptools_dso.probetoolchain.info": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain.info",
    "setuptools_dso.probetoolchain.sizeof": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain.sizeof",
    "setuptools_dso.probetoolchain.try_compile": "https://mdavidsaver.github.io/setuptools_dso/probe.html#setuptools_dso.ProbeToolchain.try_compile",
    "setuptools_dso.runtime": "https://mdavidsaver.github.io/setuptools_dso/usage.html",
    "setuptools_dso.runtime.import_dsoinfo": "https://mdavidsaver.github.io/setuptools_dso/usage.html#setuptools_dso.runtime.import_dsoinfo",
    "setuptools_dso.setup": "https://mdavidsaver.github.io/setuptools_dso/usage.html#setuptools_dso.setup",
}
