VERSION = "1.2.2"

# fmt: off
MAPPING = {
    "sftpretty": "https://docs.sftpretty.com/",
    "sftpretty.cnopts": "https://docs.sftpretty.com/sftpretty.html#sftpretty.CnOpts",
    "sftpretty.cnopts.get_agentkey": "https://docs.sftpretty.com/sftpretty.html#sftpretty.CnOpts.get_agentkey",
    "sftpretty.cnopts.get_config": "https://docs.sftpretty.com/sftpretty.html#sftpretty.CnOpts.get_config",
    "sftpretty.cnopts.get_hostkey": "https://docs.sftpretty.com/sftpretty.html#sftpretty.CnOpts.get_hostkey",
    "sftpretty.connection": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection",
    "sftpretty.connection.active_ciphers": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.active_ciphers",
    "sftpretty.connection.active_compression": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.active_compression",
    "sftpretty.connection.cd": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.cd",
    "sftpretty.connection.chdir": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.chdir",
    "sftpretty.connection.chmod": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.chmod",
    "sftpretty.connection.chown": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.chown",
    "sftpretty.connection.close": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.close",
    "sftpretty.connection.execute": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.execute",
    "sftpretty.connection.exists": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.exists",
    "sftpretty.connection.get": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.get",
    "sftpretty.connection.get_d": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.get_d",
    "sftpretty.connection.get_r": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.get_r",
    "sftpretty.connection.getcwd": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.getcwd",
    "sftpretty.connection.getfo": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.getfo",
    "sftpretty.connection.isdir": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.isdir",
    "sftpretty.connection.isfile": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.isfile",
    "sftpretty.connection.lexists": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.lexists",
    "sftpretty.connection.listdir": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.listdir",
    "sftpretty.connection.listdir_attr": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.listdir_attr",
    "sftpretty.connection.logfile": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.logfile",
    "sftpretty.connection.lstat": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.lstat",
    "sftpretty.connection.mkdir": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.mkdir",
    "sftpretty.connection.mkdir_p": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.mkdir_p",
    "sftpretty.connection.normalize": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.normalize",
    "sftpretty.connection.open": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.open",
    "sftpretty.connection.put": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.put",
    "sftpretty.connection.put_d": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.put_d",
    "sftpretty.connection.put_r": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.put_r",
    "sftpretty.connection.putfo": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.putfo",
    "sftpretty.connection.pwd": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.pwd",
    "sftpretty.connection.readlink": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.readlink",
    "sftpretty.connection.remote_server_key": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.remote_server_key",
    "sftpretty.connection.remotetree": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.remotetree",
    "sftpretty.connection.remove": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.remove",
    "sftpretty.connection.rename": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.rename",
    "sftpretty.connection.rmdir": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.rmdir",
    "sftpretty.connection.security_options": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.security_options",
    "sftpretty.connection.sftp_client": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.sftp_client",
    "sftpretty.connection.stat": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.stat",
    "sftpretty.connection.symlink": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.symlink",
    "sftpretty.connection.timeout": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.timeout",
    "sftpretty.connection.truncate": "https://docs.sftpretty.com/sftpretty.html#sftpretty.Connection.truncate",
}
