VERSION = "1.12.10"

# fmt: off
MAPPING = {
    "simple_salesforce": "https://simple-salesforce.readthedocs.io/en/stable/",
    "simple_salesforce.bulk": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#module-simple_salesforce.bulk",
    "simple_salesforce.bulk.sfbulkhandler": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkHandler",
    "simple_salesforce.bulk.sfbulkhandler.__init__": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkHandler.__init__",
    "simple_salesforce.bulk.sfbulkhandler.submit_dml": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkHandler.submit_dml",
    "simple_salesforce.bulk.sfbulktype": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType",
    "simple_salesforce.bulk.sfbulktype.__init__": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.__init__",
    "simple_salesforce.bulk.sfbulktype.delete": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.delete",
    "simple_salesforce.bulk.sfbulktype.hard_delete": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.hard_delete",
    "simple_salesforce.bulk.sfbulktype.insert": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.insert",
    "simple_salesforce.bulk.sfbulktype.query": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.query",
    "simple_salesforce.bulk.sfbulktype.query_all": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.query_all",
    "simple_salesforce.bulk.sfbulktype.submit_dml": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.submit_dml",
    "simple_salesforce.bulk.sfbulktype.update": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.update",
    "simple_salesforce.bulk.sfbulktype.upsert": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.upsert",
    "simple_salesforce.bulk.sfbulktype.worker": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.bulk.html#simple_salesforce.bulk.SFBulkType.worker",
    "simple_salesforce.exceptions": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#module-simple_salesforce.exceptions",
    "simple_salesforce.exceptions.salesforceauthenticationfailed": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceAuthenticationFailed",
    "simple_salesforce.exceptions.salesforceauthenticationfailed.__init__": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceAuthenticationFailed.__init__",
    "simple_salesforce.exceptions.salesforceauthenticationfailed.message": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceAuthenticationFailed.message",
    "simple_salesforce.exceptions.salesforcebulkv2extracterror": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceBulkV2ExtractError",
    "simple_salesforce.exceptions.salesforcebulkv2loaderror": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceBulkV2LoadError",
    "simple_salesforce.exceptions.salesforceerror": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceError",
    "simple_salesforce.exceptions.salesforceerror.__init__": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceError.__init__",
    "simple_salesforce.exceptions.salesforceerror.message": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceError.message",
    "simple_salesforce.exceptions.salesforceexpiredsession": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceExpiredSession",
    "simple_salesforce.exceptions.salesforceexpiredsession.message": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceExpiredSession.message",
    "simple_salesforce.exceptions.salesforcegeneralerror": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceGeneralError",
    "simple_salesforce.exceptions.salesforcegeneralerror.message": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceGeneralError.message",
    "simple_salesforce.exceptions.salesforcemalformedrequest": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceMalformedRequest",
    "simple_salesforce.exceptions.salesforcemalformedrequest.message": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceMalformedRequest.message",
    "simple_salesforce.exceptions.salesforcemorethanonerecord": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceMoreThanOneRecord",
    "simple_salesforce.exceptions.salesforcemorethanonerecord.message": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceMoreThanOneRecord.message",
    "simple_salesforce.exceptions.salesforceoperationerror": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceOperationError",
    "simple_salesforce.exceptions.salesforcerefusedrequest": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceRefusedRequest",
    "simple_salesforce.exceptions.salesforcerefusedrequest.message": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceRefusedRequest.message",
    "simple_salesforce.exceptions.salesforceresourcenotfound": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceResourceNotFound",
    "simple_salesforce.exceptions.salesforceresourcenotfound.message": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.exceptions.html#simple_salesforce.exceptions.SalesforceResourceNotFound.message",
    "simple_salesforce.util": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#module-simple_salesforce.util",
    "simple_salesforce.util.call_salesforce": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.call_salesforce",
    "simple_salesforce.util.date_to_iso8601": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.date_to_iso8601",
    "simple_salesforce.util.exception_handler": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.exception_handler",
    "simple_salesforce.util.getuniqueelementvaluefromxmlstring": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.getUniqueElementValueFromXmlString",
    "simple_salesforce.util.list_from_generator": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.list_from_generator",
    "simple_salesforce.util.perappusage": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.PerAppUsage",
    "simple_salesforce.util.perappusage.name": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.PerAppUsage.name",
    "simple_salesforce.util.perappusage.total": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.PerAppUsage.total",
    "simple_salesforce.util.perappusage.used": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.PerAppUsage.used",
    "simple_salesforce.util.usage": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.Usage",
    "simple_salesforce.util.usage.total": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.Usage.total",
    "simple_salesforce.util.usage.used": "https://simple-salesforce.readthedocs.io/en/stable/api/simple_salesforce.util.html#simple_salesforce.util.Usage.used",
}
