VERSION = "2.0.2"

# fmt: off
MAPPING = {
    "smartypants": "https://smartypants.readthedocs.io/en/latest/",
    "smartypants._attr": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr",
    "smartypants._Attr.B": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.B",
    "smartypants._Attr.b": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.b",
    "smartypants._attr.b": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.b",
    "smartypants._Attr.D": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.D",
    "smartypants._Attr.d": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.d",
    "smartypants._attr.d": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.d",
    "smartypants._attr.default": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.default",
    "smartypants._attr.e": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.e",
    "smartypants._attr.h": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.h",
    "smartypants._attr.i": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.i",
    "smartypants._attr.q": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.q",
    "smartypants._attr.s": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.s",
    "smartypants._attr.set0": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.set0",
    "smartypants._attr.set1": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.set1",
    "smartypants._attr.set2": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.set2",
    "smartypants._attr.set3": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.set3",
    "smartypants._attr.u": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.u",
    "smartypants._attr.w": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._Attr.w",
    "smartypants._tags_to_skip_regex": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._tags_to_skip_regex",
    "smartypants._tokenize": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants._tokenize",
    "smartypants.attr": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.Attr",
    "smartypants.convert_backticks": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.convert_backticks",
    "smartypants.convert_dashes": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.convert_dashes",
    "smartypants.convert_dashes_oldschool": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.convert_dashes_oldschool",
    "smartypants.convert_dashes_oldschool_inverted": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.convert_dashes_oldschool_inverted",
    "smartypants.convert_ellipses": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.convert_ellipses",
    "smartypants.convert_entities": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.convert_entities",
    "smartypants.convert_quotes": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.convert_quotes",
    "smartypants.convert_single_backticks": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.convert_single_backticks",
    "smartypants.process_escapes": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.process_escapes",
    "smartypants.smartypants": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.smartypants",
    "smartypants.tags_to_skip": "https://smartypants.readthedocs.io/en/latest/reference.html#smartypants.tags_to_skip",
}
