VERSION = "1.3.10"

# fmt: off
MAPPING = {
    "sparkpost": "https://python-sparkpost.readthedocs.io/en/stable/",
    "sparkpost.recipient_lists": "https://python-sparkpost.readthedocs.io/en/stable/api/recipient_lists.html#module-sparkpost.recipient_lists",
    "sparkpost.recipient_lists.recipientlists": "https://python-sparkpost.readthedocs.io/en/stable/api/recipient_lists.html#sparkpost.recipient_lists.RecipientLists",
    "sparkpost.recipient_lists.recipientlists.create": "https://python-sparkpost.readthedocs.io/en/stable/api/recipient_lists.html#sparkpost.recipient_lists.RecipientLists.create",
    "sparkpost.recipient_lists.recipientlists.delete": "https://python-sparkpost.readthedocs.io/en/stable/api/recipient_lists.html#sparkpost.recipient_lists.RecipientLists.delete",
    "sparkpost.recipient_lists.recipientlists.get": "https://python-sparkpost.readthedocs.io/en/stable/api/recipient_lists.html#sparkpost.recipient_lists.RecipientLists.get",
    "sparkpost.recipient_lists.recipientlists.list": "https://python-sparkpost.readthedocs.io/en/stable/api/recipient_lists.html#sparkpost.recipient_lists.RecipientLists.list",
    "sparkpost.recipient_lists.recipientlists.update": "https://python-sparkpost.readthedocs.io/en/stable/api/recipient_lists.html#sparkpost.recipient_lists.RecipientLists.update",
    "sparkpost.suppression_list": "https://python-sparkpost.readthedocs.io/en/stable/api/suppression_list.html#module-sparkpost.suppression_list",
    "sparkpost.suppression_list.suppressionlist": "https://python-sparkpost.readthedocs.io/en/stable/api/suppression_list.html#sparkpost.suppression_list.SuppressionList",
    "sparkpost.suppression_list.suppressionlist.create": "https://python-sparkpost.readthedocs.io/en/stable/api/suppression_list.html#sparkpost.suppression_list.SuppressionList.create",
    "sparkpost.suppression_list.suppressionlist.delete": "https://python-sparkpost.readthedocs.io/en/stable/api/suppression_list.html#sparkpost.suppression_list.SuppressionList.delete",
    "sparkpost.suppression_list.suppressionlist.get": "https://python-sparkpost.readthedocs.io/en/stable/api/suppression_list.html#sparkpost.suppression_list.SuppressionList.get",
    "sparkpost.suppression_list.suppressionlist.list": "https://python-sparkpost.readthedocs.io/en/stable/api/suppression_list.html#sparkpost.suppression_list.SuppressionList.list",
    "sparkpost.suppression_list.suppressionlist.update": "https://python-sparkpost.readthedocs.io/en/stable/api/suppression_list.html#sparkpost.suppression_list.SuppressionList.update",
    "sparkpost.templates": "https://python-sparkpost.readthedocs.io/en/stable/api/templates.html#module-sparkpost.templates",
    "sparkpost.templates.templates": "https://python-sparkpost.readthedocs.io/en/stable/api/templates.html#sparkpost.templates.Templates",
    "sparkpost.templates.templates.create": "https://python-sparkpost.readthedocs.io/en/stable/api/templates.html#sparkpost.templates.Templates.create",
    "sparkpost.templates.templates.delete": "https://python-sparkpost.readthedocs.io/en/stable/api/templates.html#sparkpost.templates.Templates.delete",
    "sparkpost.templates.templates.get": "https://python-sparkpost.readthedocs.io/en/stable/api/templates.html#sparkpost.templates.Templates.get",
    "sparkpost.templates.templates.list": "https://python-sparkpost.readthedocs.io/en/stable/api/templates.html#sparkpost.templates.Templates.list",
    "sparkpost.templates.templates.preview": "https://python-sparkpost.readthedocs.io/en/stable/api/templates.html#sparkpost.templates.Templates.preview",
    "sparkpost.templates.templates.update": "https://python-sparkpost.readthedocs.io/en/stable/api/templates.html#sparkpost.templates.Templates.update",
    "sparkpost.transmissions": "https://python-sparkpost.readthedocs.io/en/stable/api/transmissions.html#module-sparkpost.transmissions",
    "sparkpost.transmissions.transmissions": "https://python-sparkpost.readthedocs.io/en/stable/api/transmissions.html#sparkpost.transmissions.Transmissions",
    "sparkpost.transmissions.transmissions.delete": "https://python-sparkpost.readthedocs.io/en/stable/api/transmissions.html#sparkpost.transmissions.Transmissions.delete",
    "sparkpost.transmissions.transmissions.get": "https://python-sparkpost.readthedocs.io/en/stable/api/transmissions.html#sparkpost.transmissions.Transmissions.get",
    "sparkpost.transmissions.transmissions.list": "https://python-sparkpost.readthedocs.io/en/stable/api/transmissions.html#sparkpost.transmissions.Transmissions.list",
    "sparkpost.transmissions.transmissions.send": "https://python-sparkpost.readthedocs.io/en/stable/api/transmissions.html#sparkpost.transmissions.Transmissions.send",
}
