VERSION = "1.0.1"

# fmt: off
MAPPING = {
    "spectate": "https://python-spectate.readthedocs.io/en/stable/",
    "spectate.base": "https://python-spectate.readthedocs.io/en/stable/api.html#module-spectate.base",
    "spectate.base.control": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.base.Control",
    "spectate.base.link": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.base.link",
    "spectate.base.model": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.base.Model",
    "spectate.base.notifier": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.base.notifier",
    "spectate.base.unlink": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.base.unlink",
    "spectate.base.unview": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.base.unview",
    "spectate.base.view": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.base.view",
    "spectate.base.views": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.base.views",
    "spectate.events": "https://python-spectate.readthedocs.io/en/stable/api.html#module-spectate.events",
    "spectate.events.hold": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.events.hold",
    "spectate.events.mute": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.events.mute",
    "spectate.events.rollback": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.events.rollback",
    "spectate.models": "https://python-spectate.readthedocs.io/en/stable/api.html#module-spectate.models",
    "spectate.models.dict": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Dict",
    "spectate.models.dict.clear": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Dict.clear",
    "spectate.models.dict.pop": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Dict.pop",
    "spectate.models.dict.setdefault": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Dict.setdefault",
    "spectate.models.dict.update": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Dict.update",
    "spectate.models.list": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.List",
    "spectate.models.list.append": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.List.append",
    "spectate.models.list.clear": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.List.clear",
    "spectate.models.list.extend": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.List.extend",
    "spectate.models.list.insert": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.List.insert",
    "spectate.models.list.pop": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.List.pop",
    "spectate.models.list.remove": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.List.remove",
    "spectate.models.list.reverse": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.List.reverse",
    "spectate.models.list.sort": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.List.sort",
    "spectate.models.object": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Object",
    "spectate.models.set": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set",
    "spectate.models.set.add": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set.add",
    "spectate.models.set.clear": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set.clear",
    "spectate.models.set.difference_update": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set.difference_update",
    "spectate.models.set.discard": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set.discard",
    "spectate.models.set.intersection_update": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set.intersection_update",
    "spectate.models.set.pop": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set.pop",
    "spectate.models.set.remove": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set.remove",
    "spectate.models.set.symmetric_difference_update": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set.symmetric_difference_update",
    "spectate.models.set.update": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Set.update",
    "spectate.models.structure": "https://python-spectate.readthedocs.io/en/stable/api.html#spectate.models.Structure",
    "spectate.mvc": "https://python-spectate.readthedocs.io/en/stable/api.html#module-spectate.mvc",
    "spectate.utils": "https://python-spectate.readthedocs.io/en/stable/api.html#module-spectate.utils",
}
