VERSION = "2.5"

# fmt: off
MAPPING = {
    "sphinxcontrib_django": "https://sphinxcontrib-django.readthedocs.io/en/stable/",
    "sphinxcontrib_django.docstrings": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#module-sphinxcontrib_django.docstrings",
    "sphinxcontrib_django.docstrings.attributes": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#module-sphinxcontrib_django.docstrings.attributes",
    "sphinxcontrib_django.docstrings.attributes.get_field_details": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.attributes.get_field_details",
    "sphinxcontrib_django.docstrings.attributes.improve_attribute_docstring": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.attributes.improve_attribute_docstring",
    "sphinxcontrib_django.docstrings.autodoc_skip": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.autodoc_skip",
    "sphinxcontrib_django.docstrings.classes": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#module-sphinxcontrib_django.docstrings.classes",
    "sphinxcontrib_django.docstrings.classes.add_db_table_name": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.classes.add_db_table_name",
    "sphinxcontrib_django.docstrings.classes.add_model_parameters": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.classes.add_model_parameters",
    "sphinxcontrib_django.docstrings.classes.improve_class_docstring": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.classes.improve_class_docstring",
    "sphinxcontrib_django.docstrings.classes.improve_form_docstring": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.classes.improve_form_docstring",
    "sphinxcontrib_django.docstrings.classes.improve_model_docstring": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.classes.improve_model_docstring",
    "sphinxcontrib_django.docstrings.config": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#module-sphinxcontrib_django.docstrings.config",
    "sphinxcontrib_django.docstrings.config.choices_limit": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.config.CHOICES_LIMIT",
    "sphinxcontrib_django.docstrings.config.exclude_members": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.config.EXCLUDE_MEMBERS",
    "sphinxcontrib_django.docstrings.config.include_members": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.config.INCLUDE_MEMBERS",
    "sphinxcontrib_django.docstrings.data": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#module-sphinxcontrib_django.docstrings.data",
    "sphinxcontrib_django.docstrings.data.improve_data_docstring": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.data.improve_data_docstring",
    "sphinxcontrib_django.docstrings.field_utils": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#module-sphinxcontrib_django.docstrings.field_utils",
    "sphinxcontrib_django.docstrings.field_utils.get_field_type": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.field_utils.get_field_type",
    "sphinxcontrib_django.docstrings.field_utils.get_field_verbose_name": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.field_utils.get_field_verbose_name",
    "sphinxcontrib_django.docstrings.field_utils.get_model_from_string": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.field_utils.get_model_from_string",
    "sphinxcontrib_django.docstrings.improve_docstring": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.improve_docstring",
    "sphinxcontrib_django.docstrings.methods": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#module-sphinxcontrib_django.docstrings.methods",
    "sphinxcontrib_django.docstrings.methods.improve_method_docstring": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.methods.improve_method_docstring",
    "sphinxcontrib_django.docstrings.patches": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#module-sphinxcontrib_django.docstrings.patches",
    "sphinxcontrib_django.docstrings.patches.patch_django_for_autodoc": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.patches.patch_django_for_autodoc",
    "sphinxcontrib_django.docstrings.setup": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.setup",
    "sphinxcontrib_django.docstrings.setup_django": "https://sphinxcontrib-django.readthedocs.io/en/stable/docstrings.html#sphinxcontrib_django.docstrings.setup_django",
    "sphinxcontrib_django.roles": "https://sphinxcontrib-django.readthedocs.io/en/stable/reference.html#module-sphinxcontrib_django.roles",
    "sphinxcontrib_django.roles.add_default_intersphinx_mappings": "https://sphinxcontrib-django.readthedocs.io/en/stable/reference.html#sphinxcontrib_django.roles.add_default_intersphinx_mappings",
    "sphinxcontrib_django.roles.setup": "https://sphinxcontrib-django.readthedocs.io/en/stable/reference.html#sphinxcontrib_django.roles.setup",
    "sphinxcontrib_django.setup": "https://sphinxcontrib-django.readthedocs.io/en/stable/reference.html#sphinxcontrib_django.setup",
}
