VERSION = "1.4.2"

# fmt: off
MAPPING = {
    "hoverxref": "https://sphinx-hoverxref.readthedocs.io/en/stable/",
    "hoverxref.__version__": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/index.html#hoverxref.__version__",
    "hoverxref.domains": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#module-hoverxref.domains",
    "hoverxref.domains.hoverxrefbasedomain": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefBaseDomain",
    "hoverxref.domains.hoverxrefbasedomain._inject_hoverxref_data": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefBaseDomain._inject_hoverxref_data",
    "hoverxref.domains.hoverxrefbasedomain._is_ignored_ref": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefBaseDomain._is_ignored_ref",
    "hoverxref.domains.hoverxrefbasedomain.hoverxref_types": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefBaseDomain.hoverxref_types",
    "hoverxref.domains.hoverxrefbibtexdomainmixin": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefBibtexDomainMixin",
    "hoverxref.domains.hoverxrefbibtexdomainmixin.resolve_xref": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefBibtexDomainMixin.resolve_xref",
    "hoverxref.domains.hoverxrefpythondomainmixin": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefPythonDomainMixin",
    "hoverxref.domains.hoverxrefpythondomainmixin.resolve_xref": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefPythonDomainMixin.resolve_xref",
    "hoverxref.domains.hoverxrefstandarddomainmixin": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefStandardDomainMixin",
    "hoverxref.domains.hoverxrefstandarddomainmixin._resolve_numref_xref": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefStandardDomainMixin._resolve_numref_xref",
    "hoverxref.domains.hoverxrefstandarddomainmixin._resolve_obj_xref": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefStandardDomainMixin._resolve_obj_xref",
    "hoverxref.domains.hoverxrefstandarddomainmixin._resolve_ref_xref": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefStandardDomainMixin._resolve_ref_xref",
    "hoverxref.domains.hoverxrefstandarddomainmixin.resolve_xref": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.HoverXRefStandardDomainMixin.resolve_xref",
    "hoverxref.domains.logger": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/domains/index.html#hoverxref.domains.logger",
    "hoverxref.extension": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#module-hoverxref.extension",
    "hoverxref.extension.assets_files": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.ASSETS_FILES",
    "hoverxref.extension.copy_asset_files": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.copy_asset_files",
    "hoverxref.extension.css_class_prefix": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.CSS_CLASS_PREFIX",
    "hoverxref.extension.css_classes": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.CSS_CLASSES",
    "hoverxref.extension.css_default_class": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.CSS_DEFAULT_CLASS",
    "hoverxref.extension.deprecated_configs_warning": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.deprecated_configs_warning",
    "hoverxref.extension.hoverxref_assets_files": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.HOVERXREF_ASSETS_FILES",
    "hoverxref.extension.logger": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.logger",
    "hoverxref.extension.missing_reference": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.missing_reference",
    "hoverxref.extension.modal_assets_files": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.MODAL_ASSETS_FILES",
    "hoverxref.extension.setup": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.setup",
    "hoverxref.extension.setup_assets_policy": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.setup_assets_policy",
    "hoverxref.extension.setup_domains": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.setup_domains",
    "hoverxref.extension.setup_intersphinx": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.setup_intersphinx",
    "hoverxref.extension.setup_theme": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.setup_theme",
    "hoverxref.extension.tooltip_assets_files": "https://sphinx-hoverxref.readthedocs.io/en/stable/autoapi/hoverxref/extension/index.html#hoverxref.extension.TOOLTIP_ASSETS_FILES",
}
