VERSION = "0.13.9"

# fmt: off
MAPPING = {
    "sphinx_immaterial": "https://jbms.github.io/sphinx-immaterial/",
    "sphinx_immaterial.apidoc.cpp.api_parser": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html",
    "sphinx_immaterial.apidoc.cpp.api_parser.config": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.allow_macros": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.allow_macros",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.allow_paths": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.allow_paths",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.allow_symbols": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.allow_symbols",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.compiler_flags": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.compiler_flags",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.disallow_macros": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.disallow_macros",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.disallow_namespaces": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.disallow_namespaces",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.disallow_paths": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.disallow_paths",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.disallow_symbols": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.disallow_symbols",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.hide_initializers": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.hide_initializers",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.hide_types": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.hide_types",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.ignore_diagnostics": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.ignore_diagnostics",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.ignore_template_parameters": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.ignore_template_parameters",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.include_directory_map": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.include_directory_map",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.input_content": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.input_content",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.input_path": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.input_path",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.type_replacements": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.type_replacements",
    "sphinx_immaterial.apidoc.cpp.api_parser.config.verbose": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.api_parser.Config.verbose",
    "sphinx_immaterial.apidoc.cpp.apigen": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html",
    "sphinx_immaterial.apidoc.cpp.apigen.apigenconfig": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.apigen.ApigenConfig",
    "sphinx_immaterial.apidoc.cpp.apigen.apigenconfig.api_data": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.apigen.ApigenConfig.api_data",
    "sphinx_immaterial.apidoc.cpp.apigen.apigenconfig.api_parser_config": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.apigen.ApigenConfig.api_parser_config",
    "sphinx_immaterial.apidoc.cpp.apigen.apigenconfig.document_prefix": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/apigen.html#sphinx_immaterial.apidoc.cpp.apigen.ApigenConfig.document_prefix",
    "sphinx_immaterial.apidoc.cpp.external_cpp_references": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/external_cpp_references.html",
    "sphinx_immaterial.apidoc.cpp.external_cpp_references.externalcppreference": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/external_cpp_references.html#sphinx_immaterial.apidoc.cpp.external_cpp_references.ExternalCppReference",
    "sphinx_immaterial.apidoc.cpp.external_cpp_references.externalcppreference.desc": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/external_cpp_references.html#sphinx_immaterial.apidoc.cpp.external_cpp_references.ExternalCppReference.desc",
    "sphinx_immaterial.apidoc.cpp.external_cpp_references.externalcppreference.object_type": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/external_cpp_references.html#sphinx_immaterial.apidoc.cpp.external_cpp_references.ExternalCppReference.object_type",
    "sphinx_immaterial.apidoc.cpp.external_cpp_references.externalcppreference.url": "https://jbms.github.io/sphinx-immaterial/apidoc/cpp/external_cpp_references.html#sphinx_immaterial.apidoc.cpp.external_cpp_references.ExternalCppReference.url",
    "sphinx_immaterial.apidoc.format_signatures": "https://jbms.github.io/sphinx-immaterial/apidoc/format_signatures.html",
    "sphinx_immaterial.apidoc.format_signatures.blackformatstyle": "https://jbms.github.io/sphinx-immaterial/apidoc/format_signatures.html#sphinx_immaterial.apidoc.format_signatures.BlackFormatStyle",
    "sphinx_immaterial.apidoc.format_signatures.blackformatstyle.line_length": "https://jbms.github.io/sphinx-immaterial/apidoc/format_signatures.html#sphinx_immaterial.apidoc.format_signatures.BlackFormatStyle.line_length",
    "sphinx_immaterial.apidoc.format_signatures.blackformatstyle.string_normalization": "https://jbms.github.io/sphinx-immaterial/apidoc/format_signatures.html#sphinx_immaterial.apidoc.format_signatures.BlackFormatStyle.string_normalization",
    "sphinx_immaterial.custom_admonitions": "https://jbms.github.io/sphinx-immaterial/admonitions.html",
    "sphinx_immaterial.custom_admonitions.customadmonitionconfig": "https://jbms.github.io/sphinx-immaterial/admonitions.html#sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig",
    "sphinx_immaterial.custom_admonitions.customadmonitionconfig.classes": "https://jbms.github.io/sphinx-immaterial/admonitions.html#sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.classes",
    "sphinx_immaterial.custom_admonitions.customadmonitionconfig.color": "https://jbms.github.io/sphinx-immaterial/admonitions.html#sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.color",
    "sphinx_immaterial.custom_admonitions.customadmonitionconfig.icon": "https://jbms.github.io/sphinx-immaterial/admonitions.html#sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.icon",
    "sphinx_immaterial.custom_admonitions.customadmonitionconfig.name": "https://jbms.github.io/sphinx-immaterial/admonitions.html#sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.name",
    "sphinx_immaterial.custom_admonitions.customadmonitionconfig.override": "https://jbms.github.io/sphinx-immaterial/admonitions.html#sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.override",
    "sphinx_immaterial.custom_admonitions.customadmonitionconfig.title": "https://jbms.github.io/sphinx-immaterial/admonitions.html#sphinx_immaterial.custom_admonitions.CustomAdmonitionConfig.title",
}
