VERSION = "0.3.3"

# fmt: off
MAPPING = {
    "splines": "https://splines.readthedocs.io/en/latest/",
    "splines.bernstein": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.Bernstein",
    "splines.bernstein.basis": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.Bernstein.basis",
    "splines.bernstein.evaluate": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.Bernstein.evaluate",
    "splines.catmullrom": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.CatmullRom",
    "splines.cubichermite": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.CubicHermite",
    "splines.cubichermite.matrix": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.CubicHermite.matrix",
    "splines.kochanekbartels": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.KochanekBartels",
    "splines.monomial": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.Monomial",
    "splines.monomial.evaluate": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.Monomial.evaluate",
    "splines.monotonecubic": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.MonotoneCubic",
    "splines.monotonecubic.get_time": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.MonotoneCubic.get_time",
    "splines.natural": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.Natural",
    "splines.newgridadapter": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.NewGridAdapter",
    "splines.newgridadapter.evaluate": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.NewGridAdapter.evaluate",
    "splines.piecewisemonotonecubic": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.PiecewiseMonotoneCubic",
    "splines.quaternion": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#module-splines.quaternion",
    "splines.quaternion.barrygoldman": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.BarryGoldman",
    "splines.quaternion.barrygoldman.evaluate": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.BarryGoldman.evaluate",
    "splines.quaternion.canonicalized": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.canonicalized",
    "splines.quaternion.catmullrom": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.CatmullRom",
    "splines.quaternion.decasteljau": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.DeCasteljau",
    "splines.quaternion.decasteljau.evaluate": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.DeCasteljau.evaluate",
    "splines.quaternion.kochanekbartels": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.KochanekBartels",
    "splines.quaternion.piecewiseslerp": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.PiecewiseSlerp",
    "splines.quaternion.piecewiseslerp.evaluate": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.PiecewiseSlerp.evaluate",
    "splines.quaternion.quaternion": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Quaternion",
    "splines.quaternion.quaternion.conjugate": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Quaternion.conjugate",
    "splines.quaternion.quaternion.dot": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Quaternion.dot",
    "splines.quaternion.quaternion.norm": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Quaternion.norm",
    "splines.quaternion.quaternion.normalized": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Quaternion.normalized",
    "splines.quaternion.quaternion.scalar": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Quaternion.scalar",
    "splines.quaternion.quaternion.vector": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Quaternion.vector",
    "splines.quaternion.quaternion.wxyz": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Quaternion.wxyz",
    "splines.quaternion.quaternion.xyzw": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Quaternion.xyzw",
    "splines.quaternion.slerp": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.slerp",
    "splines.quaternion.squad": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Squad",
    "splines.quaternion.squad.evaluate": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.Squad.evaluate",
    "splines.quaternion.unitquaternion": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion",
    "splines.quaternion.unitquaternion.angle": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion.angle",
    "splines.quaternion.unitquaternion.axis": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion.axis",
    "splines.quaternion.unitquaternion.exp_map": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion.exp_map",
    "splines.quaternion.unitquaternion.from_axis_angle": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion.from_axis_angle",
    "splines.quaternion.unitquaternion.from_unit_xyzw": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion.from_unit_xyzw",
    "splines.quaternion.unitquaternion.inverse": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion.inverse",
    "splines.quaternion.unitquaternion.log_map": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion.log_map",
    "splines.quaternion.unitquaternion.rotate_vector": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion.rotate_vector",
    "splines.quaternion.unitquaternion.rotation_to": "https://splines.readthedocs.io/en/latest/python-module/splines.quaternion.html#splines.quaternion.UnitQuaternion.rotation_to",
    "splines.unitspeedadapter": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.UnitSpeedAdapter",
    "splines.unitspeedadapter.evaluate": "https://splines.readthedocs.io/en/latest/python-module/splines.html#splines.UnitSpeedAdapter.evaluate",
}
