VERSION = "2.3.5"

# fmt: off
MAPPING = {
    "spurplus": "https://spurplus.readthedocs.io/en/stable/",
    "spurplus.chunk_arguments": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.chunk_arguments",
    "spurplus.connect_with_retries": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.connect_with_retries",
    "spurplus.delete": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.Delete",
    "spurplus.directorydiff": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.DirectoryDiff",
    "spurplus.sftp": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#module-spurplus.sftp",
    "spurplus.sftp.reconnectingsftp": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP",
    "spurplus.sftp.reconnectingsftp.chmod": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.chmod",
    "spurplus.sftp.reconnectingsftp.chown": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.chown",
    "spurplus.sftp.reconnectingsftp.close": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.close",
    "spurplus.sftp.reconnectingsftp.get": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.get",
    "spurplus.sftp.reconnectingsftp.listdir": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.listdir",
    "spurplus.sftp.reconnectingsftp.listdir_attr": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.listdir_attr",
    "spurplus.sftp.reconnectingsftp.lstat": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.lstat",
    "spurplus.sftp.reconnectingsftp.mkdir": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.mkdir",
    "spurplus.sftp.reconnectingsftp.posix_rename": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.posix_rename",
    "spurplus.sftp.reconnectingsftp.put": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.put",
    "spurplus.sftp.reconnectingsftp.remove": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.remove",
    "spurplus.sftp.reconnectingsftp.rmdir": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.rmdir",
    "spurplus.sftp.reconnectingsftp.stat": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.stat",
    "spurplus.sftp.reconnectingsftp.symlink": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.symlink",
    "spurplus.sftp.reconnectingsftp.unlink": "https://spurplus.readthedocs.io/en/stable/spurplus.sftp.html#spurplus.sftp.ReconnectingSFTP.unlink",
    "spurplus.sshshell": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell",
    "spurplus.sshshell.as_sftp": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.as_sftp",
    "spurplus.sshshell.as_spur": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.as_spur",
    "spurplus.sshshell.check_output": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.check_output",
    "spurplus.sshshell.chmod": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.chmod",
    "spurplus.sshshell.chown": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.chown",
    "spurplus.sshshell.close": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.close",
    "spurplus.sshshell.directory_diff": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.directory_diff",
    "spurplus.sshshell.exists": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.exists",
    "spurplus.sshshell.get": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.get",
    "spurplus.sshshell.is_dir": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.is_dir",
    "spurplus.sshshell.is_symlink": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.is_symlink",
    "spurplus.sshshell.md5": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.md5",
    "spurplus.sshshell.md5s": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.md5s",
    "spurplus.sshshell.mirror_local_permissions": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.mirror_local_permissions",
    "spurplus.sshshell.mkdir": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.mkdir",
    "spurplus.sshshell.put": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.put",
    "spurplus.sshshell.read_bytes": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.read_bytes",
    "spurplus.sshshell.read_text": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.read_text",
    "spurplus.sshshell.remove": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.remove",
    "spurplus.sshshell.run": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.run",
    "spurplus.sshshell.spawn": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.spawn",
    "spurplus.sshshell.stat": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.stat",
    "spurplus.sshshell.symlink": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.symlink",
    "spurplus.sshshell.sync_to_remote": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.sync_to_remote",
    "spurplus.sshshell.whoami": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.whoami",
    "spurplus.sshshell.write_bytes": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.write_bytes",
    "spurplus.sshshell.write_text": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.SshShell.write_text",
    "spurplus.temporarydirectory": "https://spurplus.readthedocs.io/en/stable/spurplus.html#spurplus.TemporaryDirectory",
}
