VERSION = "2.31.0"

# fmt: off
MAPPING = {
    "storage3": "https://supabase.github.io/storage-py/",
    "storage3._async.client": "https://supabase.github.io/storage-py/api/client.html",
    "storage3._async.client.asyncstorageclient": "https://supabase.github.io/storage-py/api/client.html#storage3.AsyncStorageClient",
    "storage3._async.file_api": "https://supabase.github.io/storage-py/api/bucket.html",
    "storage3._async.file_api.asyncbucket": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket",
    "storage3._async.file_api.asyncbucket.copy": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.copy",
    "storage3._async.file_api.asyncbucket.create_signed_upload_url": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.create_signed_upload_url",
    "storage3._async.file_api.asyncbucket.create_signed_url": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.create_signed_url",
    "storage3._async.file_api.asyncbucket.create_signed_urls": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.create_signed_urls",
    "storage3._async.file_api.asyncbucket.download": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.download",
    "storage3._async.file_api.asyncbucket.get_public_url": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.get_public_url",
    "storage3._async.file_api.asyncbucket.list": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.list",
    "storage3._async.file_api.asyncbucket.move": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.move",
    "storage3._async.file_api.asyncbucket.remove": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.remove",
    "storage3._async.file_api.asyncbucket.upload": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.upload",
    "storage3._async.file_api.asyncbucket.upload_to_signed_url": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucket.upload_to_signed_url",
    "storage3._async.file_api.asyncbucketproxy": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy",
    "storage3._async.file_api.asyncbucketproxy.copy": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.copy",
    "storage3._async.file_api.asyncbucketproxy.create_signed_upload_url": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.create_signed_upload_url",
    "storage3._async.file_api.asyncbucketproxy.create_signed_url": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.create_signed_url",
    "storage3._async.file_api.asyncbucketproxy.create_signed_urls": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.create_signed_urls",
    "storage3._async.file_api.asyncbucketproxy.download": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.download",
    "storage3._async.file_api.asyncbucketproxy.get_public_url": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.get_public_url",
    "storage3._async.file_api.asyncbucketproxy.list": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.list",
    "storage3._async.file_api.asyncbucketproxy.move": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.move",
    "storage3._async.file_api.asyncbucketproxy.remove": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.remove",
    "storage3._async.file_api.asyncbucketproxy.upload": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.upload",
    "storage3._async.file_api.asyncbucketproxy.upload_to_signed_url": "https://supabase.github.io/storage-py/api/bucket.html#storage3._async.file_api.AsyncBucketProxy.upload_to_signed_url",
    "storage3.asyncstorageclient": "https://supabase.github.io/storage-py/api/client.html#storage3.AsyncStorageClient",
    "storage3.asyncstorageclient.create_bucket": "https://supabase.github.io/storage-py/api/client.html#storage3.AsyncStorageClient.create_bucket",
    "storage3.asyncstorageclient.delete_bucket": "https://supabase.github.io/storage-py/api/client.html#storage3.AsyncStorageClient.delete_bucket",
    "storage3.asyncstorageclient.empty_bucket": "https://supabase.github.io/storage-py/api/client.html#storage3.AsyncStorageClient.empty_bucket",
    "storage3.asyncstorageclient.from_": "https://supabase.github.io/storage-py/api/client.html#storage3.AsyncStorageClient.from_",
    "storage3.asyncstorageclient.get_bucket": "https://supabase.github.io/storage-py/api/client.html#storage3.AsyncStorageClient.get_bucket",
    "storage3.asyncstorageclient.list_buckets": "https://supabase.github.io/storage-py/api/client.html#storage3.AsyncStorageClient.list_buckets",
    "storage3.asyncstorageclient.update_bucket": "https://supabase.github.io/storage-py/api/client.html#storage3.AsyncStorageClient.update_bucket",
    "storage3.create_client": "https://supabase.github.io/storage-py/api/client.html#storage3.create_client",
    "storage3.types": "https://supabase.github.io/storage-py/api/types.html",
    "storage3.types._sortbytype": "https://supabase.github.io/storage-py/api/types.html#storage3.types._sortByType",
    "storage3.types.createorupdatebucketoptions": "https://supabase.github.io/storage-py/api/types.html#storage3.types.CreateOrUpdateBucketOptions",
    "storage3.types.createsignedurlsoptions": "https://supabase.github.io/storage-py/api/types.html#storage3.types.CreateSignedURLsOptions",
    "storage3.types.fileoptions": "https://supabase.github.io/storage-py/api/types.html#storage3.types.FileOptions",
    "storage3.types.listbucketfilesoptions": "https://supabase.github.io/storage-py/api/types.html#storage3.types.ListBucketFilesOptions",
    "storage3.types.signeduploadurl": "https://supabase.github.io/storage-py/api/types.html#storage3.types.SignedUploadURL",
    "storage3.types.transformoptions": "https://supabase.github.io/storage-py/api/types.html#storage3.types.TransformOptions",
    "storage3.types.urloptions": "https://supabase.github.io/storage-py/api/types.html#storage3.types.URLOptions",
}
