VERSION = "4.3.0"

# fmt: off
MAPPING = {
    "supervisor": "https://supervisord.org/",
    "supervisor.rpcinterface": "https://supervisord.org/api.html#module-supervisor.rpcinterface",
    "supervisor.rpcinterface.supervisornamespacerpcinterface": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.addprocessgroup": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.addProcessGroup",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.clearallprocesslogs": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.clearAllProcessLogs",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.clearlog": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.clearLog",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.clearprocesslogs": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.clearProcessLogs",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.getallconfiginfo": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getAllConfigInfo",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.getallprocessinfo": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getAllProcessInfo",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.getapiversion": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getAPIVersion",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.getidentification": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getIdentification",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.getpid": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getPID",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.getprocessinfo": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getProcessInfo",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.getstate": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getState",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.getsupervisorversion": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.getSupervisorVersion",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.readlog": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.readLog",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.readprocessstderrlog": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.readProcessStderrLog",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.readprocessstdoutlog": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.readProcessStdoutLog",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.reloadconfig": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.reloadConfig",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.removeprocessgroup": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.removeProcessGroup",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.restart": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.restart",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.sendprocessstdin": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.sendProcessStdin",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.sendremotecommevent": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.sendRemoteCommEvent",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.shutdown": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.shutdown",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.signalallprocesses": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.signalAllProcesses",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.signalprocess": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.signalProcess",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.signalprocessgroup": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.signalProcessGroup",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.startallprocesses": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.startAllProcesses",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.startprocess": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.startProcess",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.startprocessgroup": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.startProcessGroup",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.stopallprocesses": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.stopAllProcesses",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.stopprocess": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.stopProcess",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.stopprocessgroup": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.stopProcessGroup",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.tailprocessstderrlog": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.tailProcessStderrLog",
    "supervisor.rpcinterface.supervisornamespacerpcinterface.tailprocessstdoutlog": "https://supervisord.org/api.html#supervisor.rpcinterface.SupervisorNamespaceRPCInterface.tailProcessStdoutLog",
    "supervisor.xmlrpc": "https://supervisord.org/api.html#module-supervisor.xmlrpc",
    "supervisor.xmlrpc.systemnamespacerpcinterface": "https://supervisord.org/api.html#supervisor.xmlrpc.SystemNamespaceRPCInterface",
    "supervisor.xmlrpc.systemnamespacerpcinterface.listmethods": "https://supervisord.org/api.html#supervisor.xmlrpc.SystemNamespaceRPCInterface.listMethods",
    "supervisor.xmlrpc.systemnamespacerpcinterface.methodhelp": "https://supervisord.org/api.html#supervisor.xmlrpc.SystemNamespaceRPCInterface.methodHelp",
    "supervisor.xmlrpc.systemnamespacerpcinterface.methodsignature": "https://supervisord.org/api.html#supervisor.xmlrpc.SystemNamespaceRPCInterface.methodSignature",
    "supervisor.xmlrpc.systemnamespacerpcinterface.multicall": "https://supervisord.org/api.html#supervisor.xmlrpc.SystemNamespaceRPCInterface.multicall",
}
