VERSION = "0.3.4"

# fmt: off
MAPPING = {
    "svgutils": "https://svgutils.readthedocs.io/en/stable/",
    "svgutils.compose": "https://svgutils.readthedocs.io/en/stable/compose.html#module-svgutils.compose",
    "svgutils.compose.element": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Element",
    "svgutils.compose.element.find_id": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Element.find_id",
    "svgutils.compose.element.find_ids": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Element.find_ids",
    "svgutils.compose.element.move": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Element.move",
    "svgutils.compose.element.scale": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Element.scale",
    "svgutils.compose.figure": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Figure",
    "svgutils.compose.figure.save": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Figure.save",
    "svgutils.compose.figure.tile": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Figure.tile",
    "svgutils.compose.figure.tostr": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Figure.tostr",
    "svgutils.compose.grid": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Grid",
    "svgutils.compose.image": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Image",
    "svgutils.compose.line": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Line",
    "svgutils.compose.mplfigure": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.MplFigure",
    "svgutils.compose.panel": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Panel",
    "svgutils.compose.svg": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.SVG",
    "svgutils.compose.text": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Text",
    "svgutils.compose.unit": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Unit",
    "svgutils.compose.unit.to": "https://svgutils.readthedocs.io/en/stable/compose.html#svgutils.compose.Unit.to",
    "svgutils.transform": "https://svgutils.readthedocs.io/en/stable/transform.html#module-svgutils.transform",
    "svgutils.transform.figureelement": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement",
    "svgutils.transform.figureelement.copy": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement.copy",
    "svgutils.transform.figureelement.find_id": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement.find_id",
    "svgutils.transform.figureelement.moveto": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement.moveto",
    "svgutils.transform.figureelement.rotate": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement.rotate",
    "svgutils.transform.figureelement.scale_xy": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement.scale_xy",
    "svgutils.transform.figureelement.skew": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement.skew",
    "svgutils.transform.figureelement.skew_x": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement.skew_x",
    "svgutils.transform.figureelement.skew_y": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement.skew_y",
    "svgutils.transform.figureelement.tostr": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.FigureElement.tostr",
    "svgutils.transform.from_mpl": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.from_mpl",
    "svgutils.transform.fromfile": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.fromfile",
    "svgutils.transform.fromstring": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.fromstring",
    "svgutils.transform.groupelement": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.GroupElement",
    "svgutils.transform.imageelement": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.ImageElement",
    "svgutils.transform.lineelement": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.LineElement",
    "svgutils.transform.svgfigure": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure",
    "svgutils.transform.svgfigure.append": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure.append",
    "svgutils.transform.svgfigure.find_id": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure.find_id",
    "svgutils.transform.svgfigure.get_size": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure.get_size",
    "svgutils.transform.svgfigure.getroot": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure.getroot",
    "svgutils.transform.svgfigure.height": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure.height",
    "svgutils.transform.svgfigure.save": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure.save",
    "svgutils.transform.svgfigure.set_size": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure.set_size",
    "svgutils.transform.svgfigure.to_str": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure.to_str",
    "svgutils.transform.svgfigure.width": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.SVGFigure.width",
    "svgutils.transform.textelement": "https://svgutils.readthedocs.io/en/stable/transform.html#svgutils.transform.TextElement",
}
