VERSION = "2.10.0"

# fmt: off
MAPPING = {
    "tabula": "https://tabula-py.readthedocs.io/en/stable/",
    "tabula.errors": "https://tabula-py.readthedocs.io/en/stable/tabula.errors.html#module-tabula.errors",
    "tabula.errors.csvparseerror": "https://tabula-py.readthedocs.io/en/stable/tabula.errors.html#tabula.errors.CSVParseError",
    "tabula.errors.javanotfounderror": "https://tabula-py.readthedocs.io/en/stable/tabula.errors.html#tabula.errors.JavaNotFoundError",
    "tabula.file_util": "https://tabula-py.readthedocs.io/en/stable/tabula.html#module-tabula.file_util",
    "tabula.file_util.is_file_like": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.file_util.is_file_like",
    "tabula.file_util.localize_file": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.file_util.localize_file",
    "tabula.io": "https://tabula-py.readthedocs.io/en/stable/tabula.html#module-tabula.io",
    "tabula.io.convert_into": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.io.convert_into",
    "tabula.io.convert_into_by_batch": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.io.convert_into_by_batch",
    "tabula.io.read_pdf": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.io.read_pdf",
    "tabula.io.read_pdf_with_template": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.io.read_pdf_with_template",
    "tabula.template": "https://tabula-py.readthedocs.io/en/stable/tabula.html#module-tabula.template",
    "tabula.template.load_template": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.template.load_template",
    "tabula.util": "https://tabula-py.readthedocs.io/en/stable/tabula.html#module-tabula.util",
    "tabula.util.environment_info": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.environment_info",
    "tabula.util.java_version": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.java_version",
    "tabula.util.tabulaoption": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption",
    "tabula.util.tabulaoption.area": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.area",
    "tabula.util.tabulaoption.batch": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.batch",
    "tabula.util.tabulaoption.build_option_list": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.build_option_list",
    "tabula.util.tabulaoption.columns": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.columns",
    "tabula.util.tabulaoption.format": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.format",
    "tabula.util.tabulaoption.guess": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.guess",
    "tabula.util.tabulaoption.lattice": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.lattice",
    "tabula.util.tabulaoption.merge": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.merge",
    "tabula.util.tabulaoption.multiple_tables": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.multiple_tables",
    "tabula.util.tabulaoption.options": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.options",
    "tabula.util.tabulaoption.output_path": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.output_path",
    "tabula.util.tabulaoption.pages": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.pages",
    "tabula.util.tabulaoption.password": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.password",
    "tabula.util.tabulaoption.relative_area": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.relative_area",
    "tabula.util.tabulaoption.relative_columns": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.relative_columns",
    "tabula.util.tabulaoption.silent": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.silent",
    "tabula.util.tabulaoption.stream": "https://tabula-py.readthedocs.io/en/stable/tabula.html#tabula.util.TabulaOption.stream",
}
