VERSION = "3.2.1"

# fmt: off
MAPPING = {
    "tap": "https://tappy.readthedocs.io/en/stable/",
    "tap.line": "https://tappy.readthedocs.io/en/stable/consumers.html",
    "tap.line.bail": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Bail",
    "tap.line.bail.category": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Bail.category",
    "tap.line.bail.reason": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Bail.reason",
    "tap.line.diagnostic": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Diagnostic",
    "tap.line.diagnostic.category": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Diagnostic.category",
    "tap.line.diagnostic.text": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Diagnostic.text",
    "tap.line.plan": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Plan",
    "tap.line.plan.category": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Plan.category",
    "tap.line.plan.expected_tests": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Plan.expected_tests",
    "tap.line.plan.skip": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Plan.skip",
    "tap.line.result": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Result",
    "tap.line.result.category": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Result.category",
    "tap.line.result.description": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Result.description",
    "tap.line.result.number": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Result.number",
    "tap.line.result.ok": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Result.ok",
    "tap.line.result.skip": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Result.skip",
    "tap.line.result.todo": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Result.todo",
    "tap.line.result.yaml_block": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Result.yaml_block",
    "tap.line.unknown": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Unknown",
    "tap.line.unknown.category": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Unknown.category",
    "tap.line.version": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Version",
    "tap.line.version.category": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Version.category",
    "tap.line.version.version": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.line.Version.version",
    "tap.loader": "https://tappy.readthedocs.io/en/stable/consumers.html",
    "tap.loader.loader": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.loader.Loader",
    "tap.loader.loader.load": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.loader.Loader.load",
    "tap.loader.loader.load_suite_from_file": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.loader.Loader.load_suite_from_file",
    "tap.loader.loader.load_suite_from_stdin": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.loader.Loader.load_suite_from_stdin",
    "tap.parser": "https://tappy.readthedocs.io/en/stable/consumers.html",
    "tap.parser.parser": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.parser.Parser",
    "tap.parser.parser.parse": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.parser.Parser.parse",
    "tap.parser.parser.parse_file": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.parser.Parser.parse_file",
    "tap.parser.parser.parse_line": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.parser.Parser.parse_line",
    "tap.parser.parser.parse_stdin": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.parser.Parser.parse_stdin",
    "tap.parser.parser.parse_text": "https://tappy.readthedocs.io/en/stable/consumers.html#tap.parser.Parser.parse_text",
}
