VERSION = "2.2.0"

# fmt: off
MAPPING = {
    "telegraph": "https://python-telegraph.readthedocs.io/en/stable/",
    "telegraph.api": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#module-telegraph.api",
    "telegraph.api.telegraph": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph",
    "telegraph.api.telegraph.create_account": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.create_account",
    "telegraph.api.telegraph.create_page": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.create_page",
    "telegraph.api.telegraph.edit_account_info": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.edit_account_info",
    "telegraph.api.telegraph.edit_page": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.edit_page",
    "telegraph.api.telegraph.get_access_token": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.get_access_token",
    "telegraph.api.telegraph.get_account_info": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.get_account_info",
    "telegraph.api.telegraph.get_page": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.get_page",
    "telegraph.api.telegraph.get_page_list": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.get_page_list",
    "telegraph.api.telegraph.get_views": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.get_views",
    "telegraph.api.telegraph.revoke_access_token": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.revoke_access_token",
    "telegraph.api.telegraph.upload_file": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.Telegraph.upload_file",
    "telegraph.api.telegraphapi": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.TelegraphApi",
    "telegraph.api.telegraphapi.access_token": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.TelegraphApi.access_token",
    "telegraph.api.telegraphapi.domain": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.TelegraphApi.domain",
    "telegraph.api.telegraphapi.method": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.TelegraphApi.method",
    "telegraph.api.telegraphapi.session": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.TelegraphApi.session",
    "telegraph.api.telegraphapi.upload_file": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.api.TelegraphApi.upload_file",
    "telegraph.upload": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#module-telegraph.upload",
    "telegraph.upload.upload_file": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.upload.upload_file",
    "telegraph.utils": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#module-telegraph.utils",
    "telegraph.utils.filesopener": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.FilesOpener",
    "telegraph.utils.filesopener.close_files": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.FilesOpener.close_files",
    "telegraph.utils.filesopener.open_files": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.FilesOpener.open_files",
    "telegraph.utils.html_to_nodes": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.html_to_nodes",
    "telegraph.utils.htmltonodesparser": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.HtmlToNodesParser",
    "telegraph.utils.htmltonodesparser.add_str_node": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.HtmlToNodesParser.add_str_node",
    "telegraph.utils.htmltonodesparser.get_nodes": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.HtmlToNodesParser.get_nodes",
    "telegraph.utils.htmltonodesparser.handle_charref": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.HtmlToNodesParser.handle_charref",
    "telegraph.utils.htmltonodesparser.handle_data": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.HtmlToNodesParser.handle_data",
    "telegraph.utils.htmltonodesparser.handle_endtag": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.HtmlToNodesParser.handle_endtag",
    "telegraph.utils.htmltonodesparser.handle_entityref": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.HtmlToNodesParser.handle_entityref",
    "telegraph.utils.htmltonodesparser.handle_starttag": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.HtmlToNodesParser.handle_starttag",
    "telegraph.utils.json_dumps": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.json_dumps",
    "telegraph.utils.nodes_to_html": "https://python-telegraph.readthedocs.io/en/stable/telegraph.html#telegraph.utils.nodes_to_html",
}
