VERSION = "2.6.5"

# fmt: off
MAPPING = {
    "tensorboardx": "https://tensorboard-pytorch.readthedocs.io/en/stable/",
    "tensorboardx.globalsummarywriter": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.GlobalSummaryWriter",
    "tensorboardx.globalsummarywriter.__init__": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.GlobalSummaryWriter.__init__",
    "tensorboardx.globalsummarywriter.add_image": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.GlobalSummaryWriter.add_image",
    "tensorboardx.globalsummarywriter.add_scalar": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.GlobalSummaryWriter.add_scalar",
    "tensorboardx.globalsummarywriter.add_text": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.GlobalSummaryWriter.add_text",
    "tensorboardx.globalsummarywriter.getsummarywriter": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.GlobalSummaryWriter.getSummaryWriter",
    "tensorboardx.summarywriter": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter",
    "tensorboardx.summarywriter.__init__": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.__init__",
    "tensorboardx.summarywriter.add_audio": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_audio",
    "tensorboardx.summarywriter.add_custom_scalars": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_custom_scalars",
    "tensorboardx.summarywriter.add_custom_scalars_marginchart": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_custom_scalars_marginchart",
    "tensorboardx.summarywriter.add_custom_scalars_multilinechart": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_custom_scalars_multilinechart",
    "tensorboardx.summarywriter.add_embedding": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_embedding",
    "tensorboardx.summarywriter.add_figure": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_figure",
    "tensorboardx.summarywriter.add_graph": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_graph",
    "tensorboardx.summarywriter.add_histogram": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_histogram",
    "tensorboardx.summarywriter.add_histogram_raw": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_histogram_raw",
    "tensorboardx.summarywriter.add_hparams": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_hparams",
    "tensorboardx.summarywriter.add_image": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_image",
    "tensorboardx.summarywriter.add_image_with_boxes": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_image_with_boxes",
    "tensorboardx.summarywriter.add_images": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_images",
    "tensorboardx.summarywriter.add_mesh": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_mesh",
    "tensorboardx.summarywriter.add_onnx_graph": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_onnx_graph",
    "tensorboardx.summarywriter.add_openvino_graph": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_openvino_graph",
    "tensorboardx.summarywriter.add_pr_curve": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_pr_curve",
    "tensorboardx.summarywriter.add_pr_curve_raw": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_pr_curve_raw",
    "tensorboardx.summarywriter.add_scalar": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_scalar",
    "tensorboardx.summarywriter.add_scalars": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_scalars",
    "tensorboardx.summarywriter.add_text": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_text",
    "tensorboardx.summarywriter.add_video": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.add_video",
    "tensorboardx.summarywriter.close": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.close",
    "tensorboardx.summarywriter.export_scalars_to_json": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.export_scalars_to_json",
    "tensorboardx.summarywriter.flush": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.SummaryWriter.flush",
    "tensorboardx.torchvis": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.TorchVis",
    "tensorboardx.torchvis.__init__": "https://tensorboard-pytorch.readthedocs.io/en/stable/tensorboard.html#tensorboardX.TorchVis.__init__",
    "tensorboardx.utils": "https://tensorboard-pytorch.readthedocs.io/en/stable/utils.html",
    "tensorboardx.utils.figure_to_image": "https://tensorboard-pytorch.readthedocs.io/en/stable/utils.html#tensorboardX.utils.figure_to_image",
}
