VERSION = "0.4.5"

# fmt: off
MAPPING = {
    "textcase": "https://zobweyt.github.io/textcase/",
    "textcase.acronym": "https://zobweyt.github.io/textcase/ru/reference/#textcase.ACRONYM",
    "textcase.boundary": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Boundary",
    "textcase.boundary.from_delimiter": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Boundary.from_delimiter",
    "textcase.boundary.length": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Boundary.length",
    "textcase.boundary.match": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Boundary.match",
    "textcase.boundary.start": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Boundary.start",
    "textcase.camel": "https://zobweyt.github.io/textcase/ru/reference/#textcase.camel",
    "textcase.case": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Case",
    "textcase.case.__call__": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Case.__call__",
    "textcase.case.delimiter": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Case.delimiter",
    "textcase.case.match": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Case.match",
    "textcase.case.transform": "https://zobweyt.github.io/textcase/ru/reference/#textcase.Case.transform",
    "textcase.constant": "https://zobweyt.github.io/textcase/ru/reference/#textcase.constant",
    "textcase.digit_lower": "https://zobweyt.github.io/textcase/ru/reference/#textcase.DIGIT_LOWER",
    "textcase.digit_upper": "https://zobweyt.github.io/textcase/ru/reference/#textcase.DIGIT_UPPER",
    "textcase.hyphen": "https://zobweyt.github.io/textcase/ru/reference/#textcase.HYPHEN",
    "textcase.interpunct": "https://zobweyt.github.io/textcase/ru/reference/#textcase.INTERPUNCT",
    "textcase.kebab": "https://zobweyt.github.io/textcase/ru/reference/#textcase.kebab",
    "textcase.lower": "https://zobweyt.github.io/textcase/ru/reference/#textcase.lower",
    "textcase.lower_digit": "https://zobweyt.github.io/textcase/ru/reference/#textcase.LOWER_DIGIT",
    "textcase.lower_upper": "https://zobweyt.github.io/textcase/ru/reference/#textcase.LOWER_UPPER",
    "textcase.middot": "https://zobweyt.github.io/textcase/ru/reference/#textcase.middot",
    "textcase.pascal": "https://zobweyt.github.io/textcase/ru/reference/#textcase.pascal",
    "textcase.sentence": "https://zobweyt.github.io/textcase/ru/reference/#textcase.sentence",
    "textcase.snake": "https://zobweyt.github.io/textcase/ru/reference/#textcase.snake",
    "textcase.space": "https://zobweyt.github.io/textcase/ru/reference/#textcase.SPACE",
    "textcase.title": "https://zobweyt.github.io/textcase/ru/reference/#textcase.title",
    "textcase.underscore": "https://zobweyt.github.io/textcase/ru/reference/#textcase.UNDERSCORE",
    "textcase.upper": "https://zobweyt.github.io/textcase/ru/reference/#textcase.upper",
    "textcase.upper_digit": "https://zobweyt.github.io/textcase/ru/reference/#textcase.UPPER_DIGIT",
    "textcase.upper_lower": "https://zobweyt.github.io/textcase/ru/reference/#textcase.UPPER_LOWER",
}
