VERSION = "1.6.1"

# fmt: off
MAPPING = {
    "tkcalendar": "https://tkcalendar.readthedocs.io/en/stable/",
    "tkcalendar.calendar": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar",
    "tkcalendar.calendar.__init__": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.__init__",
    "tkcalendar.calendar.calevent_cget": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.calevent_cget",
    "tkcalendar.calendar.calevent_configure": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.calevent_configure",
    "tkcalendar.calendar.calevent_create": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.calevent_create",
    "tkcalendar.calendar.calevent_lower": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.calevent_lower",
    "tkcalendar.calendar.calevent_raise": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.calevent_raise",
    "tkcalendar.calendar.calevent_remove": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.calevent_remove",
    "tkcalendar.calendar.configure": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.configure",
    "tkcalendar.calendar.format_date": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.format_date",
    "tkcalendar.calendar.get_calevents": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.get_calevents",
    "tkcalendar.calendar.get_date": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.get_date",
    "tkcalendar.calendar.get_displayed_month": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.get_displayed_month",
    "tkcalendar.calendar.keys": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.keys",
    "tkcalendar.calendar.see": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.see",
    "tkcalendar.calendar.selection_clear": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.selection_clear",
    "tkcalendar.calendar.selection_get": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.selection_get",
    "tkcalendar.calendar.selection_set": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.selection_set",
    "tkcalendar.calendar.tag_cget": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.tag_cget",
    "tkcalendar.calendar.tag_config": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.tag_config",
    "tkcalendar.calendar.tag_delete": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.tag_delete",
    "tkcalendar.calendar.tag_names": "https://tkcalendar.readthedocs.io/en/stable/Calendar.html#tkcalendar.Calendar.tag_names",
    "tkcalendar.dateentry": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry",
    "tkcalendar.dateentry.__init__": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.__init__",
    "tkcalendar.dateentry.cget": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.cget",
    "tkcalendar.dateentry.config": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.config",
    "tkcalendar.dateentry.configure": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.configure",
    "tkcalendar.dateentry.destroy": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.destroy",
    "tkcalendar.dateentry.drop_down": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.drop_down",
    "tkcalendar.dateentry.get_date": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.get_date",
    "tkcalendar.dateentry.keys": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.keys",
    "tkcalendar.dateentry.set_date": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.set_date",
    "tkcalendar.dateentry.state": "https://tkcalendar.readthedocs.io/en/stable/DateEntry.html#tkcalendar.DateEntry.state",
}
