VERSION = "0.3.0"

# fmt: off
MAPPING = {
    "torch_optimizer": "https://pytorch-optimizer.readthedocs.io/en/latest/",
    "torch_optimizer.accsgd": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AccSGD",
    "torch_optimizer.accsgd.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AccSGD.step",
    "torch_optimizer.adabound": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AdaBound",
    "torch_optimizer.adabound.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AdaBound.step",
    "torch_optimizer.adafactor": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.Adafactor",
    "torch_optimizer.adafactor.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.Adafactor.step",
    "torch_optimizer.adamod": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AdaMod",
    "torch_optimizer.adamod.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AdaMod.step",
    "torch_optimizer.adamp": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AdamP",
    "torch_optimizer.adamp.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AdamP.step",
    "torch_optimizer.aggmo": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AggMo",
    "torch_optimizer.aggmo.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.AggMo.step",
    "torch_optimizer.diffgrad": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.DiffGrad",
    "torch_optimizer.diffgrad.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.DiffGrad.step",
    "torch_optimizer.lamb": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.Lamb",
    "torch_optimizer.lamb.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.Lamb.step",
    "torch_optimizer.novograd": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.NovoGrad",
    "torch_optimizer.novograd.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.NovoGrad.step",
    "torch_optimizer.pid": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.PID",
    "torch_optimizer.pid.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.PID.step",
    "torch_optimizer.qhadam": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.QHAdam",
    "torch_optimizer.qhadam.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.QHAdam.step",
    "torch_optimizer.qhm": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.QHM",
    "torch_optimizer.qhm.direct": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.QHM.DIRECT",
    "torch_optimizer.qhm.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.QHM.step",
    "torch_optimizer.radam": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.RAdam",
    "torch_optimizer.radam.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.RAdam.step",
    "torch_optimizer.sgdp": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.SGDP",
    "torch_optimizer.sgdp.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.SGDP.step",
    "torch_optimizer.sgdw": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.SGDW",
    "torch_optimizer.sgdw.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.SGDW.step",
    "torch_optimizer.shampoo": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.Shampoo",
    "torch_optimizer.shampoo.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.Shampoo.step",
    "torch_optimizer.swats": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.SWATS",
    "torch_optimizer.swats.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.SWATS.step",
    "torch_optimizer.yogi": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.Yogi",
    "torch_optimizer.yogi.step": "https://pytorch-optimizer.readthedocs.io/en/latest/api.html#torch_optimizer.Yogi.step",
}
