VERSION = "0.12.2"

# fmt: off
MAPPING = {
    "trio_websocket": "https://trio-websocket.readthedocs.io/en/stable/",
    "trio_websocket._impl": "https://trio-websocket.readthedocs.io/en/stable/api.html",
    "trio_websocket._impl.closereason": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.CloseReason",
    "trio_websocket._impl.connectionclosed": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.ConnectionClosed",
    "trio_websocket._impl.connectionrejected": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.ConnectionRejected",
    "trio_websocket._impl.connectiontimeout": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.ConnectionTimeout",
    "trio_websocket._impl.disconnectiontimeout": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.DisconnectionTimeout",
    "trio_websocket._impl.endpoint": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.Endpoint",
    "trio_websocket._impl.handshakeerror": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.HandshakeError",
    "trio_websocket.closereason": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.CloseReason",
    "trio_websocket.closereason.code": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.CloseReason.code",
    "trio_websocket.closereason.name": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.CloseReason.name",
    "trio_websocket.closereason.reason": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.CloseReason.reason",
    "trio_websocket.connect_websocket": "https://trio-websocket.readthedocs.io/en/stable/clients.html#trio_websocket.connect_websocket",
    "trio_websocket.connect_websocket_url": "https://trio-websocket.readthedocs.io/en/stable/clients.html#trio_websocket.connect_websocket_url",
    "trio_websocket.connectionclosed": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.ConnectionClosed",
    "trio_websocket.connectionrejected": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.ConnectionRejected",
    "trio_websocket.connectiontimeout": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.ConnectionTimeout",
    "trio_websocket.disconnectiontimeout": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.DisconnectionTimeout",
    "trio_websocket.endpoint": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.Endpoint",
    "trio_websocket.endpoint.address": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.Endpoint.address",
    "trio_websocket.endpoint.is_ssl": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.Endpoint.is_ssl",
    "trio_websocket.endpoint.port": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.Endpoint.port",
    "trio_websocket.endpoint.url": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.Endpoint.url",
    "trio_websocket.handshakeerror": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.HandshakeError",
    "trio_websocket.open_websocket": "https://trio-websocket.readthedocs.io/en/stable/clients.html#trio_websocket.open_websocket",
    "trio_websocket.open_websocket_url": "https://trio-websocket.readthedocs.io/en/stable/clients.html#trio_websocket.open_websocket_url",
    "trio_websocket.serve_websocket": "https://trio-websocket.readthedocs.io/en/stable/servers.html#trio_websocket.serve_websocket",
    "trio_websocket.websocketconnection": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection",
    "trio_websocket.websocketconnection.aclose": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.aclose",
    "trio_websocket.websocketconnection.closed": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.closed",
    "trio_websocket.websocketconnection.get_message": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.get_message",
    "trio_websocket.websocketconnection.handshake_headers": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.handshake_headers",
    "trio_websocket.websocketconnection.is_client": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.is_client",
    "trio_websocket.websocketconnection.is_server": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.is_server",
    "trio_websocket.websocketconnection.local": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.local",
    "trio_websocket.websocketconnection.path": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.path",
    "trio_websocket.websocketconnection.ping": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.ping",
    "trio_websocket.websocketconnection.pong": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.pong",
    "trio_websocket.websocketconnection.remote": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.remote",
    "trio_websocket.websocketconnection.send_message": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.send_message",
    "trio_websocket.websocketconnection.subprotocol": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketConnection.subprotocol",
    "trio_websocket.websocketrequest": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketRequest",
    "trio_websocket.websocketrequest.accept": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketRequest.accept",
    "trio_websocket.websocketrequest.headers": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketRequest.headers",
    "trio_websocket.websocketrequest.local": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketRequest.local",
    "trio_websocket.websocketrequest.proposed_subprotocols": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketRequest.proposed_subprotocols",
    "trio_websocket.websocketrequest.reject": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketRequest.reject",
    "trio_websocket.websocketrequest.remote": "https://trio-websocket.readthedocs.io/en/stable/api.html#trio_websocket.WebSocketRequest.remote",
    "trio_websocket.wrap_client_stream": "https://trio-websocket.readthedocs.io/en/stable/clients.html#trio_websocket.wrap_client_stream",
    "trio_websocket.wrap_server_stream": "https://trio-websocket.readthedocs.io/en/stable/servers.html#trio_websocket.wrap_server_stream",
}
