VERSION = "1.1.1"

# fmt: off
MAPPING = {
    "urduhack": "https://urduhack.akkefa.com/en/stable/",
    "urduhack.conll": "https://urduhack.akkefa.com/en/stable/reference/conll.html#module-urduhack.conll",
    "urduhack.conll.conll": "https://urduhack.akkefa.com/en/stable/reference/conll.html#urduhack.conll.CoNLL",
    "urduhack.conll.conll.get_fields": "https://urduhack.akkefa.com/en/stable/reference/conll.html#urduhack.conll.CoNLL.get_fields",
    "urduhack.conll.conll.iter_file": "https://urduhack.akkefa.com/en/stable/reference/conll.html#urduhack.conll.CoNLL.iter_file",
    "urduhack.conll.conll.iter_string": "https://urduhack.akkefa.com/en/stable/reference/conll.html#urduhack.conll.CoNLL.iter_string",
    "urduhack.conll.conll.load_file": "https://urduhack.akkefa.com/en/stable/reference/conll.html#urduhack.conll.CoNLL.load_file",
    "urduhack.normalization": "https://urduhack.akkefa.com/en/stable/reference/normalization.html#module-urduhack.normalization",
    "urduhack.normalization.digits_space": "https://urduhack.akkefa.com/en/stable/reference/normalization.html#urduhack.normalization.digits_space",
    "urduhack.normalization.english_characters_space": "https://urduhack.akkefa.com/en/stable/reference/normalization.html#urduhack.normalization.english_characters_space",
    "urduhack.normalization.normalize": "https://urduhack.akkefa.com/en/stable/reference/normalization.html#urduhack.normalization.normalize",
    "urduhack.normalization.normalize_characters": "https://urduhack.akkefa.com/en/stable/reference/normalization.html#urduhack.normalization.normalize_characters",
    "urduhack.normalization.normalize_combine_characters": "https://urduhack.akkefa.com/en/stable/reference/normalization.html#urduhack.normalization.normalize_combine_characters",
    "urduhack.normalization.punctuations_space": "https://urduhack.akkefa.com/en/stable/reference/normalization.html#urduhack.normalization.punctuations_space",
    "urduhack.normalization.remove_diacritics": "https://urduhack.akkefa.com/en/stable/reference/normalization.html#urduhack.normalization.remove_diacritics",
    "urduhack.preprocessing": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#module-urduhack.preprocessing",
    "urduhack.preprocessing.normalize_whitespace": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#urduhack.preprocessing.normalize_whitespace",
    "urduhack.preprocessing.remove_accents": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#urduhack.preprocessing.remove_accents",
    "urduhack.preprocessing.remove_english_alphabets": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#urduhack.preprocessing.remove_english_alphabets",
    "urduhack.preprocessing.remove_punctuation": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#urduhack.preprocessing.remove_punctuation",
    "urduhack.preprocessing.replace_currency_symbols": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#urduhack.preprocessing.replace_currency_symbols",
    "urduhack.preprocessing.replace_emails": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#urduhack.preprocessing.replace_emails",
    "urduhack.preprocessing.replace_numbers": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#urduhack.preprocessing.replace_numbers",
    "urduhack.preprocessing.replace_phone_numbers": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#urduhack.preprocessing.replace_phone_numbers",
    "urduhack.preprocessing.replace_urls": "https://urduhack.akkefa.com/en/stable/reference/preprocessing.html#urduhack.preprocessing.replace_urls",
    "urduhack.tokenization": "https://urduhack.akkefa.com/en/stable/reference/tokenization.html#module-urduhack.tokenization",
    "urduhack.tokenization.sentence_tokenizer": "https://urduhack.akkefa.com/en/stable/reference/tokenization.html#urduhack.tokenization.sentence_tokenizer",
    "urduhack.tokenization.word_tokenizer": "https://urduhack.akkefa.com/en/stable/reference/tokenization.html#urduhack.tokenization.word_tokenizer",
    "urduhack.utils": "https://urduhack.akkefa.com/en/stable/reference/utils.html#module-urduhack.utils",
    "urduhack.utils.download_from_url": "https://urduhack.akkefa.com/en/stable/reference/utils.html#urduhack.utils.download_from_url",
    "urduhack.utils.pickle_dump": "https://urduhack.akkefa.com/en/stable/reference/utils.html#urduhack.utils.pickle_dump",
    "urduhack.utils.pickle_load": "https://urduhack.akkefa.com/en/stable/reference/utils.html#urduhack.utils.pickle_load",
    "urduhack.utils.remove_file": "https://urduhack.akkefa.com/en/stable/reference/utils.html#urduhack.utils.remove_file",
}
