VERSION = "0.26"

# fmt: off
MAPPING = {
    "validate_pyproject": "https://validate-pyproject.readthedocs.io/en/stable/",
    "validate_pyproject.api": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.api.html#module-validate_pyproject.api",
    "validate_pyproject.api.validator": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.api.html#validate_pyproject.api.Validator",
    "validate_pyproject.api.validator.__call__": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.api.html#validate_pyproject.api.Validator.__call__",
    "validate_pyproject.api.validator.extra_validations": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.api.html#validate_pyproject.api.Validator.extra_validations",
    "validate_pyproject.api.validator.formats": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.api.html#validate_pyproject.api.Validator.formats",
    "validate_pyproject.api.validator.generated_code": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.api.html#validate_pyproject.api.Validator.generated_code",
    "validate_pyproject.api.validator.registry": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.api.html#validate_pyproject.api.Validator.registry",
    "validate_pyproject.api.validator.schema": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.api.html#validate_pyproject.api.Validator.schema",
    "validate_pyproject.error_reporting": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.errors.html",
    "validate_pyproject.error_reporting.validationerror": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.errors.html#validate_pyproject.errors.ValidationError",
    "validate_pyproject.errors": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.errors.html#module-validate_pyproject.errors",
    "validate_pyproject.errors.invalidschemaversion": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.errors.html#validate_pyproject.errors.InvalidSchemaVersion",
    "validate_pyproject.errors.schemamissingid": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.errors.html#validate_pyproject.errors.SchemaMissingId",
    "validate_pyproject.errors.schemawithduplicatedid": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.errors.html#validate_pyproject.errors.SchemaWithDuplicatedId",
    "validate_pyproject.errors.validationerror": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.errors.html#validate_pyproject.errors.ValidationError",
    "validate_pyproject.errors.validationerror.details": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.errors.html#validate_pyproject.errors.ValidationError.details",
    "validate_pyproject.errors.validationerror.summary": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.errors.html#validate_pyproject.errors.ValidationError.summary",
    "validate_pyproject.formats": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#module-validate_pyproject.formats",
    "validate_pyproject.formats.import_name": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.import_name",
    "validate_pyproject.formats.int": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.int",
    "validate_pyproject.formats.int16": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.int16",
    "validate_pyproject.formats.int32": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.int32",
    "validate_pyproject.formats.int64": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.int64",
    "validate_pyproject.formats.int8": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.int8",
    "validate_pyproject.formats.pep440": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.pep440",
    "validate_pyproject.formats.pep508": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.pep508",
    "validate_pyproject.formats.pep508_identifier": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.pep508_identifier",
    "validate_pyproject.formats.pep508_versionspec": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.pep508_versionspec",
    "validate_pyproject.formats.pep517_backend_reference": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.pep517_backend_reference",
    "validate_pyproject.formats.pep561_stub_name": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.pep561_stub_name",
    "validate_pyproject.formats.python_entrypoint_group": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.python_entrypoint_group",
    "validate_pyproject.formats.python_entrypoint_name": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.python_entrypoint_name",
    "validate_pyproject.formats.python_entrypoint_reference": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.python_entrypoint_reference",
    "validate_pyproject.formats.python_identifier": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.python_identifier",
    "validate_pyproject.formats.python_module_name": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.python_module_name",
    "validate_pyproject.formats.python_module_name_relaxed": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.python_module_name_relaxed",
    "validate_pyproject.formats.python_qualified_identifier": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.python_qualified_identifier",
    "validate_pyproject.formats.spdx": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.SPDX",
    "validate_pyproject.formats.trove_classifier": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.trove_classifier",
    "validate_pyproject.formats.uint": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.uint",
    "validate_pyproject.formats.uint16": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.uint16",
    "validate_pyproject.formats.uint32": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.uint32",
    "validate_pyproject.formats.uint64": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.uint64",
    "validate_pyproject.formats.uint8": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.uint8",
    "validate_pyproject.formats.url": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.formats.html#validate_pyproject.formats.url",
    "validate_pyproject.types": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.types.html#module-validate_pyproject.types",
    "validate_pyproject.types.formatvalidationfn": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.types.html#validate_pyproject.types.FormatValidationFn",
    "validate_pyproject.types.plugin": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.types.html#validate_pyproject.types.Plugin",
    "validate_pyproject.types.schema": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.types.html#validate_pyproject.types.Schema",
    "validate_pyproject.types.validationfn": "https://validate-pyproject.readthedocs.io/en/stable/api/validate_pyproject.types.html#validate_pyproject.types.ValidationFn",
}
