VERSION = "1.1.1"

# fmt: off
MAPPING = {
    "versionfinder": "https://versionfinder.readthedocs.io/en/stable/",
    "versionfinder.find_version": "https://versionfinder.readthedocs.io/en/stable/versionfinder.html#versionfinder.find_version",
    "versionfinder.version": "https://versionfinder.readthedocs.io/en/stable/versionfinder.version.html#module-versionfinder.version",
    "versionfinder.versionfinder": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#module-versionfinder.versionfinder",
    "versionfinder.versionfinder.chdir": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#versionfinder.versionfinder.chdir",
    "versionfinder.versionfinder.versionfinder": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#versionfinder.versionfinder.VersionFinder",
    "versionfinder.versionfinder.versionfinder._dist_version_url": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#versionfinder.versionfinder.VersionFinder._dist_version_url",
    "versionfinder.versionfinder.versionfinder._find_git_info": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#versionfinder.versionfinder.VersionFinder._find_git_info",
    "versionfinder.versionfinder.versionfinder._find_pip_info": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#versionfinder.versionfinder.VersionFinder._find_pip_info",
    "versionfinder.versionfinder.versionfinder._find_pkg_info": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#versionfinder.versionfinder.VersionFinder._find_pkg_info",
    "versionfinder.versionfinder.versionfinder._git_repo_path": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#versionfinder.versionfinder.VersionFinder._git_repo_path",
    "versionfinder.versionfinder.versionfinder._package_top_dir": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#versionfinder.versionfinder.VersionFinder._package_top_dir",
    "versionfinder.versionfinder.versionfinder.find_package_version": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versionfinder.html#versionfinder.versionfinder.VersionFinder.find_package_version",
    "versionfinder.versioninfo": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#module-versionfinder.versioninfo",
    "versionfinder.versioninfo.versioninfo": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo",
    "versionfinder.versioninfo.versioninfo.as_dict": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.as_dict",
    "versionfinder.versioninfo.versioninfo.git_commit": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.git_commit",
    "versionfinder.versioninfo.versioninfo.git_is_dirty": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.git_is_dirty",
    "versionfinder.versioninfo.versioninfo.git_remote": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.git_remote",
    "versionfinder.versioninfo.versioninfo.git_remotes": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.git_remotes",
    "versionfinder.versioninfo.versioninfo.git_str": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.git_str",
    "versionfinder.versioninfo.versioninfo.git_tag": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.git_tag",
    "versionfinder.versioninfo.versioninfo.long_str": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.long_str",
    "versionfinder.versioninfo.versioninfo.pip_requirement": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.pip_requirement",
    "versionfinder.versioninfo.versioninfo.pip_url": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.pip_url",
    "versionfinder.versioninfo.versioninfo.pip_version": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.pip_version",
    "versionfinder.versioninfo.versioninfo.pkg_resources_url": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.pkg_resources_url",
    "versionfinder.versioninfo.versioninfo.pkg_resources_version": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.pkg_resources_version",
    "versionfinder.versioninfo.versioninfo.short_str": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.short_str",
    "versionfinder.versioninfo.versioninfo.url": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.url",
    "versionfinder.versioninfo.versioninfo.version": "https://versionfinder.readthedocs.io/en/stable/versionfinder.versioninfo.html#versionfinder.versioninfo.VersionInfo.version",
}
