VERSION = "1.0.1"

# fmt: off
MAPPING = {
    "walkscore": "https://walkscore-api.readthedocs.io/en/latest/",
    "walkscore.api": "https://walkscore-api.readthedocs.io/en/latest/api.html#module-walkscore.api",
    "walkscore.api.walkscoreapi": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.api.WalkScoreAPI",
    "walkscore.api.walkscoreapi.api_key": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.api.WalkScoreAPI.api_key",
    "walkscore.api.walkscoreapi.get_score": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.api.WalkScoreAPI.get_score",
    "walkscore.api.walkscoreapi.http_client": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.api.WalkScoreAPI.http_client",
    "walkscore.api.walkscoreapi.max_retries": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.api.WalkScoreAPI.max_retries",
    "walkscore.api.walkscoreapi.proxy": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.api.WalkScoreAPI.proxy",
    "walkscore.errors": "https://walkscore-api.readthedocs.io/en/latest/errors.html#module-walkscore.errors",
    "walkscore.errors.authenticationerror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.AuthenticationError",
    "walkscore.errors.bindingerror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.BindingError",
    "walkscore.errors.blockediperror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.BlockedIPError",
    "walkscore.errors.httpconnectionerror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.HTTPConnectionError",
    "walkscore.errors.httptimeouterror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.HTTPTimeoutError",
    "walkscore.errors.internalapierror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.InternalAPIError",
    "walkscore.errors.invalidcoordinateserror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.InvalidCoordinatesError",
    "walkscore.errors.quotaerror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.QuotaError",
    "walkscore.errors.scoreinprogresserror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.ScoreInProgressError",
    "walkscore.errors.sslerror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.SSLError",
    "walkscore.errors.walkscoreerror": "https://walkscore-api.readthedocs.io/en/latest/errors.html#walkscore.errors.WalkScoreError",
    "walkscore.http_client": "https://walkscore-api.readthedocs.io/en/latest/api.html#module-walkscore.http_client",
    "walkscore.http_client.httpclient": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.http_client.HTTPClient",
    "walkscore.http_client.httpclient.close": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.http_client.HTTPClient.close",
    "walkscore.http_client.httpclient.request": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.http_client.HTTPClient.request",
    "walkscore.http_client.httpclient.request_with_retries": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.http_client.HTTPClient.request_with_retries",
    "walkscore.locationscore": "https://walkscore-api.readthedocs.io/en/latest/api.html#module-walkscore.locationscore",
    "walkscore.locationscore.locationscore": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore",
    "walkscore.locationscore.locationscore.address": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.address",
    "walkscore.locationscore.locationscore.bike_description": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.bike_description",
    "walkscore.locationscore.locationscore.bike_score": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.bike_score",
    "walkscore.locationscore.locationscore.from_dict": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.from_dict",
    "walkscore.locationscore.locationscore.from_json": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.from_json",
    "walkscore.locationscore.locationscore.help_link": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.help_link",
    "walkscore.locationscore.locationscore.logo_url": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.logo_url",
    "walkscore.locationscore.locationscore.more_info_icon": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.more_info_icon",
    "walkscore.locationscore.locationscore.more_info_link": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.more_info_link",
    "walkscore.locationscore.locationscore.original_coordinates": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.original_coordinates",
    "walkscore.locationscore.locationscore.original_latitude": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.original_latitude",
    "walkscore.locationscore.locationscore.original_longitude": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.original_longitude",
    "walkscore.locationscore.locationscore.property_page_link": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.property_page_link",
    "walkscore.locationscore.locationscore.snapped_coordinates": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.snapped_coordinates",
    "walkscore.locationscore.locationscore.snapped_latitude": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.snapped_latitude",
    "walkscore.locationscore.locationscore.snapped_longitude": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.snapped_longitude",
    "walkscore.locationscore.locationscore.status": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.status",
    "walkscore.locationscore.locationscore.to_dict": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.to_dict",
    "walkscore.locationscore.locationscore.to_json": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.to_json",
    "walkscore.locationscore.locationscore.transit_description": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.transit_description",
    "walkscore.locationscore.locationscore.transit_score": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.transit_score",
    "walkscore.locationscore.locationscore.transit_summary": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.transit_summary",
    "walkscore.locationscore.locationscore.walk_description": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.walk_description",
    "walkscore.locationscore.locationscore.walk_score": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.walk_score",
    "walkscore.locationscore.locationscore.walk_updated": "https://walkscore-api.readthedocs.io/en/latest/api.html#walkscore.locationscore.LocationScore.walk_updated",
}
