VERSION = "0.11.0"

# fmt: off
MAPPING = {
    "webdav4": "https://skshetry.github.io/webdav4/",
    "webdav4.client": "https://skshetry.github.io/webdav4/reference/client.html#module-webdav4.client",
    "webdav4.client.badgatewayerror": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.BadGatewayError",
    "webdav4.client.client": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client",
    "webdav4.client.client.content_language": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.content_language",
    "webdav4.client.client.content_length": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.content_length",
    "webdav4.client.client.content_type": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.content_type",
    "webdav4.client.client.copy": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.copy",
    "webdav4.client.client.created": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.created",
    "webdav4.client.client.detected_features": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.detected_features",
    "webdav4.client.client.download_file": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.download_file",
    "webdav4.client.client.download_fileobj": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.download_fileobj",
    "webdav4.client.client.etag": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.etag",
    "webdav4.client.client.exists": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.exists",
    "webdav4.client.client.get_property": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.get_property",
    "webdav4.client.client.get_props": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.get_props",
    "webdav4.client.client.info": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.info",
    "webdav4.client.client.isdir": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.isdir",
    "webdav4.client.client.isfile": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.isfile",
    "webdav4.client.client.join_url": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.join_url",
    "webdav4.client.client.ls": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.ls",
    "webdav4.client.client.mkdir": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.mkdir",
    "webdav4.client.client.modified": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.modified",
    "webdav4.client.client.move": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.move",
    "webdav4.client.client.open": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.open",
    "webdav4.client.client.options": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.options",
    "webdav4.client.client.propfind": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.propfind",
    "webdav4.client.client.remove": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.remove",
    "webdav4.client.client.request": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.request",
    "webdav4.client.client.set_property": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.set_property",
    "webdav4.client.client.upload_file": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.upload_file",
    "webdav4.client.client.upload_fileobj": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.Client.upload_fileobj",
    "webdav4.client.clienterror": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.ClientError",
    "webdav4.client.featuredetection": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.FeatureDetection",
    "webdav4.client.forbiddenoperation": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.ForbiddenOperation",
    "webdav4.client.httperror": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.HTTPError",
    "webdav4.client.insufficientstorage": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.InsufficientStorage",
    "webdav4.client.isacollectionerror": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.IsACollectionError",
    "webdav4.client.isaresourceerror": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.IsAResourceError",
    "webdav4.client.multistatuserror": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.MultiStatusError",
    "webdav4.client.resourcealreadyexists": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.ResourceAlreadyExists",
    "webdav4.client.resourceconflict": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.ResourceConflict",
    "webdav4.client.resourcelocked": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.ResourceLocked",
    "webdav4.client.resourcenotfound": "https://skshetry.github.io/webdav4/reference/client.html#webdav4.client.ResourceNotFound",
}
