VERSION = "5.1.3"

# fmt: off
MAPPING = {
    "wolframalpha": "https://wolframalpha.readthedocs.io/en/stable/",
    "wolframalpha.assumption": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Assumption",
    "wolframalpha.assumption.text": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Assumption.text",
    "wolframalpha.client": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Client",
    "wolframalpha.client.aquery": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Client.aquery",
    "wolframalpha.client.from_env": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Client.from_env",
    "wolframalpha.client.query": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Client.query",
    "wolframalpha.client.url": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Client.url",
    "wolframalpha.document": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Document",
    "wolframalpha.document.children": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Document.children",
    "wolframalpha.document.make": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Document.make",
    "wolframalpha.errorhandler": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.ErrorHandler",
    "wolframalpha.identity": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.identity",
    "wolframalpha.image": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Image",
    "wolframalpha.image.key": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Image.key",
    "wolframalpha.pod": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Pod",
    "wolframalpha.pod.children": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Pod.children",
    "wolframalpha.pod.primary": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Pod.primary",
    "wolframalpha.pod.text": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Pod.text",
    "wolframalpha.pod.texts": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Pod.texts",
    "wolframalpha.result": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Result",
    "wolframalpha.result.children": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Result.children",
    "wolframalpha.result.details": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Result.details",
    "wolframalpha.result.info": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Result.info",
    "wolframalpha.result.key": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Result.key",
    "wolframalpha.result.results": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Result.results",
    "wolframalpha.subpod": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Subpod",
    "wolframalpha.warning": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.Warning",
    "wolframalpha.xml_bool": "https://wolframalpha.readthedocs.io/en/stable/index.html#wolframalpha.xml_bool",
}
