VERSION = "0.11.0"

# fmt: off
MAPPING = {
    "xcomponent": "https://mardiros.github.io/xcomponent/",
    "xcomponent.adapters": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.adapters.html#module-xcomponent.adapters",
    "xcomponent.adapters.babel": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.adapters.babel.html#module-xcomponent.adapters.babel",
    "xcomponent.adapters.babel.extract_xcomponent": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.adapters.babel.html#xcomponent.adapters.babel.extract_xcomponent",
    "xcomponent.catalog": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.Catalog",
    "xcomponent.catalog.component": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.Catalog.component",
    "xcomponent.catalog.function": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.Catalog.function",
    "xcomponent.catalog.register_component": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.Catalog.register_component",
    "xcomponent.catalog.render": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.Catalog.render",
    "xcomponent.component": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.Component",
    "xcomponent.extract_xcomponent": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.extract_xcomponent",
    "xcomponent.function": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.Function",
    "xcomponent.service": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.service.html#module-xcomponent.service",
    "xcomponent.service.catalog": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.service.catalog.html#module-xcomponent.service.catalog",
    "xcomponent.service.catalog.catalog": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.service.catalog.html#xcomponent.service.catalog.Catalog",
    "xcomponent.service.catalog.catalog.component": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.service.catalog.html#xcomponent.service.catalog.Catalog.component",
    "xcomponent.service.catalog.catalog.function": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.service.catalog.html#xcomponent.service.catalog.Catalog.function",
    "xcomponent.service.catalog.catalog.register_component": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.service.catalog.html#xcomponent.service.catalog.Catalog.register_component",
    "xcomponent.service.catalog.catalog.render": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.service.catalog.html#xcomponent.service.catalog.Catalog.render",
    "xcomponent.service.catalog.component": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.service.catalog.html#xcomponent.service.catalog.Component",
    "xcomponent.service.catalog.function": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.service.catalog.html#xcomponent.service.catalog.Function",
    "xcomponent.xcore": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.xcore.html#module-xcomponent.xcore",
    "xcomponent.xcore.extract_expr_i18n_messages": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.xcore.html#xcomponent.xcore.extract_expr_i18n_messages",
    "xcomponent.xcore.nodetype": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.xcore.html#xcomponent.xcore.NodeType",
    "xcomponent.xcore.parse_markup": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.xcore.html#xcomponent.xcore.parse_markup",
    "xcomponent.xcore.xcatalog": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.xcore.html#xcomponent.xcore.XCatalog",
    "xcomponent.xcore.xnode": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.xcore.html#xcomponent.xcore.XNode",
    "xcomponent.xcore.xnode.__eq__": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.xcore.html#xcomponent.xcore.XNode.__eq__",
    "xcomponent.xcore.xnode.__repr__": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.xcore.html#xcomponent.xcore.XNode.__repr__",
    "xcomponent.xnode": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.XNode",
    "xcomponent.xnode.__eq__": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.XNode.__eq__",
    "xcomponent.xnode.__repr__": "https://mardiros.github.io/xcomponent/develop/xcomponent/xcomponent.html#xcomponent.XNode.__repr__",
}
