VERSION = "0.16.0"

# fmt: off
MAPPING = {
    "yagmail": "https://yagmail.readthedocs.io/en/stable/",
    "yagmail.async_core": "https://yagmail.readthedocs.io/en/stable/api.html",
    "yagmail.async_core.aio": "https://yagmail.readthedocs.io/en/stable/api.html",
    "yagmail.async_core.aio.asyncclient": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.AsyncClient",
    "yagmail.asyncclient": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.AsyncClient",
    "yagmail.asyncclient.aclose": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.AsyncClient.aclose",
    "yagmail.asyncclient.close": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.AsyncClient.close",
    "yagmail.asyncclient.login": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.AsyncClient.login",
    "yagmail.asyncclient.send": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.AsyncClient.send",
    "yagmail.asyncclient.send_unsent": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.AsyncClient.send_unsent",
    "yagmail.client": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.Client",
    "yagmail.client.close": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.Client.close",
    "yagmail.client.feedback": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.Client.feedback",
    "yagmail.client.login": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.Client.login",
    "yagmail.client.send": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.Client.send",
    "yagmail.client.send_unsent": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.Client.send_unsent",
    "yagmail.client.set_logging": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.Client.set_logging",
    "yagmail.dkim": "https://yagmail.readthedocs.io/en/stable/api.html",
    "yagmail.dkim.dkim": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.dkim.DKIM",
    "yagmail.dkim.dkim.domain": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.dkim.DKIM.domain",
    "yagmail.dkim.dkim.include_headers": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.dkim.DKIM.include_headers",
    "yagmail.dkim.dkim.private_key": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.dkim.DKIM.private_key",
    "yagmail.dkim.dkim.selector": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.dkim.DKIM.selector",
    "yagmail.error": "https://yagmail.readthedocs.io/en/stable/api.html#module-yagmail.error",
    "yagmail.error.yagaddresserror": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.error.YagAddressError",
    "yagmail.error.yagconnectionclosed": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.error.YagConnectionClosed",
    "yagmail.error.yaginvalidemailaddress": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.error.YagInvalidEmailAddress",
    "yagmail.inline": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.inline",
    "yagmail.raw": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.raw",
    "yagmail.register": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.register",
    "yagmail.sender": "https://yagmail.readthedocs.io/en/stable/api.html",
    "yagmail.sender.client": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.Client",
    "yagmail.utils": "https://yagmail.readthedocs.io/en/stable/api.html",
    "yagmail.utils.inline": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.inline",
    "yagmail.utils.raw": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.raw",
    "yagmail.validate": "https://yagmail.readthedocs.io/en/stable/api.html",
    "yagmail.validate.validate_email_with_regex": "https://yagmail.readthedocs.io/en/stable/api.html#yagmail.validate.validate_email_with_regex",
}
