VERSION = "1.19.1"

# fmt: off
MAPPING = {
    "yamlfix": "https://lyz-code.github.io/yamlfix/",
    "yamlfix.adapters": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters",
    "yamlfix.adapters.sourcecodefixer": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.SourceCodeFixer",
    "yamlfix.adapters.sourcecodefixer.__init__": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.SourceCodeFixer.__init__",
    "yamlfix.adapters.sourcecodefixer.fix": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.SourceCodeFixer.fix",
    "yamlfix.adapters.yaml": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.Yaml",
    "yamlfix.adapters.yaml.__init__": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.Yaml.__init__",
    "yamlfix.adapters.yamlfixconfig": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.model.YamlfixConfig",
    "yamlfix.adapters.yamlfixrepresenter": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.YamlfixRepresenter",
    "yamlfix.adapters.yamlfixrepresenter.__init__": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.YamlfixRepresenter.__init__",
    "yamlfix.adapters.yamlfixrepresenter.represent_mapping": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.YamlfixRepresenter.represent_mapping",
    "yamlfix.adapters.yamlfixrepresenter.represent_none": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.YamlfixRepresenter.represent_none",
    "yamlfix.adapters.yamlfixrepresenter.represent_str": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.adapters.YamlfixRepresenter.represent_str",
    "yamlfix.adapters.yamlnodestyle": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.model.YamlNodeStyle",
    "yamlfix.config": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.config",
    "yamlfix.config.configure_yamlfix": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.config.configure_yamlfix",
    "yamlfix.config.yamlfixconfig": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.model.YamlfixConfig",
    "yamlfix.entrypoints": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.entrypoints",
    "yamlfix.entrypoints.ansifgcolorcode": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.entrypoints.ANSIFGColorCode",
    "yamlfix.entrypoints.consolecolorformatter": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.entrypoints.ConsoleColorFormatter",
    "yamlfix.entrypoints.consolecolorformatter.format": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.entrypoints.ConsoleColorFormatter.format",
    "yamlfix.entrypoints.load_logger": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.entrypoints.load_logger",
    "yamlfix.fix_code": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.services.fix_code",
    "yamlfix.fix_files": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.services.fix_files",
    "yamlfix.model": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.model",
    "yamlfix.model.yamlfixconfig": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.model.YamlfixConfig",
    "yamlfix.model.yamlnodestyle": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.model.YamlNodeStyle",
    "yamlfix.services": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.services",
    "yamlfix.services.fix_code": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.services.fix_code",
    "yamlfix.services.fix_files": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.services.fix_files",
    "yamlfix.version": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.version",
    "yamlfix.version.version_info": "https://lyz-code.github.io/yamlfix/reference/#yamlfix.version.version_info",
}
