VERSION = "4.3"

# fmt: off
MAPPING = {
    "zconfig": "https://zconfig.readthedocs.io/en/stable/",
    "zconfig.cmdline": "https://zconfig.readthedocs.io/en/stable/py-mod-cmdline.html#module-ZConfig.cmdline",
    "zconfig.cmdline.extendedconfigloader": "https://zconfig.readthedocs.io/en/stable/py-mod-cmdline.html#ZConfig.cmdline.ExtendedConfigLoader",
    "zconfig.cmdline.extendedconfigloader.addoption": "https://zconfig.readthedocs.io/en/stable/py-mod-cmdline.html#ZConfig.cmdline.ExtendedConfigLoader.addOption",
    "zconfig.components": "https://zconfig.readthedocs.io/en/stable/logging-components.html",
    "zconfig.components.logger": "https://zconfig.readthedocs.io/en/stable/logging-components.html",
    "zconfig.components.logger.loghandler": "https://zconfig.readthedocs.io/en/stable/logging-components.html",
    "zconfig.components.logger.loghandler.reopenfiles": "https://zconfig.readthedocs.io/en/stable/logging-components.html#ZConfig.components.logger.loghandler.reopenFiles",
    "zconfig.configurationerror": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.ConfigurationError",
    "zconfig.configurationsyntaxerror": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.ConfigurationSyntaxError",
    "zconfig.configureloggers": "https://zconfig.readthedocs.io/en/stable/using-logging.html#ZConfig.configureLoggers",
    "zconfig.dataconversionerror": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.DataConversionError",
    "zconfig.datatypes": "https://zconfig.readthedocs.io/en/stable/py-mod-datatypes.html#module-ZConfig.datatypes",
    "zconfig.datatypes.memoizedconversion": "https://zconfig.readthedocs.io/en/stable/py-mod-datatypes.html#ZConfig.datatypes.MemoizedConversion",
    "zconfig.datatypes.rangecheckedconversion": "https://zconfig.readthedocs.io/en/stable/py-mod-datatypes.html#ZConfig.datatypes.RangeCheckedConversion",
    "zconfig.datatypes.registry": "https://zconfig.readthedocs.io/en/stable/py-mod-datatypes.html#ZConfig.datatypes.Registry",
    "zconfig.datatypes.registry.get": "https://zconfig.readthedocs.io/en/stable/py-mod-datatypes.html#ZConfig.datatypes.Registry.get",
    "zconfig.datatypes.registry.register": "https://zconfig.readthedocs.io/en/stable/py-mod-datatypes.html#ZConfig.datatypes.Registry.register",
    "zconfig.datatypes.registry.search": "https://zconfig.readthedocs.io/en/stable/py-mod-datatypes.html#ZConfig.datatypes.Registry.search",
    "zconfig.datatypes.regularexpressionconversion": "https://zconfig.readthedocs.io/en/stable/py-mod-datatypes.html#ZConfig.datatypes.RegularExpressionConversion",
    "zconfig.loadconfig": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.loadConfig",
    "zconfig.loadconfigfile": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.loadConfigFile",
    "zconfig.loader": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#module-ZConfig.loader",
    "zconfig.loader.baseloader": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.BaseLoader",
    "zconfig.loader.baseloader.createresource": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.BaseLoader.createResource",
    "zconfig.loader.baseloader.ispath": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.BaseLoader.isPath",
    "zconfig.loader.baseloader.loadfile": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.BaseLoader.loadFile",
    "zconfig.loader.baseloader.loadresource": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.BaseLoader.loadResource",
    "zconfig.loader.baseloader.loadurl": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.BaseLoader.loadURL",
    "zconfig.loader.baseloader.normalizeurl": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.BaseLoader.normalizeURL",
    "zconfig.loader.baseloader.openresource": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.BaseLoader.openResource",
    "zconfig.loader.configloader": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.ConfigLoader",
    "zconfig.loader.resource": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.Resource",
    "zconfig.loader.schemaloader": "https://zconfig.readthedocs.io/en/stable/py-mod-loader.html#ZConfig.loader.SchemaLoader",
    "zconfig.loadschema": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.loadSchema",
    "zconfig.loadschemafile": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.loadSchemaFile",
    "zconfig.schemaerror": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.SchemaError",
    "zconfig.schemaresourceerror": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.SchemaResourceError",
    "zconfig.substitution": "https://zconfig.readthedocs.io/en/stable/py-mod-subst.html#module-ZConfig.substitution",
    "zconfig.substitution.isname": "https://zconfig.readthedocs.io/en/stable/py-mod-subst.html#ZConfig.substitution.isname",
    "zconfig.substitution.substitute": "https://zconfig.readthedocs.io/en/stable/py-mod-subst.html#ZConfig.substitution.substitute",
    "zconfig.substitutionreplacementerror": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.SubstitutionReplacementError",
    "zconfig.substitutionsyntaxerror": "https://zconfig.readthedocs.io/en/stable/py-mod-zconfig.html#ZConfig.SubstitutionSyntaxError",
}
