VERSION = "6.2"

# fmt: off
MAPPING = {
    "zeo": "https://zeo.readthedocs.io/en/stable/",
    "zeo.client": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.client",
    "zeo.clientstorage": "https://zeo.readthedocs.io/en/stable/reference.html",
    "zeo.clientstorage.clientstorage": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage",
    "zeo.clientstorage.clientstorage.close": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.close",
    "zeo.clientstorage.clientstorage.copytransactionsfrom": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.copyTransactionsFrom",
    "zeo.clientstorage.clientstorage.getname": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.getName",
    "zeo.clientstorage.clientstorage.getsize": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.getSize",
    "zeo.clientstorage.clientstorage.history": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.history",
    "zeo.clientstorage.clientstorage.info": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.info",
    "zeo.clientstorage.clientstorage.invalidatetransaction": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.invalidateTransaction",
    "zeo.clientstorage.clientstorage.is_connected": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.is_connected",
    "zeo.clientstorage.clientstorage.is_read_only": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.is_read_only",
    "zeo.clientstorage.clientstorage.isreadonly": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.isReadOnly",
    "zeo.clientstorage.clientstorage.iterator": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.iterator",
    "zeo.clientstorage.clientstorage.loadserial": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.loadSerial",
    "zeo.clientstorage.clientstorage.new_oid": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.new_oid",
    "zeo.clientstorage.clientstorage.notify_connected": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.notify_connected",
    "zeo.clientstorage.clientstorage.notify_disconnected": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.notify_disconnected",
    "zeo.clientstorage.clientstorage.pack": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.pack",
    "zeo.clientstorage.clientstorage.record_iternext": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.record_iternext",
    "zeo.clientstorage.clientstorage.registerdb": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.registerDB",
    "zeo.clientstorage.clientstorage.restore": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.restore",
    "zeo.clientstorage.clientstorage.server_status": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.server_status",
    "zeo.clientstorage.clientstorage.store": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.store",
    "zeo.clientstorage.clientstorage.storeblob": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.storeBlob",
    "zeo.clientstorage.clientstorage.supportsundo": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.supportsUndo",
    "zeo.clientstorage.clientstorage.tpc_abort": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.tpc_abort",
    "zeo.clientstorage.clientstorage.tpc_begin": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.tpc_begin",
    "zeo.clientstorage.clientstorage.tpc_finish": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.tpc_finish",
    "zeo.clientstorage.clientstorage.tpc_vote": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.tpc_vote",
    "zeo.clientstorage.clientstorage.undo": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.undo",
    "zeo.clientstorage.clientstorage.undoinfo": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.undoInfo",
    "zeo.clientstorage.clientstorage.undolog": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.ClientStorage.ClientStorage.undoLog",
    "zeo.db": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.DB",
    "zeo.exceptions": "https://zeo.readthedocs.io/en/stable/reference.html#module-ZEO.Exceptions",
    "zeo.exceptions.clientdisconnected": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.Exceptions.ClientDisconnected",
    "zeo.exceptions.clientstorageerror": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.Exceptions.ClientStorageError",
    "zeo.exceptions.protocolerror": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.Exceptions.ProtocolError",
    "zeo.exceptions.serverexception": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.Exceptions.ServerException",
    "zeo.exceptions.unrecognizedresult": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.Exceptions.UnrecognizedResult",
    "zeo.server": "https://zeo.readthedocs.io/en/stable/reference.html#ZEO.server",
}
