VERSION = "4.1.0"

# fmt: off
MAPPING = {
    "zipp": "https://zipp.readthedocs.io/en/latest/",
    "zipp.glob": "https://zipp.readthedocs.io/en/latest/",
    "zipp.glob.separate": "https://zipp.readthedocs.io/en/latest/#zipp.glob.separate",
    "zipp.glob.translator": "https://zipp.readthedocs.io/en/latest/#zipp.glob.Translator",
    "zipp.glob.translator.extend": "https://zipp.readthedocs.io/en/latest/#zipp.glob.Translator.extend",
    "zipp.glob.translator.match_dirs": "https://zipp.readthedocs.io/en/latest/#zipp.glob.Translator.match_dirs",
    "zipp.glob.translator.replace": "https://zipp.readthedocs.io/en/latest/#zipp.glob.Translator.replace",
    "zipp.glob.translator.restrict_rglob": "https://zipp.readthedocs.io/en/latest/#zipp.glob.Translator.restrict_rglob",
    "zipp.glob.translator.seps": "https://zipp.readthedocs.io/en/latest/#zipp.glob.Translator.seps",
    "zipp.glob.translator.star_not_empty": "https://zipp.readthedocs.io/en/latest/#zipp.glob.Translator.star_not_empty",
    "zipp.glob.translator.translate": "https://zipp.readthedocs.io/en/latest/#zipp.glob.Translator.translate",
    "zipp.glob.translator.translate_core": "https://zipp.readthedocs.io/en/latest/#zipp.glob.Translator.translate_core",
    "zipp.path": "https://zipp.readthedocs.io/en/latest/#zipp.Path",
    "zipp.path.exists": "https://zipp.readthedocs.io/en/latest/#zipp.Path.exists",
    "zipp.path.filename": "https://zipp.readthedocs.io/en/latest/#zipp.Path.filename",
    "zipp.path.glob": "https://zipp.readthedocs.io/en/latest/#zipp.Path.glob",
    "zipp.path.is_dir": "https://zipp.readthedocs.io/en/latest/#zipp.Path.is_dir",
    "zipp.path.is_file": "https://zipp.readthedocs.io/en/latest/#zipp.Path.is_file",
    "zipp.path.is_symlink": "https://zipp.readthedocs.io/en/latest/#zipp.Path.is_symlink",
    "zipp.path.iterdir": "https://zipp.readthedocs.io/en/latest/#zipp.Path.iterdir",
    "zipp.path.joinpath": "https://zipp.readthedocs.io/en/latest/#zipp.Path.joinpath",
    "zipp.path.match": "https://zipp.readthedocs.io/en/latest/#zipp.Path.match",
    "zipp.path.name": "https://zipp.readthedocs.io/en/latest/#zipp.Path.name",
    "zipp.path.open": "https://zipp.readthedocs.io/en/latest/#zipp.Path.open",
    "zipp.path.parent": "https://zipp.readthedocs.io/en/latest/#zipp.Path.parent",
    "zipp.path.read_bytes": "https://zipp.readthedocs.io/en/latest/#zipp.Path.read_bytes",
    "zipp.path.read_text": "https://zipp.readthedocs.io/en/latest/#zipp.Path.read_text",
    "zipp.path.relative_to": "https://zipp.readthedocs.io/en/latest/#zipp.Path.relative_to",
    "zipp.path.rglob": "https://zipp.readthedocs.io/en/latest/#zipp.Path.rglob",
    "zipp.path.stem": "https://zipp.readthedocs.io/en/latest/#zipp.Path.stem",
    "zipp.path.suffix": "https://zipp.readthedocs.io/en/latest/#zipp.Path.suffix",
    "zipp.path.suffixes": "https://zipp.readthedocs.io/en/latest/#zipp.Path.suffixes",
}
